src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Foundation</fullName>
        <active>true</active>
        <description>Use this record type for foundation entities</description>
        <label>Foundation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <fields>
        <fullName>ISO_Standard_Code__c</fullName>
        <label>ISO Standard Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Dashboard_Section__c.object
<CustomObject>
    <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
    <fields>
        <fullName>Dashboard__c</fullName>
        <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
        <inlineHelpText>Select the dashboard that this section belongs to</inlineHelpText>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Sections</relationshipLabel>
        <relationshipName>Dashboard_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this section is active i.e. should be displayed on the dashboard</description>
        <inlineHelpText>Uncheck if this section should not be on the dashboard</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title to display on the page section that contains this section</description>
        <inlineHelpText>Enter the title that will head this section on the dashboard</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Dashboard Section</label>
    <nameField>
        <displayFormat>DS{0000000000}</displayFormat>
        <label>Dashboard Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <fields>
        <fullName>Is_On_Fly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this metrics value should be calculated on the fly</description>
        <inlineHelpText>Only check this if you know what you are doing</inlineHelpText>
        <label>Is On Fly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>The label for this metric. Will be displayed on the dashboard.</description>
        <inlineHelpText>The label for this metric. Will be displayed on the dashboard.</inlineHelpText>
        <label>Label</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Metric_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The section that the metric belongs to</description>
        <inlineHelpText>Leave blank if this metric is in the old style dashboard</inlineHelpText>
        <label>Metric Section</label>
        <referenceTo>Metric_Section__c</referenceTo>
        <relationshipLabel>M&amp;E Metrics</relationshipLabel>
        <relationshipName>M_E_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>On_The_Fly_Calculation_Type__c</fullName>
        <description>The type of on the fly calculation that this metric requires</description>
        <inlineHelpText>Choose one of these if the metric is to be calculated on the fly</inlineHelpText>
        <label>On The Fly Calculation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sum</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Ordering in list</description>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date of the quarter to which this metric belongs</description>
        <inlineHelpText>This can simply be any date falling in the quarter to which this metric belongs. We shall calculate the quarter dynamically. It defaults to the current date.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Metric_Section__c.object
<CustomObject>
    <description>A section that holds metrics to be shown on a dashboard</description>
    <fields>
        <fullName>Dashboard_Section__c</fullName>
        <description>The section of a dashboard that this metric section belongs to</description>
        <inlineHelpText>Please select the section of the dashboard that the metrics will be displayed in</inlineHelpText>
        <label>Dashboard Section</label>
        <referenceTo>Dashboard_Section__c</referenceTo>
        <relationshipLabel>Metric Sections</relationshipLabel>
        <relationshipName>Metric_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Blurb that is shown just below the title in the page block section</description>
        <inlineHelpText>Enter the description that will be displayed for this metric sectiom</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the section still active to be displayed on a dashboard</description>
        <inlineHelpText>Uncheck this to indicate that the metric section should be displayed</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RollOver_Time__c</fullName>
        <description>The time period that each metric data lasts for</description>
        <inlineHelpText>Select how often you want the metrics to change</inlineHelpText>
        <label>RollOver Time</label>
        <picklist>
            <picklistValues>
                <fullName>Biannually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Show_Spark_Line__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the metrics should show a spark line</description>
        <inlineHelpText>Check if a spark line should be shown</inlineHelpText>
        <label>Show Spark Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that data started being collected for this dashboard. Will be the earliest option that shows up in the date selector for the selector</description>
        <inlineHelpText>Set to the date that data collection started. Should be the start of the time period i.e. if collection started 02/02/2012 and the roll over period is quarterly then the start date is 01/01/2012</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The title for the metric section</description>
        <inlineHelpText>Enter a title for this section</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Metric Section</label>
    <nameField>
        <displayFormat>MS{0000000000}</displayFormat>
        <label>Metric Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metric Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>A region in a given country</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country that the region is in</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Regions</relationshipLabel>
        <relationshipName>Regions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Region</label>
    <nameField>
        <displayFormat>REG-{000000000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FHITests.cls
/**
 *
 * Copyright (c) 2013 AppLab, Grameen Foundation
 *
 *  This class contains tests for IG/NUSAF Dashboard
 **/
@isTest
private class FHITests {
    
    static testMethod void testDashboardComponents() {    	
        
        //no metric map markers
        List<MetricMapWrapper> fieldVisits = IGDashboardHelpers.getFieldVisitsMapMarkers('', '', '', '', '', null);
        System.assert(fieldVisits.size() == 0);
        
        FHIDashboardController controller = new FHIDashboardController();
        
        Account testOrg = new Account();
        testOrg.Name = 'TestCKW';
        testOrg.BillingState = 'CA';
        database.SaveResult accSaveResult = database.insert(testOrg);

        Country__c country = new Country__c();
        country.Name = 'TestUganda';
        country.ISO_Standard_Code__c = 'sw';
        database.SaveResult countrySaveResult = database.insert(country);

        Dashboard__c dash = new Dashboard__c();
        dash.Account__c = accSaveResult.getId();
        dash.Title__c = 'Title';
        dash.Description__c = 'Description';
        Database.insert(dash);

        Dashboard_Section__c section = new Dashboard_Section__c();
        section.Dashboard__c = dash.Id;
        section.Title__c = 'Title';
        Database.insert(section);

        Dashboard_Section__c sec = [SELECT Name FROM Dashboard_Section__c WHERE Id = :section.Id];
        controller.setDashboardSection(sec.Name);
        List<Metric_Section__c> secs = controller.getMetricSections();
        System.assert(secs.size() == 0);

        Metric_Section__c metricsection = new Metric_Section__c();
        metricsection.Dashboard_Section__c = section.Id;
        metricsection.Description__c='Farmers Reached by Year';
        metricsection.Is_Active__c=true;
        metricsection.RollOver_Time__c='Quarterly';
        metricsection.Title__c='Farmers  by Year';
        metricsection.Start_Date__c=Date.today();
        metricsection.Default_Show__c=1;
        metricsection.Show_Spark_Line__c = true;
        metricsection.View_Mode__c='Disaggregated';
        insert metricsection;

        secs = controller.getMetricSections();
        //should not do any db access, returns last data
        System.assert(secs.size() == 0);

        M_E_Metric__c metric = new M_E_Metric__c();
        metric.Label__c='% of';
        metric.Is_On_Fly__c=true;
        metric.On_The_Fly_Calculation_Type__c='Percentage';
        metric.Order__c=0;
        metric.Name='FHI_target_farmers_reached_in_year_1';
        metric.Metric_Section__c = metricsection.Id;
        insert metric;

        List<M_E_Metric__c> metrics = controller.getMetrics(metricsection.Id);
        System.assert(metrics.size() == 1);
        
        //test regions listbox		
        Region__c region = new Region__c();
        region.Display_Name__c = 'Central';
        region.Country__c = countrySaveResult.getId();
        insert region;
        
        List<SelectOption> regions = controller.getSubregionsList();
        Schema.DescribeFieldResult districtRegions = District__c.Region__c.getDescribe();
        List<Schema.PicklistEntry> districtRegionsValues = districtRegions.getPicklistValues();
        System.assert(regions.size() == districtRegionsValues.size() + 1);	//including the default --select all--		
        controller.setSubregionsList(null);
        
        //test districts list box
        District__c testDistrict = new District__c();
        testDistrict.Name = 'TestMasaka';
        testDistrict.Region__c = region.Display_Name__c;
        database.SaveResult districtSaveResult = database.insert(testDistrict);
        
        List<SelectOption> districts = controller.getDistrictList();
        System.assert(districts.size() == 2);//including the default --select all		
        controller.setDistrictList(null);
        
        //test subcounty listbox
        Subcounty__c testSubcounty = new Subcounty__c();
        testSubcounty.Display_Name__c = 'TestLukaya-TC';
        testSubcounty.District__c = districtSaveResult.getId();
        insert testSubcounty;      

        List<SelectOption> subs = controller.getSubcountiesList();
        System.assert(subs.size() == 2);//including the default --select all	
        controller.setSubcountiesList(null);
        
        //test CBT listbox
        Phone__c testHandset = new Phone__c();
        testHandset.IMEI__c = '123456789101112';
        testHandset.Serial_Number__c = '123456789101112';
        testHandset.Purchase_Value_USD__c = 100.00;
        database.SaveResult phoneSaveResult = database.insert(testHandset);

        Person__c testPerson = new Person__c();
        testPerson.First_Name__c = 'David';
        testPerson.Last_Name__c = 'Mugume' ;
        testPerson.Gender__c = 'Male';
        testPerson.District__c = districtSaveResult.getId();
        testPerson.Handset__c = phoneSaveResult.getId();
        testPerson.Type__c = 'CKW';
        insert testPerson;

        //test setup
        PageReference resultPage =  new PageReference('/a00/e');
        resultPage.getParameters().put('subregion', String.valueOf(region.Display_Name__c));
        resultPage.getParameters().put('district', String.valueOf(testDistrict.Id));
        resultPage.getParameters().put('subcounty', String.valueOf(testSubcounty.Id));
        resultPage.getParameters().put('dateFrom', '1987-12-18');
        resultPage.getParameters().put('dateTo', '2013-12-18');
        resultPage.getParameters().put('editMode', 'true');
        resultPage.getParameters().put('sfdc.tabName', '/a00/e');
        System.assert(controller.getIsEditMode() == 'false');

        controller.setUp(resultPage);
        System.assert(controller.subregion != '');
        System.assert(controller.district != null);
        System.assert(controller.subcounty != null);
        System.assert(controller.dummyObject != null);
        System.assert(controller.getIsEditMode() == 'true');

        //retest after region is set
        districts = controller.getDistrictList();
        System.assert(districts.size() == 2);//including the default --select all    

        //retest after district is set
        subs = controller.getSubcountiesList();
        System.assert(subs.size() == 2);//including the default --select all       
        
        controller.subcounty = testSubcounty;
        controller.district = testDistrict;
        controller.subregion = region.Id;
        controller.cbt = testPerson;

        //changeFilters
        PageReference page = controller.changeFilters();
        System.assert(page != null);

        //listbox events
        controller.subregion = testDistrict.Region__c;
        PageReference pageRegion = controller.onRegionChanged();
        System.assert(pageRegion == null);
        PageReference pageDistrict = controller.onDistrictChanged();
        System.assert(pageDistrict == null);
    }

    static testMethod void testMetricSectionComponentController() {
        
        Account testOrg = new Account();
        testOrg.Name = 'TestCKW';
        testOrg.BillingState = 'CA';
        database.SaveResult accSaveResult = database.insert(testOrg);

        Country__c country = new Country__c();
        country.Name = 'TestUganda';
        country.ISO_Standard_Code__c = 'sw';
        database.SaveResult countrySaveResult = database.insert(country);

        //test districts list box
        District__c testDistrict = new District__c();
        testDistrict.Name = 'TestMasaka';
        database.insert(testDistrict);

        Dashboard__c dash = new Dashboard__c();
        dash.Account__c = accSaveResult.getId();
        dash.Title__c = 'Title';
        dash.Description__c = 'Description';
        Database.insert(dash);

        Dashboard_Section__c section = new Dashboard_Section__c();
        section.Dashboard__c = dash.Id;
        section.Title__c = 'Title';
        Database.insert(section);

        Metric_Section__c metricsection = new Metric_Section__c();
        metricsection.Dashboard_Section__c = section.Id;
        metricsection.Description__c='Farmers Reached by Year';
        metricsection.Is_Active__c=true;
        metricsection.RollOver_Time__c='Quarterly';
        metricsection.Title__c='Farmers  by Year';
        metricsection.Start_Date__c=Date.today();
        metricsection.Default_Show__c=1;
        metricsection.Show_Spark_Line__c = true;
        metricsection.View_Mode__c='Disaggregated';
        insert metricsection;

        M_E_Metric__c metric1 = new M_E_Metric__c();
        metric1.Metric_Section__c = metricsection.Id;
        metric1.Name = 'Farmers Registered';
        metric1.Label__c = 'FHI ';
        metric1.Is_Header__c = false;
        metric1.Is_On_Fly__c = true;
        metric1.On_The_Fly_Calculation_Type__c = 'Count';
        metric1.Organisation__c = accSaveResult.getId();
        M_E_Metric__c metric2= new M_E_Metric__c();
        metric2.Name = 'Farmers Reached';
        metric2.Metric_Section__c = metricsection.Id;
        metric2.Label__c = 'FHI 1';
        metric2.Is_Header__c = false;
        metric2.Is_On_Fly__c = true;
        metric2.On_The_Fly_Calculation_Type__c = 'Sum';
        metric2.Organisation__c = accSaveResult.getId();
        M_E_Metric__c metric3= new M_E_Metric__c();
        metric3.Name = 'Farmers in Group';
        metric3.Metric_Section__c = metricsection.Id;
        metric3.Subdivider__c = 'District';
        metric3.Label__c = 'FHI 2';
        metric3.Is_Header__c = false;
        metric3.Is_On_Fly__c = true;
        metric3.On_The_Fly_Calculation_Type__c = 'Percentage';
        metric3.Organisation__c = accSaveResult.getId();
        M_E_Metric__c metric4= new M_E_Metric__c();
        metric4.Name = 'FHI in Group';
        metric4.Metric_Section__c = metricsection.Id;
        metric4.Label__c = 'FHI 3';
        metric4.Is_Header__c = false;
        metric4.Is_On_Fly__c = true;
        metric4.On_The_Fly_Calculation_Type__c = 'Average';
        metric4.Organisation__c = accSaveResult.getId();
        M_E_Metric__c metric5= new M_E_Metric__c();
        metric5.Name = 'FHI in farmer';
        metric5.Metric_Section__c = metricsection.Id;
        metric5.Label__c = 'FHI 3';
        metric5.Is_Header__c = false;
        metric5.Is_On_Fly__c = false;
        metric5.Projected_Value__c = 20;
        metric5.Automated__c = 'False';
        metric5.Organisation__c = accSaveResult.getId();
        database.insert(new M_E_Metric__c[] { metric1,  metric2, metric3, metric4, metric5});

        M_E_Metric_Data__C metricdata = new M_E_Metric_Data__C();
        metricdata.M_E_Metric__c = metric5.Id;
        metricdata.Comment__c = 'Extension tool submissions';
        metricdata.Manual_Value__c = 30;
        metricdata.Actual_Value__c = 8000;
        metricdata.Projected_Value__c = 9000;
        metricdata.Date__c = Date.today();
        metricdata.Projected_Value__c = 85;
        insert metricdata;

        MetricSectionComponentController controller = new MetricSectionComponentController();
        controller.metricId = metricsection.Id;
        controller.districtId = testDistrict.Id;
        //List<M_E_Metric__c> metrics_s = controller.getMetrics();
        //System.assert(metrics_s.size() == 4);

        //we have five metrics calculations
        List<MetricDataWrapper> datas = controller.getMetricDatas();
        System.assert(datas.size() == 5);

        //based on dashboard section id provided, the object has been retrieved
        System.assert(controller.thisSection != null);

        //metrics in this dashboard section have been populated
        List<M_E_Metric__c> metrics_s = controller.getMetrics();
        System.assert(metrics_s.size() == 5);

        M_E_Metric_Data__c manualMetricData = MetricSectionComponentController.getMetricData(String.valueOf(metricdata.Id));
        System.assert(manualMetricData != null);
        System.assert(manualMetricData.Projected_Value__c == metricdata.Projected_Value__c);
    }
}