src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>Use this record type for corporations or small businesses</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Foundation</fullName>
        <active>true</active>
        <description>Use this record type for foundation entities</description>
        <label>Foundation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Picture_Attachment_Id__c</fullName>
        <description>Stores the Id of the attachment that is used for the profile picture for this contact</description>
        <inlineHelpText>Stores the Id of the attachment that is used for the profile picture for this contact</inlineHelpText>
        <label>Picture Attachment Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/EMP_Consultant__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Consultant_contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EMP Consultants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Consultant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Consultant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Consultants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Farm__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Banana_area__c</fullName>
        <label>Banana area</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LAC_Household__c</fullName>
        <label>LAC Household</label>
        <referenceTo>LAC_Household__c</referenceTo>
        <relationshipLabel>LAC Farms</relationshipLabel>
        <relationshipName>LAC_Farms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LAC Farm</label>
    <nameField>
        <label>LAC Farm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAC_Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LAC Household</label>
        <referenceTo>LAC_Household__c</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PPI_Score__c</fullName>
        <label>PPI Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Household__c.object
<CustomObject>
    <description>Object that contains details about the household that people can belong to</description>
    <fields>
        <fullName>Family_Size__c</fullName>
        <label>Family Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LAC Household</label>
    <nameField>
        <displayFormat>HH-{0000000}</displayFormat>
        <label>LAC Household Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LAC Households</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <description>A message sent to a user in our system</description>
    <fields>
        <fullName>Recipient__c</fullName>
        <description>The recipient of the message</description>
        <label>Recipient</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of the message</description>
        <label>Subject</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>MSG-{00000000}</displayFormat>
        <label>Message ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Search_Log__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Handset_Submit_Time__c</fullName>
        <description>Time the phone sent the request</description>
        <label>Handset Submit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person who requests information</description>
        <label>Interviewee</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Administered)</relationshipLabel>
        <relationshipName>Interviewee_Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Log</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Submission_Meta_Data__c.object
<CustomObject>
    <description>Contains the data that every submission requires. Every submission will have one of these irrelevant of the submission object that corresponds to the submission</description>
    <fields>
        <fullName>Handset_Submit_Time__c</fullName>
        <description>The time that the submission was entered on the handset</description>
        <label>Handset Submit Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interviewee__c</fullName>
        <description>The person answering the survey</description>
        <label>Interviewee</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>Submission_Meta_Datas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result_Hash__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>unique hash created using SHA1 to ensure that this submission has not been entered into the system already</description>
        <label>Result Hash</label>
        <length>160</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Submission_Size__c</fullName>
        <description>The size in bytes of the submission</description>
        <label>Submission Size (Bytes)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SMD-{0000000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LacFarmerDetailsControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of the
 * LacFarmerDetailsController class.
 */
@isTest
private class LacFarmerDetailsControllerTest {
	
	public static testMethod void testLacPpi() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerDetailsController c = new LacFarmerDetailsController(sc);
		c.save();
		
		system.assertEquals(c.getPovertyProbabilityLessThanOneQuarter(), 81.1);
		system.assertEquals(c.getPovertyProbabilityLessThanTwoAndHalf(), 100);
		system.assertEquals(c.getPovertyProbabilityLessThanOneThreeAndThreeQuarter(), 100);
		system.assertEquals(c.getPovertyProbabilityLessThanOneFive(), 100);
	}
	
	public static testMethod void testRetreivingProfilePicture() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerDetailsController c = new LacFarmerDetailsController(sc);
		c.getProfilePicture().Name = 'TestProfilePic';
    	c.getProfilePicture().Body = Blob.valueOf('Unit Test Attachment Body');
		c.save();
		
		Id attachmentId = farmerDetails.Contact__r.Picture_Attachment_Id__c;
		
		ApexPages.StandardController sc2 = new ApexPages.StandardController(farmerDetails);
		LacFarmerDetailsController c2 = new LacFarmerDetailsController(sc);
		
		
		system.assertEquals(attachmentId, c2.getProfilePicture().Id);
	}
	
	private static LAC_Farmer_Details__c createLacFarmer() {
		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		system.assert(p != null);
		
		User user = new User(Alias = 'ckwtest', Email='ckwtest@testorg.com', 
	    	EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
	     	LocaleSidKey='en_US', ProfileId = p.Id, 
	     	TimeZoneSidKey='America/Los_Angeles', UserName='ckwtest@testorg.com');
		insert user;
		
		RecordType recordType = new RecordType();
    	recordType.Name='Business';
    	
    	Account account = new Account(Name='CKW', RecordType=recordType);
    	account.BillingState='CA';
    	insert account;
    	
    	Contact contact = new Contact();
    	contact.FirstName = 'Grameen';
    	contact.LastName = 'Foundation';
    	contact.AccountId = account.Id;
    	insert contact;
    	
    	Person__c person = new Person__c();
    	person.Last_Name__c = 'Foundation';
    	person.First_Name__c = 'Grameen';
    	person.Contact__c = contact.Id;
    	insert person;
    	
		LAC_Household__c household = new LAC_Household__c(Family_Size__c = 10);
		insert household;
		
		LAC_Farm__c farm = new LAC_Farm__c();
		farm.Name = 'LAC-Farm-222';
		farm.Area__c = 334;
		farm.Banana_area__c = 333;
		farm.LAC_Household__c = household.Id;
		insert farm;
		
		LAC_Farmer_Details__c farmerDetails = new LAC_Farmer_Details__c();
		farmerDetails.Person__c = person.Id;
		farmerDetails.Contact__c = contact.Id;
		farmerDetails.Contact__r = contact;
		farmerDetails.LAC_Household__c = household.Id;
		farmerDetails.OwnerId = user.Id;
		farmerDetails.PPI_Score__c = 2;
		
		return farmerDetails;
	}
	
		/**
	 * tests the change owner method of the LacFarmerDetailsController
	 */
	public static testMethod void testChangeOwner() {
		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		system.assert(p != null);
		
		User user = new User(Alias = 'ckwtest', Email='ckwtest@testorg.com', 
	    	EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
	     	LocaleSidKey='en_US', ProfileId = p.Id, 
	     	TimeZoneSidKey='America/Los_Angeles', UserName='ckwtest@testorg.com');
		insert user;
		
		RecordType recordType = new RecordType();
    	recordType.Name='Business';
    	
    	Account account = new Account(Name='CKW', RecordType=recordType);
    	account.BillingState='CA';
    	insert account;
    	
    	Contact contact = new Contact();
    	contact.FirstName = 'Grameen';
    	contact.LastName = 'Foundation';
    	contact.AccountId = account.Id;
    	insert contact;
    	
    	Person__c person = new Person__c();
    	person.Last_Name__c = 'Foundation';
    	person.First_Name__c = 'Grameen';
    	person.Contact__c = contact.Id;
    	insert person;
    	
		LAC_Household__c household = new LAC_Household__c(Family_Size__c = 10);
		insert household;
		
		LAC_Farm__c farm = new LAC_Farm__c();
		farm.Name = 'LAC-Farm-222';
		farm.Area__c = 334;
		farm.Banana_area__c = 333;
		farm.LAC_Household__c = household.Id;
		insert farm;
		
		LAC_Farmer_Details__c farmerDetails = new LAC_Farmer_Details__c();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerDetailsController c = new LacFarmerDetailsController(sc);
		
		c.getProfilePicture().Name = 'TestProfilePic';
    	c.getProfilePicture().Body = Blob.valueOf('Unit Test Attachment Body');
		c.getFarmer().Person__c = person.Id;
		c.getFarmer().Contact__c = contact.Id;
		c.getFarmer().LAC_Household__c = household.Id;
		c.getFarmer().OwnerId = user.Id;
		c.getFarmer().Contact__r = contact;
		
		c.save();
		
		contact = [SELECT Id, OwnerId FROM Contact WHERE Id = :contact.Id];
		person = [SELECT Id, OwnerId FROM Person__c WHERE Id = :person.Id];
		household = [SELECT Id, OwnerId FROM LAC_Household__c WHERE Id = :household.Id];
		
		system.assertEquals(user.Id, contact.OwnerId);
		system.assertEquals(user.Id, person.OwnerId);
		system.assertEquals(user.Id, household.OwnerId);		
	}
	
	public static testMethod void test() {
		LAC_Farmer_Details__c obj = new LAC_Farmer_Details__c();
		ApexPages.StandardController sc = new ApexPages.StandardController(obj);
		LacFarmerDetailsController c = new LacFarmerDetailsController(sc);

		System.assertEquals(0,c.getSearchesNum());
		System.assertEquals(0,c.getSubmissionsNum());
		System.assertEquals(0,c.getMessagesNum());

		Person__c person = new Person__c(
			First_Name__c = 'test'
		);
		insert person;

		LAC_Farmer_Details__c farmerDetails = new LAC_Farmer_Details__c(Person__c = person.Id);
		insert farmerDetails;

		Search_Log__c searchLog = new Search_Log__c(Interviewee__c = person.Id);
		insert searchLog;

		Submission_Meta_Data__c submission = new Submission_Meta_Data__c(
			Interviewee__c = person.Id,
			Handset_Submit_Time__c = DateTime.now(),
			Result_Hash__c = 'hash',
			Submission_Size__c = 10
		);
		Submission_Meta_Data__c submission2 = submission.clone();
		submission2.Result_Hash__c = 'hash2';
		insert new Submission_Meta_Data__c[]{submission, submission2};


		Message__c message = new Message__c(
			Recipient__c = person.Id,
			Subject__c = 'subject'
		);
		insert new Message__c[]{message,message.clone()};

		sc = new ApexPages.StandardController(farmerDetails);
		c = new LacFarmerDetailsController(sc);

		System.assertEquals(1,c.getSearchesNum());
		System.assertEquals(2,c.getSubmissionsNum());
		System.assertEquals(2,c.getMessagesNum());
	}
}