src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>Use this record type for corporations or small businesses</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Crops__c</fullName>
        <description>Top crops grown by the farmer</description>
        <label>Crops</label>
        <picklist>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wheat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cassava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irish Potatoes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundnuts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sorghum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bananas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cotton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Household_Status__c</fullName>
        <description>The farmer&apos;s status in the household</description>
        <label>Household Status</label>
        <picklist>
            <picklistValues>
                <fullName>Household head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse of household head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child of household head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Land_Size__c</fullName>
        <description>Amount of land, in acres, owned by the farmer</description>
        <label>Land Size (Acres)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Topics_of_Interest__c</fullName>
        <description>Topics of interest for the farmer</description>
        <label>Topics of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>Market Prices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planting/Garden Prep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pest and Disease Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soil Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harvesting/PHH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farming as a Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Livestock Rearing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agricultural Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Father_Name__c</fullName>
        <description>The person&apos;s father&apos;s name, used for identification purposes</description>
        <label>Father&apos;s Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raw_Mobile_Number__c</fullName>
        <description>(optional) Phone number provided for non GF-assets</description>
        <label>Raw Mobile Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Village__c</fullName>
        <description>Village that the person lives in</description>
        <label>Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PPI_Data__c.object
<CustomObject>
    <description>Temp warehouse object that stores data for the PPI surveys until the new platform is ready</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Uganda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kenya</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>PPI Datas</relationshipLabel>
        <relationshipName>PPI_Datas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question_10__c</fullName>
        <label>Question 10</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <description>The first question on the PPI scorecard</description>
        <label>Question 1</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_2__c</fullName>
        <description>The second question on the PPI survey</description>
        <label>Question 2</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_3__c</fullName>
        <description>The third question in the PPI survey</description>
        <label>Question 3</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_4__c</fullName>
        <description>The 4th question in the PPI survey</description>
        <label>Question 4</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_5__c</fullName>
        <label>Question 5</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_6__c</fullName>
        <label>Question 6</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_7__c</fullName>
        <label>Question 7</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_8__c</fullName>
        <label>Question 8</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_9__c</fullName>
        <label>Question 9</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>PPI Data</label>
    <nameField>
        <displayFormat>PPI{0000000000}</displayFormat>
        <label>PPI Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PPI Datas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission_Answer__c.object
<CustomObject>
    <description>Object to hold one answer to a survey</description>
    <label>Submission Answer</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Submission Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcessAgrowaysSurveys.cls
/**
* A class to handle post processing of 
* all the Agroways surveys
*/
public class ProcessAgrowaysSurveys {

    /**
    *  Fill in the objects for this Farmer Registration
    *
    *  @param submission - The submission object being processed
    *  @param answers    - A map containing the values for the registration
    *                       The keys are <binding>_<instance> for compatibility
    *  @param person     - The Person__c object VAC who submitted the form
    *
    *  @return - A three element list of Strings with the following format
    *              element 1 - Binary indicator of success (0 = fail, 1 = success)
    *              element 2 - Error message if required for the logs and tech team
    *              element 3 - Message body to the VAC if required.
    */
    public static List<String> processAgrowaysFarmerRegistration(ProcessSurveySubmission.SurveySubmission submission,
        Map<String, Submission_Answer__c> answers, Person__c interviewer) {

        // Check that the farmer id does not already exist
        Farmer__c[] farmers = Utils.loadFarmerFromId(ProcessSubmissionHelpers.getAnswerString(answers.get('q1_0')));
        if (!farmers.isEmpty()) {
            return new String[] {'0', 'The Farmer Id is already in use by another', 'SUPPRESSMSG'};
        }
        Account account = [Select Id from Account where Name = 'Agroways' limit 1];

        String name = ProcessSubmissionHelpers.getAnswerString(answers.get('q2_0')).replaceAll('\\s+',' ');System.debug(name);
        String[] fullName = name.split(' ');
        String firstName = fullName[0];
        String lastName = fullName[1];

        // Create the Contact object
        Contact contact = new Contact(firstName=firstName, LastName = lastName, accountId = account.Id);
        insert contact;

        // Create the Person object
        Person__c person = new Person__c(First_Name__c=firstName, Last_Name__c = lastName);
        person.Raw_Mobile_Number__c = ProcessSubmissionHelpers.getAnswerString(answers.get('q3_0'));
        person.Father_Name__c = ProcessSubmissionHelpers.getAnswerString(answers.get('q4_0'));
        person.Gender__c = genderMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q8_0')));
        person.District__c = [Select Id from District__c where Name =:districtMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q5_0'))) limit 1].Id;
        person.Subcounty__c = [Select Id from Subcounty__c where Display_Name__c =:ProcessSubmissionHelpers.getAnswerString(answers.get('q6_0')) limit 1].Id;
        person.Village__c = ProcessSubmissionHelpers.getAnswerString(answers.get('q7_0')); 
        insert person;

        // Create the PPI object
        PPI_Data__c ppiObject = new PPI_Data__c();
        ppiObject.Person__c = person.Id;
        ppiObject.Country__c = 'Uganda';
        ppiObject.Version__c = 'Uganda';
        ppiObject.Date__c = ProcessSurveySubmission.getTimestamp(submission.handsetSubmitTime).date();
        ppiObject.Question_1__c = hhMembersMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q15_0'))).toPlainString();
        ppiObject.Question_2__c = childrenInSchoolMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q16_0'))).toPlainString();
        ppiObject.Question_3__c = femaleGradeMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q17_0'))).toPlainString();
        ppiObject.Question_4__c = roofMaterialMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q18_0'))).toPlainString();
        ppiObject.Question_5__c = wallMaterialMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q19_0'))).toPlainString();
        ppiObject.Question_6__c = lightingSourceMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q20_0'))).toPlainString();
        ppiObject.Question_7__c = toiletTypeMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q21_0'))).toPlainString();
        ppiObject.Question_8__c = ownElectricEquipmentMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q22_0'))).toPlainString();
        ppiObject.Question_9__c = ownTwoClothesSetMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q23_0'))).toPlainString();
        ppiObject.Question_10__c = ownOnePairOfShoesMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q24_0'))).toPlainString();
        ppiObject.Score__c = Decimal.valueOf(ppiObject.Question_1__c)        +
                    Decimal.valueOf(ppiObject.Question_2__c)                 +
                    Decimal.valueOf(ppiObject.Question_3__c)                 +
                    Decimal.valueOf(ppiObject.Question_4__c)                 +
                    Decimal.valueOf(ppiObject.Question_5__c)                 +
                    Decimal.valueOf(ppiObject.Question_6__c)                 +
                    Decimal.valueOf(ppiObject.Question_7__c)                 +
                    Decimal.valueOf(ppiObject.Question_8__c)                 +
                    Decimal.valueOf(ppiObject.Question_9__c)                 +
                    Decimal.valueOf(ppiObject.Question_10__c);
        // Create the Farmer object
        Farmer__c farmer = new Farmer__c(Person__c = person.Id);
        farmer.Household_Status__c = householdStatusMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q9_0')));
        farmer.Land_Size__c = ProcessSubmissionHelpers.getAnswerNumber(answers.get('q10_0'), 'q10', 0);
        Set<String> crops = ProcessSubmissionHelpers.getAnswerSet(answers.get('q11_0'));
        String cropString = '';
        for (String crop : crops) {
            if (String.isEmpty(cropString)) {
               cropString = cropMap.get(crop);
            }
            else {
                cropString = cropMap.get(crop) + ';' + cropString;
            } 
        }
        farmer.Crops__c = cropString;
        Set<String> topics = ProcessSubmissionHelpers.getAnswerSet(answers.get('q13_0'));
        String topicString = '';
        for (String topic : topics) {
            if (String.isEmpty(topicString)) {
               topicString = topicsMap.get(topic);
            }
            else {
                topicString = topicsMap.get(topic) + ';' + topicString;
            } 
        }
        farmer.Topics_of_Interest__c = topicString;
        insert farmer;
        return new String[]{ '1', 'Agroways Farmer Registration successful for IMEI: ' + submission.imei, 'SUPRESSMSG' };
    }

    // A map of gender
    private static Map<String, String> genderMap = new Map<String, String> {
        '1' => 'Male',
        '2' => 'Female'
    };

    // A map of Districts
    private static Map<String, String> districtMap = new Map<String, String> {
        '1' => 'Mayuge',
        '2' => 'Kamuli',
        '3' => 'Luuka',
        '4' => 'Kaliro',
        '5' => 'Buyende',
        '6' => 'Jinja'
    };

    // A map of household status
    private static Map<String, String> householdStatusMap = new Map<String, String> {
        '1' => 'Household head',
        '2' => 'Spouse of household head',
        '3' => 'Child of household head',
        '4' => 'Other'
    };

    // Map of the crops grown by the Agroways farmers
    private static Map<String, String> cropMap = new Map<String, String> {
        '1' => 'Maize',
        '2' => 'Beans',
        '3' => 'Cassava',
        '4' => 'Groundnuts',
        '5' => 'Sorghum',
        '6' => 'Rice',
        '7' => 'Millet',
        '8' => 'Coffee',
        '9' => 'Bananas',
        '10' => 'Sugarcane',
        '11' => 'Other',
        '12' => 'None'
    };

    // Map of Subscription Topics
    private static Map<String, String> topicsMap = new Map<String, String> {
        '1' => 'Market Prices',
        '2' => 'Market Opportunities',
        '3' => 'Weather',
        '4' => 'Planting/Garden Prep',
        '5' => 'Pest and Disease Management',
        '6' => 'Soil Management',
        '7' => 'Harvesting/PHH',
        '8' => 'Farming as a Business',
        '9' => 'Livestock Rearing',
        '10' => 'Health',
        '11' => 'Education',
        '12' => 'Agricultural Financing',
        '13' => 'Other'
    };

    // A map of to calculate hh members count score
    private static Map<String, Decimal> hhMembersMap = new Map<String, Decimal> {
        '1' => 0,
        '2' => 6,
        '3' => 9,
        '4' => 14,
        '5' => 27
    };

    // A map of to calculate children in school score
    private static Map<String, Decimal> childrenInSchoolMap = new Map<String, Decimal> {
        '1' => 0,
        '2' => 2,
        '3' => 4,
        '4' => 5
    };

    // A map of to calculate highest grade female score
    private static Map<String, Decimal> femaleGradeMap = new Map<String, Decimal> {
        '1' => 0,
        '2' => 2,
        '3' => 6,
        '4' => 8,
        '5' => 19
    };

    // A map to calculate score of major roof material
    private static Map<String, Decimal> roofMaterialMap = new Map<String, Decimal> {
        '1' => 0,
        '2' => 5
    };

    // A map to calculate score of major wall material
    private static Map<String, Decimal> wallMaterialMap = new Map<String, Decimal> {
        '1' => 0,
        '2' => 2
    };

    // A map to calculate score of lighting source
    private static Map<String, Decimal> lightingSourceMap = new Map<String, Decimal> {
        '1' => 0,
        '2' => 11,
        '3' => 17 
    };

    // A map to calculate score of toilet type
    private static Map<String, Decimal> toiletTypeMap = new Map<String, Decimal> {
        '1' => 0,
        '2' => 4
    };

    // A map to calculate score of toilet type
    private static Map<String, Decimal> ownElectricEquipmentMap = new Map<String, Decimal> {
        '1' => 7,
        '2' => 0
    };

    // A map to calculate score of toilet type
    private static Map<String, Decimal> ownTwoClothesSetMap = new Map<String, Decimal> {
        '1' => 5,
        '2' => 0
    };

    // A map to calculate score of toilet type
    private static Map<String, Decimal> ownOnePairOfShoesMap = new Map<String, Decimal> {
        '1' => 9,
        '2' => 0
    };
}