src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>Use this record type for corporations or small businesses</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Foundation</fullName>
        <active>true</active>
        <description>Use this record type for foundation entities</description>
        <label>Foundation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Construct that represents a group of People. Used by features including Agriculture Information channel, survey assignment, bulk SMS.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this group active?</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CkwUniversalOwnershipPropagationTest.cls
/**
 * This class contains unit tests for validating the behavior of 
 * CkwUniversalContactOwnershipPropagationTrigger, CkwUniversalGroupOwnershipPropagationTrigger,
 * CkwUniversalPersonOwnershipPropagationTrigger
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public with sharing class CkwUniversalOwnershipPropagationTest {

	/**
	 * tests the propagation of ownership from contact to person
	 */
	@IsTest
	static void testPropagationFromContactToPerson(){
		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		system.assert(p != null);
		
		User user = new User(Alias = 'ckwtest', Email='ckwtest@testorg.com', 
	    	EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
	     	LocaleSidKey='en_US', ProfileId = p.Id, 
	     	TimeZoneSidKey='America/Los_Angeles', UserName='ckwtest@testorg.com');
		insert user;
		
		RecordType recordType = new RecordType();
    	recordType.Name='Business';
    	
    	Account account = new Account(Name='CKW', RecordType=recordType);
    	account.BillingState='CA';
    	insert account;
    	
    	Contact contact = new Contact();
    	contact.FirstName = 'Grameen';
    	contact.LastName = 'Foundation';
    	contact.AccountId = account.Id;
    	insert contact;
    	
    	Person__c person = new Person__c();
    	person.Last_Name__c = 'Foundation';
    	person.First_Name__c = 'Grameen';
    	person.Contact__c = contact.Id;
    	insert person;
    	
    	system.assertEquals(contact.OwnerId, person.OwnerId);
    	contact.OwnerId = user.Id;
    	update contact;
    	
    	person = [SELECT Id, OwnerId FROM Person__c WHERE Id = :person.Id];
    	
    	system.assertEquals(person.OwnerId, user.Id);
	}
	
	/**
	 * tests the propagation of ownership from person to contact
	 */
	@IsTest
	static void testPropagationFromPersonToContact() {
		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		system.assert(p != null);
		
		User user = new User(Alias = 'ckwtest', Email='ckwtest@testorg.com', 
	    	EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
	     	LocaleSidKey='en_US', ProfileId = p.Id, 
	     	TimeZoneSidKey='America/Los_Angeles', UserName='ckwtest@testorg.com');
		insert user;
		
		RecordType recordType = new RecordType();
    	recordType.Name='Business';
    	
    	Account account = new Account(Name='CKW', RecordType=recordType);
    	account.BillingState='CA';
    	insert account;
    	
    	Contact contact = new Contact();
    	contact.FirstName = 'Grameen';
    	contact.LastName = 'Foundation';
    	contact.AccountId = account.Id;
    	insert contact;
    	
    	Person__c person = new Person__c();
    	person.Last_Name__c = 'Foundation';
    	person.First_Name__c = 'Grameen';
    	person.Contact__c = contact.Id;
    	insert person;
    	
    	system.assertEquals(contact.OwnerId, person.OwnerId);
    	person.OwnerId = user.Id;
    	update person;
    	
    	contact = [SELECT Id, OwnerId FROM Contact WHERE Id = :contact.Id];
    	
    	system.assertEquals(contact.OwnerId, user.Id);
	}
	
	/**
	 * tests the propagation from the Group__c record to the gfsurveys__ContactGroup__c
	 */
	@IsTest
	static void testPropagationFromGroupToGfSurveyGroup() {
		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		system.assert(p != null);
		
		User user = new User(Alias = 'ckwtest', Email='ckwtest@testorg.com', 
	    	EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
	     	LocaleSidKey='en_US', ProfileId = p.Id, 
	     	TimeZoneSidKey='America/Los_Angeles', UserName='ckwtest@testorg.com');
		insert user;
		
		gfsurveys__ContactGroup__c gfGroup = new gfsurveys__ContactGroup__c();
    	gfGroup.Name = 'Testing';
    	gfGroup.gfsurveys__Description__c = 'Testing Trigger';
    	insert gfGroup;
    	
    	/*
    	 * record would have been created because of the 
    	 * GfSurveyContactGroupTrigger
    	 */
    	Group__c ckwGroup = [SELECT Id, Name, Active__c FROM Group__c WHERE Name=:gfGroup.Name];
    	ckwGroup.OwnerId = user.Id;
    	update ckwGroup;
    	
    	gfGroup = [SELECT Id, OwnerId FROM gfsurveys__ContactGroup__c WHERE Id = :gfGroup.Id];
    	
    	system.assertEquals(gfGroup.OwnerId, user.Id);
	}
}