src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Foundation</fullName>
        <active>true</active>
        <description>Use this record type for foundation entities</description>
        <label>Foundation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Active_Date__c</fullName>
        <description>The date that the ckw passed their training</description>
        <label>Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of CKW</description>
        <label>CKW Status</label>
        <picklist>
            <picklistValues>
                <fullName>Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Construct that represents a group of People. Used by features including Agriculture Information channel, survey assignment, bulk SMS.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Current_Poverty_Scorecard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The most recent poverty scorecard for this person</description>
        <label>Current Poverty Scorecard</label>
        <referenceTo>Poverty_Scorecard__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Village__c</fullName>
        <description>Village that the person lives in</description>
        <label>Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person_Group_Association__c.object
<CustomObject>
    <description>Junction object used for many-to-many relationship between Person and Group objects. The existence of a Person-Group Association is what defines a single &quot;membership&quot;.</description>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group associated with this junction object</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person-Group Association</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Person Group Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person-Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person_Organisation_Association__c.object
<CustomObject>
    <description>Links a person to an organisation/partner/farmer group/account/whatever the hell we are calling them</description>
    <fields>
        <fullName>Organisation__c</fullName>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Person Organisation Associations</relationshipLabel>
        <relationshipName>Person_Organisation_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Person Organisation Associations</relationshipLabel>
        <relationshipName>Person_Organisation_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person Organisation Association</label>
    <nameField>
        <displayFormat>POA-{0000000}</displayFormat>
        <label>Person Organisation Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Organisation Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Poverty_Scorecard__c.object
<CustomObject>
    <description>Poverty scorecard data for a person in our system</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Person with whom this poverty data is associated</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Poverty Scorecards</relationshipLabel>
        <relationshipName>Poverty_Scorecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Poverty_Percentage__c</fullName>
        <description>Calculate the poverty percentage based on the score</description>
        <formula>CASE( Score__c ,
    0, 97.20,
    1, 97.20,
    2, 97.20,
    3, 97.20,
    4, 97.20,
    5, 95.20,
    6, 95.20,
    7, 95.20,
    8, 95.20,
    9, 95.20,
    10, 93.60,
    11, 93.60,
    12, 93.60,
    13, 93.60,
    14, 93.60,
    15, 80.60,
    16, 80.60,
    17, 80.60,
    18, 80.60,
    19, 80.60,
    20, 76.10,
    21, 76.10,
    22, 76.10,
    23, 76.10,
    24, 76.10,
    25, 71.20,
    26, 71.20,
    27, 71.20,
    28, 71.20,
    29, 71.20,
    30, 62.50,
    31, 62.50,
    32, 62.50,
    33, 62.50,
    34, 62.50,
    35, 47.70,
    36, 47.70,
    37, 47.70,
    38, 47.70,
    39, 47.70,
    40, 44.00,
    41, 44.00,
    42, 44.00,
    43, 44.00,
    44, 44.00,
    45, 38.70,
    46, 38.70,
    47, 38.70,
    48, 38.70,
    49, 38.70,
    50, 27.00,
    51, 27.00,
    52, 27.00,
    53, 27.00,
    54, 27.00,
    55, 26.20,
    56, 26.20,
    57, 26.20,
    58, 26.20,
    59, 26.20,
    60, 13.30,
    61, 13.30,
    62, 13.30,
    63, 13.30,
    64, 13.30,
    65, 8.10,
    66, 8.10,
    67, 8.10,
    68, 8.10,
    69, 8.10,
    70, 6.50,
    71, 6.50,
    72, 6.50,
    73, 6.50,
    74, 6.50,
    75, 3.10,
    76, 3.10,
    77, 3.10,
    78, 3.10,
    79, 3.10,
    80, 2.70,
    81, 2.70,
    82, 2.70,
    83, 2.70,
    84, 2.70,
    85, 1.30,
    86, 1.30,
    87, 1.30,
    88, 1.30,
    89, 1.30,
    90, 0.70,
    91, 0.70,
    92, 0.70,
    93, 0.70,
    94, 0.70,
    0.00)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Poverty Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Poverty Scorecard</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Poverty Scorecard ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Poverty Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <description>Surveys run by CKWs. There is one entry here for each type of survey. Survey questions (and responses) are NOT stored here.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that ordered to run the survey</description>
        <inlineHelpText>Select the customer who ordered to run the survey</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduledDailyMetricsUpdate.cls
global class ScheduledDailyMetricsUpdate implements Schedulable {

    // CronExpression = Seconds Minutes Hours Day_of_month Month Day_of_week optional_year
    public static String cronExpression = '0 0 2 * * ?'; // run every day at 2am

    global void execute(SchedulableContext sc) {

        // Get the organisation
        Account partner = [
            SELECT
                Name
            FROM
                Account
            WHERE
                Name = 'Grameen Foundation'
            ];

        // Start Batch Apex job to update the farmer metrics.
        List<String> farmerMetricList = new List<String>();

        // The following metrics should only be calculated if this is not the first month of the quarter
        Boolean calculateRepeats = false;
        Integer month = date.today().month();
        if (month != 1 && month != 4 && month != 7 && month != 10) {
            calculateRepeats = true;
            farmerMetricList.add('percent_repeat_farmers');
            farmerMetricList.add('percent_repeat_farmers_female');
            farmerMetricList.add('percent_repeat_farmers_poor');
        }
        farmerMetricList.add('total_poor_farmers_reached');
        farmerMetricList.add('total_farmers_reached');
        farmerMetricList.add('total_female_farmers_reached');
        farmerMetricList.add('total_villages');
        farmerMetricList.add('average_quarterly_total_repeat_usage');
        farmerMetricList.add('average_quarterly_poor_repeat_usage');
        farmerMetricList.add('average_quarterly_woman_repeat_usage');
        String farmerQuery =
            'SELECT '                   +
                'Name, '                +
                'Id, '                  +
                'Person__c, '           +
                'Person__r.Gender__c, ' +
                'Person__r.Village__c ' +
            'FROM '                     +
                'Farmer__c '            +
            'WHERE '                    +
                'Name LIKE \'UA%\' '    +
                'OR Name LIKE \'UB%\'';
        ID batchprocessid = Database.executeBatch(new FarmerMetrics(farmerQuery, farmerMetricList, calculateRepeats, partner));

        // Start the Batch Apex for the CKW metrics
        String ckwQuery = 
            'SELECT '                                  +
                'Id, '                                 +
                'Active_Date__c, '                     +
                'Status__c, '                          +
                'Person__c '                           +
            'FROM '                                    +
                'CKW__c '                              +
            'WHERE '                                   +
                'Person__c NOT IN ('                   +
                    'SELECT '                          +
                        'Person__c '                   +
                    'FROM '                            +
                        'Person_Group_Association__c ' +
                    'WHERE '                           +
                        'Group__r.Name = \''           +
                            'Applab Staff'             +
                        '\''                           +
                ')';
        List<String> metricList = new List<String>();
        metricList.add('total_interactions_surveys');
        metricList.add('total_interactions_searches');
        metricList.add('total_interactions_channels');
        metricList.add('percent_ckws_high_performance');
        metricList.add('total_info_services_offered');
        metricList.add('total_ckws');
        metricList.add('percent_poor_ckws');
        metricList.add('percent_woman_ckws');
        ID ckwBatchProcessId = Database.executeBatch(new CKWMetrics(ckwQuery, metricList, false, partner));

        Account naads = [
            SELECT
                Name
            FROM
                Account
            WHERE
                Name = 'NAADS'
            ];

        String naadsQuery = 
            'SELECT '                                                  +
                'Id, '                                                 +
                'District__r.Name, '                                   +
                'Current_Poverty_Scorecard__r.Poverty_Percentage__c, ' +
                'Gender__c '                                           +
            'FROM '                                                    +
                'Person__c '                                           +
            'WHERE '                                                   +
                'Id IN ('                                              +
                    'SELECT '                                          +
                        'Person__c '                                   +
                    'FROM '                                            +
                        'Person_Organisation_Association__c '          +
                    'WHERE '                                           +
                        'Organisation__r.Name = \''                    +
                            'NAADS'                                    +
                        '\''                                           +
                ') '                                                   +
                'AND Id NOT IN (SELECT Person__c FROM Farmer__c)';

        Map<String, Survey__c> surveyMap = new Map<String, Survey__c>();
        Survey__c[] surveys = [
            SELECT
                Id,
                Name
            FROM
                Survey__c
            WHERE
                Account__r.Name = 'NAADS'];
        for (Survey__c survey : surveys ) {
            surveyMap.put(survey.Id, survey);
        }
        ID naadsBatchProcessId = Database.executeBatch(new PartnerMetrics(naadsQuery, naads, NaadsMAndEDashboardParameters.getParameters(false), surveyMap));
    }
}