src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>Use this record type for corporations or small businesses</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Foundation</fullName>
        <active>true</active>
        <description>Use this record type for foundation entities</description>
        <label>Foundation</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EADD_Farmer_extra_info__c.object
<CustomObject>
    <description>Extra information from an EADD Farmer</description>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>District of the dairy farmer</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>EADD Farmer extra info</relationshipLabel>
        <relationshipName>EADD_Farmer_extra_info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty of the dairy farmer</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>EADD Farmer extra info</relationshipLabel>
        <relationshipName>EADD_Farmer_extra_info</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EADD Farmer extra info</label>
    <nameField>
        <label>EADD Farmer extra info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EADD Farmer extra info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EADD_Hub__c.object
<CustomObject>
    <description>An EADD Hub or Milk collection center</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date for collection of this data</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>District In which the Hub is located</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>EADD Hubs</relationshipLabel>
        <relationshipName>EADD_Hubs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Farmers_served_by_hub__c</fullName>
        <description>Number of farmers that bring milk to the hub</description>
        <inlineHelpText>Number of farmers that bring milk to the hub</inlineHelpText>
        <label>Farmers served by hub</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milk_sale_profits__c</fullName>
        <label>Milk sale profits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milk_sale_revenue__c</fullName>
        <label>Milk sale revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milk_volumes_bulked__c</fullName>
        <label>Milk volumes bulked</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>EADD Hubs</relationshipLabel>
        <relationshipName>EADD_Hubs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EADD Hub</label>
    <nameField>
        <label>EADD Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EADD Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <fields>
        <fullName>Further_Link_Text__c</fullName>
        <description>The text that is displayed on the link</description>
        <inlineHelpText>Put something meaningful and human readable</inlineHelpText>
        <label>Further Link Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Further_Link_Url__c</fullName>
        <description>The link to a VF page that will open when the link is pressed</description>
        <inlineHelpText>Only needs to be the file extensions. Will assume that it is on the same server</inlineHelpText>
        <label>Further Link Url</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>The label for this metric. Will be displayed on the dashboard.</description>
        <inlineHelpText>The label for this metric. Will be displayed on the dashboard.</inlineHelpText>
        <label>Label</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>M&amp;E Metrics</relationshipLabel>
        <relationshipName>M_E_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Organisation_District_Association__c.object
<CustomObject>
    <description>Link a partner to a district that they are working in.</description>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Organisation District Associations</relationshipLabel>
        <relationshipName>Organisation_District_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Organisation District Associations</relationshipLabel>
        <relationshipName>Organisation_District_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Organisation District Association</label>
    <nameField>
        <label>Organisation District Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisation District Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EADDHelpers.cls
/**
 *
 * Copyright (c) 2013 AppLab, Grameen Foundation
 *
 *  This is class provides assistance to the EADD Dashboard controller
 *  Its test methods are in the EADDDashboardTests class 
 **/
 public with sharing class EADDHelpers {
 	 	
 	/*
 	 * Metrics related to EADD Hub survey.
 	 *
 	 * business-performance section metrics */
 	public static final String NUMBER_OF_FARMERS_SUPPLYING_MILK = 'EADD_farmers_supplying_milk';
 	public static final String MILK_VOLUME_BULKED = 'EADD_milk_volume_bulked';
 	public static final String REVENUE_RAISED_FROM_MILK_SALES = 'EADD_revenue_from_milk_sales';
 	public static final String PROFIT_RAISED_FROM_MILK_SALES = 'EADD_profit_from_milk_sales';
 	
 	/*
 	 * Metrics related to EADD Farmer reg extra info survey
 	 *
 	 * famers-reached section metrics */
 	public static final String AVERAGE_NUMBER_OF_FARMERS_REACHED = 'EADD_average_farmers_reached';
 	public static final String FEMALE_NUMBER_OF_FARMERS_REACHED = 'EADD_female_farmers_reached';
 	public static final String MALE_NUMBER_OF_FARMERS_REACHED = 'EADD_male_farmers_reached';
 	public static final String YOUTH_NUMBER_OF_FARMERS_REACHED = 'EADD_youth_farmers_reached';
 	
 	/* metrics for 	access-to-business-dev't-services section */
 	public static final String FARMERS_ACCESSING_INPUTS = 'EADD_farmers_accessing_inputs';
 	public static final String FEMALE_FARMERS_ACCESSING_INPUTS = 'EADD_female_farmers_accessing_inputs';
 	public static final String MALE_FARMERS_ACCESSING_INPUTS = 'EADD_male_farmers_accessing_inputs';
 	public static final String YOUTH_FARMERS_ACCESSING_INPUTS = 'EADD_youth_farmers_accessing_inputs';
 	
 	public static final String FARMERS_ACCESSING_AI = 'EADD_farmers_accessing_ai';
 	public static final String FEMALE_FARMERS_ACCESSING_AI = 'EADD_female_farmers_accessing_ai';
 	public static final String MALE_FARMERS_ACCESSING_AI = 'EADD_male_farmers_accessing_ai';
 	public static final String YOUTH_FARMERS_ACCESSING_AI = 'EADD_youth_farmers_accessing_ai';
	
 	public static final String FARMERS_ACCESSING_HEALTH = 'EADD_farmers_accessing_health';
 	public static final String FEMALE_FARMERS_ACCESSING_HEALTH = 'EADD_female_farmers_accessing_health';
 	public static final String MALE_FARMERS_ACCESSING_HEALTH = 'EADD_male_farmers_accessing_health';
 	public static final String YOUTH_FARMERS_ACCESSING_HEALTH = 'EADD_youth_farmers_accessing_health';

 	public static final String FARMERS_ACCESSING_TRAINING = 'EADD_farmers_accessing_training';
 	public static final String FEMALE_FARMERS_ACCESSING_TRAINING = 'EADD_female_farmers_accessing_training';
 	public static final String MALE_FARMERS_ACCESSING_TRAINING = 'EADD_male_farmers_accessing_training';
 	public static final String YOUTH_FARMERS_ACCESSING_TRAINING = 'EADD_youth_farmers_accessing_training';
 	
 	public static final String FARMERS_ACCESSING_SUPPLIES = 'EADD_farmers_accessing_supplies';
 	public static final String FEMALE_FARMERS_ACCESSING_SUPPLIES = 'EADD_female_farmers_accessing_supplies';
 	public static final String MALE_FARMERS_ACCESSING_SUPPLIES = 'EADD_male_farmers_accessing_supplies';
 	public static final String YOUTH_FARMERS_ACCESSING_SUPPLIES = 'EADD_youth_farmers_accessing_supplies';
 	
 	public static final String FARMERS_ACCESSING_FINANCIAL_SERVICES = 'EADD_farmers_accessing_financial_services';
 	public static final String FEMALE_FARMERS_ACCESSING_FINANCIAL_SERVICES = 'EADD_female_farmers_accessing_financial_services';
 	public static final String MALE_FARMERS_ACCESSING_FINANCIAL_SERVICES = 'EADD_male_farmers_accessing_financial_services';
 	public static final String YOUTH_FARMERS_ACCESSING_FINANCIAL_SERVICES = 'EADD_youth_farmers_accessing_financial_services';
 	
 	public static final String FARMERS_ACCESSING_TRANSPORT = 'EADD_farmers_accessing_transport';
 	public static final String FEMALE_FARMERS_ACCESSING_TRANSPORT = 'EADD_female_farmers_accessing_transport';
 	public static final String MALE_FARMERS_ACCESSING_TRANSPORT = 'EADD_male_farmers_accessing_transport';
 	public static final String YOUTH_FARMERS_ACCESSING_TRANSPORT = 'EADD_youth_farmers_accessing_transport';
 	
 	public static final String FARMERS_ACCESSING_CHECKOFF_SERVICES = 'EADD_farmers_accessing_checkoff_services';
 	public static final String FEMALE_FARMERS_ACCESSING_CHECKOFF_SERVICES = 'EADD_female_farmers_accessing_checkoff_services';
 	public static final String MALE_FARMERS_ACCESSING_CHECKOFF_SERVICES = 'EADD_male_farmers_accessing_checkoff_services';
 	public static final String YOUTH_FARMERS_ACCESSING_CHECKOFF_SERVICES = 'EADD_youth_farmers_accessing_checkoff_services';
 	
 	/* metrics for technology adoption */
 	public static final String FARMERS_USING_AI = 'EADD_farmers_using_ai';
 	public static final String FEMALE_FARMERS_USING_AI = 'EADD_female_farmers_using_ai';
 	public static final String MALE_FARMERS_USING_AI = 'EADD_male_farmers_using_ai';
 	public static final String YOUTH_FARMERS_USING_AI = 'EADD_youth_farmers_using_ai';
 	
 	public static final String FARMERS_USING_DRY_SEASON_FEEDING = 'EADD_farmers_using_dry_season_feeding';
 	public static final String FEMALE_FARMERS_USING_DRY_SEASON_FEEDING = 'EADD_female_farmers_using_dry_season_feeding';
 	public static final String MALE_FARMERS_USING_DRY_SEASON_FEEDING = 'EADD_male_farmers_using_dry_season_feeding';
 	public static final String YOUTH_FARMERS_USING_DRY_SEASON_FEEDING = 'EADD_youth_farmers_using_dry_season_feeding';
 	
 	public static final String FARMERS_USING_SUPPLEMENTARY = 'EADD_farmers_using_supplementary';
 	public static final String FEMALE_FARMERS_USING_SUPPLEMENTARY = 'EADD_female_farmers_using_supplementary';
 	public static final String MALE_FARMERS_USING_SUPPLEMENTARY = 'EADD_male_farmers_using_supplementary';
 	public static final String YOUTH_FARMERS_USING_SUPPLEMENTARY = 'EADD_youth_farmers_using_supplementary';
 	
 	public static final String FARMERS_USING_HIGH_QUALITY = 'EADD_farmers_using_high_quality';
 	public static final String FEMALE_FARMERS_USING_HIGH_QUALITY = 'EADD_female_farmers_using_high_quality';
 	public static final String MALE_FARMERS_USING_HIGH_QUALITY = 'EADD_male_farmers_using_high_quality';
 	public static final String YOUTH_FARMERS_USING_HIGH_QUALITY = 'EADD_youth_farmers_using_high_quality';
 	
	public static String getSubcounties(){
		String inclause =
                ' AND '                                           	+
                    'District__c IN ('                             	+
                        'SELECT '                                   +
                            'District__c '                          +
                        'FROM '                                     +
                            'Organisation_District_Association__c ' +
                        'WHERE '                                    +
                            'Organisation__r.Name = \'EADD\''		+
                    ') ';
		return 'SELECT Id, '					+
					'Display_Name__c, '			+
					'District__c '				+
				'FROM Subcounty__c '			+
				'WHERE District__c != NULL '	+
				'	AND  District__c != \'\' '	+
					inclause					+
				'ORDER BY Display_Name__c ';
	}
    
    public static Map<String, M_E_Metric__c> getAllMetrics(){
		String query = 'SELECT '										+
							'Id, '										+
							'Name, '									+
							'Label__c, '								+
							'Projected_Value__c, '						+
							'Further_Link_Text__c, '					+
							'Further_Link_Url__c '						+
						'FROM '											+
							'M_E_Metric__c ' 							+
						'WHERE '										+
							'Name LIKE \'EADD_%\' ';
		Map<String, M_E_Metric__c> metricMap = new Map<String, M_E_Metric__c>();
		for(M_E_Metric__c metric : database.query(query)){
			metricMap.put(metric.Name, metric);
		}
		return metricMap;
    }
    
    public static String getFarmersActualValueQuery(String district, String subcounty, String dateFrom, String dateTo){
    	String query =	getCountAllQuery(district, subcounty, dateFrom, dateTo);
    	System.debug(query);
    	return query;
    }
    
    public static String getGenderFarmersQuery(String district, String subcounty, String dateFrom, String dateTo){
    	return getCountAllByGenderQuery(district, subcounty, dateFrom, dateTo) + 'GROUP BY Gender__c  ORDER BY Gender__c ';
    }    
    
    public static String getYouthFarmersQuery(String district, String subcounty, String dateFrom, String dateTo){
    	return getCountAllQuery(district, subcounty, dateFrom, dateTo) + 'AND Age__c < 45';
    }	
    
    public static String getSuppliersActualValueQuery(String district, String subcounty, String dateFrom, String dateTo){    	
		return getActualValueQuery(district, subcounty, dateFrom, dateTo, 'Farmers_served_by_hub__c');
    }
    
    public static String getVolumesBulkedActualValueQuery(String district, String subcounty, String dateFrom, String dateTo){    	
		return getActualValueQuery(district, subcounty, dateFrom, dateTo, 'Milk_volumes_bulked__c');
    }
    
    public static String getRevenueActualValueQuery(String district, String subcounty, String dateFrom, String dateTo){    	
		return getActualValueQuery(district, subcounty, dateFrom, dateTo, 'Milk_sale_revenue__c');
    }
    
    public static String getProfitActualValueQuery(String district, String subcounty, String dateFrom, String dateTo){    	
		return getActualValueQuery(district, subcounty, dateFrom, dateTo, 'Milk_sale_profits__c');
    }
    
    public static String getGenderActualValueQuery(String district, String subcounty, String dateFrom, String dateTo, String column){
    	return	getCountAllByGenderQuery(district, subcounty, dateFrom, dateTo) +
    			'AND ' + column + ' = TRUE ' +
    			'GROUP BY Gender__c  ORDER BY Gender__c ';
    }
    
    public static String getYouthActualValueQuery(String district, String subcounty, String dateFrom, String dateTo, String column){
    	return	getCountAllQuery(district, subcounty, dateFrom, dateTo) + 
    			'AND ' + column + ' = TRUE ' +
    			'AND Age__c < 45';
    }
    
    /*
     * There are many normal queries you cant run in SOQL
     * That being said, we have to get the Ids of the most
     * recent metric since a new metric is created monthly.
     * Then we return a query sum suppliers
     *
     * @param district	- district if not null then filter by
     * @param subcounty	- subcounty if not null then filter by
     * @param dateFrom	- filter start date
     * @param dateTo	- filter end date
     * @param column	- the column whose aggregate to return
     * @return querry 	- string querry
     */
    public static String getActualValueQuery(String district, String subcounty, String dateFrom, String dateTo, String column){
    	
		String ids = getIdsOfLatestHubInformation();
		String inClause = '';
		if(ids != ''){
			inClause = 	'Id IN ('		+
								ids		+
							') '		+
						'AND ';
		}
							
		String query = 	'SELECT '								+
							'SUM(' + column + ') '				+
						'FROM '									+
						'EADD_Hub__c '							+
						'WHERE '								+
								inClause						+ 
							'District__c != NULL '				+ 
							'AND Subcounty__c != NULL '			+
							getDistrictAndSubcountyClause(district, subcounty, dateFrom, dateTo);
    	
    	return query;
    }
    
    /*
    * a hub can have multiple details, we always want the latest information
    */
    public static String getIdsOfLatestHubInformation(){
		String ids = '';
		String recordIds = 	'SELECT Id, MAX(Date__c) ' 	+
		    				'FROM EADD_Hub__c '			+
		    				'GROUP BY Id ';
		for(AggregateResult[] results : database.query(recordIds)){
		    for(AggregateResult result : results){
		        if(ids == ''){
		            ids = '\'' + (String)result.get('Id') + '\'';
		        }else{
		            ids += ',\'' + (String)result.get('Id') + '\'';
		        }
		    }
		}
		return ids;
    }
    
    public static String getCountAllQuery(String district, String subcounty, String dateFrom, String dateTo){
    	return	'SELECT '						+
					'COUNT(Id) '				+
				'FROM '							+
					'EADD_Farmer_extra_info__c '+ 
				'WHERE '						+
					'District__c != NULL '		+ 
					'AND Subcounty__c != NULL '	+
					getDistrictAndSubcountyClause(district, subcounty, dateFrom, dateTo) + ' ';
    }
       
    public static String getCountAllByGenderQuery(String district, String subcounty, String dateFrom, String dateTo){
    	return	'SELECT '						+
					'COUNT(Id), Gender__c '		+
				'FROM '							+
					'EADD_Farmer_extra_info__c '+ 
				'WHERE '						+
					'District__c != NULL '		+ 
					'AND Subcounty__c != NULL '	+
					getDistrictAndSubcountyClause(district, subcounty, dateFrom, dateTo) + ' ';
    }
    
    public static String getDistrictAndSubcountyClause(String district, String subcounty, String dateFrom, String dateTo){
        // Check to see if we have a district and subcounty to check.
        String districtNameClause = 'null';
        String subcountyNameClause = 'null';
        String query = '';
        if (district != null && !district.equals('')) {
            query += ' AND District__r.Name = \'' + district + '\' ';
        }
        if (subcounty != null && !subcounty.equals('')) {
            query += 'AND Subcounty__r.Display_Name__c = \'' + subcounty + '\' ';
        }
		
		if(dateFrom != null && !dateFrom.equals('')){
			query += ' AND Date__c >= ' + dateFrom + ' ';
		}
		if(dateTo != null && !dateTo.equals('')){
			query += ' AND Date__c <= ' + dateTo + ' ';
		}
		return query;
    }
}