src/objects/Alsur_Farmer__c.object
<CustomObject>
    <fields>
        <fullName>Association__c</fullName>
        <label>Association</label>
        <referenceTo>Association__c</referenceTo>
        <relationshipLabel>Alsur Farmers</relationshipLabel>
        <relationshipName>Alsur_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Alsur Farmer</label>
    <nameField>
        <label>Alsur Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alsur Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Association__c.object
<CustomObject>
    <description>Associations that ALSUR contacts when it receives orders from its clients</description>
    <label>Association</label>
    <nameField>
        <label>Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPA_Order__c.object
<CustomObject>
    <description>Client Product Association Order object</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CPA Orders</relationshipLabel>
        <relationshipName>CPA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>CPA Order</label>
    <nameField>
        <displayFormat>Order-{00000}</displayFormat>
        <label>CPA Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPA_Order_Allocation__c.object
<CustomObject>
    <description>ALSUR: Allocation of Orders to Associations</description>
    <fields>
        <fullName>Association__c</fullName>
        <label>Association</label>
        <referenceTo>Association__c</referenceTo>
        <relationshipLabel>CPA Order Allocations</relationshipLabel>
        <relationshipName>CPA_Order_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPA_Order__c</fullName>
        <label>CPA Order</label>
        <referenceTo>CPA_Order__c</referenceTo>
        <relationshipLabel>CPA Order Allocations</relationshipLabel>
        <relationshipName>CPA_Order_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CPA Order Allocation</label>
    <nameField>
        <displayFormat>CPAON-{000}</displayFormat>
        <label>CPA Order Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Order Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Farmer_Order_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Alsur_Farmer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Alsur Farmer</label>
        <referenceTo>Alsur_Farmer__c</referenceTo>
        <relationshipLabel>Farmer Order Allocations</relationshipLabel>
        <relationshipName>Farmer_Order_Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPA_Order_Allocation__c</fullName>
        <label>CPA Order Allocation</label>
        <referenceTo>CPA_Order_Allocation__c</referenceTo>
        <relationshipLabel>Farmer Order Allocations</relationshipLabel>
        <relationshipName>Farmer_Order_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Delivery Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Shows whether an order was assigned to a provider or not.</description>
        <label>Provider</label>
        <picklist>
            <picklistValues>
                <fullName>Sí</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Farmer Order Allocation</label>
    <nameField>
        <displayFormat>FOAN-{00000000}</displayFormat>
        <label>Farmer Order Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmer Order Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Farmer_Product_Delivery__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Delivery Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Farmer_Order_Allocation__c</fullName>
        <label>Farmer Order Allocation</label>
        <referenceTo>Farmer_Order_Allocation__c</referenceTo>
        <relationshipLabel>Farmer Product Deliveries</relationshipLabel>
        <relationshipName>Farmer_Product_Deliveries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>typeOfDelivery__c</fullName>
        <description>Marks whether and delivery was equal to the initial order</description>
        <label>Type of delivery</label>
        <picklist>
            <picklistValues>
                <fullName>Productor - entrega IGUAL a asignación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Productor-entrega DIFERENTE a asignación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proveedor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Farmer Product Delivery</label>
    <nameField>
        <displayFormat>FPD-{00000000}</displayFormat>
        <label>Farmer Product Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farmer Product Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAlsurCreateFarmerProdDeliverytrigger.cls
@isTest
private class TestAlsurCreateFarmerProdDeliverytrigger {
	
	@isTest 
	static void test_method_one() {
	
		Association__c association = new Association__c();
		association.Name = 'Alsur';
		insert association;

		Contact contact = new Contact();
		contact.LastName = 'testAlsurCreateProductDelivery';
		contact.FirstName = 'Contact';
		insert contact;

		Alsur_Farmer__c farmer = new Alsur_Farmer__c();
		farmer.Association__c = association.Id;
		insert farmer;

		CPA_Order__c order = new CPA_Order__c();
		order.Number_of_Units_of_Presentation__c = 10;
		order.Contact__c = contact.Id;
		insert order;

		CPA_Order_Allocation__c allocation = new CPA_Order_Allocation__c();
		allocation.Association__c = association.Id;
		allocation.CPA_Order__c = order.Id;
		allocation.Number_of_Units_of_Presentation__c = 10;
		insert allocation;
		
		Farmer_Order_Allocation__c farmerAllocation = new Farmer_Order_Allocation__c();
		farmerAllocation.Alsur_Farmer__c = farmer.Id;
		farmerAllocation.CPA_Order_Allocation__c = allocation.Id;
		farmerAllocation.Delivery_Date__c = System.today();
		farmerAllocation.Number_of_Units_of_Presentation__c = 3;
		farmerAllocation.Provider__c = 'No';
		insert farmerAllocation;

		Farmer_Product_Delivery__c farmerProductDelivery = new Farmer_Product_Delivery__c();
		farmerProductDelivery.Farmer_Order_Allocation__c = farmerAllocation.Id;
		farmerProductDelivery.TypeOfDelivery__c = 'Productor - entrega IGUAL a asignación';
		farmerProductDelivery.Number_of_Units_of_Presentation__c = 5;
		insert farmerProductDelivery;

		Farmer_Product_Delivery__c farmerProductDelivery2= new Farmer_Product_Delivery__c();
		farmerProductDelivery2.Farmer_Order_Allocation__c = farmerAllocation.Id;
		farmerProductDelivery2.TypeOfDelivery__c = 'Productor-entrega DIFERENTE a asignación';
		farmerProductDelivery2.Number_of_Units_of_Presentation__c = 5;
		insert farmerProductDelivery2;

		List<Farmer_Product_Delivery__c> deliveries = [SELECT Id, Farmer_Order_Allocation__c, TypeOfDelivery__c from Farmer_Product_Delivery__c where TypeOfDelivery__c = 'Productor - entrega IGUAL a asignación'];
		System.assertEquals(1, deliveries.size());

	}
		
}