src/objects/Application_Version__c.object
<CustomObject>
    <description>The version of an application.</description>
    <fields>
        <fullName>Application_Available__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this version of the application available to download</description>
        <inlineHelpText>Check to make this version available to the CKWs</inlineHelpText>
        <label>Application Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Name__c</fullName>
        <description>The name of the application that this version is for</description>
        <label>Application Name</label>
        <picklist>
            <picklistValues>
                <fullName>pulse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ckw search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ckw surveys</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Application_Version__c</fullName>
        <description>The version number for the application.</description>
        <inlineHelpText>The format for this is YYYYMMDDNN</inlineHelpText>
        <label>Application Version</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Name_Human_Readable__c</fullName>
        <description>The human readable version name E.g. 2.10, 2.11-pre3</description>
        <label>Version Name (Human Readable)</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Application Version</label>
    <nameField>
        <displayFormat>AppV-{0000}</displayFormat>
        <label>Application Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Versions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Application_Version_Group_Association__c.object
<CustomObject>
    <description>Links a group to an application version</description>
    <fields>
        <fullName>Application_Version__c</fullName>
        <description>The application that belongs to this group</description>
        <label>Application Version</label>
        <referenceTo>Application_Version__c</referenceTo>
        <relationshipLabel>Application Version Group Associations</relationshipLabel>
        <relationshipName>Application_Version_Group_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <description>The group that this association is for</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Application Version Group Associations</relationshipLabel>
        <relationshipName>Application_Version_Group_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Version Group Association</label>
    <nameField>
        <displayFormat>AVGA-{000000000}</displayFormat>
        <label>Application Version Group Association Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Version Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Construct that represents a group of People. Used by features including Agriculture Information channel, survey assignment, bulk SMS.</description>
    <fields>
        <fullName>Membership_Count__c</fullName>
        <description>The number of people that are in this group. Value is calculated daily by Apex.</description>
        <label>Membership Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Handset_Application_Association__c.object
<CustomObject>
    <description>Junction object to associate a Handset with a version of an installed application</description>
    <fields>
        <fullName>Application_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Version</label>
        <referenceTo>Application_Version__c</referenceTo>
        <relationshipLabel>Handsets Installed On</relationshipLabel>
        <relationshipName>Handset_Application_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Installed Applications</relationshipLabel>
        <relationshipName>Handset_Application_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Handset Application Association</label>
    <nameField>
        <label>Handset Application Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Handset Application Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District_Name__c</fullName>
        <formula>District__r.Name</formula>
        <label>District Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physical handset assigned to this Person (in the case of GF-managed assets)</description>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Assignee</relationshipLabel>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <description>Mobile phone number calculated based on Mobile Phone and Raw Mobile Number fields</description>
        <formula>/* If we have a Handset, use the number from its SIM Card */
IF( NOT( ISBLANK( Handset__c)),  
     Handset__r.SIM__r.Name, 
/* otherwise use the raw mobile number */
       Raw_Mobile_Number__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parish__c</fullName>
        <description>Parish</description>
        <label>Parish</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Village__c</fullName>
        <description>Village that the person lives in</description>
        <label>Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person_Group_Association__c.object
<CustomObject>
    <description>Junction object used for many-to-many relationship between Person and Group objects. The existence of a Person-Group Association is what defines a single &quot;membership&quot;.</description>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group associated with this junction object</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person-Group Association</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Person Group Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person-Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ApplicationManagementController.cls
public class ApplicationManagementController {

    public List<String> groups { get; set; }
    public List<SelectOption> groupsList;
    public List<SelectOption> getGroupsList() {

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','-- All Groups --'));
        Group__c[] groups = database.query(SoqlHelpers.getGroups());
        for (Group__c groupToAdd : groups) {
            options.add(new SelectOption(groupToAdd.Id, groupToAdd.Name));
        }
        return options;
    }

    public void setGroupsList(List<SelectOption> options) {
        this.groupsList = options;
    }

    public List<String> applications { get; set; }
    public List<SelectOption> applicationsList;
    public List<SelectOption> getApplicationsList() {

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','-- All Applications --'));
        Application_Version__c[] applications = database.query(SoqlHelpers.getApplications(true));
        for (Application_Version__c application : applications) {
            options.add(new SelectOption(application.Id, application.Application_Name__c + ' ' + application.Version_Name_Human_Readable__c));
        }
        return options;
    }

    public void setApplicationsList(List<SelectOption> options) {
        this.applicationsList = options;
    }

    public List<ApplicationGroupWrapper> applicationGroupList;
    public List<ApplicationGroupWrapper> getApplicationGroupList() {
        return this.applicationGroupList;
    }
    public void setApplicationGroupList(List<ApplicationGroupWrapper> applicationGroupList) {
        this.applicationGroupList = applicationGroupList;
    }

    public List<Person__c> applicationGroupPersonList;
    public List<Person__c> getApplicationGroupPersonList() {
        return this.applicationGroupPersonList;
    }
    public void setApplicationGroupPersonList(List<Person__c> applicationGroupPersonList) {
        this.applicationGroupPersonList = applicationGroupPersonList;
    }

    public Boolean showApplicationGroupList;
    public Boolean getShowApplicationGroupList() {
        return this.showApplicationGroupList;
    }
    public void setShowApplicationGroupList(Boolean show) {
        this.showApplicationGroupList = show;
    }

    public Boolean showPeopleList;
    public Boolean getShowPeopleList() {
        return this.showPeopleList;
    }
    public void setShowPeopleList(Boolean show) {
        this.showPeopleList = show;
    }

    public String errorMsg;
    public String getErrorMsg() {
        return this.errorMsg;
    }
    public void setErrorMsg(String msg) {

        if (this.errorMsg == null || this.errorMsg.equals('')) {
            this.errorMsg = msg;
        }
        else {
            this.errorMsg = this.errorMsg + '<br />' + msg;
        }
    }

    Transient Map<String, Group__c> groupTotalMap;

    // Constructor for this controller
    public ApplicationManagementController() {

        setUp();
    }

    private void setUp() {

        this.groups = new List<String>();
        this.applications = new List<String>();
        setErrorMsg('');
        setShowApplicationGroupList(false);
        setShowPeopleList(false);
    }

    public PageReference reloadPage() {

        // Decide which method has been called from the visualforce page.
        String method = Apexpages.currentPage().getParameters().get('methodParam');
        getParameters();
        if (method.equalsIgnoreCase('ADD')) {
            System.debug(LoggingLevel.INFO, 'Adding applications');
            return addApplications();
        }
        else if (method.equalsIgnoreCase('REMOVE')) {
            System.debug(LoggingLevel.INFO, 'Removeing applications');
            return removeApplications();
        }
        else if (method.equalsIgnoreCase('SHOW_GROUPS')) {
            System.debug(LoggingLevel.INFO, 'Showing apps in a group');
            setGroupMap(this.groups);
            return showApplicationsGroupCount();
        }
        else if (method.equalsIgnoreCase('SHOW_APPS')) {
            System.debug(LoggingLevel.INFO, 'Showing groups with an app');
            return showGroupsApplicationCount();
        }
        else if (method.equalsIgnoreCase('SHOW_PEOPLE')) {
            System.debug(LoggingLevel.INFO, 'Showing people ina a group with a particualar app');
            return getPeopleGroupApplication(this.groups.get(0), this.applications.get(0), Apexpages.currentPage().getParameters().get('negateParam'));
        }
        else {
        
            // Should not see this error. If it is shown there is a programming error
            setErrorMsg('Failed to run your query. Please try again');
            return null;
        }
    }

    /**
     *  Add the application versions passed in to the groups passed in
     */
    public PageReference addApplications() {

        if(checkParameters()) {

            System.debug(LoggingLevel.INFO, 'Adding applications: ' + this.applications + ' to groups: ' + this.groups);
            List<Application_Version_Group_Association__c> newVersions = new List<Application_Version_Group_Association__c>();
            for (String groupId : this.groups) {

                // Check the application versions that already exist so we are not duplicating them.
                List<String> groupIds = new List<String>();
                groupIds.add(groupId);
                Set<String> exisitingGroupAppIds = getApplicationIds(database.query(SoqlHelpers.getApplicationGroupAssociations(groupIds, this.applications, false, null, 'Application_Version__r.Application_Version__c')));
                for (String applicationId : this.applications) {
                    if (exisitingGroupAppIds.size() == 0 || !exisitingGroupAppIds.contains(applicationId)) {
                        Application_Version_Group_Association__c newAppVersion = new Application_Version_Group_Association__c();
                        newAppVersion.Group__c = groupId;
                        newAppVersion.Application_Version__c = applicationId;
                        newVersions.add(newAppVersion);
                    }
                }
            }

            // Batch the DML insert just incase. Need the batchNumber as SF doesn't support standard % operator
            Integer batchNumber = 1;
            Integer totalLinksAdded = 0;
            System.debug(LoggingLevel.INFO, 'Application Links to be added = ' + newVersions.size());
            List<Application_Version_Group_Association__c> newApplicationsBatch = new List<Application_Version_Group_Association__c>();
            for (Application_Version_Group_Association__c appVersion : newVersions) {
                newApplicationsBatch.add(appVersion);
                if (newApplicationsBatch.size() == (batchNumber * 100)) {
                    database.insert(newApplicationsBatch);
                    newApplicationsBatch.clear();
                    totalLinksAdded = totalLinksAdded + 100;
                    batchNumber++;
                }
            }

            // Add the last batch
            if (newApplicationsBatch.size() > 0) {
                totalLinksAdded = totalLinksAdded + newApplicationsBatch.size();
                database.insert(newApplicationsBatch);
            }
            System.debug(LoggingLevel.INFO, 'Application Links added = ' + totalLinksAdded);
        }
        return null;
    }

    /**
     *  Remove the application versions passed in from the groups passed in
     */
    public PageReference removeApplications() {

        if(checkParameters()) {
            Set<String> appIdsToDelete = new Set<String>();
            appIdsToDelete.addAll(this.applications);
            List<Application_Version_Group_Association__c> versionsToDelete = new List<Application_Version_Group_Association__c>();

            // Get the existing application versions for the group
            List<Application_Version_Group_Association__c> exisitingVersions = database.query(SoqlHelpers.getApplicationGroupAssociations(this.groups, this.applications, false, null, 'CreatedDate'));
            for (Application_Version_Group_Association__c exisitingVersion : exisitingVersions) {
                if (appIdsToDelete.contains(exisitingVersion.Application_Version__c)) {
                    versionsToDelete.add(exisitingVersion);
                }
            }
            System.debug(LoggingLevel.INFO, 'Apllication links to delete = ' + versionsToDelete.size());

            // Batch the DML delete just incase. Need the batchNumber as SF doesn't support standard % operator
            Integer batchNumber = 1;
            List<Application_Version_Group_Association__c> versionsToDeleteBatch = new List<Application_Version_Group_Association__c>();
            for (Application_Version_Group_Association__c appVersion : versionsToDelete) {
                versionsToDeleteBatch.add(appVersion);
                if (versionsToDeleteBatch.size() == (batchNumber * 100)) {
                    database.delete(versionsToDeleteBatch);
                    versionsToDeleteBatch.clear();
                    batchNumber++;
                }
            }

            // Delete the last batch
            if (versionsToDeleteBatch.size() > 0) {
                database.delete(versionsToDeleteBatch);
            }
        }
        return null;
    }

    /**
     *  Show a count of who does and does not have the application in all groups.
     */
    public PageReference showGroupsApplicationCount() {

        List<ApplicationGroupWrapper> counts = new List<ApplicationGroupWrapper>();
        if (this.applications == null || this.applications.size() == 1) {

            // Get all the groups that should have this application
            Application_Version_Group_Association__c[] appVersionGroupAssociaitons = database.query(SoqlHelpers.getApplicationGroupAssociations(null, this.applications, true, null, null));

            // Loop through each group and get the imeis for that group and then get the counts
            List<String> groupIds = new List<String>();
            for (Application_Version_Group_Association__c appVersionGroupAssociaiton :appVersionGroupAssociaitons) {
                String id = (String)appVersionGroupAssociaiton.Group__c;
                groupIds.add(id);
            }

            // Set up the group map
            setGroupMap(groupIds);
            for (String groupId : groupIds) {
                List<String> imeis = getImeiList(groupId);

                if (imeis.size() == 0) {

                    // No people in this group 
                }
                else {

                    // This should only return one row
                    AggregateResult[] appPersonCounts = database.query(SoqlHelpers.getApplicationPersonCount(this.applications, imeis));
                    if (appPersonCounts.size() == 0) {

                        // No people in this group with this app return a blank wrapper
                        ApplicationGroupWrapper applicationGroupWrapper = new ApplicationGroupWrapper(this.groupTotalMap.get(groupId).Name, 0, this.groupTotalMap.get(groupId).Membership_Count__c.intValue(), groupId, this.applications.get(0));
                        counts.add(applicationGroupWrapper);
                    }
                    else {
                        Integer total = (Integer)(appPersonCounts[0].get('total'));
                        String appId = (String)(appPersonCounts[0].get('app'));
                        ApplicationGroupWrapper applicationGroupWrapper = new ApplicationGroupWrapper(this.groupTotalMap.get(groupId).Name, total, this.groupTotalMap.get(groupId).Membership_Count__c.intValue() - total, groupId, appId);
                        counts.add(applicationGroupWrapper);
                    }
                }
            }
            setApplicationGroupList(counts);
            System.debug(LoggingLevel.INFO, 'Showing ' + counts.size() + ' in list');
            setShowApplicationGroupList(true);
            setShowPeopleList(false);
        }
        else {

            // Add the error message. Front end should not let us get here
            setErrorMsg('Please select one application only');
            setShowApplicationGroupList(false);
            setShowPeopleList(false);
        }
        return null;
    }

    /**
     *  Show counts for who has the current applications for a particular group
     */
    public PageReference showApplicationsGroupCount() {

        if(this.groups == null || this.groups.size() == 1) {

            // Get the latest applications for this group
            Application_Version_Group_Association__c[] appGroupLinks = database.query(SoqlHelpers.getApplicationGroupAssociations(this.groups, null, true, null, 'CreatedDate'));
            if (appGroupLinks.size() == 0) {
                setErrorMsg('There are no applications assigned to this group');
                return null;
            }
            Map<String, Application_Version_Group_Association__c> appGroupLinksMap = new Map<String, Application_Version_Group_Association__c>();
            for (Application_Version_Group_Association__c appGroupLink : appGroupLinks) {
                if (!appGroupLinksMap.keySet().contains(appGroupLink.Application_Version__r.Application_Name__c)) {
                    appGroupLinksMap.put(appGroupLink.Application_Version__r.Application_Name__c, appGroupLink);
                }
                else {
                    Application_Version_Group_Association__c comparison = appGroupLinksMap.get(appGroupLink.Application_Version__r.Application_Name__c);
                    if (comparison.Application_Version__r.Application_Version__c < appGroupLink.Application_Version__r.Application_Version__c) {
                        appGroupLinksMap.put(appGroupLink.Application_Version__r.Application_Name__c, appGroupLink);
                    }
                }
            }

            // Loop through the newest apps and count who has them and who doesn't
            List<String> appIds = new List<String>();
            for (String appName : appGroupLinksMap.keySet()) {
                appIds.add(appGroupLinksMap.get(appName).Application_Version__r.Id);
            }

            // Create a map of the applications that are being used so we can fill the details in
            String query =
                'SELECT '                             +
                    'Id, '                            +
                    'Name, '                          +
                    'Application_Name__c, '           +
                    'Version_Name_Human_Readable__c ' +
                'FROM '                               +
                    'Application_Version__c '         +
                'WHERE '                              +
                    'Id IN (' + MetricHelpers.generateCommaSeperatedString(appIds, true) + ')';
            System.debug(LoggingLevel.INFO, query);
            Application_Version__c[] applications = database.query(query);
            Map<String, Application_Version__c> appMap = new Map<String, Application_Version__c>(); 
            for (Application_Version__c application : applications) {
                String appId = (String)application.Id;
                appMap.put(appId, application);
            }

            // Get the IMEIs for this group
            List<String> imeis = getImeiList(this.groups.get(0));
            
            // For each application that we are looking at go and find the counts
            List<ApplicationGroupWrapper> counts = new List<ApplicationGroupWrapper>();

            AggregateResult[] appPersonCounts = database.query(SoqlHelpers.getApplicationPersonCount(appIds, imeis));
            Set<String> foundAppIds = new Set<String>();
            for (AggregateResult appPersonCount :appPersonCounts) {
                Integer total = (Integer)(appPersonCount.get('total'));
                String appId = (String)(appPersonCount.get('app'));
                foundAppIds.add(appId);
                Application_Version__c appVer = appMap.get(appId);
                ApplicationGroupWrapper applicationGroupWrapper = new ApplicationGroupWrapper(appVer.Application_Name__c + ' ' + appVer.Version_Name_Human_Readable__c, total, this.groupTotalMap.get(this.groups.get(0)).Membership_Count__c.intValue() - total, this.groups.get(0), appId);
                counts.add(applicationGroupWrapper);
            }

            // Loop through the apps and check that they were found. If not then create empty groups
            for (String appId : appIds) {
                if (!foundAppIds.contains(appId)) {
                    Application_Version__c appVer = appMap.get(appId);
                    ApplicationGroupWrapper applicationGroupWrapper = new ApplicationGroupWrapper(appVer.Application_Name__c + ' ' + appVer.Version_Name_Human_Readable__c, 0, this.groupTotalMap.get(this.groups.get(0)).Membership_Count__c.intValue(), this.groups.get(0), appId);
                    counts.add(applicationGroupWrapper);
                }
            }

            setApplicationGroupList(counts);
            System.debug(LoggingLevel.INFO, 'Showing ' + counts.size() + ' in list');
            setShowApplicationGroupList(true);
            setShowPeopleList(false);
        }
        else {

            // Add the error message. Front end should not let us get here
            setErrorMsg('Please select one group only');
            setShowApplicationGroupList(false);
            setShowPeopleList(false);
        }
        return null;
    }

    /**
     *  Show a list of people of either have an application in a group  or who don't
     *
     *  @param groupId       - Id of the group we are looking at
     *  @param applicationId - Id of the application we are looking at
     *  @param have          - true if they have this app, false if not
     */
    public PageReference getPeopleGroupApplication(String groupId, String applicationId, String have) {

        // Get the people we are looking for
        String query =
            'SELECT '               +
                'Id, '              +
                'First_Name__c, '   +
                'Last_Name__c, '    +
                'District__c, '     +
                'District_Name__c, '     +
                'Parish__c, '       +
                'Village__c, '      +
                'Mobile_Number__c ' +
            'FROM '                 +
                'Person__c '        +
            'WHERE '                +
                'Handset__c ';

        // Negate if required
        if (have.equals('false')) {
            query = query + ' NOT ';
        }
        query = query + 'IN ( '                                                 +
                    'SELECT '                                                   +
                        'Handset__c '                                           +
                    'FROM '                                                     +
                        'Handset_Application_Association__c '                   +
                    'WHERE '                                                    +
                        'Application_Version__r.Id = \'' + applicationId + '\'' +
                ') '                                                            +
                'AND Id IN ( '                                                  +
                    'SELECT '                                                   +
                        'Person__c '                                            +
                    'FROM '                                                     +
                        'Person_Group_Association__c '                          +
                    'WHERE '                                                    +
                        'Group__c = \'' + groupId + '\''                        +
                ')';
        System.debug(LoggingLevel.INFO, query);
        Person__c[] people = database.query(query);
        if (people.size() == 0) {
            setErrorMsg('No people matched the group and application you selected');
            setShowPeopleList(false);
            setShowApplicationGroupList(false);
        }
        else {
            setShowPeopleList(true);
            setShowApplicationGroupList(false);
            System.debug(LoggingLevel.INFO, 'Returning ' + people.size() + ' people.');
        }
        setApplicationGroupPersonList(people);
        return null;
    }

    /**
     *  Get the parameters from the visualforce page
     *
     *  @return - Boolean stating if the parameters passed in are valid. They always should be as the
     *            js validation on the front end should catch it.
     */
    private void getParameters() {

        this.applications = Apexpages.currentPage().getParameters().get('applicationsParam').split(',');
        this.groups = Apexpages.currentPage().getParameters().get('groupsParam').split(',');
    }

    private Boolean checkParameters() {

        // Check that we have some valid parameters
        if (this.applications.size() == 0 && this.groups.size() == 0) {
            return false;
        }
        return true;
    }

    /**
     *  Generate a set of unique applicationIds from a list of Application_Version_Group_Association__c
     */
    private set<String> getApplicationIds(List<Application_Version_Group_Association__c> appVersionGroups) {

        Set<String> appIds = new Set<String>();
        for (Application_Version_Group_Association__c appVersionGroup : appVersionGroups) {
            appIds.add((String)appVersionGroup.Application_Version__c);
        }
        return appIds;
    }

    private void setGroupMap(List<String> groupId) {

        this.groupTotalMap = new Map<String, Group__c>();
        String query =
            'SELECT '                  +
                'Id, '                 +
                'Name, '               +
                'Membership_Count__c ' +
            'FROM '                    +
                'Group__c '            +
            'WHERE '                   +
                'Id IN (' + MetricHelpers.generateCommaSeperatedString(groupId, true) + ')';
        System.debug(LoggingLevel.INFO, query);
        Group__c[] groups = database.query(query);

        for (Group__c groupToAdd : groups) {
            this.groupTotalMap.put(groupToAdd.Id, groupToAdd);
        }
    }

    private List<String> getImeiList(String groupId) {

        List<String> imeis = new List<String>();
        Person__c[] persons = database.query(SoqlHelpers.getGroupMemberInfo(groupId));
        for (Person__c person : persons) {
            imeis.add(person.Handset__r.IMEI__c);
        }
        return imeis;
    }

    public static testMethod void testController() {

        PageReference pageRef = Page.ApplicationManagement;

        Test.setCurrentPageReference(pageRef);
        ApplicationManagementController controller = new ApplicationManagementController();

        List<String> groupIds = new List<String>();
        Group__c currentGroup = new Group__c();
        database.insert(currentGroup);
        groupIds.add((String)currentGroup.Id);

        controller.groups = groupIds;

        Person__c person = Utils.createTestPerson('', 'TESTME', true, null, 'Female');
        database.insert(person);

        Person_Group_Association__c pga = new Person_Group_Association__c();
        pga.Person__c = person.Id;
        pga.Group__c = currentGroup.Id;
        database.insert(pga);

        Application_Version__c application = [SELECT Id FROM Application_Version__c WHERE Application_Available__c = true LIMIT 1];
        List<String> applicationIds = new List<String>();
        applicationIds.add((String)application.Id);

        Application_Version_Group_Association__c appVerAssoc = new Application_Version_Group_Association__c();
        appVerAssoc.Application_Version__c = application.Id;
        appVerAssoc.Group__c = currentGroup.Id;
        database.insert(appVerAssoc);

        controller.applications = applicationIds;
        controller.setGroupMap(groupIds);
        controller.getImeiList(groupIds.get(0));
        controller.setGroupsList(controller.getGroupsList());
        controller.setApplicationsList(controller.getApplicationsList());
        controller.setErrorMsg('ERROR');
        controller.setErrorMsg('ERROR');
        controller.getErrorMsg();
        controller.addApplications();
        controller.showApplicationsGroupCount();
        controller.showGroupsApplicationCount();
        controller.getPeopleGroupApplication(controller.groups.get(0), controller.applications.get(0),'true');
        controller.getPeopleGroupApplication(controller.groups.get(0), controller.applications.get(0),'false');
        controller.removeApplications();
    }
}