src/objects/Asset__c.object
<CustomObject>
    <description>Applab related assets</description>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <description>Serial Number</description>
        <label>Serial Number</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Asset</label>
    <nameField>
        <displayFormat>Asset-{YY}-{0000}</displayFormat>
        <label>Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Equipment_Return__c.object
<CustomObject>
    <description>Parent object that contains the meta data about an individual return of some equipment from the field</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The asset that the return is for if it is not a phone return</description>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Equipment Returns</relationshipLabel>
        <relationshipName>Equipment_Returns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Equipment_Type__c</fullName>
        <description>The type of equipment that has been returned</description>
        <label>Equipment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laptop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field officer who first reported the issue</description>
        <label>Field Officer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Equipment Returns (Field Officer)</relationshipLabel>
        <relationshipName>Equipment_Returns1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The handset that is being returned</description>
        <inlineHelpText>Enter the handset that is being returned</inlineHelpText>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Equipment Returns</relationshipLabel>
        <relationshipName>Equipment_Returns</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Equipment Return</label>
    <nameField>
        <label>Equipment Return Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Field_Officer__c.object
<CustomObject>
    <description>Indonesia Field Officers</description>
    <label>Field Officer</label>
    <nameField>
        <label>FO_ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Officers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District_Name__c</fullName>
        <formula>District__r.Name</formula>
        <label>District Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physical handset assigned to this Person (in the case of GF-managed assets)</description>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Assignee</relationshipLabel>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduledAssetTrackerDailyEmail.cls
global class ScheduledAssetTrackerDailyEmail implements Schedulable {

    global void execute(SchedulableContext sc) {
    	//pick all equipment returns from yesterday
    	Equipment_Return__c[] equipmentReturns = [Select Id, Equipment_Type__c, 
    	Field_Officer__r.District_Name__c, Field_Officer__r.First_Name__c, Handset__c, Asset__c From Equipment_Return__c 
    	where CreatedDate >=:date.today().addDays(-1) And Field_Officer__c !=: null];

    	List<String>emailAddresses = new List<String>();
    	//construct an email for each, send to Cecilia and Sadat
    	for (Equipment_Return__c equipmentReturn : equipmentReturns) {
    		emailAddresses.add('cmbawadde@grameenfoundation.org');
        	emailAddresses.add('sntume@grameenfoundation.org');
        	String subject = 'Asset from field';
        	String message = '';
        	if (equipmentReturn.Equipment_Type__c.equals('Phone')) {
        		Phone__c phone = [Select IMEI__c from Phone__c where Id =: equipmentReturn.Handset__c];
        	    message = 'Phone with IMEI ' + phone.IMEI__c + ' is supposed to be returned to the field, it is with '+ equipmentReturn.Field_Officer__r.First_Name__c
        	     + ' of ' + equipmentReturn.Field_Officer__r.District_Name__c;
        	}
        	else {
        		Asset__c asset = [Select Serial_Number__c From Asset__c where Id=: equipmentReturn.Asset__c];
        		message= 'Asset with serial number ' + asset.Serial_Number__c + ' is supposed to be returned to the field, it is with '+
        		equipmentReturn.Field_Officer__r.First_Name__c + ' of ' + equipmentReturn.Field_Officer__r.District_Name__c;
        	}
            Messaging.SingleEmailMessage email = EmailHelpers.createEmail(emailAddresses, subject, message);
            List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
            emails.add(email);
            EmailHelpers.sendEmails(emails);
    	}
    }
}