src/objects/Association__c.object
<CustomObject>
    <description>Associations that ALSUR contacts when it receives orders from its clients</description>
    <label>Association</label>
    <nameField>
        <label>Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Association_CPA_Order_Delivery__c.object
<CustomObject>
    <fields>
        <fullName>CPA_Order_Allocation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CPA Order Allocation</label>
        <referenceTo>CPA_Order_Allocation__c</referenceTo>
        <relationshipLabel>Association CPA Order Deliveries</relationshipLabel>
        <relationshipName>Association_CPA_Order_Deliveries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Delivery Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Receipt_Number__c</fullName>
        <label>Delivery Receipt Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Baskets__c</fullName>
        <label>Number of Baskets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Kilos__c</fullName>
        <label>Number of Kilos</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Code__c</fullName>
        <formula>CPA_Order_Allocation__r.Order_Code__c</formula>
        <label>Order Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_Presentation__c</fullName>
        <label>Unit of Presentation</label>
        <picklist>
            <picklistValues>
                <fullName>Bags</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Satchels</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Association CPA Order Delivery</label>
    <nameField>
        <displayFormat>ACODN-{00000}</displayFormat>
        <label>Association CPA Order Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Association CPA Order Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client__c.object
<CustomObject>
    <description>Object representing clients of ALSUR</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPA_Order__c.object
<CustomObject>
    <description>Client Product Association Order object</description>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Client_Product_Association__r.Client_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <defaultValue>TODAY() + 2</defaultValue>
        <label>Expected Delivery Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Baskets__c</fullName>
        <label>Number of Baskets</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Kilos__c</fullName>
        <label>Number of Kilos</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Code__c</fullName>
        <formula>Client__c + &apos; &apos; +  Client_Product_Association__r.Product_Name__c + &apos; &apos; + TEXT(Expected_Delivery_Date__c)</formula>
        <label>Order Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Presentacion__c</fullName>
        <label>Presentación</label>
        <picklist>
            <picklistValues>
                <fullName>5 al día</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bandeja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolsa transparente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ekono</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Por paquete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solo a mil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Todo a 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitafilado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solo hoja</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_per_Kilo__c</fullName>
        <label>Price per Kilo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Client_Product_Association__r.Product_Name__c</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_Presentation__c</fullName>
        <label>Unit of Presentation</label>
        <picklist>
            <picklistValues>
                <fullName>100 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>125 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>400 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>450 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>600 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>700 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1000 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1200 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3000 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CPA Order</label>
    <nameField>
        <displayFormat>Order-{00000}</displayFormat>
        <label>CPA Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPA_Order_Allocation__c.object
<CustomObject>
    <description>ALSUR: Allocation of Orders to Associations</description>
    <fields>
        <fullName>Association__c</fullName>
        <label>Association</label>
        <referenceTo>Association__c</referenceTo>
        <relationshipLabel>CPA Order Allocations</relationshipLabel>
        <relationshipName>CPA_Order_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPA_Order__c</fullName>
        <label>CPA Order</label>
        <referenceTo>CPA_Order__c</referenceTo>
        <relationshipLabel>CPA Order Allocations</relationshipLabel>
        <relationshipName>CPA_Order_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>CPA_Order__r.Client_Product_Association__r.Client_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <formula>CPA_Order__r.Expected_Delivery_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Baskets__c</fullName>
        <label>Number of Baskets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Kilos__c</fullName>
        <label>Number of Kilos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Code__c</fullName>
        <formula>Association__r.Name + &apos;-&apos;+CPA_Order__r.Order_Code__c</formula>
        <label>Order Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Presentacion__c</fullName>
        <formula>TEXT(CPA_Order__r.Presentacion__c)</formula>
        <label>Presentación</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_per_Kilo__c</fullName>
        <formula>CPA_Order__r.Price_per_Kilo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price per Kilo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>CPA_Order__r.Client_Product_Association__r.Product_Name__c</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_Presentation__c</fullName>
        <formula>TEXT(CPA_Order__r.Unit_of_Presentation__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit of Presentation</label>
        <type>Text</type>
    </fields>
    <label>CPA Order Allocation</label>
    <nameField>
        <displayFormat>CPAON-{000}</displayFormat>
        <label>CPA Order Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Order Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AlsurOrderDelivery.cls
public class AlsurOrderDelivery {   
public String asociation {get; set;}
public String nameQuery {get; set;}
public List<CPA_Order_Allocation__c> orders {get; set;}
public Association_CPA_Order_Delivery__c allocation { get; set; }

public PageReference executeSearch() {
  orders=[select Id,
                Number_of_Units_of_Presentation__c,
                Number_of_Kilos__c,
                Expected_Delivery_Date__c,
                CPA_Order__r.Presentacion__c,
                CPA_Order__r.Unit_of_Presentation__c,
                Client__c,
                Product_Name__c,
                Price_per_Kilo__c,
                Order_Code__c,
                Number_of_Baskets__c
          from CPA_Order_Allocation__c
          where Id = :nameQuery];       
  return null;
}

public AlsurOrderDelivery(){
  
}

public List<SelectOption> getAssociationItems() {
  Set<ID> del1 = new Set<ID>();
  for (Association_CPA_Order_Delivery__c deli1 : [select CPA_Order_Allocation__c 
                                                  from Association_CPA_Order_Delivery__c]){ 
    del1.add(deli1.CPA_Order_Allocation__c);
  }
  Set<ID> aso= new Set<ID>();
  for (CPA_Order_Allocation__c asos : [select Association__c 
                                        from CPA_Order_Allocation__c 
                                        where Id != :del1]){ 
    aso.add(asos.Association__c);
  }
  list<Association__c> associations = [Select Name 
                                        from Association__c 
                                        where Id = :aso];
  List<SelectOption> options = new List<SelectOption>();
  for (Association__c asociation : associations) {
    options.add(new SelectOption(asociation.Name, asociation.Name));
  }
  return options;
}

public List<SelectOption> getclientItems() {
  Set<ID> del = new Set<ID>();
  for (Association_CPA_Order_Delivery__c deli : [select CPA_Order_Allocation__c 
                                                  from Association_CPA_Order_Delivery__c]){ 
    del.add(deli.CPA_Order_Allocation__c);
  }
  List<SelectOption> options = new List<SelectOption>();
  List<CPA_Order_Allocation__c> clients = new List<CPA_Order_Allocation__c>();
  if (asociation == null || String.isEmpty(asociation)) {
    options.add(new SelectOption('NoClientSelected', 'Seleccione una asociación primero'));
  }
  else {
    clients =  [Select Id, Client__c from CPA_Order_Allocation__c where Association__r.Name = :asociation and Id != :del ];
  }
  for (CPA_Order_Allocation__c nameQuery : clients) {
    options.add(new SelectOption(nameQuery.Id, nameQuery.Client__c));
  }
  return options;
}

public PageReference save() {
  for (CPA_Order_Allocation__c ord: orders){ 
    Association_CPA_Order_Delivery__c allocation = new Association_CPA_Order_Delivery__c(
    CPA_Order_Allocation__c = ord.Id,
    Number_of_Kilos__c = ord.Number_of_Kilos__c,
    Number_of_Units_of_Presentation__c = ord.Number_of_Units_of_Presentation__c,
    Delivery_Date__c = ord.Expected_Delivery_Date__c,
    Unit_of_Presentation__c = ord.CPA_Order__r.Unit_of_Presentation__c,
    Number_of_Baskets__c = ord.Number_of_Baskets__c,
    Delivery_Receipt_Number__c = '0');
  insert allocation;
  }
  PageReference currentPage = ApexPages.currentPage();
  currentPage.setRedirect(true);
  return currentPage;
}
}