src/objects/Association__c.object
<CustomObject>
    <description>Associations that ALSUR contacts when it receives orders from its clients</description>
    <label>Association</label>
    <nameField>
        <label>Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Association_Contact_Association__c.object
<CustomObject>
    <description>Link between Mobile User Contacts and Associations, primarily Alsur to facilitate record sharing in the TaroWorks app</description>
    <fields>
        <fullName>Association__c</fullName>
        <label>Association</label>
        <referenceTo>Association__c</referenceTo>
        <relationshipLabel>Association Contact Associations</relationshipLabel>
        <relationshipName>Association_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Association Contact Associations</relationshipLabel>
        <relationshipName>Association_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Association Contact Association</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Association Contact Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Association Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Client__c.object
<CustomObject>
    <description>Object representing clients of ALSUR</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Product_Association__c.object
<CustomObject>
    <description>Junction Object to be used for associating Products to Clients</description>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Product Associations</relationshipLabel>
        <relationshipName>Client_Product_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <label>Client Product Association</label>
    <nameField>
        <displayFormat>CP-{000}</displayFormat>
        <label>Client Product Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Product Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CPA_Order__c.object
<CustomObject>
    <description>Client Product Association Order object</description>
    <fields>
        <fullName>Client_Product_Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Product Association</label>
        <referenceTo>Client_Product_Association__c</referenceTo>
        <relationshipLabel>CPA Orders</relationshipLabel>
        <relationshipName>CPA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Client_Product_Association__r.Client_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CPA Orders</relationshipLabel>
        <relationshipName>CPA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <defaultValue>TODAY() + 2</defaultValue>
        <label>Expected Delivery Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Baskets__c</fullName>
        <label>Number of Baskets</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Kilos__c</fullName>
        <label>Number of Kilos</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Code__c</fullName>
        <formula>Client__c + &apos; &apos; +  Client_Product_Association__r.Product_Name__c + &apos; &apos; + TEXT(Expected_Delivery_Date__c)</formula>
        <label>Order Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Presentacion__c</fullName>
        <label>Presentación</label>
        <picklist>
            <picklistValues>
                <fullName>5 al día</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bandeja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolsa transparente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ekono</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Por paquete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solo a mil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Todo a 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitafilado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solo hoja</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_per_Kilo__c</fullName>
        <label>Price per Kilo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Client_Product_Association__r.Product_Name__c</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_of_Presentation__c</fullName>
        <label>Unit of Presentation</label>
        <picklist>
            <picklistValues>
                <fullName>100 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>125 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>400 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>450 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>600 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>700 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1000 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1200 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3000 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CPA Order</label>
    <nameField>
        <displayFormat>Order-{00000}</displayFormat>
        <label>CPA Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AlsurOrdersController.cls
public with sharing class AlsurOrdersController {

    public List<CPA_Order__c> ordersToCreate { 
        get {
            ordersToCreate = [Select Id,
                                    Order_Code__c,
                                    Client_Product_Association__c,
                                    Product_Name__c,
                                    Client__c,
                                    Presentacion__c,
                                    Unit_of_Presentation__c,
                                    Number_of_Units_of_Presentation__c,
                                    Number_of_Kilos__c,
                                    Number_of_Baskets__c,
                                    Price_per_Kilo__c,
                                    Expected_Delivery_Date__c
                            FROM
                                CPA_Order__c
                            WHERE
                                Id IN:ordersToCreate];
            return ordersToCreate;
        } 
        set; 
    } 
    public Client_Product_Association__c cpa { get; set; }
    public String client { get; set; }
    public String product { get; set;}
    public CPA_Order__c currentOrder { get; set; }
    public boolean showOrderPanel { get; set;}
    

    public AlsurOrdersController()
    {
        ordersToCreate = new List<CPA_Order__c>();
        showOrderPanel = false;
    }

    public PageReference createOrder() {
        currentOrder = new CPA_Order__c(Client_Product_Association__c = product);
        showOrderPanel = true;
        return null;
    }
    
    public List<SelectOption> getClientItems() {
        List<Client__c> clients = [Select Id, Name from Client__c];
        List<SelectOption> options = new List<SelectOption>();
        for (Client__c client : clients) {
            options.add(new SelectOption(client.Id, client.Name));
        }
        return options;
    }

    public List<SelectOption> getProductItems() {
        List<SelectOption> options = new List<SelectOption>();
        List<Client_Product_Association__c> cpaItems = new List<Client_Product_Association__c>();
        if (client == null || String.isEmpty(client)) {
            options.add(new SelectOption('NoClientSelected', 'Select a client first'));
        }
        else {
            cpaItems = [Select Id, Product_Name__c from Client_Product_Association__c where Client__c =:client];
        }
        for (Client_Product_Association__c cpaItem : cpaItems) {
            options.add(new SelectOption(cpaItem.Id, cpaItem.Product_Name__c));
        }
        return options;
    }

    public PageReference save() {
        Association_Contact_Association__c aca = [Select Contact__c from Association_Contact_Association__c
            where Association__r.Name = 'ALSUR MAIN' limit 1];
        currentOrder.Contact__c = aca.Contact__c;
        insert currentOrder;
        System.debug(currentOrder.Client_Product_Association__r.Product_Name__c);
        ordersToCreate.add(currentOrder);
        showOrderPanel = false;
        return null;
    }
    // The method to add a new item to the list
    public PageReference next(){
        return null;
    }

}