src/objects/Association__c.object
<CustomObject>
    <description>Associations that ALSUR contacts when it receives orders from its clients</description>
    <label>Association</label>
    <nameField>
        <label>Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Association_Contact_Association__c.object
<CustomObject>
    <description>Link between Mobile User Contacts and Associations, primarily Alsur to facilitate record sharing in the TaroWorks app</description>
    <fields>
        <fullName>Association__c</fullName>
        <label>Association</label>
        <referenceTo>Association__c</referenceTo>
        <relationshipLabel>Association Contact Associations</relationshipLabel>
        <relationshipName>Association_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Association Contact Associations</relationshipLabel>
        <relationshipName>Association_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Association Contact Association</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Association Contact Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Association Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Client__c.object
<CustomObject>
    <description>Object representing clients of ALSUR</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Product_Association__c.object
<CustomObject>
    <description>Junction Object to be used for associating Products to Clients</description>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Product Associations</relationshipLabel>
        <relationshipName>Client_Product_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Client Product Associations</relationshipLabel>
        <relationshipName>Client_Product_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Product Association</label>
    <nameField>
        <displayFormat>CP-{000}</displayFormat>
        <label>Client Product Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Product Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CPA_Order__c.object
<CustomObject>
    <description>Client Product Association Order object</description>
    <fields>
        <fullName>Client_Product_Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Product Association</label>
        <referenceTo>Client_Product_Association__c</referenceTo>
        <relationshipLabel>CPA Orders</relationshipLabel>
        <relationshipName>CPA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Client_Product_Association__r.Client_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CPA Orders</relationshipLabel>
        <relationshipName>CPA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>CPA Order</label>
    <nameField>
        <displayFormat>Order-{00000}</displayFormat>
        <label>CPA Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAlsurOrdersController.cls
@isTest
private class TestAlsurOrdersController {
	
	@isTest static void test_method_one() {

        Association__c association = new Association__c();
        association.Name = 'Alsurtest';
        insert association;

	Client__c client = new Client__c();
        client.Name = 'Alsurtest';
        insert client;

        Product__c product = new Product__c();
        product.Name = 'Papaya';
        insert product;

        Contact contact = new Contact();
        contact.FirstName = 'pedrito';
        contact.LastName = 'perez';
        insert contact;

        Client_Product_Association__c cpaItems = new Client_Product_Association__c();
        cpaItems.Product__c = product.Id;
        cpaItems.Client__c = client.Id;
        insert  cpaItems;

        Association_Contact_Association__c aca = new Association_Contact_Association__c(Contact__c = contact.Id, Association__c = association.Id);
        insert aca;

        CPA_Order__c currentOrder = new CPA_Order__c(Contact__c = aca.Contact__c, Number_of_Units_of_Presentation__c = 4);
        insert  currentOrder;

        PageReference ref = new PageReference('/apex/AccountPage?aId=' + contact.Id);
        Test.setCurrentPage(ref);

	AlsurOrdersController aoc = new AlsurOrdersController();

        List<SelectOption> options = aoc.getClientItems();
        System.assert(options != null);

        List<SelectOption> option = aoc.getProductItems();
        System.assert(option != null);

        aoc.createOrder();

        System.assert(aoc.ordersToCreate != null);
                   
        aoc.currentOrder = currentOrder;
        System.assert(aoc.currentOrder != null);

        Test.startTest();
        PageReference ref2 = aoc.next();
        Test.stopTest();
     
        system.assertEquals(ref2, null);
       
	}
}