src/objects/Association__c.object
<CustomObject>
    <description>Associations that ALSUR contacts when it receives orders from its clients</description>
    <label>Association</label>
    <nameField>
        <label>Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Association_Contact_Association__c.object
<CustomObject>
    <description>Link between Mobile User Contacts and Associations, primarily Alsur to facilitate record sharing in the TaroWorks app</description>
    <fields>
        <fullName>Association__c</fullName>
        <label>Association</label>
        <referenceTo>Association__c</referenceTo>
        <relationshipLabel>Association Contact Associations</relationshipLabel>
        <relationshipName>Association_Contact_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Association Contact Associations</relationshipLabel>
        <relationshipName>Association_Contact_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Association Contact Association</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Association Contact Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Association Contact Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Client__c.object
<CustomObject>
    <description>Object representing clients of ALSUR</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Client_Product_Association__c.object
<CustomObject>
    <description>Junction Object to be used for associating Products to Clients</description>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Client__c</referenceTo>
        <relationshipLabel>Client Product Associations</relationshipLabel>
        <relationshipName>Client_Product_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Client Product Associations</relationshipLabel>
        <relationshipName>Client_Product_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Client Product Association</label>
    <nameField>
        <displayFormat>CP-{000}</displayFormat>
        <label>Client Product Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Product Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CPA_Order__c.object
<CustomObject>
    <description>Client Product Association Order object</description>
    <fields>
        <fullName>Client_Product_Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Product Association</label>
        <referenceTo>Client_Product_Association__c</referenceTo>
        <relationshipLabel>CPA Orders</relationshipLabel>
        <relationshipName>CPA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>Client_Product_Association__r.Client_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CPA Orders</relationshipLabel>
        <relationshipName>CPA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <defaultValue>TODAY() + 2</defaultValue>
        <label>Expected Delivery Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Baskets__c</fullName>
        <label>Number of Baskets</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Kilos__c</fullName>
        <label>Number of Kilos</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Presentacion__c</fullName>
        <label>Presentación</label>
        <picklist>
            <picklistValues>
                <fullName>5 al día</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bandeja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolsa transparente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ekono</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Malla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Por paquete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solo a mil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Todo a 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitafilado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solo hoja</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_per_Kilo__c</fullName>
        <label>Price per Kilo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_of_Presentation__c</fullName>
        <label>Unit of Presentation</label>
        <picklist>
            <picklistValues>
                <fullName>100 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>125 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>400 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>450 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>600 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>700 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1000 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1200 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3000 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CPA Order</label>
    <nameField>
        <displayFormat>Order-{00000}</displayFormat>
        <label>CPA Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPA_Order_Allocation__c.object
<CustomObject>
    <description>ALSUR: Allocation of Orders to Associations</description>
    <fields>
        <fullName>Association__c</fullName>
        <label>Association</label>
        <referenceTo>Association__c</referenceTo>
        <relationshipLabel>CPA Order Allocations</relationshipLabel>
        <relationshipName>CPA_Order_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPA_Order__c</fullName>
        <label>CPA Order</label>
        <referenceTo>CPA_Order__c</referenceTo>
        <relationshipLabel>CPA Order Allocations</relationshipLabel>
        <relationshipName>CPA_Order_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>CPA_Order__r.Client_Product_Association__r.Client_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <formula>CPA_Order__r.Expected_Delivery_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Baskets__c</fullName>
        <label>Number of Baskets</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Kilos__c</fullName>
        <label>Number of Kilos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Presentacion__c</fullName>
        <formula>TEXT(CPA_Order__r.Presentacion__c)</formula>
        <label>Presentación</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_per_Kilo__c</fullName>
        <formula>CPA_Order__r.Price_per_Kilo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price per Kilo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_of_Presentation__c</fullName>
        <formula>TEXT(CPA_Order__r.Unit_of_Presentation__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit of Presentation</label>
        <type>Text</type>
    </fields>
    <label>CPA Order Allocation</label>
    <nameField>
        <displayFormat>CPAON-{000}</displayFormat>
        <label>CPA Order Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Order Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAllocationToAssociationMobileUser.cls
@isTest
public class TestAllocationToAssociationMobileUser{

	static testMethod void testAssignAllocationToAssociationMobileUser() {

		// Create a test Association
        Association__c association = new Association__c(Name='ALSUR ASSOC');
        insert association;

        //Create 2 contacts to assign to the above association
        Contact testContact = new Contact(FirstName='test', LastName='contact');
        insert testContact;
        Contact testContact2 = new Contact(FirstName='test2', LastName='contact2');
        insert testContact2;

        // Create the contact association objects for the 2 contacts
        Association_Contact_Association__c assoc = new Association_Contact_Association__c();
        assoc.Association__c = association.Id;
        assoc.Contact__c = testContact.Id;
        insert assoc;
        Association_Contact_Association__c assoc2 = new Association_Contact_Association__c();
        assoc2.Association__c = association.Id;
        assoc2.Contact__c = testContact2.Id;
        insert assoc2;

        // Create a client and then a client product association
        Client__c client = new Client__c(Name='testClient');
        insert client;
        Product__c product = new Product__c(Name='testProduct');
        insert product;
        Client_Product_Association__c cpa = new Client_Product_Association__c();
        cpa.Product__c = product.Id;
        cpa.Client__c = client.id;
        insert cpa;

        // Create an Order
        CPA_Order__c cpaOrder = new CPA_Order__c();
        cpaOrder.Client_Product_Association__c = cpa.id;
        cpaOrder.Price_per_Kilo__c = 550;
        cpaOrder.Presentacion__c = 'Malla';
        cpaOrder.Unit_of_Presentation__c = 'Kg.';
        cpaOrder.Contact__c = testContact.Id;
        cpaOrder.Expected_Delivery_Date__c = date.today().addDays(1);
        cpaOrder.Number_of_Baskets__c = 10;
        cpaOrder.Number_of_Kilos__c = 100;
        cpaOrder.Number_of_Units_of_Presentation__c = 100;
        insert cpaOrder;

        // Create an allocation for this order to the association above
        CPA_Order_Allocation__c allocation = new CPA_Order_Allocation__c();
        allocation.Association__c = association.Id;
        allocation.CPA_Order__c = cpaOrder.Id;
        allocation.Number_of_Kilos__c = 5;
        allocation.Number_of_Baskets__c = 50;
        allocation.Number_of_Units_of_Presentation__c = 50;
        insert allocation;
        test.startTest();
        List<gfsurveys__SObjectContactAssociation__c> scas = [Select Id, 
        																gfsurveys__AssociatedIds__c 
															    from 
                                                                    gfsurveys__SObjectContactAssociation__c
                                                            	where 
                                                            		gfsurveys__SObjectApiName__c='CPA_Order_Allocation__c'];
		System.assertEquals(2, scas.size());
		test.stopTest();
	}

}