src/objects/Association__c.object
<CustomObject>
    <description>Associations that ALSUR contacts when it receives orders from its clients</description>
    <label>Association</label>
    <nameField>
        <label>Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Association_CPA_Order_Delivery__c.object
<CustomObject>
    <fields>
        <fullName>CPA_Order_Allocation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CPA Order Allocation</label>
        <referenceTo>CPA_Order_Allocation__c</referenceTo>
        <relationshipLabel>Association CPA Order Deliveries</relationshipLabel>
        <relationshipName>Association_CPA_Order_Deliveries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Delivery Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Receipt_Number__c</fullName>
        <label>Delivery Receipt Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Kilos__c</fullName>
        <label>Number of Kilos</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_of_Presentation__c</fullName>
        <label>Unit of Presentation</label>
        <picklist>
            <picklistValues>
                <fullName>Bags</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Satchels</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Association CPA Order Delivery</label>
    <nameField>
        <displayFormat>ACODN-{00000}</displayFormat>
        <label>Association CPA Order Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Association CPA Order Deliveries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CPA_Order__c.object
<CustomObject>
    <description>Client Product Association Order object</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CPA Orders</relationshipLabel>
        <relationshipName>CPA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <defaultValue>TODAY() + 2</defaultValue>
        <label>Expected Delivery Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Kilos__c</fullName>
        <label>Number of Kilos</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_of_Presentation__c</fullName>
        <label>Unit of Presentation</label>
        <picklist>
            <picklistValues>
                <fullName>100 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>125 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>400 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>450 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>500 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>600 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>700 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1000 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1200 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3000 gr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CPA Order</label>
    <nameField>
        <displayFormat>Order-{00000}</displayFormat>
        <label>CPA Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CPA_Order_Allocation__c.object
<CustomObject>
    <description>ALSUR: Allocation of Orders to Associations</description>
    <fields>
        <fullName>Association__c</fullName>
        <label>Association</label>
        <referenceTo>Association__c</referenceTo>
        <relationshipLabel>CPA Order Allocations</relationshipLabel>
        <relationshipName>CPA_Order_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPA_Order__c</fullName>
        <label>CPA Order</label>
        <referenceTo>CPA_Order__c</referenceTo>
        <relationshipLabel>CPA Order Allocations</relationshipLabel>
        <relationshipName>CPA_Order_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expected_Delivery_Date__c</fullName>
        <formula>CPA_Order__r.Expected_Delivery_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Kilos__c</fullName>
        <label>Number of Kilos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Units_of_Presentation__c</fullName>
        <label>Number of Units of Presentation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_of_Presentation__c</fullName>
        <formula>TEXT(CPA_Order__r.Unit_of_Presentation__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit of Presentation</label>
        <type>Text</type>
    </fields>
    <label>CPA Order Allocation</label>
    <nameField>
        <displayFormat>CPAON-{000}</displayFormat>
        <label>CPA Order Allocation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPA Order Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAlsurOrderDelivery.cls
@isTest
private class TestAlsurOrderDelivery {
        
        @isTest static void test_method_one() {

        Association__c association = new Association__c();
        association.Name = 'Alsurtest';
        insert association;

        Contact contact = new Contact();
        contact.FirstName = 'pedrito';
        contact.LastName = 'perez';
        insert contact;

        CPA_Order__c order = new CPA_Order__c();
        order.Number_of_Units_of_Presentation__c = 10;
        order.Contact__c = contact.Id;
        order.Expected_Delivery_Date__c = System.today();
        order.Unit_of_Presentation__c = '5';
        insert order;
                
        CPA_Order_Allocation__c orders = new CPA_Order_Allocation__c();
        orders.CPA_Order__c = order.Id;
        orders.Association__c = association.Id;
        orders.Number_of_Units_of_Presentation__c = 5;
        orders.Number_of_Kilos__c = 5;
        insert orders;

        AlsurOrderDelivery deliverys = new AlsurOrderDelivery();

        List<SelectOption> options = deliverys.getAssociationItems();
        System.assert(options != null);

        test.startTest();
        String nameQuery = 'Alsurtest';

        deliverys.executeSearch();
        System.assert(deliverys.orders != null);  

        Association_CPA_Order_Delivery__c allocation = new Association_CPA_Order_Delivery__c(
        CPA_Order_Allocation__c = orders.Id,
        Number_of_Kilos__c = orders.Number_of_Kilos__c,
        Number_of_Units_of_Presentation__c = orders.Number_of_Units_of_Presentation__c,
        Delivery_Date__c = System.today(),
        Unit_of_Presentation__c = orders.CPA_Order__r.Unit_of_Presentation__c,
        Delivery_Receipt_Number__c = '0');
        insert allocation;
        deliverys.save();
        System.assert(deliverys.save() != null);

        test.stopTest();

        }
}