src/objects/Banana_Farmer__c.object
<CustomObject>
    <description>Banana Farmers in CKW 3.0</description>
    <fields>
        <fullName>Focus_Farmer__c</fullName>
        <label>Focus Farmer</label>
        <referenceTo>Focus_Farmer__c</referenceTo>
        <relationshipLabel>Banana Farmers</relationshipLabel>
        <relationshipName>Banana_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Banana Farmer</label>
    <nameField>
        <displayFormat>BF{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Farmer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banana Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Banana_Farmer_GAPs_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Banana_Farmer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Banana Farmer</label>
        <referenceTo>Banana_Farmer__c</referenceTo>
        <relationshipName>Banana_Farmer_GAP_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CKW_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CKW Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Banana Farmer GAPs Selections</relationshipLabel>
        <relationshipName>Banana_Farmer_GAPs_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Banana Farmer GAPs Selection</label>
    <nameField>
        <displayFormat>BG{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Banana Farmer GAP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banana Farmer GAPs Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <fields>
        <fullName>ISO_Standard_Code__c</fullName>
        <label>ISO Standard Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Focus_Farmer__c.object
<CustomObject>
    <fields>
        <fullName>Farmer_Type__c</fullName>
        <label>Farmer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Banana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Focus Farmers</relationshipLabel>
        <relationshipName>Focus_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Focus Farmer</label>
    <nameField>
        <displayFormat>FFN{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Focus Farmer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Focus Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestAssignBananaGAPsToContact.cls
@isTest
public class TestAssignBananaGAPsToContact {

    @isTest static void TestAssignGAPsToContact() {

        // Create the Country record for Uganda
        Country__c uganda = new Country__c();
        uganda.Name = 'Uganda';
        uganda.ISO_Standard_Code__c = 'UG';
        uganda.Language__c = 'English';
        insert uganda;
        
        // Create the contact who registers the Banana farmer
        Contact ckw = new Contact();
        ckw.FirstName = 'test';
        ckw.LastName = 'ckw';
        insert ckw;

        // Create a test person
        Person__c person = new Person__c();
        person.First_Name__c = 'Test1';
        person.Last_Name__c = 'Test2';
        person.Gender__c = 'Female';
        person.Type__c = 'Focus Farmer';
        insert person;

        // Create a focus farmer
        Focus_Farmer__c focusFarmer = new Focus_Farmer__c();
        focusFarmer.Person__c = person.id;
        focusFarmer.Farmer_Type__c = 'Banana';
        insert focusFarmer;
        
        // Create a Banana farmer object
        Banana_Farmer__c BananaFarmer = new Banana_Farmer__c();
        BananaFarmer.Focus_Farmer__c = focusFarmer.Id;
        BananaFarmer.Registered_By__c = ckw.Id;
        insert BananaFarmer;
        
        // Create a Banana Farmer GAPs object
        Banana_Farmer_GAPs_Selection__c gap = new Banana_Farmer_GAPs_Selection__c();
        gap.CKW_Contact__c = ckw.Id;
        gap.Banana_Farmer__c = BananaFarmer.Id;
        gap.Location__latitude__s = 30.117334;
        gap.Location__longitude__s = 0.396258;
        insert gap;
        
        Test.startTest();
        List<gfsurveys__SObjectContactAssociation__c> scas = [Select Id, 
                                                                gfsurveys__AssociatedIds__c 
                                                              from 
                                                                    gfsurveys__SObjectContactAssociation__c
                                                              where 
                                                                gfsurveys__SObjectApiName__c='Banana_Farmer_GAPs_Selection__c'
                                                              and
                                                                gfsurveys__Contact__c =:gap.CKW_Contact__c];
        System.assertEquals(gap.Id, scas[0].gfsurveys__AssociatedIds__c);
        Test.stopTest();
    }
    
    @isTest static void TestAssignGAPsToContacts() {
        Country__c uganda = new Country__c();
        uganda.Name = 'Uganda';
        uganda.ISO_Standard_Code__c = 'UG';
        uganda.Language__c = 'English';
        insert uganda;
        
        Contact ckw = new Contact();
        ckw.FirstName = 'test';
        ckw.LastName = 'ckw';
        insert ckw;
        
        Contact ckw2 = new Contact();
        ckw2.FirstName = 'test2';
        ckw2.LastName = 'ckw2';
        insert ckw2;
        
        Person__c person = new Person__c();
        person.First_Name__c = 'Test1';
        person.Last_Name__c = 'Test2';
        person.Gender__c = 'Female';
        person.Type__c = 'Focus Farmer';
        insert person;
        
        Person__c person2 = new Person__c();
        person2.First_Name__c = 'Test12';
        person2.Last_Name__c = 'Test22';
        person2.Gender__c = 'Male';
        person2.Type__c = 'Focus Farmer';
        insert person2;
        
        Person__c person3 = new Person__c();
        person3.First_Name__c = 'Test13';
        person3.Last_Name__c = 'Test23';
        person3.Gender__c = 'Female';
        person3.Type__c = 'Focus Farmer';
        insert person3;
        
        Focus_Farmer__c focusFarmer = new Focus_Farmer__c();
        focusFarmer.Person__c = person.id;
        focusFarmer.Farmer_Type__c = 'Banana';
        insert focusFarmer;
        
        Focus_Farmer__c focusFarmer2 = new Focus_Farmer__c();
        focusFarmer2.Person__c = person2.id;
        focusFarmer2.Farmer_Type__c = 'Banana';
        insert focusFarmer2;
        
        Focus_Farmer__c focusFarmer3 = new Focus_Farmer__c();
        focusFarmer3.Person__c = person3.id;
        focusFarmer3.Farmer_Type__c = 'Banana';
        insert focusFarmer3;
        
        Banana_Farmer__c BananaFarmer = new Banana_Farmer__c();
        BananaFarmer.Focus_Farmer__c = focusFarmer.Id;
        BananaFarmer.Registered_By__c = ckw.Id;
        insert BananaFarmer;
        
        Banana_Farmer__c BananaFarmer2 = new Banana_Farmer__c();
        BananaFarmer2.Focus_Farmer__c = focusFarmer2.Id;
        BananaFarmer2.Registered_By__c = ckw.Id;
        insert BananaFarmer2;
        
        Banana_Farmer__c BananaFarmer3 = new Banana_Farmer__c();
        BananaFarmer3.Focus_Farmer__c = focusFarmer3.Id;
        BananaFarmer3.Registered_By__c = ckw2.Id;
        insert BananaFarmer3;
        
        // Create a Banana Farmer GAPs object
        Banana_Farmer_GAPs_Selection__c gap = new Banana_Farmer_GAPs_Selection__c();
        gap.CKW_Contact__c = ckw.Id;
        gap.Banana_Farmer__c = BananaFarmer.Id;
        gap.Location__latitude__s = 30.117334;
        gap.Location__longitude__s = 0.396258;
        
        // Create a Banana Farmer GAPs object
        Banana_Farmer_GAPs_Selection__c gap2 = new Banana_Farmer_GAPs_Selection__c();
        gap2.CKW_Contact__c = ckw.Id;
        gap2.Banana_Farmer__c = BananaFarmer2.Id;
        gap2.Location__latitude__s = 29.950921;
        gap2.Location__longitude__s = 0.111868;
        
        // Create a Banana Farmer GAPs object
        Banana_Farmer_GAPs_Selection__c gap3 = new Banana_Farmer_GAPs_Selection__c();
        gap3.CKW_Contact__c = ckw2.Id;
        gap3.Banana_Farmer__c = BananaFarmer3.Id;
        gap3.Location__latitude__s = 30.108763;
        gap3.Location__longitude__s = -0.195478;
        
        insert gap;
        insert new Banana_Farmer_GAPs_Selection__c [] {gap2, gap3};
        
        Test.startTest();
        List<gfsurveys__SObjectContactAssociation__c> scas = [Select Id, 
                                                                gfsurveys__AssociatedIds__c 
                                                              from 
                                                                    gfsurveys__SObjectContactAssociation__c
                                                              where 
                                                                gfsurveys__SObjectApiName__c='Banana_Farmer_GAPs_Selection__c'];
        System.assertEquals(2, scas.size());
        Test.stopTest();
    }
}