src/objects/Banana_Cluster_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Banana_Farmer__c</fullName>
        <label>Banana Farmer</label>
        <referenceTo>Banana_Farmer__c</referenceTo>
        <relationshipLabel>Banana Cluster Meetings</relationshipLabel>
        <relationshipName>Banana_Cluster_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Banana Cluster Meetings</relationshipLabel>
        <relationshipName>Banana_Cluster_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Banana Cluster Meeting</label>
    <nameField>
        <displayFormat>BCM{000000}</displayFormat>
        <label>Banana Cluster Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banana Cluster Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Banana_Farmer__c.object
<CustomObject>
    <description>Banana Farmers in CKW 3.0</description>
    <fields>
        <fullName>Focus_Farmer__c</fullName>
        <label>Focus Farmer</label>
        <referenceTo>Focus_Farmer__c</referenceTo>
        <relationshipLabel>Banana Farmers</relationshipLabel>
        <relationshipName>Banana_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Banana Farmer</label>
    <nameField>
        <displayFormat>BF{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Farmer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Banana Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Coffee_cluster_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Coffee_Farmer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Coffee Farmer</label>
        <referenceTo>Coffee_Farmer__c</referenceTo>
        <relationshipLabel>Coffee cluster Meetings</relationshipLabel>
        <relationshipName>Coffee_cluster_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Coffee cluster Meeting</label>
    <nameField>
        <label>Coffee cluster Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coffee cluster Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Coffee_Farmer__c.object
<CustomObject>
    <fields>
        <fullName>Focus_Farmer__c</fullName>
        <label>Focus Farmer</label>
        <referenceTo>Focus_Farmer__c</referenceTo>
        <relationshipLabel>Coffee Farmers</relationshipLabel>
        <relationshipName>Coffee_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Coffee Farmer</label>
    <nameField>
        <displayFormat>CF{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Farmer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coffee Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Farmer_Cluster_Meeting__c.object
<CustomObject>
    <description>Object to hold aggregated info of Banana, Coffee and Maize Cluster Meetings for a specific Contact per month</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 Farmer Cluster Meetings</relationshipLabel>
        <relationshipName>Farmer_Cluster_Meetings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Focus_Farmer__c</fullName>
        <description>The Banana, Coffee or Maize farmer</description>
        <inlineHelpText>The Banana, Coffee or Maize farmer</inlineHelpText>
        <label>Focus Farmer</label>
        <referenceTo>Focus_Farmer__c</referenceTo>
        <relationshipLabel>3.0 Farmer Cluster Meetings</relationshipLabel>
        <relationshipName>Farmer_Cluster_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>3.0 Farmer Cluster Meeting</label>
    <nameField>
        <displayFormat>FCM{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>3.0 Farmer Cluster Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Farmer Cluster Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Focus_Farmer__c.object
<CustomObject>
    <label>Focus Farmer</label>
    <nameField>
        <displayFormat>FFN{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Focus Farmer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Focus Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Maize_Cluster_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Maize Cluster Meetings</relationshipLabel>
        <relationshipName>Maize_Cluster_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maize_Farmer__c</fullName>
        <label>Maize Farmer</label>
        <referenceTo>Maize_Farmer__c</referenceTo>
        <relationshipLabel>Maize Cluster Meetings</relationshipLabel>
        <relationshipName>Maize_Cluster_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Maize Cluster Meeting</label>
    <nameField>
        <displayFormat>MCM{000000}</displayFormat>
        <label>Maize Cluster Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maize Cluster Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Maize_Farmer__c.object
<CustomObject>
    <fields>
        <fullName>Focus_Farmer__c</fullName>
        <label>Focus Farmer</label>
        <referenceTo>Focus_Farmer__c</referenceTo>
        <relationshipLabel>Maize Farmers</relationshipLabel>
        <relationshipName>Maize_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Maize Farmer</label>
    <nameField>
        <displayFormat>MF{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Maize Farmer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maize Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateMonthlyFarmerCluster.cls
public class CreateMonthlyFarmerCluster {
    
    public static void createVisit(Date aDay) {
        Date thisDay = aDay;
        Date previousDay = aDay.addDays(-1);
        
        List<Farmer_Cluster_Meeting__c> meets = new List<Farmer_Cluster_Meeting__c>();
        
        List<String> focusFarmerIds = new List<String>();
        if (thisDay.day() != 1) {
            for (Farmer_Cluster_Meeting__c thisMonthVisit : [SELECT Id, Focus_Farmer__c from Farmer_Cluster_Meeting__c
                  where Date__c = THIS_MONTH]) {
                if (null != thisMonthVisit) {
                    focusFarmerIds.add(thisMonthVisit.Focus_Farmer__c);
                }
            }
        }
        else {
            for (Farmer_Cluster_Meeting__c thisMonthVisit : [SELECT Id, Focus_Farmer__c from Farmer_Cluster_Meeting__c
                  where Date__c = LAST_MONTH]) {
                focusFarmerIds.add(thisMonthVisit.Focus_Farmer__c);
            }
        }
        Map<String, String> focusFarmerMeets = new Map<String, String>();

        // Get Banana Cluster Meeting info
        for (Banana_Cluster_Meeting__c clusterMeet : [Select Contact__c, Banana_Farmer__r.Focus_Farmer__c, CreatedDate from Banana_Cluster_Meeting__c
            where CreatedDate >=: previousDay and CreatedDate <: thisDay and Banana_Farmer__r.Focus_Farmer__c not in: focusFarmerIds]) {
            
            if (null != clusterMeet) {
                focusFarmerMeets.put(clusterMeet.Banana_Farmer__r.Focus_Farmer__c, clusterMeet.Contact__c);
            }
        }

        // Get Coffee Cluster Meeting Info
        for (Coffee_Cluster_Meeting__c clusterMeet : [Select Contact__c, Coffee_Farmer__r.Focus_Farmer__c, CreatedDate from Coffee_Cluster_Meeting__c
            where CreatedDate >=: previousDay and CreatedDate <: thisDay and Coffee_Farmer__r.Focus_Farmer__c not in: focusFarmerIds]) {
            
            if (null != clusterMeet) {
                focusFarmerMeets.put(clusterMeet.Coffee_Farmer__r.Focus_Farmer__c, clusterMeet.Contact__c);
            }
        }

        // Get Maize Cluster Meeting info
        for (Maize_Cluster_Meeting__c clusterMeet : [Select Contact__c, Maize_Farmer__r.Focus_Farmer__c, CreatedDate from Maize_Cluster_Meeting__c
            where CreatedDate >=: previousDay and CreatedDate <: thisDay and Maize_Farmer__r.Focus_Farmer__c not in: focusFarmerIds]) {
            
            if (null != clusterMeet) {
                focusFarmerMeets.put(clusterMeet.Maize_Farmer__r.Focus_Farmer__c, clusterMeet.Contact__c);
            }
        }
        for (String focusFarmer : focusFarmerMeets.keyset()) {
            String contactId = focusFarmerMeets.get(focusFarmer);
            Farmer_Cluster_Meeting__c meet = new Farmer_Cluster_Meeting__c();
            meet.Contact__c= contactId;
            meet.Focus_Farmer__c = focusFarmer;
            meet.Date__c = previousDay;
            meets.add(meet);
        }
        insert meets; 
    }
}