src/objects/Bank_Deposit__c.object
<CustomObject>
    <description>This is the bank deposit details that are added before a sale is entered</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank_Transaction_ID__c</fullName>
        <externalId>true</externalId>
        <label>Bank Transaction ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Purchase_Groups__c</fullName>
        <label>Commercial Purchase Groups</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verification_Code__c</fullName>
        <label>Verification Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bank Deposit</label>
    <nameField>
        <label>Bank Deposit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ewarehouse_Farmer__c.object
<CustomObject>
    <description>This is the farmer that is registered by the VKW at the field.</description>
    <fields>
        <fullName>Auto_Generated_Farmer_ID__c</fullName>
        <label>Farmer FCI Id</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Commercial_Purchase_Group_ID__c</fullName>
        <label>Commercial Purchase Group ID</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Purchase_Groups__c</fullName>
        <description>This is the code for the CPG (Commercial Purchase Group) that a VKW belongs to. It is the second last segment of the unique FCI Farmer ID [**/***/CPG/***]</description>
        <label>Commercial Purchase Groups</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ewarehouse Farmer</label>
    <nameField>
        <label>Ewarehouse Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ewarehouse_Sale_Pigeon_Peas_Association__c.object
<CustomObject>
    <fields>
        <fullName>Bags_Not_Sold__c</fullName>
        <label>Bags Not Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commercial_Purchase_Group_ID__c</fullName>
        <label>Commercial Purchase Group ID</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Purchase_Group__c</fullName>
        <label>Commercial Purchase Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Sale__c</fullName>
        <label>Ewarehouse Sale</label>
        <referenceTo>Sale_Record__c</referenceTo>
        <relationshipLabel>Ewarehouse Sale Pigeon Peas Associations</relationshipLabel>
        <relationshipName>Ewarehouse_Sale_Pigeon_Peas_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Farmer_FCI_ID__c</fullName>
        <label>Farmer FCI ID</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_3_Digits_of_Farmer_ID__c</fullName>
        <label>Last 3 Digits of Farmer ID</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Moisture_Content__c</fullName>
        <label>Moisture Content</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_For_Not_Selling__c</fullName>
        <label>Reason For Not Selling</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Total_Bags_Sold__c</fullName>
        <label>Total Bags Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ewarehouse Sale Pigeon Peas Association</label>
    <nameField>
        <label>Ewarehouse Sale Pigeon Peas Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Sale Pigeon Peas Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sale_Farmer_Associations__c.object
<CustomObject>
    <fields>
        <fullName>Beans_Number_of_90kg_Bags__c</fullName>
        <label>Beans Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Number_of_90kg_Bags__c</fullName>
        <label>Cow Peas Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dolichos_Number_of_90kg_Bags__c</fullName>
        <label>Dolichos Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Farmer__c</fullName>
        <label>Ewarehouse Farmer</label>
        <referenceTo>Ewarehouse_Farmer__c</referenceTo>
        <relationshipLabel>Ewarehouse Sale Farmer Associations</relationshipLabel>
        <relationshipName>Ewarehouse_Sale_Farmer_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Sale_Pigeon_Peas_Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ewarehouse Sale Pigeon Peas Association</label>
        <referenceTo>Ewarehouse_Sale_Pigeon_Peas_Association__c</referenceTo>
        <relationshipLabel>Ewarehouse Sale Farmer Associations</relationshipLabel>
        <relationshipName>Ewarehouse_Sale_Farmer_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Sale__c</fullName>
        <label>Ewarehouse Sale</label>
        <referenceTo>Sale_Record__c</referenceTo>
        <relationshipLabel>Ewarehouse Sale Farmer Associations</relationshipLabel>
        <relationshipName>Ewarehouse_Sale_Farmer_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Green_Grams_Number_of_90kg_Bags__c</fullName>
        <label>Green Grams Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maize_Number_of_90kg_Bags__c</fullName>
        <label>Maize Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Moisture_Content__c</fullName>
        <label>Pigeon Peas Moisture Content</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Number_of_90kg_Bags__c</fullName>
        <label>Pigeon Peas Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale_Farmer_Unique_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Sale Farmer Unique ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ewarehouse Sale Farmer Association</label>
    <nameField>
        <label>Ewarehouse Sale Farmer Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Sale Farmer Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sale_Record__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Deposit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Deposit</label>
        <referenceTo>Bank_Deposit__c</referenceTo>
        <relationshipLabel>Ewarehouse Sales</relationshipLabel>
        <relationshipName>Ewarehouse_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Beans_Number_of_90kg_Bags__c</fullName>
        <label>Beans Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beans_Price_per_90kg_Bag__c</fullName>
        <label>Beans Price per 90kg Bag</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commercial_Purchase_Group__c</fullName>
        <label>Commercial Purchase Groups</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Village__c</fullName>
        <label>Commercial Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Number_of_90kg_Bags__c</fullName>
        <label>Cow Peas Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Price_per_90kg_Bag__c</fullName>
        <label>Cow Peas Price per 90kg Bag</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dolichos_Number_of_90kg_Bags__c</fullName>
        <label>Dolichos Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dolichos_Price_per_90kg_Bag__c</fullName>
        <label>Dolichos Price per 90kg Bag</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Sale_Total_Amount__c</fullName>
        <label>Ewarehouse Sale Total Amount</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Green_Grams_Number_of_90kg_Bags__c</fullName>
        <label>Green Grams Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Green_Grams_Price_per_90kg_Bag__c</fullName>
        <label>Green Grams Price per 90kg Bag</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maize_Number_of_90kg_Bags__c</fullName>
        <label>Maize Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maize_Price_per_90kg_Bag__c</fullName>
        <label>Maize Price per 90kg Bag</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Price_per_90kg_Bag__c</fullName>
        <label>Pigeon Peas Price per 90kg Bag</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Total_Amount__c</fullName>
        <label>Pigeon Peas Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale_Date__c</fullName>
        <label>Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tigania_East_Commercial_Village__c</fullName>
        <label>Tigania East Commercial Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tigania_West_Commercial_Village__c</fullName>
        <label>Tigania West Commercial Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VKW_Name__c</fullName>
        <label>VKW Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Ewarehouse Sale</label>
    <nameField>
        <label>Sale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PigeonPeasSaleFAssociationCreatorTest.cls
@isTest
public class PigeonPeasSaleFAssociationCreatorTest{
     //Method to fetch the Pigeon Peas Association details of the pigeon peas sale association that was created
     static testMethod void getSaleFarmerDetails() {
      
      Bank_Deposit__c eBankDeposit = new Bank_Deposit__c(Amount__c=4500,Bank_Transaction_Id__c='XYZ123',Commercial_Purchase_Groups__c='KARATHIA WOMEN GROUP',District__c='TIGANIA WEST',Verification_Code__c='Gf003');
      insert eBankDeposit;
      
      Sale_Record__c eSale = new Sale_Record__c(Name='a3Hn00000008X0B',Bank_Deposit__c=eBankDeposit.Id,Beans_Number_of_90kg_Bags__c=3,Beans_Price_per_90kg_Bag__c=650,Commercial_Purchase_Group__c='a1cn00000004RwWAAU a1cn00000004RwXAAU',Commercial_Village__c='ATHWANA',Cow_Peas_Number_of_90kg_Bags__c=5,Cow_Peas_Price_per_90kg_Bag__c=500,District__c='TIGANIA WEST',Division__c='',Dolichos_Number_of_90kg_Bags__c=4,Dolichos_Price_per_90kg_Bag__c=780,Ewarehouse_Sale_Total_Amount__c='4500',Green_Grams_Number_of_90kg_Bags__c=3,Green_Grams_Price_per_90kg_Bag__c=350,Maize_Number_of_90kg_Bags__c=4,Maize_Price_per_90kg_Bag__c=300,Pigeon_Peas_Total_Amount__c=6,Pigeon_Peas_Price_per_90kg_Bag__c=100,Sale_Date__c=date.newInstance(2014, 2, 4),Status__c='Processing',Tigania_East_Commercial_Village__c='',Tigania_West_Commercial_Village__c='ATHWANA',VKW_Name__c='Steven Mugo');
      insert eSale;
      
      Ewarehouse_Sale_Pigeon_Peas_Association__c pigeon_peas_association_records= new Ewarehouse_Sale_Pigeon_Peas_Association__c (Farmer_FCI_ID__c='TW/A4/01/999',Ewarehouse_Sale__c=eSale.Id,Last_3_Digits_of_Farmer_ID__c='999',Moisture_Content__c='Exactly 13.5%',Total_Bags_Sold__c=10);
      insert pigeon_peas_association_records;
      
      Ewarehouse_Sale_Pigeon_Peas_Association__c pigeon_peas_association_1 = [SELECT Bags_Not_Sold__c, Commercial_Purchase_Group__c, Commercial_Purchase_Group_ID__c, Ewarehouse_Sale__c, Farmer_FCI_ID__c, Last_3_Digits_of_Farmer_ID__c, Moisture_Content__c, Reason_For_Not_Selling__c, Total_Bags_Sold__c FROM Ewarehouse_Sale_Pigeon_Peas_Association__c WHERE Id =: pigeon_peas_association_records.Id LIMIT 1];
      pigeon_peas_association_1.Bags_Not_Sold__c=1;
      update pigeon_peas_association_1;
      
      Ewarehouse_Sale_Pigeon_Peas_Association__c [] pigeon_peas_association = [SELECT Bags_Not_Sold__c, Commercial_Purchase_Group__c, Commercial_Purchase_Group_ID__c, Ewarehouse_Sale__c, Farmer_FCI_ID__c, Last_3_Digits_of_Farmer_ID__c, Moisture_Content__c, Reason_For_Not_Selling__c, Total_Bags_Sold__c FROM Ewarehouse_Sale_Pigeon_Peas_Association__c];
         
         
         //Variable to hold the FCI ID's from the Pigeon Peas association record
         List<String> ewarehouse_farmer_fci_ids= new List<String>();
         
         for(Ewarehouse_Sale_Pigeon_Peas_Association__c pigeon_peas_associations : pigeon_peas_association){
             if(pigeon_peas_associations.Farmer_FCI_ID__c != null){
                 ewarehouse_farmer_fci_ids.add(pigeon_peas_associations.Farmer_FCI_ID__c);
             } 
         } 
         
         //The Variable object to fetch the Ewarehouse Farmer ID to be used to create a new Ewarehouse Sale Farmer Association Record
         Ewarehouse_Farmer__c[] existing_farmer = [SELECT Ewarehouse_Farmer__c.Id, Ewarehouse_Farmer__c.Auto_Generated_Farmer_ID__c FROM Ewarehouse_Farmer__c WHERE Ewarehouse_Farmer__c.Auto_Generated_Farmer_ID__c IN : ewarehouse_farmer_fci_ids];    
         for(Ewarehouse_Farmer__c farmer_details : existing_farmer){
             if(farmer_details.Status__c == 'New Farmer'){
                 farmer_details.Status__c = 'New';
             }             
         }
         
         //Create a variable to hold the new Sale Farmer Association records to be inserted
         Sale_Farmer_Associations__c[] newFarmerAssociations = new List<Sale_Farmer_Associations__c>();
         for(Ewarehouse_Sale_Pigeon_Peas_Association__c pigeon_peas_associations : pigeon_peas_association){
             for(Ewarehouse_Farmer__c existing_farmers : existing_farmer ){
                 if(pigeon_peas_associations.Farmer_FCI_ID__c == existing_farmers.Auto_Generated_Farmer_ID__c){
                     newFarmerAssociations.add(new Sale_Farmer_Associations__c (Ewarehouse_Sale__c = pigeon_peas_associations.Ewarehouse_Sale__c,Ewarehouse_Sale_Pigeon_Peas_Association__c = pigeon_peas_associations.Id,Pigeon_Peas_Moisture_Content__c=pigeon_peas_associations.Moisture_Content__c,Pigeon_Peas_Number_of_90kg_Bags__c=pigeon_peas_associations.Total_Bags_Sold__c,Ewarehouse_Farmer__c = existing_farmers.Id, Sale_Farmer_Unique_ID__c = ''+ pigeon_peas_associations.Ewarehouse_Sale__c + ''+ existing_farmers.Id));
                     break;
                 }else{
                     
                 }
             }             
         }
         //Check that the array object variable for insertion is not empty
         if(newFarmerAssociations.size() > 0) {
           upsert newFarmerAssociations Sale_Farmer_Unique_ID__c ;
         } 
    }
}