src/objects/BSS_CKW_Project__c.object
<CustomObject>
    <fields>
        <fullName>CKW__c</fullName>
        <label>CKW</label>
        <referenceTo>gfsurveys__Mobile_User__c</referenceTo>
        <relationshipLabel>BSS CKW Projects</relationshipLabel>
        <relationshipName>BSS_CKW_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monthly_Discount__c</fullName>
        <label>Monthly Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>BSS_Project__c</referenceTo>
        <relationshipLabel>BSS CKW Projects</relationshipLabel>
        <relationshipName>BSS_CKW_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BSS CKW Project</label>
    <nameField>
        <displayFormat>BSS_CKW{000000}</displayFormat>
        <label>BSS CKW Proyect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS CKW Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BSS_Monthly_Bill_Detail__c.object
<CustomObject>
    <fields>
        <fullName>BSS_Monthly_Bill_Header__c</fullName>
        <label>BSS_Monthly_Bill_Header</label>
        <referenceTo>BSS_Monthly_Bill_Header__c</referenceTo>
        <relationshipLabel>BSS_Monthly_Bill_Details_Header</relationshipLabel>
        <relationshipName>BSS_Monthly_Bill_Details_Header</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>BSS_Survey_Value__c</referenceTo>
        <relationshipLabel>BSS Monthly Bill Details</relationshipLabel>
        <relationshipName>BSS_Monthly_Bill_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BSS Monthly Bill Detail</label>
    <nameField>
        <displayFormat>BSSMBD-{000000}</displayFormat>
        <label>BSS_Monthly_Bill_Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS Monthly Bill Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BSS_Monthly_Bill_Header__c.object
<CustomObject>
    <fields>
        <fullName>BSS_CKW_Project__c</fullName>
        <label>BSS_CKW_Project</label>
        <referenceTo>BSS_CKW_Project__c</referenceTo>
        <relationshipLabel>BSS_Monthly_Bill_Headers_Projects</relationshipLabel>
        <relationshipName>BSS_Monthly_Bill_Headers_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bill_Subtotal__c</fullName>
        <formula>IF( Survey_Subtotal__c &gt; BSS_CKW_Project__r.Monthly_top_payment__c , BSS_CKW_Project__r.Monthly_top_payment__c , Survey_Subtotal__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bill Subtotal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_discounts__c</fullName>
        <label>Total discounts</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_survey__c</fullName>
        <label>Total survey</label>
        <summarizedField>BSS_Monthly_Bill_Detail__c.Quantity__c</summarizedField>
        <summaryForeignKey>BSS_Monthly_Bill_Detail__c.BSS_Monthly_Bill_Header__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_value__c</fullName>
        <formula>Bill_Subtotal__c - Total_discounts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>BSS Monthly Bill Header</label>
    <nameField>
        <displayFormat>BSMBH-{000000}</displayFormat>
        <label>BSS Monthly Bill Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS Monthly Bill Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BSS_Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( End_Date__c &gt; TODAY(), &apos;Activo&apos;, &apos;Inactivo&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>BSS Project</label>
    <nameField>
        <displayFormat>BSS_{000000}</displayFormat>
        <label>BSS Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BSS_Survey_Value__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>BSS_Project__c</referenceTo>
        <relationshipLabel>BSS Survey Values</relationshipLabel>
        <relationshipName>BSS_Survey_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>gfsurveys__Survey__c</referenceTo>
        <relationshipLabel>BSS_Survey_Values_Survey</relationshipLabel>
        <relationshipName>BSS_Survey_Values_Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_value__c</fullName>
        <label>Survey value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>BSS Survey Value</label>
    <nameField>
        <displayFormat>BSSV-{000000}</displayFormat>
        <label>BSS_Survey_Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS Survey Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of CKW</description>
        <label>CKW Status</label>
        <picklist>
            <picklistValues>
                <fullName>Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>gfsurveys__Mobile_User__c</fullName>
        <formula>IF( gfsurveys__IsMobileUser__c &gt; 0
,
IMAGE(&apos;/img/checkbox_checked.gif&apos;, &apos;Checked&apos;)
,
IMAGE(&apos;/img/checkbox_unchecked.gif&apos;, &apos;Not Checked&apos;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile User Count</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>A scheme run by one of our partners(organisations) that uses our CKWs or another part of our network</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <description>Surveys run by CKWs. There is one entry here for each type of survey. Survey questions (and responses) are NOT stored here.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of survey</description>
        <inlineHelpText>End date of survey</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BSS_MonthlyBill.cls
global class BSS_MonthlyBill implements Schedulable{
	public Set<ID> activeProject = new Set<ID>();	
    public Date todayDate = Date.today();
    public Date lastDate = todayDate.addMonths(-1);
    public Date ancestorDate = todayDate.addMonths(-2);
    public Date billDate = date.newInstance(lastdate.year(), lastdate.month(), 1);
    public Date lastBillDate = date.newInstance(ancestorDate.year(), ancestorDate.month(), 1);
    Decimal sum = 0;
    
    global void execute(SchedulableContext sc){
        
        //create active project list
        for(BSS_Project__c projects : [select Id From BSS_Project__c Where End_Date__c >= LAST_MONTH] ){
            activeProject.add(projects.Id);
        }
        //create active CKWs list
        for(List<BSS_CKW_Project__c> activeCKW : [Select Id, Monthly_Discount__c, CKW__c, Project__c From BSS_CKW_Project__c Where Project__c in :activeProject and Status__c = 'Activo']) {  
            //insert monthly bill header each ckw active    
            for (BSS_CKW_Project__c ckwPrjIds: activeCKW){ 
                for(List<BSS_Monthly_Bill_Header__c> lastMonthDiscounts : [Select Bill_Subtotal__c, Total_survey__c, Total_discounts__c, Total_value__c From BSS_Monthly_Bill_Header__c Where BSS_CKW_Project__c = :ckwPrjIds.Id and Month__c =:lastBillDate]){ 
                 	Integer size = lastMonthDiscounts.size();
                    if(size == 0){
                        BSS_Monthly_Bill_Header__c monthlyBill = new BSS_Monthly_Bill_Header__c();
                        monthlyBill.BSS_CKW_Project__c = ckwPrjIds.Id;
                        monthlyBill.Month__c = billDate;
                        monthlyBill.Total_discounts__c = ckwPrjIds.Monthly_Discount__c;
                        insert monthlyBill;
                    }
                    else{
                        for(BSS_Monthly_Bill_Header__c lastMonthDiscount : lastMonthDiscounts){
                            BSS_Monthly_Bill_Header__c monthlyBill = new BSS_Monthly_Bill_Header__c();
                            monthlyBill.BSS_CKW_Project__c = ckwPrjIds.Id;
                            monthlyBill.Month__c = billDate;
                            if(lastMonthDiscount.Total_survey__c == 0 ) {
                                Decimal sum = lastMonthDiscount.Total_discounts__c + ckwPrjIds.Monthly_Discount__c;
                                monthlyBill.Total_discounts__c = sum;
                                monthlyBill.Notes__c = 'Se adiciona el descuento del mes anterior'+ lastBillDate +'por un valor de $'+lastMonthDiscount.Total_discounts__c;
                            }
                            else if (lastMonthDiscount.Bill_Subtotal__c < lastMonthDiscount.Total_discounts__c){
                                monthlyBill.Total_discounts__c = lastMonthDiscount.Total_discounts__c-lastMonthDiscount.Bill_Subtotal__c+ckwPrjIds.Monthly_Discount__c;
                                monthlyBill.Notes__c = 'Se adiciona saldo restante del descuento del mes anterior'+ lastBillDate +'por un valor de $'+lastMonthDiscount.Total_value__c;
                            }
                            else{
                                monthlyBill.Total_discounts__c = ckwPrjIds.Monthly_Discount__c;
                            }
                        	insert monthlyBill;
                        }
                    }
                }
                //Create active ckw contact list
                for(List<gfsurveys__Mobile_User__c> ckwContacts : [Select gfsurveys__Contact__c From gfsurveys__Mobile_User__c Where Id = :ckwPrjIds.CKW__c]){
                	for(gfsurveys__Mobile_User__c ckwContact : ckwContacts){
                		//Create active project survey list
                		for(List<BSS_Survey_Value__c> activeSurveys : [Select Id, Survey__c, Survey_value__c From BSS_Survey_Value__c Where Project__c = :ckwPrjIds.Project__c]) {
                			for(BSS_Survey_Value__c activeSurvey : activeSurveys){
                				//create list of survey count records per survey per ckw
                				List<aggregateResult> numberOfSurveys = [Select COUNT(Id) i, gfsurveys__Survey__c, gfsurveys__Surveyor__c surveyor  From gfsurveys__Submission__c Where gfsurveys__Survey__c = :activeSurvey.Survey__c and gfsurveys__Surveyor__c = :ckwContact.gfsurveys__Contact__c and gfsurveys__startDate__c = LAST_MONTH GROUP BY gfsurveys__Surveyor__c, gfsurveys__Survey__c];
                				//create list of Monthly bill headers
                				for(List<BSS_Monthly_Bill_Header__c> monthlyBills : [Select Id From BSS_Monthly_Bill_Header__c Where BSS_CKW_Project__c = :ckwPrjIds.Id and Month__c = :billDate]){
                					//insert monthly bill detail per survey per ckw
                					for(BSS_Monthly_Bill_Header__c monthBills : monthlyBills){
                						for(AggregateResult surveyCount : numberOfSurveys) {
                							if((String)surveyCount.get('surveyor') == ckwContact.gfsurveys__Contact__c){
                                            	BSS_Monthly_Bill_Detail__c monthlyBillDetail = new BSS_Monthly_Bill_Detail__c(
                                                BSS_Monthly_Bill_Header__c = monthBills.Id,
                                                Quantity__c = (Decimal)surveyCount.get('i'),
                                                Survey__c = activeSurvey.Id);
                                                insert monthlyBillDetail;
                                            }
                               			}
                           			}
                       			}
                   			}
               			}
           			}
       			}
            }
        }
    }
}