src/objects/BSS_CKW_Project__c.object
<CustomObject>
    <fields>
        <fullName>Account_Place__c</fullName>
        <label>Account Place</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Holder_Id__c</fullName>
        <label>Bank Account Holder Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Holder__c</fullName>
        <label>Bank Account Holder</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank_Account_Type__c</fullName>
        <label>Bank Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Cuenta de Ahorros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuenta Corriente</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <label>Bank</label>
        <picklist>
            <picklistValues>
                <fullName>Bancolombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banco Agrario</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banco de Bogotá</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Davivienda</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CKW_Name__c</fullName>
        <formula>CKW__r.gfsurveys__Contact__r.FirstName  +  CKW__r.gfsurveys__Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CKW Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_obs__c</fullName>
        <label>Discount obs</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_expedition_place__c</fullName>
        <label>ID expedition place</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>National_ID__c</fullName>
        <label>National ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>BSS_Project__c</referenceTo>
        <relationshipLabel>BSS CKW Projects</relationshipLabel>
        <relationshipName>BSS_CKW_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BSS CKW Project</label>
    <nameField>
        <displayFormat>BSS_CKW{000000}</displayFormat>
        <label>BSS CKW Proyect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS CKW Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BSS_Monthly_Bill_Detail__c.object
<CustomObject>
    <fields>
        <fullName>BSS_Monthly_Bill_Header__c</fullName>
        <label>BSS_Monthly_Bill_Header</label>
        <referenceTo>BSS_Monthly_Bill_Header__c</referenceTo>
        <relationshipLabel>BSS_Monthly_Bill_Details_Header</relationshipLabel>
        <relationshipName>BSS_Monthly_Bill_Details_Header</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <formula>Survey__r.Survey__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Survey Name</label>
        <type>Text</type>
    </fields>
    <label>BSS Monthly Bill Detail</label>
    <nameField>
        <displayFormat>BSSMBD-{000000}</displayFormat>
        <label>BSS_Monthly_Bill_Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS Monthly Bill Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BSS_Monthly_Bill_Header__c.object
<CustomObject>
    <fields>
        <fullName>BSS_CKW_Project__c</fullName>
        <label>BSS_CKW_Project</label>
        <referenceTo>BSS_CKW_Project__c</referenceTo>
        <relationshipLabel>BSS_Monthly_Bill_Headers_Projects</relationshipLabel>
        <relationshipName>BSS_Monthly_Bill_Headers_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bill_Subtotal__c</fullName>
        <formula>IF( Survey_Subtotal__c &gt; BSS_CKW_Project__r.Monthly_top_payment__c , BSS_CKW_Project__r.Monthly_top_payment__c , Survey_Subtotal__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bill Subtotal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bill_approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bill_paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bill paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CKW_signature__c</fullName>
        <label>CKW signature</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LastDayBill__c</fullName>
        <formula>DATE((YEAR(Month__c)),MOD((MONTH(Month__c)+1)-1,12)+1,DAY(Month__c))-1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LastDayBill</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_discounts__c</fullName>
        <label>Total discounts</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_value__c</fullName>
        <formula>Bill_Subtotal__c - Total_discounts__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>BSS Monthly Bill Header</label>
    <nameField>
        <displayFormat>BSMBH-{000000}</displayFormat>
        <label>BSS Monthly Bill Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS Monthly Bill Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BSS_Project__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>BSS Project</label>
    <nameField>
        <displayFormat>BSS_{000000}</displayFormat>
        <label>BSS Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BSS_MonthlyBillPageController.cls
public class BSS_MonthlyBillPageController {

	private ApexPages.StandardController stdCtrl {get; set;}
	public BSS_Monthly_Bill_Header__c monthlyBill {get; set;}
	public BSS_CKW_Project__c monthlyBillDetails {get; set;}
	public List<BSS_Monthly_Bill_Detail__c> monthlySurveysDetails {get; set;}
	  
	public BSS_MonthlyBillPageController(ApexPages.StandardController std){
		stdCtrl=std;
		setupmonthlyBill();
	}
	  
	private void setupmonthlyBill(){
		monthlyBill=[Select Id, BSS_CKW_Project__c, Month__c, LastDayBill__c, Total_discounts__c, Bill_Subtotal__c, Total_value__c, Notes__c, CKW_signature__c, Bill_approval__c, Bill_paid__c From BSS_Monthly_Bill_Header__c where Id =:stdCtrl.getId()];
		
		monthlyBillDetails = [Select Id, Organization__c, CKW_Name__c, National_ID__c, ID_expedition_place__c, Bank_Account_Number__c, Bank_Account_Type__c, Bank__c, Bank_Account_Holder__c, Bank_Account_Holder_Id__c, Account_Place__c, Discount_obs__c, Project__r.Name__c
                                                                    From BSS_CKW_Project__c
                                                                    where Id =:monthlyBill.BSS_CKW_Project__c ];
		
		monthlySurveysDetails = [Select Id, Survey_Name__c, Quantity__c, Notes__c
        	                                                        From BSS_Monthly_Bill_Detail__c
                                                                    where BSS_Monthly_Bill_Header__c =:monthlyBill.Id ];
	}

}