src/objects/BSS_CKW_Project__c.object
<CustomObject>
    <fields>
        <fullName>CKW__c</fullName>
        <label>CKW</label>
        <referenceTo>gfsurveys__Mobile_User__c</referenceTo>
        <relationshipLabel>BSS CKW Projects</relationshipLabel>
        <relationshipName>BSS_CKW_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monthly_Discount__c</fullName>
        <label>Monthly Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>BSS_Project__c</referenceTo>
        <relationshipLabel>BSS CKW Projects</relationshipLabel>
        <relationshipName>BSS_CKW_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>BSS CKW Project</label>
    <nameField>
        <displayFormat>BSS_CKW{000000}</displayFormat>
        <label>BSS CKW Proyect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS CKW Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BSS_Monthly_Bill_Header__c.object
<CustomObject>
    <fields>
        <fullName>BSS_CKW_Project__c</fullName>
        <label>BSS_CKW_Project</label>
        <referenceTo>BSS_CKW_Project__c</referenceTo>
        <relationshipLabel>BSS_Monthly_Bill_Headers_Projects</relationshipLabel>
        <relationshipName>BSS_Monthly_Bill_Headers_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_discounts__c</fullName>
        <label>Total discounts</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>BSS Monthly Bill Header</label>
    <nameField>
        <displayFormat>BSMBH-{000000}</displayFormat>
        <label>BSS Monthly Bill Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS Monthly Bill Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BSS_Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grameen_Project_Manager__c</fullName>
        <label>Grameen Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BSS Projects</relationshipLabel>
        <relationshipName>BSS_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <label>Project Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>BSS Projects (Project Manager)</relationshipLabel>
        <relationshipName>BSS_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>BSS Project</label>
    <nameField>
        <displayFormat>BSS_{000000}</displayFormat>
        <label>BSS Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BSS_Survey_Value__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>BSS_Project__c</referenceTo>
        <relationshipLabel>BSS Survey Values</relationshipLabel>
        <relationshipName>BSS_Survey_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>gfsurveys__Survey__c</referenceTo>
        <relationshipLabel>BSS_Survey_Values_Survey</relationshipLabel>
        <relationshipName>BSS_Survey_Values_Survey</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_value__c</fullName>
        <label>Survey value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>BSS Survey Value</label>
    <nameField>
        <displayFormat>BSSV-{000000}</displayFormat>
        <label>BSS_Survey_Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BSS Survey Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>gfsurveys__Mobile_User__c</fullName>
        <formula>IF( gfsurveys__IsMobileUser__c &gt; 0
,
IMAGE(&apos;/img/checkbox_checked.gif&apos;, &apos;Checked&apos;)
,
IMAGE(&apos;/img/checkbox_unchecked.gif&apos;, &apos;Not Checked&apos;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile User Count</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>A scheme run by one of our partners(organisations) that uses our CKWs or another part of our network</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <description>Surveys run by CKWs. There is one entry here for each type of survey. Survey questions (and responses) are NOT stored here.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of survey</description>
        <inlineHelpText>End date of survey</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date of Survey</description>
        <inlineHelpText>Start Date of Survey</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BSS_MonthlyBillTest.cls
@isTest
public class BSS_MonthlyBillTest {

    @isTest static void monthlyBill_test_method_one() {
    	
        //create contact1
		Contact contact1 = new Contact(LastName = 'Perez');
		insert contact1;
        
        //create contact2
		Contact contact2 = new Contact(LastName = 'Ramirez');
		insert contact2;
        
        //create contact3
		Contact contact3 = new Contact(LastName = 'Gutierrez');
		insert contact3;
        
        //create mobile user
        gfsurveys__Mobile_User__c mu = New gfsurveys__Mobile_User__c();
        mu.gfsurveys__Contact__c = contact3.Id;
        mu.gfsurveys__Username__c = 'test';
        mu.gfsurveys__Password__c = 'test';
        insert mu;
        
        Date todayDate = Date.today();
  		Date lastDate = todayDate.addMonths(12);
        
        //create project
        BSS_Project__c project = new BSS_Project__c();
        project.Name__c= 'Coocafisa';
        project.Project_Manager__c = contact1.Id;
        project.Grameen_Project_Manager__c = contact2.Id;
        project.Start_Date__c = system.today();
        project.End_Date__c = lastDate;
        insert project;
        
        //create project ckw
		BSS_CKW_Project__c ckwpjt =  new BSS_CKW_Project__c();
        ckwpjt.Project__c = project.Id;
        ckwpjt.CKW__c = mu.Id;
        ckwpjt.Start_Date__c = system.today();
        ckwpjt.End_Date__c = lastDate;
        ckwpjt.Monthly_Discount__c = 10000;
        insert ckwpjt;

         //create project ckw2
        BSS_CKW_Project__c ckwpjt2 =  new BSS_CKW_Project__c();
        ckwpjt2.Project__c = project.Id;
        ckwpjt2.CKW__c = mu.Id;
        ckwpjt2.Start_Date__c = system.today();
        ckwpjt2.End_Date__c = lastDate;
        ckwpjt2.Monthly_Discount__c = 10000;
        insert ckwpjt2;

        //create survey
        gfsurveys__Survey__c survey = new gfsurveys__Survey__c();
        survey.Name = 'Survey prueba';
        insert survey;

        //create projet survey
        BSS_Survey_Value__c pjtsurvey = new BSS_Survey_Value__c();
        pjtsurvey.Project__c = project.Id;
        pjtsurvey.Survey__c = survey .Id;
        pjtsurvey.Survey_value__c = 15000;
        insert pjtsurvey;        

        Date submisionDate = todayDate.addMonths(-1);
        
        //create submission
        gfsurveys__Submission__c submission = new gfsurveys__Submission__c ();
        submission.gfsurveys__Survey__c = survey.Id;
        submission.gfsurveys__Surveyor__c = contact3.Id;
        submission.gfsurveys__startDate__c = submisionDate;
        insert submission;

        Date submisionDate2 = todayDate.addMonths(-2);
        Date lastBillDate = date.newInstance(submisionDate2.year(), submisionDate2.month(), 1);

        //create header
        BSS_Monthly_Bill_Header__c header = new BSS_Monthly_Bill_Header__c();
        header.BSS_CKW_Project__c = ckwpjt2.Id;
        header.Month__c = lastBillDate;
        header.Total_discounts__c = 5000;
        insert header;

        //make tests
        Test.StartTest();

        BSS_MonthlyBill mb = new BSS_MonthlyBill();
        String sch = '0 0 23 * * ?'; system.schedule('Test monthly bill', sch, mb); 

        Test.stopTest(); 
        
    }
}