src/objects/BVAT_Farmer__c.object
<CustomObject>
    <description>BVAT Farmer</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Personal Details of the Farmer</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>BVAT Farmers</relationshipLabel>
        <relationshipName>BVAT_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BVAT Farmer</label>
    <nameField>
        <displayFormat>BF-{0000000}</displayFormat>
        <label>BVAT Farmer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BVAT Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_E__c</fullName>
        <description>GPS Location E. Must be in Decimal format</description>
        <label>GPS Location E</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_N__c</fullName>
        <description>GPS Location N. Must be in Decimal forma</description>
        <label>GPS Location N</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BvatFarmerMapMarker.cls
/**
 *  Class to represent a map marker that contains details about a BVAT Farmer
 */

public with sharing class BvatFarmerMapMarker extends MapMarkers {

    private BVAT_Farmer__c farmer;

    public BvatFarmerMapMarker(BVAT_Farmer__c farmer) {
        this.farmer = farmer;
        this.setLatitude(farmer.Person__r.GPS_Location_N__c);
        this.setLongitude(farmer.Person__r.GPS_Location_E__c);
        this.setMarkerTitle(farmer.Name + ', ' + farmer.Person__r.Last_Name__c + ' ' + farmer.Person__r.First_Name__c);
        setDefaultColour('Blue');
    }

    // Generate the content string for a CIW
    public override String getMarkerInfoContentString() {

        String content = '<div>' +
            this.farmer.Name + ', ' + this.farmer.Person__r.Last_Name__c + ' ' + this.farmer.Person__r.First_Name__c + '<br />' +
            getGender(this.farmer.Person__r.Gender__c) + '<br />';
            

        // This needs to be changed to add links to the ectra details for the BVAT Farmer
        // Will implement when this feature is required
        if (getShowMoreDetails()) {
        }
        return content;
    }
}