src/objects/C3P0_Farmer_Visit__c.object
<CustomObject>
    <description>Represents 1 visit to a distinct farmer in a month</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The CKW who makes the visit to a farmer and uses CKW Search</description>
        <inlineHelpText>The CKW who makes the visit to a farmer and uses CKW Search</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 Monthly Farmer Visits</relationshipLabel>
        <relationshipName>C3P0_Monthly_Farmer_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>3.0 Monthly Farmer Visits</relationshipLabel>
        <relationshipName>C3P0_Monthly_Farmer_Visits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Search_Log__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Search Log</label>
        <referenceTo>Search_Log__c</referenceTo>
        <relationshipLabel>3.0 Monthly Farmer Visits</relationshipLabel>
        <relationshipName>C3P0_Monthly_Farmer_Visits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>3.0 Monthly Farmer Visit</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>3.0 Farmer Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Monthly Farmer Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Search_Log__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Interviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person who requests information</description>
        <label>Interviewee</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Administered)</relationshipLabel>
        <relationshipName>Interviewee_Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Search Logs</relationshipLabel>
        <relationshipName>Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Log</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreateMonthlyFarmerVisit.cls
public class CreateMonthlyFarmerVisit {


    public static void createVisit(Date aDay) {
        
        Date thisDay = aDay;
        Date previousDay = aDay.addDays(-1);
        List<C3P0_Farmer_Visit__c> visits = new List<C3P0_Farmer_Visit__c>();

        List<String> personIds = new List<String>();
        if (thisDay.day() != 1) {
            for (C3P0_Farmer_Visit__c thisMonthVisit : [SELECT Id, Person__c from C3P0_Farmer_Visit__c
                  where Visit_Date__c = THIS_MONTH]) {
                if (null != thisMonthVisit) {
                    personIds.add(thisMonthVisit.Person__c);
                }
            }
        }
        else {
            for (C3P0_Farmer_Visit__c thisMonthVisit : [SELECT Id, Person__c from C3P0_Farmer_Visit__c
                  where Visit_Date__c = LAST_MONTH]) {
                personIds.add(thisMonthVisit.Person__c);
            }
        }
        Map<String, Search_Log__c> personLogs = new Map<String, Search_Log__c>();
        for (Search_Log__c searchLog : [Select Interviewer_Contact__c, Interviewee__c, CreatedDate from Search_Log__c
            where Interviewer_Contact__c != null and CreatedDate >=: previousDay and CreatedDate <: thisDay and Interviewee__c != null and Interviewee__c not in:personIds]) {
            
            if (null != searchLog) {
                personLogs.put(searchLog.Interviewee__c, searchLog);
            }
        }
        for (String personId : personLogs.keyset()) {
            Search_Log__c searchLog = personLogs.get(personId);
            C3P0_Farmer_Visit__c visit = new C3P0_Farmer_Visit__c();
            visit.Contact__c = searchLog.Interviewer_Contact__c;
            visit.Search_Log__c = searchLog.Id;
            visit.Person__c = personId;
            visit.Visit_Date__c = date.newinstance(searchLog.CreatedDate.year(), searchLog.CreatedDate.month(), searchLog.CreatedDate.day());
            visits.add(visit);
        }
        insert visits;
    }

}