src/objects/C3P0_Market__c.object
<CustomObject>
    <fields>
        <fullName>Peak__c</fullName>
        <label>Peak</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>3.0 Market</label>
    <nameField>
        <label>3.0 Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>3.0 Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market_Bushenyi__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_capture__c</fullName>
        <label>Date of capture</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>3.0 Market Bushenyi</label>
    <nameField>
        <displayFormat>MB-{0000}</displayFormat>
        <label>3.0 Market Bushenyi Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Market Bushenyi</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Market_Kasese__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_capture__c</fullName>
        <label>Date of capture</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>3.0 Market Kasese</label>
    <nameField>
        <displayFormat>MK-{0000}</displayFormat>
        <label>3.0 Market Kasese Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Market Kasese</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Market_Masindi__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_capture__c</fullName>
        <label>Date of capture</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>3.0 Market Masindi</label>
    <nameField>
        <displayFormat>MM-{0000}</displayFormat>
        <label>3.0 Market Masindi Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Market Masindi</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MISPeakDayTest.cls
@isTest
private class MISPeakDayTest
{
	
	static testMethod void testValidatePeakDayCorrect() {
       
        C3P0_Market__c c3po=new C3P0_Market__c();
        Date dDate = System.today();
        Datetime dt = (DateTime)dDate;
        String dayOfWeek = dt.format('EEEE'); 
        c3po.Peak__c=dayOfWeek;
              
        system.assertEquals(true,MISPeakDay.applyPeakDayValidation(c3po));        
    }
    
    static testMethod void testValidatePeakDayWrong() {
       
        C3P0_Market__c c3po=new C3P0_Market__c();
        c3po.Peak__c='Thursd';
              
        system.assertEquals(false,MISPeakDay.applyPeakDayValidation(c3po));        
    }

    static testMethod void testValidatePeakDayCorrectBushenyi() {

        Market_Bushenyi__c market=new Market_Bushenyi__c();
        market.Date_of_capture__c=System.today();
        C3P0_Market__c c3po=new C3P0_Market__c();
        Date dDate = System.today();
        Datetime dt = (DateTime)dDate;
        String dayOfWeek = dt.format('EEEE');
        c3po.Peak__c=dayOfWeek;
              
        system.assertEquals(true,MISPeakDay.applyPeakDayValidationBushenyi(c3po,market));        
    }

    static testMethod void testValidatePeakDayWrongBushenyi() {
        Market_Bushenyi__c market=new Market_Bushenyi__c();
        market.Date_of_capture__c=System.today();
        C3P0_Market__c c3po=new C3P0_Market__c();
        c3po.Peak__c='Thursd';
              
        system.assertEquals(false,MISPeakDay.applyPeakDayValidationBushenyi(c3po,market));        
    }

    static testMethod void testValidatePeakDayCorrectMasindi() {

        Market_Masindi__c market=new Market_Masindi__c();
        market.Date_of_capture__c=System.today();
        C3P0_Market__c c3po=new C3P0_Market__c();
        Date dDate = System.today();
        Datetime dt = (DateTime)dDate;
        String dayOfWeek = dt.format('EEEE');
        c3po.Peak__c=dayOfWeek;
              
        system.assertEquals(true,MISPeakDay.applyPeakDayValidationMasindi(c3po,market));        
    }

    static testMethod void testValidatePeakDayWrongMasindi() {
        Market_Masindi__c market=new Market_Masindi__c();
        market.Date_of_capture__c=System.today();
        C3P0_Market__c c3po=new C3P0_Market__c();
        c3po.Peak__c='Thur';
              
        system.assertEquals(false,MISPeakDay.applyPeakDayValidationMasindi(c3po,market));        
    }

    static testMethod void testValidatePeakDayCorrectKasese() {

        Market_Kasese__c market=new Market_Kasese__c();
        market.Date_of_capture__c=System.today();
        C3P0_Market__c c3po=new C3P0_Market__c();
        Date dDate = System.today();
        Datetime dt = (DateTime)dDate;
        String dayOfWeek = dt.format('EEEE');
        c3po.Peak__c=dayOfWeek;
              
        system.assertEquals(true,MISPeakDay.applyPeakDayValidationKasese(c3po,market));        
    }

    static testMethod void testValidatePeakDayWrongKasese() {
        Market_Kasese__c market=new Market_Kasese__c();
        market.Date_of_capture__c=System.today();
        C3P0_Market__c c3po=new C3P0_Market__c();
        c3po.Peak__c='Thu';
              
        system.assertEquals(false,MISPeakDay.applyPeakDayValidationKasese(c3po,market));        
    }
}