src/objects/C3P0_CKW_Performance__c.object
<CustomObject>
    <fields>
        <fullName>CKW_Gender__c</fullName>
        <label>CKW Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 CKW Performances</relationshipLabel>
        <relationshipName>CKW_Performances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Performance_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>This date represents the Month in which a CKW was active</description>
        <label>Performance Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unique_Farmer_Visits__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unique Farmer Visits</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unique_Searches__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unique Searches</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Visits_to_F0__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Visits to FO</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>3.0 CKW Performance</label>
    <nameField>
        <displayFormat>CPN{YYYY}{MM}{0000}</displayFormat>
        <label>3.0 CKW Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 CKW Performances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/C3P0_Farmer_Visit__c.object
<CustomObject>
    <description>Represents 1 visit to a distinct farmer in a month</description>
    <fields>
        <fullName>Contact__c</fullName>
        <description>The CKW who makes the visit to a farmer and uses CKW Search</description>
        <inlineHelpText>The CKW who makes the visit to a farmer and uses CKW Search</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 Monthly Farmer Visits</relationshipLabel>
        <relationshipName>C3P0_Monthly_Farmer_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>3.0 Monthly Farmer Visits</relationshipLabel>
        <relationshipName>C3P0_Monthly_Farmer_Visits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Search_Log__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Search Log</label>
        <referenceTo>Search_Log__c</referenceTo>
        <relationshipLabel>3.0 Monthly Farmer Visits</relationshipLabel>
        <relationshipName>C3P0_Monthly_Farmer_Visits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>3.0 Monthly Farmer Visit</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>3.0 Farmer Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Monthly Farmer Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>gfsurveys__Mobile_User__c</fullName>
        <formula>IF( gfsurveys__IsMobileUser__c &gt; 0
,
IMAGE(&apos;/img/checkbox_checked.gif&apos;, &apos;Checked&apos;)
,
IMAGE(&apos;/img/checkbox_unchecked.gif&apos;, &apos;Not Checked&apos;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile User Count</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer_Cluster_Meeting__c.object
<CustomObject>
    <description>Object to hold aggregated info of Banana, Coffee and Maize Cluster Meetings for a specific Contact per month</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 Farmer Cluster Meetings</relationshipLabel>
        <relationshipName>Farmer_Cluster_Meetings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Focus_Farmer__c</fullName>
        <description>The Banana, Coffee or Maize farmer</description>
        <inlineHelpText>The Banana, Coffee or Maize farmer</inlineHelpText>
        <label>Focus Farmer</label>
        <referenceTo>Focus_Farmer__c</referenceTo>
        <relationshipLabel>3.0 Farmer Cluster Meetings</relationshipLabel>
        <relationshipName>Farmer_Cluster_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>3.0 Farmer Cluster Meeting</label>
    <nameField>
        <displayFormat>FCM{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>3.0 Farmer Cluster Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Farmer Cluster Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FO__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 FOs</relationshipLabel>
        <relationshipName>C3P0_FOs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>3.0 FOs</relationshipLabel>
        <relationshipName>FOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>3.0 FO</label>
    <nameField>
        <displayFormat>FO-{YYYY}{MM}-{0}</displayFormat>
        <label>FO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 FOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Focus_Farmer__c.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <picklist>
            <picklistValues>
                <fullName>Kasese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masindi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bushenyi</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Focus Farmers</relationshipLabel>
        <relationshipName>Focus_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Focus Farmer</label>
    <nameField>
        <displayFormat>FFN{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Focus Farmer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Focus Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Monthly_CKW_Visit__c.object
<CustomObject>
    <description>This object represents a unique interaction between an FO and a CKW per month. Each CKW is meant to meet their FO once every month.</description>
    <fields>
        <fullName>CKW__c</fullName>
        <label>CKW Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 Monthly CKW Visits (CKW Contact)</relationshipLabel>
        <relationshipName>CKW_Monthly_CKW_Visits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FO__c</fullName>
        <label>FO Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 Monthly CKW Visits</relationshipLabel>
        <relationshipName>Monthly_CKW_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Visit Date</description>
        <inlineHelpText>Visit Date</inlineHelpText>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>3.0 Monthly CKW Visit</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>3.0 Monthly CKW Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Monthly CKW Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District_Name__c</fullName>
        <formula>District__r.Name</formula>
        <label>District Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Search_Log__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Group_Search__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CKW 3.O tracks group searches with this flag</description>
        <label>Group Search</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Handset_Submit_Time__c</fullName>
        <description>Time the phone sent the request</description>
        <label>Handset Submit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person who requests information</description>
        <label>Interviewee</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Administered)</relationshipLabel>
        <relationshipName>Interviewee_Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Search Logs</relationshipLabel>
        <relationshipName>Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CKW/Interviewer as obtained from Salesforce using handset id</description>
        <label>Interviewer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Done)</relationshipLabel>
        <relationshipName>Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Log</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UpdateCkwPerformanceBatched.cls
/**
 *
 * Copyright (c) 2015 AppLab, Grameen Foundation
 *
 *  Tests are in TestUpdateCkwPerformance
 *  
 */
global class UpdateCkwPerformanceBatched implements Database.batchable<sObject>, Database.Stateful {
    
    global List<C3P0_CKW_Performance__c> ckwMonthlyPerformanceStats = new List<C3P0_CKW_Performance__c>();
        
    global Database.QueryLocator start(Database.BatchableContext BC) {
        User ckwadmin = [Select Id from User where alias = 'ckwadmin'];
        return Database.getQueryLocator('Select Id, Name from Contact where Ownerid = \'' + ckwadmin.id + '\' and Id In (Select gfsurveys__Contact__c from gfsurveys__Mobile_User__c where gfsurveys__Status__c = \'Active\')');
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> contacts) {
        updatePerformance(contacts);
    }
    
    global void finish(Database.BatchableContext BC) {
        upsert(ckwMonthlyPerformanceStats);
    }
    
    global void updatePerformance(List<Contact> contacts) {
        
        Map<String, Contact> ckws= new Map<String, Contact>();
        
        for(Contact c : contacts) {
            ckws.put(c.Id, c);
        }
        
        List<Person__c> contactPersons = [Select Contact__c, Gender__c, District_Name__c FROM Person__c where Contact__c in:ckws.keyset()];
        Map<String, Person__c> ckwPersonRecords = new Map<String, Person__c>();
        for (Person__c contactPerson : contactPersons) {
            ckwPersonRecords.put(contactPerson.Contact__c, contactPerson);
        }
        
        Map<String, Integer> ckwClusterMeets = new Map<String, Integer>();
        Map<String, Integer> ckwFarmerSearches = new Map<String, Integer>();
        Map<String, Integer> foCkwClusterMeets = new Map<String, Integer>();
        List<C3P0_CKW_Performance__c> monthlyPerformanceList = new List<C3P0_CKW_Performance__c>();
        for (String contactId : ckws.keyset()) {
            ckwClusterMeets.put(contactId, 0);
            ckwFarmerSearches.put(contactId, 0);
            foCkwClusterMeets.put(contactId, 0);
        }
        System.debug(ckwClusterMeets.size());System.debug(ckwFarmerSearches.size());System.debug(foCkwClusterMeets.size());
        AggregateResult[] farmerMonthlyClusterMeets = new AggregateResult[]{};
        AggregateResult[] farmerSearches = new AggregateResult[]{};
        AggregateResult[] foCkwClusters = new AggregateResult[]{};
        Map<String, C3P0_CKW_Performance__c> ckwMonthlyPerformanceStatsMap = new Map<String, C3P0_CKW_Performance__c>();
        
        if (date.today().day() == 1 || date.today().day() == 2) {
        // Get all unique farmer cluster meetings, searches and fo visits for last month
            farmerMonthlyClusterMeets = [Select Contact__c, count(Focus_Farmer__c) clusters from Farmer_Cluster_Meeting__c where date__c = LAST_MONTH group by Contact__c ];
            //farmerSearches = [Select Contact__c, count(Person__c) searches from C3P0_Farmer_Visit__c where Visit_Date__c = LAST_MONTH group by Contact__c ];

            farmerSearches = [
                SELECT 
                    Interviewer_Contact__c, 
                    COUNT_DISTINCT(Interviewee__c) searches
                FROM 
                    Search_Log__c 
                WHERE 
                    CreatedDate = LAST_MONTH 
                    AND
                        Interviewer_Contact__c IN :ckws.keyset()
                    AND 
                        Self_Search__c = False
                    AND 
                        Group_Search__c = False 
                GROUP BY 
                    Interviewer_Contact__c ];
            
            foCkwClusters = [Select CKW__c, count(FO__c) foCluster from Monthly_CKW_Visit__c where Visit_Date__c = LAST_MONTH group by CKW__c];
            monthlyPerformanceList = [Select Id, 
                                            Contact__c,
                                            Performance_Date__c,
                                            Unique_Farmer_Visits__c, 
                                            Unique_Searches__c,
                                            Visits_to_F0__c
                                        FROM
                                            C3P0_CKW_Performance__c
                                        WHERE
                                            Performance_Date__c = LAST_MONTH
                                        AND
                                            Contact__c in:ckws.keyset()];
        }
        else {
            farmerMonthlyClusterMeets = [Select Contact__c, count(Focus_Farmer__c) clusters from Farmer_Cluster_Meeting__c where date__c = THIS_MONTH and Contact__c in:ckws.keyset() group by Contact__c ];

            //farmerSearches = [Select Contact__c, count(Person__c) searches from C3P0_Farmer_Visit__c where Visit_Date__c = THIS_MONTH and Contact__c in:ckws.keyset() group by Contact__c];
            farmerSearches = [
                SELECT Interviewer_Contact__c, 
                    COUNT_DISTINCT(Interviewee__c) searches
                FROM 
                    Search_Log__c 
                WHERE 
                    CreatedDate = THIS_MONTH
                    AND
                        Interviewer_Contact__c IN :ckws.keyset()
                    AND 
                        Self_Search__c = False
                    AND 
                        Group_Search__c = False 
                GROUP BY 
                    Interviewer_Contact__c ];
            
            foCkwClusters = [Select CKW__c, count(FO__c) foCluster from Monthly_CKW_Visit__c where Visit_Date__c = THIS_MONTH and CKW__c in:ckws.keyset() group by CKW__c];
            monthlyPerformanceList = [Select Id, 
                                            Contact__c,
                                            Performance_Date__c,
                                            Unique_Farmer_Visits__c, 
                                            Unique_Searches__c,
                                            Visits_to_F0__c
                                        FROM
                                            C3P0_CKW_Performance__c
                                        WHERE
                                            Performance_Date__c = THIS_MONTH
                                        AND
                                            Contact__c in:ckws.keyset()];

        }
        //AggregateResult[] result = [Select COUNT_DISTINCT(Interviewee__c) from Search_Log__c where Handset_Submit_Time__c >=: firstDate AND Handset_Submit_Time__c <: secondDate AND Interviewer__r.Full_Name__c = 'John Mutagubya'];
        ckwMonthlyPerformanceStatsMap = new Map<String, C3P0_CKW_Performance__c>();
        for (C3P0_CKW_Performance__c performance : monthlyPerformanceList) {
            ckwMonthlyPerformanceStatsMap.put(performance.Contact__c, performance);
        }
        for (AggregateResult farmerMonthlyClusterMeet : farmerMonthlyClusterMeets) {
            String contactId = (String)farmerMonthlyClusterMeet.get('Contact__c');
            Integer clusterCount = (Integer)farmerMonthlyClusterMeet.get('clusters');
            ckwClusterMeets.put(contactId, clusterCount);
        }

        for (AggregateResult farmerSearch : farmerSearches) {
            String contactId = (String)farmerSearch.get('Interviewer_Contact__c');
            Integer searchCount = (Integer)farmerSearch.get('searches');
            ckwFarmerSearches.put(contactId, searchCount);
        }

        for (AggregateResult foCkwCluster : foCkwClusters) {
            String contactId = (String)foCkwCluster.get('CKW__c');
            Integer foClusterCount = (Integer)foCkwCluster.get('foCluster');
            foCkwClusterMeets.put(contactId, foClusterCount);
        }

        If (ckwMonthlyPerformanceStatsMap.size() == 0) {
            for (String contactId : ckws.keyset()) {
                C3P0_CKW_Performance__c ckwPerformance = new C3P0_CKW_Performance__c();
                ckwPerformance.Contact__c = contactId;
                ckwPerformance.Unique_Farmer_Visits__c = 0;
                ckwPerformance.Unique_Searches__c = 0;
                ckwPerformance.Visits_to_F0__c = 0;
                ckwPerformance.CKW_Gender__c = ckwPersonRecords.get(contactId).Gender__c;
                ckwPerformance.District__c = ckwPersonRecords.get(contactId).District_Name__c;
                if (date.today().day() != 1 && date.today().day() != 2) {
                    ckwPerformance.Performance_Date__c = date.today();
                }
                else {
                    ckwPerformance.Performance_Date__c = date.today().day() == 1 ? date.today().addDays(-1) : date.today().addDays(-2);
                }
                ckwMonthlyPerformanceStatsMap.put(contactid, ckwPerformance);
            }
        }
        
        System.debug('performance map size ='+ckwMonthlyPerformanceStatsMap.size());
        for (String contactId : ckws.keyset()) {
            C3P0_CKW_Performance__c performance = ckwMonthlyPerformanceStatsMap.get(contactId);
            if (performance == null) {
                performance = new C3P0_CKW_Performance__c();
                performance.Contact__c = contactId;
                if (date.today().day() != 1 && date.today().day() != 2) {
                    performance.Performance_Date__c = date.today();
                }
                else {
                    performance.Performance_Date__c = date.today().day() == 1 ? date.today().addDays(-1) : date.today().addDays(-2);
                }
            }
            performance.Unique_Farmer_Visits__c = ckwClusterMeets.get(contactId);
            performance.Unique_Searches__c = ckwFarmerSearches.get(contactId);
            performance.Visits_to_F0__c = foCkwClusterMeets.get(contactId);
            System.debug(performance.Unique_Farmer_Visits__c);
            System.debug(performance.Unique_Searches__c);
            System.debug(performance.Visits_to_F0__c);
            ckwMonthlyPerformanceStats.add(performance);
        }        
    }
}