src/objects/Campaign_Message_Def__c.object
<CustomObject>
    <description>The message campaign message definition. This is the message that is set to enrollments.</description>
    <fields>
        <fullName>Cron__c</fullName>
        <description>A valid cron expression that specifies the scheduling of the messages.</description>
        <inlineHelpText>A valid cron expression that specifies the scheduling of the messages.</inlineHelpText>
        <label>Cron</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>The date on which the absolute message will be sent.</description>
        <inlineHelpText>The date on which the absolute message will be sent.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <inlineHelpText>The format of the campaign message e.g. SMS, IVR etc</inlineHelpText>
        <label>Format</label>
        <picklist>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The language(s) for the message, in this case, en (English).</description>
        <inlineHelpText>The language(s) for the message, in this case, en (English).</inlineHelpText>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>EN</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Message_Campaign__c</fullName>
        <description>The message campaign related to this message.</description>
        <inlineHelpText>The message campaign related to this message.</inlineHelpText>
        <label>Message Campaign</label>
        <referenceTo>MessageCampaign__c</referenceTo>
        <relationshipLabel>Campaign Messages</relationshipLabel>
        <relationshipName>Campaign_Messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Message_Key__c</fullName>
        <description>A key uniquely identifying this message.</description>
        <inlineHelpText>A key uniquely identifying this message.</inlineHelpText>
        <label>Message Key</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offset_Time__c</fullName>
        <description>The amount of time from the reference date or current date that will elapse before the message is sent.</description>
        <inlineHelpText>The amount of time from the reference date or current date that will elapse before the message is sent.</inlineHelpText>
        <label>Offset Time</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repeat_Every__c</fullName>
        <description>An interval that determines how often the message is sent until the maxDuration period has elapsed.</description>
        <inlineHelpText>An interval that determines how often the message is sent until the maxDuration period has elapsed.</inlineHelpText>
        <label>Repeat Every</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repeat_On__c</fullName>
        <description>The day of the week on which the message will be sent until the maxDuration period has elapsed.</description>
        <inlineHelpText>The day of the week on which the message will be sent until the maxDuration period has elapsed.</inlineHelpText>
        <label>Repeat On</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>The time at which the message will be sent.</description>
        <inlineHelpText>The time at which the message will be sent.</inlineHelpText>
        <label>Start Time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Campaign Message</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MessageCampaign__c.object
<CustomObject>
    <description>Represents a message campaign defined in motech</description>
    <fields>
        <fullName>Campaign_Type__c</fullName>
        <description>Store the type of message campaign</description>
        <label>Campaign Type</label>
        <picklist>
            <picklistValues>
                <fullName>Absolute</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Offset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repeat Interval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day of Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cron</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Message Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Message Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CampaignMessageDefController.cls
public with sharing class CampaignMessageDefController {

	private ApexPages.StandardController controller;
	public Campaign_Message_Def__c campaignMessage {get;set;}
	public MessageCampaign__c campaign {get;set;}
	
	public CampaignMessageDefController(ApexPages.StandardController controller) {
		this.campaignMessage = (Campaign_Message_Def__c)controller.getRecord();
		this.controller = controller;
		
		if(campaignMessage.Id != null) {
			campaignMessage = [
				SELECT 
					Name, 
					Format__c,
					Language__c,
					Message_Key__c,
					Date__c,
					Start_Time__c,
					Offset_Time__c,
					Repeat_Every__c,
					Cron__c,
					Repeat_On__c,
					Message_Campaign__r.Id,
					Message_Campaign__r.Name,
					Message_Campaign__r.Campaign_Type__c 
				FROM Campaign_Message_Def__c 
				WHERE Id =: campaignMessage.Id ];
			
			campaign = campaignMessage.Message_Campaign__r;
		} else {
			campaignMessage = new Campaign_Message_Def__c();
		}
	}
	
	/**
	 * saves the campaign message and returns the page reference to the message campaign in which the 
	 * campaign message belongs.
	 */
	public PageReference save() {
		try{
			upsert campaignMessage;		
			String ObjectPrefix = CKW__c.sObjectType.getDescribe().getKeyPrefix();
			PageReference p = new PageReference('/apex/MessageCampaign?id='+campaignMessage.Message_Campaign__c);
			p.setRedirect(true);
			
			return p;
		}catch(Exception ex) {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, ex.getMessage()));
			return null;
		}
	}
	
	public PageReference saveAndNew() {
		try{
			upsert campaignMessage;		
			String ObjectPrefix = Campaign_Message_Def__c.sObjectType.getDescribe().getKeyPrefix();
			PageReference p = new PageReference('/'+ objectPrefix + '/e');
			p.setRedirect(true);
			
			return p;
		}catch(Exception ex) {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, ex.getMessage()));
			return null;
		}
	}
	
	/**
	 * called when the user changes the message campaign from the user interface and it's used 
	 * to load the message campaign details from the data store.
	 */
	public void onChangeMessageCampaign() {
		if(campaignMessage.Message_Campaign__c != null) {
			campaign = [SELECT Id, Name, Campaign_Type__c FROM MessageCampaign__c WHERE Id =: campaignMessage.Message_Campaign__c];
		} else {
			campaignMessage.Message_Campaign__c = null;
			campaign = null;
		}
	}
	
	/**
	 * checks whether the campaign is an Absolute campaign
	 */
	public Boolean isAbsoluteCampaign() {
		return isCampaignType('Absolute');
	}
	
	/**
	 * checks whether the campaign is an offset campaign
	 */
	public Boolean isOffsetCampaign() {
		return isCampaignType('Offset');
	}
	
	/**
	 * checks whether the campaign is a Repeat Interval campaign
	 */
	public Boolean isRepeatIntervalCampaign() {
		return isCampaignType('Repeat Interval');
	}
	
	/**
	 * checks whether the campaign is a Cron campaign
	 */
	public Boolean isCronCampaign() {
		return isCampaignType('Cron');
	}
	
	/**
	 * checks whether the campaign is a Day of Week campaign
	 */
	public Boolean isDayOfWeekCampaign() {
		return isCampaignType('Day of Week');
	}
	
	/**
	 * checks whether the campaign is of a given type
	 */
	public Boolean isCampaignType(String campaignType) {
		if(campaign != null && campaign.Campaign_Type__c == campaignType) {
			return true;
		}
		
		return false;
	}
}