src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Please select a category for the support request based on the content of support</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Phone handset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application - Pulse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application - CKW Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application - Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content  - Pulse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content - CKW Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content - Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Money</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charging Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer ID Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue from Field Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Animals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Crops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Market Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Farm Inputs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Service Providers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN SIM Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAADS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person associated with this request</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCallCenterController.cls
@isTest
public class TestCallCenterController {

    static testmethod void testGetByPhoneNumber() {
        CallCenterController controller = new CallCenterController();
        String dummyPhoneNumber = '0749876342';
        controller.setPhoneNumber(dummyPhoneNumber);
        Farmer__c testFarmer = controller.createDefaultFarmer();  
        controller.setFarmer(testFarmer);      
        Farmer__c[] farmers = controller.getByPhoneNumber(dummyPhoneNumber);
        system.assert(!farmers.isEmpty());
        system.assert(farmers[0].Id == testfarmer.Id);
    }
    
    static testmethod void testSearchByPhoneNumber() {
        CallCenterController controller = new CallCenterController();
        controller.callerType = 'Farmer';
        String dummyPhoneNumber = '+256771234567';
        controller.setPhoneNumber(dummyPhoneNumber);       
        PageReference pageRef1 = controller.searchByPhoneNumber();
        //PageReference pageRef2 = controller.saveFarmerChanges();
        system.assert(pageRef1 == null);
        //system.assert(pageRef2 == null);
    }
    
    static testmethod void testCreateCases() {        
        CallCenterController controller = new CallCenterController();
        Farmer__c testFarmer = controller.createDefaultFarmer(); 
        Case farmerCase = controller.getCurrentCase();  
        
        System.assert(controller.saveCurrentCase(new Person__c()) == false);   
           
        boolean saved = controller.saveCurrentCase(testFarmer);
        system.assertEquals(saved , false);
        farmerCase.Subject = 'test';
        farmerCase.Category__c = 'Pulse';
        farmerCase.Status = 'New';
        saved = controller.saveCurrentCase(testFarmer);
        system.assertEquals(saved , true);
        
        Person__c person = new Person__c();
        person.First_Name__c = 'testName';
        insert person;
        controller.setChosenId(String.valueOf(person.Id));
        controller.setCkw(person);
        boolean psaved = controller.saveCurrentCase(person);
        system.assertEquals(psaved , true);        
    }
    
   static testmethod void testGetFarmerCases() {
        CallCenterController controller = new CallCenterController();
        Farmer__c testFarmer = null;
        Case[] cases1 = controller.getFarmerCases(testFarmer);
        testFarmer = controller.createDefaultFarmer(); 
        Case[] cases2 = controller.getFarmerCases(testFarmer);
        Case[] cases3 = controller.getCases();
        system.assert(cases1 ==null);
        //system.assert(!cases2.isEmpty());        
    }
    
    static testmethod void testPageReferences() {
        CallCenterController controller = new CallCenterController();
        controller.callerType = 'Farmer';
        controller.setPhoneNumber('0791568666');
        controller.searchByPhoneNumber();
        Case currentCase = controller.getCurrentCase();
        currentCase.Status = 'Closed';
        controller.saveCase();
        controller.saveCaseAndClose();
        
        Person__c person = new Person__c();
        person.First_Name__c = 'testName';
        insert person;
        controller.setCkw(person);
        controller.savePersonChanges();//for existing person
        controller.setIsNewFarmer(true);
        controller.savePersonChanges();//for new person
        controller.finish();
        controller.changeFarmer();
        system.assert(currentCase != null);
    }

    // Testing getters and setters to increase code coverage
    static testmethod void testGettersAndSetters() {
        CallCenterController controller = new CallCenterController();
        controller.callerType = 'Farmer';
        String phoneNumber = '078000000';
        controller.setPhoneNumber(phoneNumber);               
        system.assert(controller.getPhoneNumber() == phoneNumber);       
        system.assert(controller.getFarmer() == null);
        system.assert(controller.getFarmers() == null);
        system.assert(controller.searchByPhoneNumber() ==  null);
        system.assert(controller.getIsNewFarmer() == false);
        system.assert(controller.getResponse() != 'response');
        controller.callerType = 'CKW';
        system.assert(controller.getPhoneNumber() == phoneNumber);  
        system.assert(controller.getCallBackRequired() == false);  
        system.assert(controller.getChosenId() == null); 
        system.assert(controller.getCkw() == null); 
        controller.setChosenId('');
    }
}