src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Please select a category for the support request based on the content of support</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Phone handset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application - Pulse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application - CKW Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application - Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content  - Pulse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content - CKW Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content - Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Money</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charging Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer ID Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue from Field Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Animals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Crops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Market Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Farm Inputs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Service Providers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call center - Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN SIM Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ministry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAADS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person associated with this request</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>Current response of support staff on this ticket</description>
        <inlineHelpText>Enter a description here about how the user should address this case</inlineHelpText>
        <label>Response</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Crops__c</fullName>
        <description>Top crops grown by the farmer</description>
        <label>Crops</label>
        <picklist>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wheat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cassava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irish Potatoes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundnuts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sorghum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bananas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cotton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Livestock__c</fullName>
        <description>Livestock kept by the farmer</description>
        <label>Livestock</label>
        <picklist>
            <picklistValues>
                <fullName>Cattle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goats</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chickens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Turkeys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donkeys</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sheep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pigs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rabbits</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Topics_of_Interest__c</fullName>
        <description>Topics of interest for the farmer</description>
        <label>Topics of Interest</label>
        <picklist>
            <picklistValues>
                <fullName>Market Prices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Opportunities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weather</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planting/Garden Prep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pest and Disease Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soil Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harvesting/PHH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farming as a Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Livestock Rearing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agricultural Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District_Name__c</fullName>
        <formula>District__r.Name</formula>
        <label>District Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>(optional) middle name for the person</description>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <description>Mobile phone number calculated based on Mobile Phone and Raw Mobile Number fields</description>
        <formula>/* If we have a Handset, use the number from its SIM Card */
IF( NOT( ISBLANK( Handset__c)),  
     Handset__r.SIM__r.Name, 
/* otherwise use the raw mobile number */
       Raw_Mobile_Number__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raw_Mobile_Number__c</fullName>
        <description>(optional) Phone number provided for non GF-assets</description>
        <label>Raw Mobile Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Village__c</fullName>
        <description>Village that the person lives in</description>
        <label>Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CallCenterController.cls
public class CallCenterController {
        
    String caseId = '';
    String phoneNumber;  
    String response;
    Boolean isNewFarmer;
    Farmer__c[] farmers;
    Farmer__c farmer;
    Case[] cases;

    Case currentCase;
        
    public String getPhoneNumber() {
        return phoneNumber;     
    }
        
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }  
    
    public Boolean getIsNewFarmer() {
        return this.isNewFarmer;
    }                                                          
    
    public Farmer__c[] getFarmers() {
        return farmers;
    }
        
    public Farmer__c getFarmer() {
        return farmer;
    }
        
    public void setFarmer(Farmer__c farmer) {
        this.farmer = farmer;
    }
        
    public Case[] getCases() {
        cases = getFarmerCases(farmer);
        return cases;
    }
        
    public Case getCurrentCase() {
        if(currentCase == null) {
            currentCase = new Case();
        }
        return currentCase;
    }
    
    public String getResponse() {
        return this.response;
    }
    
    public void setResponse(String response) {
        this.response = response;
    }
                        
    public PageReference searchByPhoneNumber() {  
        // Clear all farmer details in preparation for new search
        isNewFarmer = false;
        clearCaseFields();
        clearAllFarmers(); 
        // Check if string is in format +2567xxxxxxxx and change to 7xxxxxxxx
        // where x in [0-9]
        if (phoneNumber.startsWith('+256')) {
            phoneNumber = phoneNumber.substring(4);  
        }   
        else if (phoneNumber.length() == 10) {
            phoneNumber = phoneNumber.substring(1);
        }
        if (isWellFormedPhoneNumber(phoneNumber)) {                   
            farmers = getByPhoneNumber(phoneNumber);
            // Check if there is any farmer with a matching phone number  
            if (farmers.isEmpty() || farmers == null) {
                farmer = createDefaultFarmer();
                isNewFarmer  = true;
                farmers = getByPhoneNumber(phoneNumber);
                farmer = farmers[0];
            }  
            else {
                farmer = farmers[0];
            }     
        }      
        return null;        
    }
        
    public PageReference getFarmerDetails() {
        String farmerId = ApexPages.currentPage().getParameters().get('fId');
        PageReference pageRef = new PageReference('/' + farmerId);
        return pageRef.setRedirect(true);
    }
    
    public PageReference saveFarmerChanges() {
        database.update(farmer.Person__r);
        database.update(farmer);
        farmers = getByPhoneNumber(farmer.Person__r.Mobile_Number__c);
        farmer = farmers[0];
        isNewFarmer = false;
        return null;
    }
       
    public PageReference getCaseDetails () {
        String caseId= ApexPages.currentPage().getParameters().get('cId');
        PageReference pageRef = new PageReference('/' + caseId + '?isdtp=mn&retURL=/ui/desktop/DesktopMainDefaultPage?isdtp=mn');
        return pageRef.setRedirect(true);
    }
         
    public PageReference linkArticles() {
        if (saveCurrentCase(farmer)) {
            PageReference pageRef = new PageReference('/knowledge/knowledgeHome.apexp?id=' + currentCase.Id + '&isdtp=mn');
            return pageRef.setRedirect(true);
        }            
        return null;
    }
    
    public PageReference saveCaseAndClear() {
        if (saveCurrentCase(farmer)) {
            if (currentCase.Status == 'Closed') {
                // For all closed cases update total_complete_interactions_call_center
                MetricHelpers.updateMetric('total_complete_interactions_call_center', 1.0, null, null, MetricHelpers.getQuarterFirstDay(MetricHelpers.getCurrentQuarterAsString(0)), MetricHelpers.getQuarterLastDay(MetricHelpers.getCurrentQuarterAsString(0)), true);
                MetricHelpers.updateMetric('total_info_services_offered', 1.0, null, null, MetricHelpers.getQuarterFirstDay(MetricHelpers.getCurrentQuarterAsString(0)), MetricHelpers.getQuarterLastDay(MetricHelpers.getCurrentQuarterAsString(0)), true);
            }
            clearCaseFields();    
            // Reset all fields and prepare for next search 
            clearAllFarmers();  
        }      
        return null;
    }
    
    public PageReference saveCaseAndClose() {
        currentCase.Status = 'Closed';
        if (saveCurrentCase(farmer)) {
             // For all closed cases update total_complete_interactions_call_center
            MetricHelpers.updateMetric('total_complete_interactions_call_center', 1.0, null, null, MetricHelpers.getQuarterFirstDay(MetricHelpers.getCurrentQuarterAsString(0)), MetricHelpers.getQuarterLastDay(MetricHelpers.getCurrentQuarterAsString(0)), true);
            MetricHelpers.updateMetric('total_info_services_offered', 1.0, null, null, MetricHelpers.getQuarterFirstDay(MetricHelpers.getCurrentQuarterAsString(0)), MetricHelpers.getQuarterLastDay(MetricHelpers.getCurrentQuarterAsString(0)), true);
            clearCaseFields();    
            // Reset all fields and prepare for next search 
            clearAllFarmers(); 
        } 
        return null;        
    }
    
    public PageReference saveCase() {
        if (saveCurrentCase(farmer)) {  
            if (currentCase.Status == 'Closed') {
                // For all closed cases update total_complete_interactions_call_center
                MetricHelpers.updateMetric('total_complete_interactions_call_center', 1.0, null, null, MetricHelpers.getQuarterFirstDay(MetricHelpers.getCurrentQuarterAsString(0)), MetricHelpers.getQuarterLastDay(MetricHelpers.getCurrentQuarterAsString(0)), true);
                MetricHelpers.updateMetric('total_info_services_offered', 1.0, null, null, MetricHelpers.getQuarterFirstDay(MetricHelpers.getCurrentQuarterAsString(0)), MetricHelpers.getQuarterLastDay(MetricHelpers.getCurrentQuarterAsString(0)), true);
                clearCaseFields(); 
            }
        }
        return null;
    }
    
    private boolean saveCurrentCase(Farmer__c farmer) {     
        if (currentCase.Subject == null || currentCase.Category__c == null || currentCase.Status == null) {
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR,'The case must have Subject, Category and Status values');
            ApexPages.addMessage(errorMessage);
            return false;
        }      
        currentCase.Type = 'Question';            
        currentCase.Person__c = farmer.Person__r.Id;            
        currentCase.Reason = 'reason';
        currentCase.Response__c = this.response;
        currentcase.Origin = 'Phone Call';
        database.upsert(currentCase);               
        return true;
     }
        
    private Farmer__c createDefaultFarmer() {   
        Farmer__c farmer;
        Person__c person;        
        farmer = new Farmer__c();
        person = new Person__c();             
        // Populate the biographical details for the farmer.
        person = addPersonBioDetails(person);          
        // Save the persons and farmer objects     
        database.insert(person);    
        farmer.Person__c = person.Id;     
        database.insert(farmer);     
        return farmer;       
    }

    private Person__c addPersonBioDetails(Person__c person) {
        
        // Set default values for Unknown Farmer
        person.First_Name__c = 'Unknown Call-Centre';
        person.Last_Name__c = 'Farmer';
        person.Raw_Mobile_Number__c = phoneNumber;
        person.Village__c = 'Unknown';  
        // Not yet on production system  
        // person.Type__c = 'Farmer';    
        return person;
    }
    
    private Boolean isWellFormedPhoneNumber(String phoneContact) {
        String phoneRegex = '[0-9]{9}';
        Pattern phoneNumberPattern = Pattern.compile(phoneRegex);
        Matcher numberMatch = phoneNumberPattern .matcher(phoneContact);
        return numberMatch.matches();
    }
    
    private Farmer__c[] getByPhoneNumber(String phoneContact) {
        farmers = [
                SELECT 
                    Id,
                    Name,
                    Crops__c,
                    Livestock__c,
                    Topics_of_Interest__c,
                    Person__c,
                    Person__r.First_Name__c,
                    Person__r.Middle_Name__c,
                    Person__r.Last_Name__c,
                     Person__r.District_Name__c,
                    Person__r.District__c,
                    Person__r.Mobile_Number__c,
                    Person__r.Raw_Mobile_Number__c
                FROM
                    Farmer__c 
                WHERE
                    Person__r.Mobile_Number__c
                    LIKE
                    :('%' + phoneContact)
                ];
        return farmers; 
    }
    
    private Case[] getFarmerCases(Farmer__c farmer) {
        if (farmer == null) {
           return null;
        }
        cases = [
                    SELECT
                        Id,                        
                        Subject,
                        CaseNumber,
                        Status,
                        Description,
                        CreatedDate
                        
                    FROM
                        Case
                    WHERE
                        Person__c = :farmer.Person__r.Id
                    ORDER BY CreatedDate DESC
                    LIMIT 5
                                               
               ];
        return cases;
    }
        
    public void clearCaseFields() {
        currentCase = null;
        setResponse('');
    }
    
    public void clearAllFarmers() {
        farmers = null;
        farmer = null;
    }
   
    static testmethod void testGetByPhoneNumber() {
        CallCenterController controller = new CallCenterController();
        String dummyPhoneNumber = '0749876342';
        controller.setPhoneNumber(dummyPhoneNumber);
        Farmer__c testFarmer = controller.createDefaultFarmer();  
        controller.setFarmer(testFarmer);      
        Farmer__c[] farmers = controller.getByPhoneNumber(dummyPhoneNumber);
        system.assert(!farmers.isEmpty());
        system.assert(farmers[0].Id == testfarmer.Id);
    }
    
    static testmethod void testSearchByPhoneNumber() {
        CallCenterController controller = new CallCenterController();
        String dummyPhoneNumber = '+256771234567';
        controller.setPhoneNumber(dummyPhoneNumber);       
        PageReference pageRef1 = controller.searchByPhoneNumber();
        PageReference pageRef2 = controller.saveFarmerChanges();
        system.assert(pageRef1 == null);
        system.assert(pageRef2 == null);
    }
    
    static testmethod void testCreateCases() {
        CallCenterController controller = new CallCenterController();
        Farmer__c testFarmer = controller.createDefaultFarmer(); 
        Case farmerCase = controller.getCurrentCase();        
        boolean saved = controller.saveCurrentCase(testFarmer);
        system.assertEquals(saved , false);
        farmerCase.Subject = 'test';
        farmerCase.Category__c = 'Pulse';
        farmerCase.Status = 'New';
        saved = controller.saveCurrentCase(testFarmer);
        system.assertEquals(saved , true);
        
    }
    
   static testmethod void testGetFarmerCases() {
        CallCenterController controller = new CallCenterController();
        Farmer__c testFarmer = null;
        Case[] cases1 = controller.getFarmerCases(testFarmer);
        testFarmer = controller.createDefaultFarmer(); 
        Case[] cases2 = controller.getFarmerCases(testFarmer);
        Case[] cases3 = controller.getCases();
        system.assert(cases1 ==null);
        system.assert(!cases2.isEmpty());        
    }
    
    static testmethod void testPageReferences() {
        CallCenterController controller = new CallCenterController();
        controller.setPhoneNumber('0791568666');
        controller.searchByPhoneNumber();
        Case currentCase = controller.getCurrentCase();
        currentCase.Status = 'Closed';
        controller.saveCase();
        controller.saveCaseAndClose();
        system.assert(currentCase != null);
    }

    // Testing getters and setters to increase code coverage
    static testmethod void testGettersAndSetters() {
        CallCenterController controller = new CallCenterController();
        String phoneNumber = '078000000';
        controller.setPhoneNumber(phoneNumber);               
        system.assert(controller.getPhoneNumber() == phoneNumber);       
        system.assert(controller.getFarmer() == null);
        system.assert(controller.getFarmers() == null);
        system.assert(controller.searchByPhoneNumber() ==  null);
        system.assert(controller.getIsNewFarmer() == true);
        system.assert(controller.getResponse() != 'response');
    }    
}