src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person associated with this request</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>Current response of support staff on this ticket</description>
        <inlineHelpText>Enter a description here about how the user should address this case</inlineHelpText>
        <label>Response</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <description>A message sent to a user in our system</description>
    <fields>
        <fullName>Recipient__c</fullName>
        <description>The recipient of the message</description>
        <label>Recipient</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>MSG-{00000000}</displayFormat>
        <label>Message ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestSupportTrigger.cls
public class TestSupportTrigger {

    static testMethod void testSupportTrigger() {
    	
        Case testCase = new Case();

        Person__c person = new Person__c();
        person.First_Name__c = 'test';        
        database.insert(person);

		Integer beforeMessageCount = [SELECT COUNT() FROM Message__c WHERE Recipient__c =:person.id];

        testCase.Person__c = person.id;
        testCase.Subject = 'test';
        database.insert(testCase);

        testCase.Response__c = 'test response';
        database.update(testCase);       
                
		Integer afterMessageCount = [SELECT COUNT() FROM Message__c WHERE Recipient__c =:person.id];
        System.assert(afterMessageCount - beforeMessageCount == 1);
    }
}