src/objects/CBL2_Farmer__c.object
<CustomObject>
    <description>CBL2_Farmer object replaced CBL_Coffebaseliine, CBL_Socioeconomic, CBL_attitude, CBL_service, CBL_commercialization</description>
    <fields>
        <fullName>sbuxSegmentProbability__c</fullName>
        <label>sbuxSegmentProbability</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>sbuxSegment__c</fullName>
        <label>sbuxSegment</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>CBL2_Farmer</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>CBL_CoffeeBaselineId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL2_Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SbuxSegmentationProcessBatchJob_CBL2.cls
global class SbuxSegmentationProcessBatchJob_CBL2 implements Database.Batchable<sObject>{

  global Database.QueryLocator start(Database.BatchableContext bc) {
  String query = 'Select Id, sbuxSegment__c, sbuxSegmentProbability__c from CBL2_Farmer__c where sbuxSegment__c = null';
  return Database.getQueryLocator(query);
  }
  
  global void execute(Database.BatchableContext bc, List<CBL2_Farmer__c> bls) {
    for (CBL2_Farmer__c bl : bls) {
        SBuxSegmentationProcessHandler_CBL2 handler = new SBuxSegmentationProcessHandler_CBL2(bl);
        handler.handle();
    }
  }
  
  global void finish(Database.BatchableContext bc) {
    // Do nothing
  }

}