src/objects/CBL2_Farmer__c.object
<CustomObject>
    <description>CBL2_Farmer object replaced CBL_Coffebaseliine, CBL_Socioeconomic, CBL_attitude, CBL_service, CBL_commercialization</description>
    <fields>
        <fullName>LAC_Farmer_Details__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LAC_Farmer_Details</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>LAC_Farmer_Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CBL2_Farmer</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>CBL_CoffeeBaselineId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL2_Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Full_Name__c</fullName>
        <formula>hyperlink (&quot;/&quot; &amp;Id, LastName &amp; &quot;, &quot; &amp; FirstName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Full Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/EMP_Consultant__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Consultant_contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EMP Consultants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Consultant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Consultant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Consultants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Coffee_CKW__c.object
<CustomObject>
    <fields>
        <fullName>LAC_Farmer_Details__c</fullName>
        <label>LAC Farmer Details</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>LAC_Coffee_CKWs_LFD</relationshipLabel>
        <relationshipName>LAC_Coffee_CKWs_LFD</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC_Coffee_CKWs_Contact</relationshipLabel>
        <relationshipName>LAC_Coffee_CKWs_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LAC_Coffee_CKW</label>
    <nameField>
        <label>LAC_Coffee_CKW Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC_Coffee_CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>interviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC_Farmer_Details_interviewer</relationshipLabel>
        <relationshipName>LAC_Farmer_Details_interviewer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LACCoffeeCKWFarmers.cls
public class LACCoffeeCKWFarmers {

public ApexPages.StandardController stdController;
public LAC_Coffee_CKW__c coffeeCKW;
public LAC_Farmer_Details__c[] farmers = new List<LAC_Farmer_Details__c>();
public LAC_Coffee_CKW__c ckwId;

public LACCoffeeCKWFarmers(ApexPages.StandardController controller) {
    this.stdController = controller;
    this.coffeeCKW = (LAC_Coffee_CKW__c)controller.getRecord();   
                                                 
    LAC_Coffee_CKW__c[] ckwIds = [Select LAC_Farmer_Details__r.Contact__c From LAC_Coffee_CKW__c Where Id =:coffeeCKW.Id];
        if (ckwIds.size() > 0) {
            ckwId = ckwIds[0];
        }
}

public LAC_Coffee_CKW__c getCkwId() {
    return ckwId;
}


public  List<LAC_Farmer_Details__c> getFarmers() {
    if (coffeeCKW != null) {
        LAC_Farmer_Details__c[] farmers = [Select Contact__r.Contact_Full_Name__c,Name
                                                     from LAC_Farmer_Details__c
                                                     where interviewer__c=:ckwId.LAC_Farmer_Details__r.Contact__c];
        if (farmers.size() > 0) {
            return farmers;
        }
    }
    return null;
}
}