src/objects/CBL2_Farm__c.object
<CustomObject>
    <fields>
        <fullName>CBL2_Farms_Farmer__c</fullName>
        <label>CBL2_Farms_Farmer</label>
        <referenceTo>CBL2_Farmer__c</referenceTo>
        <relationshipLabel>CBL2_Farms_Farmer</relationshipLabel>
        <relationshipName>CBL2_Farms_Farmer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farmer</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>CBL2_Farms_LFD</relationshipLabel>
        <relationshipName>CBL2_Farms_LFD</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>farmName__c</fullName>
        <label>farmName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CBL2_Farm</label>
    <nameField>
        <displayFormat>FM-{0000000}</displayFormat>
        <label>CBL2_Farm Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL2_Farms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL2_Farmer__c.object
<CustomObject>
    <description>CBL2_Farmer object replaced CBL_Coffebaseliine, CBL_Socioeconomic, CBL_attitude, CBL_service, CBL_commercialization</description>
    <fields>
        <fullName>LAC_Farmer_Details__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LAC_Farmer_Details</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>LAC_Farmer_Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CBL2_Farmer</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>CBL_CoffeeBaselineId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL2_Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBL2_Lot__c.object
<CustomObject>
    <fields>
        <fullName>Farm__c</fullName>
        <label>Farm</label>
        <referenceTo>CBL2_Farm__c</referenceTo>
        <relationshipLabel>CBL2_Lots_Farm</relationshipLabel>
        <relationshipName>CBL2_Lots_Farm</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>lotName__c</fullName>
        <label>lotName</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CBL2_Lot</label>
    <nameField>
        <displayFormat>LT-{0000000}</displayFormat>
        <label>CBL2_Lot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL2_Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CQT_CoffeeSample__c.object
<CustomObject>
    <fields>
        <fullName>Farm__c</fullName>
        <label>Farm</label>
        <referenceTo>CBL2_Farm__c</referenceTo>
        <relationshipLabel>CQT_CoffeeSamples_Farm</relationshipLabel>
        <relationshipName>CQT_CoffeeSamples_Farm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LAC_Farmer__c</fullName>
        <label>LAC Farmer</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>CQT_CoffeeSamples_LAC_FD</relationshipLabel>
        <relationshipName>CQT_CoffeeSamples_LAC_FD</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lot__c</fullName>
        <label>Lot</label>
        <referenceTo>CBL2_Lot__c</referenceTo>
        <relationshipLabel>CQT_CoffeeSamples_Lot</relationshipLabel>
        <relationshipName>CQT_CoffeeSamples_Lot</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CQT_CoffeeSample</label>
    <nameField>
        <label>CQT_CoffeeSample Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CQT_CoffeeSamples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EMP_Consultant__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Consultant_contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EMP Consultants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Consultant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Consultant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Consultants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>National_ID__c</fullName>
        <label>National ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CQT_SamplePageController.cls
public class CQT_SamplePageController { 
    
    public LAC_Farmer_Details__c objLACFarmerD;
    private CBL2_Farmer__c objFarmer;
    private CBL2_Farm__c objFarm;
    private CBL2_Lot__c objLot;
    //private Id LACFarmerDetails_Id;
    
    public CQT_SamplePageController () {
        Init();
        //if(ProductorId == null)
            //ProductorId = '000000003';
        //testReport();
    }
    
    private void Init(){
        ProductorId = '';
        ProductorName = '';
        ProductorLastName = '';
        FarmSelected = '';
        LotSelected = '';
        FarmSelected_Name = '';
        ProductorIdSelected = '';
        FarmsOptions = new List<SelectOption>();
        FarmsOptions.add(new SelectOption('','Seleccione una finca'));
        LotsOptions = new List<SelectOption>();
        LotsOptions.add(new SelectOption('','Lote no especificado'));
        objCoffeeSample = new CQT_CoffeeSample__c();
        ProducersOptions = new List<SelectOption>();
        ProducersOptions.add(new SelectOption('','Aquí aparecerá la lista de productores encontrados'));   
    }
    
    public String ProductorId { get; set; }
    public String ProductorName { get; set; }
    public String ProductorLastName { get; set; }
    public String FarmSelected { get; set; }
    public List<SelectOption> FarmsOptions {get; set; }
    public String LotSelected { get; set; }
    public List<SelectOption> LotsOptions {get; set; }
    public String FarmSelected_Name { get {return getNameFarmSelected();} set {} }
    public CQT_CoffeeSample__c objCoffeeSample { get; set; }
    public List<SelectOption> ProducersOptions {get; set; }
    public String ProductorIdSelected { get; set; }
        
    /*public PageReference SearchProductor() {
        //if(ProductorId != null)
        String queryStr = 'SELECT Id, National_ID__c, Contact__r.FirstName, First_Name__c, Last_Name__c FROM LAC_Farmer_Details__c WHERE National_ID__c = \'' + ProductorId + '\'';
        LAC_Farmer_Details__c [] LACfarmers = Database.query(queryStr);
        if(LACfarmers.size() > 0){
            ProductorName = LACfarmers[0].First_Name__c + ' ' + LACfarmers[0].Last_Name__c;
            LACFarmerDetails_Id = LACfarmers[0].Id;
            SearchFarmer_and_Farms(LACFarmerDetails_Id);
        }
        else
            ProductorName = 'no se encontró productor';
        return null;
    }*/
    
    public PageReference SearchProducers() {
        String queryStr = 'SELECT Id, National_ID__c, Contact__r.FirstName, First_Name__c, Last_Name__c FROM LAC_Farmer_Details__c WHERE National_ID__c LIKE \'%' + ProductorId + '%\' AND Contact__r.FirstName LIKE \'%' + ProductorName + '%\' AND Last_Name__c LIKE \'%' + ProductorLastName + '%\' LIMIT 6';
        LAC_Farmer_Details__c [] LACfarmers = Database.query(queryStr);
        if(LACfarmers.size() > 0){
            ProducersOptions = new List<SelectOption>();
            for(LAC_Farmer_Details__c farmer : LACfarmers){
                ProducersOptions.add(new SelectOption(farmer.Id, farmer.National_ID__c + ' - ' + farmer.First_Name__c + ' ' +farmer.Last_Name__c));
            }
            if(LACfarmers.size() > 5){
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Existen más registos encontrados, por favor ajuste el (los) témino(s) de búsqueda');
                ApexPages.addMessage(myMsg);
            }
        }
        else
            ProductorName = 'no se encontró productor';
        return null;
    }
    
    /*private void SearchFarmer_and_Farms(Id Id_LACFarmerDetail) {
        CBL2_Farmer__c [] cbl2Farmers = [SELECT Id FROM CBL2_Farmer__c WHERE LAC_Farmer_Details__c =: Id_LACFarmerDetail];
        if(cbl2Farmers.size() > 0){
            //CBL2_Farm__c [] cbl2Farms = [SELECT Id, farmName__c FROM CBL2_Farm__c WHERE CBL2_Farms_Farmer__c =: cbl2Farmers[0].Id];
            CBL2_Farm__c [] cbl2Farms = [SELECT Id, farmName__c FROM CBL2_Farm__c WHERE Farmer__c =: Id_LACFarmerDetail];
            FarmsOptions = new List<SelectOption>();
            //boolean isDisabled = (cbl2Farms.size() > 0) ? true: false;
            //FarmsOptions.add(new SelectOption('','Seleccione una finca', isDisabled));
            FarmsOptions.add(new SelectOption('','Seleccione una finca'));
            if(cbl2Farms.size() > 0){                
                for (CBL2_Farm__c farm : cbl2Farms){
                    FarmsOptions.add(new SelectOption(farm.Id, farm.farmName__c));                 
                }
            }
        }            
    }*/
    
    public void SearchFarmer_and_Farms() {
		FarmSelected = '';
        FarmSelected_Name = '';
        LotSelected = '';
        CBL2_Farmer__c [] cbl2Farmers = [SELECT Id, LAC_Farmer_Details__r.National_ID__c, LAC_Farmer_Details__r.First_Name__c, LAC_Farmer_Details__r.Last_Name__c FROM CBL2_Farmer__c WHERE LAC_Farmer_Details__c =: ProductorIdSelected];
        if(cbl2Farmers.size() > 0){
            ProductorId = cbl2Farmers[0].LAC_Farmer_Details__r.National_ID__c;
            ProductorName = cbl2Farmers[0].LAC_Farmer_Details__r.First_Name__c;
            ProductorLastName = cbl2Farmers[0].LAC_Farmer_Details__r.Last_Name__c;
            //CBL2_Farm__c [] cbl2Farms = [SELECT Id, farmName__c FROM CBL2_Farm__c WHERE CBL2_Farms_Farmer__c =: cbl2Farmers[0].Id];
            CBL2_Farm__c [] cbl2Farms = [SELECT Id, farmName__c FROM CBL2_Farm__c WHERE Farmer__c =: ProductorIdSelected];
            FarmsOptions = new List<SelectOption>();
            //boolean isDisabled = (cbl2Farms.size() > 0) ? true: false;
            //FarmsOptions.add(new SelectOption('','Seleccione una finca', isDisabled));
            FarmsOptions.add(new SelectOption('','Seleccione una finca'));
            if(cbl2Farms.size() > 0){                
                for (CBL2_Farm__c farm : cbl2Farms){
                    FarmsOptions.add(new SelectOption(farm.Id, farm.farmName__c));                 
                }
            }
            LotsOptions = new List<SelectOption>();
            LotsOptions.add(new SelectOption('','Lote no especificado'));
        }            
    }
    
    public void SearchLots() {
        if(FarmSelected != ''){
            CBL2_Lot__c [] cbl2lots = [SELECT Id, lotName__c FROM CBL2_Lot__c WHERE Farm__c =: FarmSelected];
            LotsOptions = new List<SelectOption>();
            LotsOptions.add(new SelectOption('','Lote no especificado'));
            for(CBL2_Lot__c lot : cbl2lots){
                LotsOptions.add(new SelectOption(lot.Id, lot.lotName__c));                
            }
        }
    }
    
    private String getNameFarmSelected(){
        String strName = '';
        for(SelectOption option : FarmsOptions){
            if(FarmSelected == option.getValue())
                strName = Option.getLabel();
        }        
        return strName;        
    }
    
    public PageReference save() {
        if(ProductorIdSelected == null){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Debe seleccionar un productor');
            ApexPages.addMessage(myMsg);
            return null;
        }
        if(FarmSelected == null){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Debe seleccionar una Finca');
            ApexPages.addMessage(myMsg);
            return null;
        } 
        objCoffeeSample.LAC_Farmer__c = ProductorIdSelected;
        objCoffeeSample.Farm__c = FarmSelected;
        if(LotSelected != null)
            objCoffeeSample.Lot__c = LotSelected;
        try{
            Database.insert(objCoffeeSample);
            Init();
            PageReference pageRef = new PageReference('/apex/CQT_SamplePage');
        	pageRef.setRedirect(true);
        	return pageRef;
            //return new pagereference(page.CQT_SamplePage.getUrl());
        }
        catch(system.Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
            ApexPages.addMessage(myMsg);
            return null;
        }
        
        //contact.accountId = account.id;
        //ApexPages.StandardController contactController = new ApexPages.StandardController(contact);
        //return contactController.save();
        return null;//redirect to other page
    }
    
    public PageReference ClearAllFilds(){
        Init();        
        return null;
    }
    
    public PageReference AddAnalysis() {
        PageReference pageRef = new PageReference('/apex/CQT_AnalysisPage');
       	pageRef.setRedirect(true);
       	return pageRef;
    }
    
    /*public PageReference callpageredirect(){
        //<apex:commandLink action="{!callpageredirect}" value="Crear Nuevo Productor"/>
        PageReference demoPage = new PageReference('/apex/DeleteSurvey');
        demoPage.setRedirect(true);
        return demoPage;
    }*/
    
    /*
    public List<Report> Reportes {get; set; }
    
    public void testReport(){
        //string abc = reports.ReportMetadata.getName();
        Id reportId = '00O700000049Sbl'; //'00O70000004rBAX';
        //Reportes = [SELECT Id, Name, OwnerId FROM Report where Id =:reportId];
        Reportes = [SELECT Id, Name, OwnerId, DeveloperName FROM Report where Id=: reportId LIMIT 10];
        for(Report rep : reportes){
            Reports.ReportMetadata rm = Reports.ReportManager.describeReport(rep.Id).getReportMetadata();
            objCoffeeSample.Notes__c = rm.getReportType().getLabel() + ' - ' + rm.getReportType().getType();
        }
        
        //id report 00O700000049Sbl
        //report type Person Group Handsets 2
        //id report type 07070000000TVkL
        
        //Reports.ReportMetadata RepMet = Reports.ReportManager.describeReport(reportId).getReportMetadata();
    }
	*/

}