src/objects/CBL2_Farm__c.object
<CustomObject>
    <fields>
        <fullName>CBL2_Farms_Farmer__c</fullName>
        <label>CBL2_Farms_Farmer</label>
        <referenceTo>CBL2_Farmer__c</referenceTo>
        <relationshipLabel>CBL2_Farms_Farmer</relationshipLabel>
        <relationshipName>CBL2_Farms_Farmer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farmer</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>CBL2_Farms_LFD</relationshipLabel>
        <relationshipName>CBL2_Farms_LFD</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>farmName__c</fullName>
        <label>farmName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CBL2_Farm</label>
    <nameField>
        <displayFormat>FM-{0000000}</displayFormat>
        <label>CBL2_Farm Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL2_Farms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL2_Farmer__c.object
<CustomObject>
    <description>CBL2_Farmer object replaced CBL_Coffebaseliine, CBL_Socioeconomic, CBL_attitude, CBL_service, CBL_commercialization</description>
    <fields>
        <fullName>LAC_Farmer_Details__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LAC_Farmer_Details</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>LAC_Farmer_Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CBL2_Farmer</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>CBL_CoffeeBaselineId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL2_Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBL_Attitude__c.object
<CustomObject>
    <description>Represents the farmer attitude information for a Coffee Baseline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_Attitudes</relationshipLabel>
        <relationshipName>CBL_Attitudes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CBL_Attitude</label>
    <nameField>
        <displayFormat>AT-{0000000}</displayFormat>
        <label>CBL_Attitude Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_Attitudes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_CoffeeBaseline__c.object
<CustomObject>
    <description>This object represents a Coffee Basline, t groups all the information related to a baseline</description>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>CBL_CoffeeBaselines</relationshipLabel>
        <relationshipName>CBL_CoffeeBaselines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CBL_CoffeeBaseline</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>CBL_CoffeeBaselineId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_CoffeeBaselines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_Commercialization__c.object
<CustomObject>
    <description>Holds the commercialization information for a Coffee Baseline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_Commercialization</relationshipLabel>
        <relationshipName>CBL_Commercializations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CBL2_Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CBL2_Farmer</label>
        <referenceTo>CBL2_Farmer__c</referenceTo>
        <relationshipLabel>CBL_Commercialization_CBL2_Farmer</relationshipLabel>
        <relationshipName>CBL_Commercialization_CBL2_Farmer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CBL_Commercialization</label>
    <nameField>
        <displayFormat>CM-{0000000}</displayFormat>
        <label>CBL_Commercialization Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_Commercializations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_Farm__c.object
<CustomObject>
    <description>Holds the farm information for a Coffee Baseline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_Farms</relationshipLabel>
        <relationshipName>CBL_Farms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CBL2_Farm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CBL2_Farm</label>
        <referenceTo>CBL2_Farm__c</referenceTo>
        <relationshipLabel>CBL_Farm_CBL2_Farm</relationshipLabel>
        <relationshipName>CBL_Farm_CBL2_Farm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farmer</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>CBL_Farms</relationshipLabel>
        <relationshipName>CBL_Farms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>farmName__c</fullName>
        <label>farmName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CBL_Farm</label>
    <nameField>
        <displayFormat>FM-{0000000}</displayFormat>
        <label>CBL_Farm Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_Farms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_FoodSecurity__c.object
<CustomObject>
    <description>Holds the food security information for a Coffee Baseline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_FoodSecurities</relationshipLabel>
        <relationshipName>CBL_FoodSecurities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CBL_FoodSecurity</label>
    <nameField>
        <displayFormat>FS-{0000000}</displayFormat>
        <label>CBL_FoodSecurity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_FoodSecurities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_Lot__c.object
<CustomObject>
    <description>Holds the information for a farm lot on a Coffee Baseline</description>
    <fields>
        <fullName>Farm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farm</label>
        <referenceTo>CBL_Farm__c</referenceTo>
        <relationshipLabel>CBL_Lots</relationshipLabel>
        <relationshipName>CBL_Lots</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CBL_Lot</label>
    <nameField>
        <displayFormat>LT-{0000000}</displayFormat>
        <label>CBL_Lot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBL_Seedbed__c.object
<CustomObject>
    <description>Represents the Seedbed information for a Coffee Basline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_Seedbed</relationshipLabel>
        <relationshipName>CBL_Seedbed</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CBL_Seedbed</label>
    <nameField>
        <displayFormat>SB-{0000000}</displayFormat>
        <label>CBL_Seedbed Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_Seedbed</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_Service__c.object
<CustomObject>
    <description>Holds the organization services information for a Coffee Baseline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_Services</relationshipLabel>
        <relationshipName>CBL_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CBL_Service</label>
    <nameField>
        <displayFormat>SV-{0000000}</displayFormat>
        <label>CBL_Service Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_SocioEconomic__c.object
<CustomObject>
    <description>Represents the socio economic information for a Coffee Baseline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_SocioEconomic</relationshipLabel>
        <relationshipName>CBL_SocioEconomic</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CBL_SocioEconomic</label>
    <nameField>
        <displayFormat>SE-{0000000}</displayFormat>
        <label>CBL_SocioEconomic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_SocioEconomic</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_WetMill__c.object
<CustomObject>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_WetMills</relationshipLabel>
        <relationshipName>CBL_WetMills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CBL2_Farm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CBL2_Farm</label>
        <referenceTo>CBL2_Farm__c</referenceTo>
        <relationshipLabel>CBL_WetMill_CBL2_Farm</relationshipLabel>
        <relationshipName>CBL_WetMill_CBL2_Farm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Farm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farm</label>
        <referenceTo>CBL_Farm__c</referenceTo>
        <relationshipLabel>CBL_WetMill_CBL_Farm</relationshipLabel>
        <relationshipName>CBL_WetMill_CBL_Farm</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CBL_WetMill</label>
    <nameField>
        <displayFormat>WM-{0000000}</displayFormat>
        <label>CBL_WetMill Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_WetMills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FMP_Diagnostic__c.object
<CustomObject>
    <fields>
        <fullName>PMF_Farm__c</fullName>
        <label>PMF_Farm</label>
        <referenceTo>CBL2_Farm__c</referenceTo>
        <relationshipLabel>FMP_Diagnostics_Farm</relationshipLabel>
        <relationshipName>FMP_Diagnostics_Farm</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>adequateTransportation__c</fullName>
        <formula>IF( TEXT(PMF_Farm__r.wetmill_protectsTransport__c) = &quot;Sí&quot; &amp;&amp; TEXT(PMF_Farm__r.wetmill_transportWithChemicals__c) = &quot;No&quot; , &quot;Cumple&quot;, &quot;No cumple&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>adequateTransportation</label>
        <type>Text</type>
    </fields>
    <label>FMP Diagnostic</label>
    <nameField>
        <displayFormat>FMP-{000000}</displayFormat>
        <label>FMP Diagnostic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FMP Diagnostics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FMP_Target__c.object
<CustomObject>
    <fields>
        <fullName>FMP_Diagnostic__c</fullName>
        <label>FMP Diagnostic</label>
        <referenceTo>FMP_Diagnostic__c</referenceTo>
        <relationshipLabel>FMP_Targets_Diagnostic</relationshipLabel>
        <relationshipName>FMP_Targets_Diagnostic</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>FMP Target</label>
    <nameField>
        <displayFormat>FMPT-{000000}</displayFormat>
        <label>FMP Targets Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FMP Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FMP_CBLTriggersTest.cls
@isTest
private class FMP_CBLTriggersTest {
    
    @isTest static void cblTest() {
        //create contact
        Contact contact = new Contact();
        contact.LastName = 'Perez';
        insert contact;

        //create LAC Farmer Detail
        LAC_Farmer_Details__c lacFarmer = new LAC_Farmer_Details__c();
        lacFarmer.Contact__c = contact.Id;
        insert lacFarmer;

        //create cbl
        CBL_CoffeeBaseline__c cbl = new CBL_CoffeeBaseline__c();
        cbl.Farmer__c = lacFarmer.Id;
        insert cbl;

        //create attitude
        CBL_Attitude__c attitude = new CBL_Attitude__c();
        attitude.Baseline__c = cbl.Id;
        insert attitude;

        //create commercialization
        CBL_Commercialization__c commercialization = new CBL_Commercialization__c();
        commercialization.Baseline__c = cbl.Id;
        insert commercialization;

        //create foodsecurity
        CBL_FoodSecurity__c foodSecurity = new CBL_FoodSecurity__c();
        foodSecurity.Baseline__c = cbl.Id;
        insert foodSecurity;

        //create service
        CBL_Service__c service = new CBL_Service__c();
        service.Baseline__c = cbl.Id;
        insert service;

        //create socioeconomic
        CBL_SocioEconomic__c socioEconomic = new CBL_SocioEconomic__c();
        socioEconomic.Baseline__c = cbl.Id;
        insert socioEconomic;

        //create farm
        CBL_Farm__c farm = new CBL_Farm__c();
        farm.Baseline__c = cbl.Id;
        farm.farmName__c = 'la finquita';
        farm.Farmer__c = lacFarmer.Id;
        insert farm;

        //create seedbed
        CBL_Seedbed__c seedBed = new CBL_Seedbed__c();
        seedBed.Baseline__c = cbl.Id;
        seedBed.Farm__c = farm.Id;
        insert seedBed;

        //create wetmill
        CBL_WetMill__c wetMill = new CBL_WetMill__c();
        wetMill.Baseline__c = cbl.Id;
        wetMill.Farm__c = farm.Id;
        insert wetMill;

        //create lot
        CBL_Lot__c lot = new CBL_Lot__c();
        lot.Farm__c = farm.Id;
        insert lot;

    }

        @isTest static void fmpTargetTest() {

        //create contact
        Contact contact = new Contact();
        contact.LastName = 'Perez';
        insert contact;

        //create LAC Farmer Detail
        LAC_Farmer_Details__c lacFarmer = new LAC_Farmer_Details__c();
        lacFarmer.Contact__c = contact.Id;
        insert lacFarmer;

        //create farmer
        CBL2_Farmer__c farmer = new CBL2_Farmer__c();
        farmer.LAC_Farmer_Details__c = lacFarmer.Id;
        insert farmer;

        //create farm
        CBL2_Farm__c farm = new CBL2_Farm__c();
        farm.CBL2_Farms_Farmer__c = farmer.Id;
        farm.Farmer__c = lacFarmer.Id;
        insert farm;

        //create diagnostic
        FMP_Diagnostic__c diagnostic = new FMP_Diagnostic__c();
        diagnostic.PMF_Farm__c = farm.Id;
        insert diagnostic;


        FMP_Target__c target = new FMP_Target__c();
        target.FMP_Diagnostic__c = diagnostic.Id;
        target.adequateTransportation__c = 'Sí';
        insert target;

    } 

}