src/objects/CBL_CoffeeBaseline__c.object
<CustomObject>
    <description>This object represents a Coffee Basline, t groups all the information related to a baseline</description>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>CBL_CoffeeBaselines</relationshipLabel>
        <relationshipName>CBL_CoffeeBaselines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>CBL_CoffeeBaseline</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>CBL_CoffeeBaselineId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_CoffeeBaselines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_Farm__c.object
<CustomObject>
    <description>Holds the farm information for a Coffee Baseline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_Farms</relationshipLabel>
        <relationshipName>CBL_Farms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farmer</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>CBL_Farms</relationshipLabel>
        <relationshipName>CBL_Farms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>farmName__c</fullName>
        <label>farmName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CBL_Farm</label>
    <nameField>
        <displayFormat>FM-{0000000}</displayFormat>
        <label>CBL_Farm Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_Farms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_WetMill__c.object
<CustomObject>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_WetMills</relationshipLabel>
        <relationshipName>CBL_WetMills</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Farm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farm</label>
        <referenceTo>CBL_Farm__c</referenceTo>
        <relationshipLabel>CBL_WetMill_CBL_Farm</relationshipLabel>
        <relationshipName>CBL_WetMill_CBL_Farm</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CBL_WetMill</label>
    <nameField>
        <displayFormat>WM-{0000000}</displayFormat>
        <label>CBL_WetMill Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_WetMills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Farm_Management_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Farm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farm</label>
        <referenceTo>CBL_Farm__c</referenceTo>
        <relationshipName>Farm_Management_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan de Manejo de Finca</label>
    <nameField>
        <displayFormat>FMP{0000000}</displayFormat>
        <label>Farm Management Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farm Management Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PMF_Finca_Categoria_1__c.object
<CustomObject>
    <fields>
        <fullName>Nivel_categor_a__c</fullName>
        <formula>IF( Puntaje_categor_a__c &lt; 2, &apos;c. Bajo&apos;, IF (Puntaje_categor_a__c &lt; 4, &apos;b. Medio&apos;, &apos;a. Alto&apos;))</formula>
        <label>Nivel categoría</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_de_Manejo_de_Finca__c</fullName>
        <label>Plan de Manejo de Finca</label>
        <referenceTo>Farm_Management_Plan__c</referenceTo>
        <relationshipLabel>PMF Finca Categoría 1 - Registro</relationshipLabel>
        <relationshipName>PMF_Finca_Categorias_1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PMF Finca Categoria 1 - Registro</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PMF Finca Categoria 1 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMF Finca Categorias 1</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FMPBaselineProcessHandlerTest.cls
@IsTest
public with sharing class FMPBaselineProcessHandlerTest {

	static CBL_Farm__c initialize() {
		Contact contact = new Contact();
		contact.LastName = 'test baseline process';
		insert contact;
		
		LAC_Farmer_Details__c farmer = new LAC_Farmer_Details__c();
		farmer.Contact__c = contact.Id;
		insert farmer;				
				
		CBL_CoffeeBaseline__c bl = new CBL_CoffeeBaseline__c();
		bl.Farmer__c = farmer.Id;
		insert bl;
		
		CBL_Farm__c farm = new CBL_Farm__c();
		farm.farmName__c = 'Test farm FMP process';
		farm.Baseline__c = bl.Id;
		insert farm;
		
		CBL_WetMill__c wetMill = new CBL_WetMill__c();
		wetMill.Baseline__c = bl.Id;
		
		return farm;
	}
	
	@IsTest
	static void testHandler() {
		CBL_Farm__c testFarm = initialize();
		System.debug('testFarm ' + testFarm.Id);
		FMPBaselineProcessHandler handler = new FMPBaselineProcessHandler(testFarm);
		handler.handle();
		CBL_Farm__c farm = [Select Id from CBL_Farm__c where Id = :testFarm.Id];
		Farm_Management_Plan__c fmp = [Select Id from Farm_Management_Plan__c where Farm__c = :farm.Id];
		PMF_Finca_Categoria_1__c cat1 = [Select Id, Nivel_categor_a__c from PMF_Finca_Categoria_1__c where Plan_de_Manejo_de_Finca__c = :fmp.Id];
		cat1.Nivel_categor_a__c = 'Bajo';
		System.assert(cat1.Nivel_categor_a__c == 'Bajo');
	}

}