src/objects/CBL_CoffeeBaseline__c.object
<CustomObject>
    <description>This object represents a Coffee Basline, t groups all the information related to a baseline</description>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>CBL_CoffeeBaselines</relationshipLabel>
        <relationshipName>CBL_CoffeeBaselines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Productivity__c</fullName>
        <formula>Total_Coffee_Planted_Area__c/Total_Production_Last_Year__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Productivity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Farm_Area__c</fullName>
        <label>Total Farm Area</label>
        <summarizedField>CBL_Farm__c.totalFarmArea__c</summarizedField>
        <summaryForeignKey>CBL_Farm__c.Baseline__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>CBL_CoffeeBaseline</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>CBL_CoffeeBaselineId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_CoffeeBaselines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_Commercialization__c.object
<CustomObject>
    <description>Holds the commercialization information for a Coffee Baseline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_Commercialization</relationshipLabel>
        <relationshipName>CBL_Commercializations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CBL_Commercialization</label>
    <nameField>
        <displayFormat>CM-{0000000}</displayFormat>
        <label>CBL_Commercialization Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_Commercializations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_Farm__c.object
<CustomObject>
    <description>Holds the farm information for a Coffee Baseline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_Farms</relationshipLabel>
        <relationshipName>CBL_Farms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farmer</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>CBL_Farms</relationshipLabel>
        <relationshipName>CBL_Farms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CBL_Farm</label>
    <nameField>
        <displayFormat>FM-{0000000}</displayFormat>
        <label>CBL_Farm Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_Farms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CBL_Lot__c.object
<CustomObject>
    <description>Holds the information for a farm lot on a Coffee Baseline</description>
    <fields>
        <fullName>Farm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Farm</label>
        <referenceTo>CBL_Farm__c</referenceTo>
        <relationshipLabel>CBL_Lots</relationshipLabel>
        <relationshipName>CBL_Lots</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CBL_Lot</label>
    <nameField>
        <displayFormat>LT-{0000000}</displayFormat>
        <label>CBL_Lot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CBL_SocioEconomic__c.object
<CustomObject>
    <description>Represents the socio economic information for a Coffee Baseline</description>
    <fields>
        <fullName>Baseline__c</fullName>
        <label>Baseline</label>
        <referenceTo>CBL_CoffeeBaseline__c</referenceTo>
        <relationshipLabel>CBL_SocioEconomic</relationshipLabel>
        <relationshipName>CBL_SocioEconomic</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>bankAccount__c</fullName>
        <label>bankAccount</label>
        <picklist>
            <picklistValues>
                <fullName>Si</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>debts__c</fullName>
        <label>debts</label>
        <picklist>
            <picklistValues>
                <fullName>Si</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>electricEnergy__c</fullName>
        <label>electricEnergy</label>
        <picklist>
            <picklistValues>
                <fullName>Si</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>homeOwnerShip__c</fullName>
        <label>homeOwnerShip</label>
        <picklist>
            <picklistValues>
                <fullName>Propia, totalmente pagada y escritura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Propia, parcialmente pagada y escritura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Propia sin escritura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>En arriendo, subarriendo / alquiler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>En usufructo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ocupante</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Propiedad comunal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derecho heredado o intestado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otras formas</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>householdIncomeSources__c</fullName>
        <label>householdIncomeSources</label>
        <picklist>
            <picklistValues>
                <fullName>Agricultura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trabajo agrícola (jornalero agrícola)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trabajo no agrícola temporal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trabajo no agrícola permanente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negocio propio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remesas y giros de familiares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidios del gobierno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>knowsHowToReadWrite__c</fullName>
        <label>knowsHowToReadWrite</label>
        <picklist>
            <picklistValues>
                <fullName>Si</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>otherAgriculturalActivities__c</fullName>
        <label>otherAgriculturalActivities</label>
        <picklist>
            <picklistValues>
                <fullName>Caballos, mulas, burros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toros, vacas, terneros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerdos, ovejas, cabras, alpacas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aves, conejos, cuyes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apicultura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Piscicultura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cacao</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardamomo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banano/plátano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aguacate/palta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hortalizas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frutales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granos básicos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caña de azúcar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leña, madera, subproductos del bosque</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pastos y forrajes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ninguna de las anteriores</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>percentageOfIncomeCoffee__c</fullName>
        <label>percentageOfIncomeCoffee</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>personsInHousehold__c</fullName>
        <label>personsInHousehold</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>savingsWay__c</fullName>
        <label>savingsWay</label>
        <picklist>
            <picklistValues>
                <fullName>No ahorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comprando animales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comprando terrenos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>En banco, cooperativa o asociación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grupos comunales de autoayuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otra forma</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>schoolingYears__c</fullName>
        <label>schoolingYears</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sewageDisposalSystem__c</fullName>
        <label>sewageDisposalSystem</label>
        <picklist>
            <picklistValues>
                <fullName>Red de drenaje / alcantarillado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pozo séptico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letrina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros tipos</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>waterSupply__c</fullName>
        <label>waterSupply</label>
        <picklist>
            <picklistValues>
                <fullName>Agua domiciliar potable (tratada)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agua domiciliar no potable-no tratada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abastecimiento propio de agua</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros tipos</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CBL_SocioEconomic</label>
    <nameField>
        <displayFormat>SE-{0000000}</displayFormat>
        <label>CBL_SocioEconomic Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBL_SocioEconomic</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Productivity__c</fullName>
        <formula>IF( Production_of_Coffee__c  == null || Production_of_Coffee__c  &lt;= 0, 0, (Production_of_Coffee__c  / Area_of_Coffee_Crop__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Productivity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LacFarmerProfilePageController.cls
public with sharing class LacFarmerProfilePageController {
    private LAC_Farmer_Details__c lacFarmer;
    private CBL_CoffeeBaseline__c coffeeBaseline;
    private CBL_SocioEconomic__c socioEconomic;
    private CBL_Commercialization__c cblCommercialization;
    private CBL_Farm__c[] cblFarms;
    private CBL_Farm__c signatureFarm;
    private CBL_Lot__c[] cblLots = new List<CBL_Lot__c>();
    private ApexPages.StandardController stdController;
    private boolean showSignaturePage = false;
    private String certifications = '';
    private CBL_Farm__c certificationFarm = new CBL_Farm__c();
    
    public String getPageLanguage() {
        return UserInfo.getLanguage();
    }
    public CBL_Farm__c getCertificationFarm() {
        return certificationFarm;
    }
    public LacFarmerProfilePageController(ApexPages.StandardController controller) {
       this.stdController = controller;
       this.lacFarmer = (LAC_Farmer_Details__c)controller.getRecord();
       
       CBL_CoffeeBaseline__c[] coffeeBaselines = [Select Id, Total_Farm_Area__c, Productivity__c From CBL_CoffeeBaseline__c 
            where Farmer__c=:lacFarmer.id];
        if (coffeeBaselines.size() > 0) {
            coffeeBaseline = coffeeBaselines[0];
        }
    }
    public boolean getShowSignaturePage() {
        return showSignaturePage;
    }
    public CBL_CoffeeBaseline__c getCoffeeBaseline() {
        return coffeeBaseline;
    }
    public CBL_SocioEconomic__c getSocioEconomic() {
        if (coffeeBaseline != null) {
            CBL_SocioEconomic__c[] socioEconomic = [Select Id,
                                                            personsInHousehold__c,
                                                            homeOwnerShip__c,
                                                            waterSupply__c,
                                                            sewageDisposalSystem__c,
                                                            electricEnergy__c,
                                                            knowsHowToReadWrite__c,
                                                            schoolingYears__c,
                                                            householdIncomeSources__c,
                                                            percentageOfIncomeCoffee__c,
                                                            otherAgriculturalActivities__c,
                                                            savingsWay__c,
                                                            bankAccount__c,
                                                            debts__c,
                                                            debtsFinancingSource__c,
                                                            creditDestination__c,
                                                            populationGroup__c,
                                                            socialSecutiryProgram__c
                                                     from CBL_SocioEconomic__c
                                                     where Baseline__c=:coffeeBaseline.id];
            return socioEconomic[0];
        }
        return null;
    }
    public CBL_Commercialization__c getCblCommercialization() {
        if (coffeeBaseline != null) {
            CBL_Commercialization__c[] cblCommercializations = [Select Id,
                                                                        producedCoffeeDestiny__c,
                                                                        lastHarvestPercCoffeeSoldToCoop__c,
                                                                        statusSoldCoffee__c,
                                                                        buysCoffee__c
                                                               From CBL_Commercialization__c
                                                               Where Baseline__c=:coffeeBaseline.id];
           cblCommercialization = cblCommercializations[0];
           return cblCommercialization;
       }
       return null;
    }

    public List<CBL_Farm__c> getCblFarms() {
        if (null != coffeeBaseline) {
            CBL_Farm__c[] cblFarmz = [Select Id, farmName__c, signature__c, coffeProcessingPlace__c, farmCertifications__c from CBL_Farm__c
                                        where Baseline__c=:coffeeBaseline.id];
            if (cblFarmz.size() > 0) {
                signatureFarm = cblFarmz[0];
                cblFarms = cblFarmz;
                List<String> farmIds = new List<String>();
                Map<String, String> certs = new Map<String, String>();
                
                for (CBL_Farm__c cblFarm : cblFarms) {
                    farmIds.add(cblFarm.Id);
                    String[] cblCerts = cblFarm.farmCertifications__c.split(';');
                    if (cblCerts.size() > 0) {
                        for (String cblCert : cblCerts) {
                            certs.put(cblCert, cblCert);
                        }
                    }
                }
                for (String key : certs.keySet()) {
                    certifications = certifications + ';' + key;
                }
                certifications =certifications.substring(1);
                certificationFarm.farmCertifications__c = certifications;
                CBL_Lot__c [] cblLotz = [Select Id, lotCoffeeVariety__c from CBL_Lot__c where Farm__c in:farmIds];
                cblLots = cblLotz;
                return cblFarms;
            }
        }
        return null;
    }

    public CBL_Farm__c getSignatureFarm() {
        if (coffeeBaseline != null) {
            CBL_Farm__c signatureFarm = [Select Id, farmName__c, signature__c, 
                                            coffeProcessingPlace__c, farmCertifications__c,
                                            Production_last_year_Kg__c
                                         from CBL_Farm__c
                                        where Baseline__c=:coffeeBaseline.id];
                                        
            if (signatureFarm != null) {
                showSignaturePage = true;
            }
                                        
            return signatureFarm;
        }
        return null;
    }

    public List<CBL_Lot__c> getCblLots() {
        if (cblLots.size() > 0) {
            return cblLots;
        }
        else {
            getCblFarms();
            return cblLots;
        }
    }
    
}