src/objects/CIW__c.object
<CustomObject>
    <description>Biovision Africa Trust Community Information Worker</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>The Person or Contact object</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CIWs</relationshipLabel>
        <relationshipName>CIWs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CIW</label>
    <nameField>
        <displayFormat>CIW-{00000}</displayFormat>
        <label>CIW Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Village__c</fullName>
        <description>Village that the person lives in</description>
        <label>Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CiwSelectorController.cls
/**
 *  Controller for the component that controls the district selector.
 *  Should be the child on a DashboardSelectorComponent.
 */
public with sharing class CiwSelectorController extends ChildComponentBase {

    public CiwSelectorController() {
        if (getShowData()) {
            setCiws(loadCiws());
        }
    }

    // Override method to return the controllers chosen value.
    public override String getValues() {

        if (this.ciw== null) {
            return '';
        }
        return getCiw();
    }

    public override PageReference refreshData() {

        if (getShowData()) {
            setCiws(loadCiws());
        }
        return null;
    }

    // Might need to update this to allow for more than one of these components on the page
    // Add a setter so the name can be changed on the fly from the parent comppnent??
    public String getActionFunctionName() {
        return 'ciwComponentController';
    }

    // Get the available CIWs.
    public String ciw;
    public String getCiw() {
        return this.ciw;
    }
    public void setCiw(String ciw) {
        addParameterToParent(ciw);
        this.ciw = ciw;
    }
    public List<SelectOption> ciws;
    public List<SelectOption> getCiws() {
        return this.ciws;
    }
    public void setCiws(List<SelectOption> options) {
        this.ciws= options;
    }
    private List<SelectOption> loadCiws() {

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '--- Select a CIW---'));
        CIW__c[] ciws = database.query(buildCiwQueryString());
        for (CIW__c ciw: ciws) {
            options.add(new SelectOption(ciw.Id, ciw.Person__r.First_Name__c + ' ' + ciw.Person__r.Last_Name__c));
        }
        return options;
    }

    private String buildCiwQueryString() {
        
        String query = 'SELECT ' +
                'Name, ' +
                'Person__r.First_Name__c, ' +   
                'Person__r.Last_Name__c ' +             
            'FROM ' +
                'CIW__c ' +            
            'ORDER BY ' +
                'Person__r.First_Name__c, Person__r.Last_Name__c';
        System.debug(LoggingLevel.INFO, query);
        return query;
    }

    private String getWhereClause() {

        String value = getParentValue('Village__c');
        if (!value.equals('')) {
            return ' Village__c = \'' + value + '\' AND ';
        }
        return '';
    }

    public static String testController() {

        CiwSelectorController controller = new CiwSelectorController();
        controller.setCiws(controller.loadCiws());
        controller.getCiws();
        controller.getActionFunctionName();
        controller.getValues();
        controller.setCiw('Hi');
        return controller.getCiw();        
    }
}