src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Market_Link_Farmer__c.object
<CustomObject>
    <description>These are created from Market Link application. They are optionally linked to existing farmer in case the farmer exists and to market link transactions</description>
    <fields>
        <fullName>Farmer_Name__c</fullName>
        <description>Farmer&apos;s Name</description>
        <label>Farmer Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Farmer associated with this Market Farmer</description>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipName>MarketLink_Farmers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market Link Farmer</label>
    <nameField>
        <label>MarketLink Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Link Farmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market_Link_Transaction__c.object
<CustomObject>
    <description>Market Link Transaction</description>
    <fields>
        <fullName>Buyer_Name__c</fullName>
        <description>Buyer Name</description>
        <label>Buyer Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CKW__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CKW</label>
        <referenceTo>CKW__c</referenceTo>
        <relationshipLabel>Market Link Transactions</relationshipLabel>
        <relationshipName>Market_Link_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Crop__c</fullName>
        <description>Crop being bought or sold</description>
        <label>Crop</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District_Name__c</fullName>
        <label>District Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Name__c</fullName>
        <description>Buyer or market name</description>
        <label>Market Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Income__c</fullName>
        <label>Total Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <label>Total Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Transaction_Fee__c</fullName>
        <label>Total Transaction Fee</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Transport_Cost__c</fullName>
        <label>Total Transport Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>Date on which the transaction was done</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Type of transaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>marketSale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>buyerSale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>buy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Market Link Transaction</label>
    <nameField>
        <label>Market Link Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Link Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Marketlink_Farmer_Association__c.object
<CustomObject>
    <fields>
        <fullName>Market_Link_Farmer__c</fullName>
        <label>Market Link Farmer</label>
        <referenceTo>Market_Link_Farmer__c</referenceTo>
        <relationshipLabel>Marketlink Farmer Associations</relationshipLabel>
        <relationshipName>Marketlink_Farmer_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Link_Transaction__c</fullName>
        <label>Market Link Transaction</label>
        <referenceTo>Market_Link_Transaction__c</referenceTo>
        <relationshipLabel>Marketlink Farmer Associations</relationshipLabel>
        <relationshipName>Marketlink_Farmer_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Marketlink Farmer Association</label>
    <nameField>
        <label>Marketlink Farmer Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketlink Farmer Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District_Name__c</fullName>
        <formula>District__r.Name</formula>
        <label>District Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physical handset assigned to this Person (in the case of GF-managed assets)</description>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Assignee</relationshipLabel>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreateMarketLinkTransaction.cls
global class CreateMarketLinkTransaction {	
	
	/**
	* Creates MarketLink_Transaction, MarketLink_Farmers and MarketLink_Farmer_Assciations
	*
	* @ MarketLinkTransaction - transaction receipt details
	* @ List<FarmerTransaction> - farmer transaction details
	* 
	* return A tuple list of Strings with the following format
    *              element 1 - Binary indicator of success (0 = fail, 1 = success)
    *              element 2 - Error message if required (should be printed to backend)
    *              element 3 - Message to be sent to the submitter
	*/
    webservice static List<String> createTransaction(MarketLinkTransaction marketLinkTransactionAdapter, List<FarmerTransaction> farmerTransactionAdapters) {
   	
    	List<String> result = new List<String>();
    	
    	// Set save point to enable rollback
    	Savepoint sPoint = Database.setSavepoint();
    	try {
    		CKW__c ckw = getTransactionCKW(marketLinkTransactionAdapter.imei);
        	Market_Link_Transaction__c marketLinkTransaction = saveMarketLinkTransactionDetails(marketLinkTransactionAdapter, ckw);
        
       		for (FarmerTransaction farmerTransactionAdapter : farmerTransactionAdapters) {
        		saveAndAssociateFarmerTransaction(farmerTransactionAdapter, marketLinkTransaction);
       		}
       		result.add('0');
       		result.add('');
       		result.add('Transaction has been successfully saved');
    	}
    	catch (Exception ex) {
    		System.debug(ex);
    	    
    	    // Rollback changes
    	    Database.rollback(sPoint);    	    
    		result.add('1');
       		result.add(ex.getMessage());
       		result.add('Transaction has not successfully saved');
    	}
    	return result;
    }
    
    private static CKW__c getTransactionCKW(String imei) {
    	CKW__c ckw = [
    		SELECT
    			Id
    		FROM
    			CKW__c
    		WHERE
    			Person__r.Handset__r.IMEI__c = :imei
    		LIMIT 1
    		];
    	return ckw;
    }
    
    private static Market_Link_Transaction__c saveMarketLinkTransactionDetails(MarketLinkTransaction adapter, CKW__c ckw) {
    	Market_Link_Transaction__c marketLinkTransaction = new Market_Link_Transaction__c();
    	marketLinkTransaction.District_Name__c = adapter.district;
    	marketLinkTransaction.Crop__c = adapter.crop;
    	marketLinkTransaction.Transaction_Date__c = DateTime.valueOf(adapter.transactionDate);
    	marketLinkTransaction.Type__c = adapter.transactionType;
    	
    	if (marketLinkTransaction.Type__c.trim().equals('marketSale')) {
    		marketLinkTransaction.Market_Name__c = adapter.name;
    	}
    	else {
    		marketLinkTransaction.Buyer_Name__c = adapter.name;
    	}
    	marketLinkTransaction.Total_Quantity__c = adapter.totalQuantity;
    	marketLinkTransaction.Total_Transaction_Fee__c = adapter.totalTransactionFee;
    	marketLinkTransaction.Total_Transport_Cost__c = adapter.totalTransportCost;
    	marketLinkTransaction.Total_Income__c = adapter.totalIncome;
    	marketLinkTransaction.Unit_Price__c = adapter.unitPrice;
    	marketLinkTransaction.CKW__c = ckw.Id;
    	database.insert(marketLinkTransaction);
    	return marketLinkTransaction;
    }
    
    private static void saveAndAssociateFarmerTransaction(FarmerTransaction adapter, Market_Link_Transaction__c marketLinkTransaction) {
    	Market_Link_Farmer__c marketLinkFarmer = new Market_Link_Farmer__c();
    	marketLinkFarmer.Farmer_Name__c = adapter.name;
    	
    	if (adapter.farmerId != null && !adapter.farmerId.equals('')) {
    		Farmer__c farmer = [
    			SELECT
    				Id
    			FROM
    				Farmer__c
    			WHERE
    				Name = :adapter.farmerId
    			LIMIT 1
    		];
    		marketLinkFarmer.Farmer__c = farmer.Id;
    	}
    	database.insert(marketLinkFarmer);
    	
    	// create and save MarketLink Farmer Association
    	MarketLink_Farmer_Association__c association = new MarketLink_Farmer_Association__c();
    	association.Income__c = adapter.income;
    	association.Quantity__c = adapter.quantity;
    	association.Transaction_Fee__c = adapter.transactionFee;
    	association.Transport_Cost__c = adapter.transportCost;
    	association.Market_Link_Transaction__c = marketLinkTransaction.Id;
    	association.Market_Link_Farmer__c = marketLinkFarmer.Id;
    	database.insert(association);   	
    }
    
    global class MarketLinkTransaction {    
        webservice String crop;
        webservice String district;
        webservice String transactionDate;
        webservice String transactionType;
        webservice double unitPrice;
        webservice double totalQuantity;
        webservice double totalTransactionFee;
        webservice double totalTransportCost;
        webservice double totalIncome;
        webservice String name;
        webservice String imei; 
    }
    
    global class FarmerTransaction {
    	webservice String name;
    	webservice String farmerId;
    	webservice double quantity;
    	webservice double transactionFee;
    	webservice double transportCost;
    	webservice double income;
    }
    
    static testMethod void testEachMethod() {
    	    	
    	String imei = '23426756';
    	database.insert(Utils.createTestCkw(null, imei, true, null, null));    	    	
    	CKW__c ckw = getTransactionCKW(imei);
    	System.assert(ckw != null);
    	
    	// build MarketLinkTransaction adapter
    	MarketLinkTransaction madapter = new MarketLinkTransaction();
    	madapter.crop = 'beans';
    	madapter.district = 'Kampala';
    	madapter.transactionDate = '2012-02-02 00:00:00';
    	madapter.transactionType = 'marketSale';
    	madapter.totalQuantity = 50;
    	madapter.totalTransactionFee = 1000;
    	madapter.totalTransportCost = 3000;
    	madapter.totalIncome = 200000;
    	madapter.unitPrice = 200;
    	madapter.name = 'Mbarara Market';
    	madapter.imei = imei;
    	
    	Market_Link_Transaction__c marketLinkTransaction = saveMarketLinkTransactionDetails(madapter, ckw);
    	System.debug('transaction Id ' + MarketLinkTransaction.Id);
    	System.assert(marketLinkTransaction.Id != null);
    	
    	// build FarmerTrasactionAdapter
    	FarmerTransaction fadapter = new FarmerTransaction();
    	fadapter.farmerId = '';
    	fadapter.income = 1000;
    	fadapter.name = 'james oo test';
    	fadapter.transactionFee = 100;
    	fadapter.transportCost = 100;
    	fadapter.quantity = 10;
    	
    	saveAndAssociateFarmerTransaction(fadapter, marketLinkTransaction);    	
    }
    
    static testmethod void testCreateTransaction() {
    	
    	String imei = '23426756';
    	database.insert(Utils.createTestCkw(null, imei, true, null, null));    	    	
    	CKW__c ckw = getTransactionCKW(imei);
    	System.assert(ckw != null);
    	
    	// build MarketLinkTransaction adapter
    	MarketLinkTransaction madapter = new MarketLinkTransaction();
    	madapter.crop = 'beans';
    	madapter.district = 'Kampala';
    	madapter.transactionDate = '2012-02-02 00:00:00';
    	madapter.transactionType = 'marketSale';
    	madapter.totalQuantity = 50;
    	madapter.totalTransactionFee = 1000;
    	madapter.totalTransportCost = 3000;
    	madapter.totalIncome = 200000;
    	madapter.unitPrice = 200;
    	madapter.name = 'Mbarara Market';
    	madapter.imei = imei;
    	
    	// build FarmerTrasactionAdapters
    	FarmerTransaction fadapter = new FarmerTransaction();
    	fadapter.farmerId = '';
    	fadapter.income = 1000;
    	fadapter.name = 'james oo test';
    	fadapter.transactionFee = 100;
    	fadapter.transportCost = 100;
    	fadapter.quantity = 10;
    	
    	// build FarmerTrasactionAdapter
    	FarmerTransaction fadapter1 = new FarmerTransaction();
    	fadapter1.farmerId = '';
    	fadapter1.income = 1000;
    	fadapter1.name = 'oo test';
    	fadapter1.transactionFee = 100;
    	fadapter1.transportCost = 100;
    	fadapter1.quantity = 10;
    	
    	List<FarmerTransaction> farmerTransactions = new List<FarmerTransaction>();
    	farmerTransactions.add(fadapter);
    	farmerTransactions.add(fadapter1);
    	
    	List<String> transactionResult = createTransaction(madapter, farmerTransactions);
    	System.assertEquals(transactionResult.get(0), '0');
    }
}