src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LacMapMarkersTest.cls
@isTest
public with sharing class LacMapMarkersTest {
	
	public static testMethod void testMapMarkers() {
		 LacMapMarkerSources.Farmers farmers = new LacMapMarkerSources.Farmers();
		farmers.loadMapMarkers(new Map<String, String>());
		
		LacMapMarkerSources.CKWs ckws = new LacMapMarkerSources.CKWs();
		ckws.loadMapMarkers(new Map<String, String>());
		
		LacMapMarkerSources.AllPeople allPeople = new LacMapMarkerSources.AllPeople();
		allPeople.loadMapMarkers(new Map<String, String>());
		
		Contact contact = new Contact();
		contact.FirstName = 'Luke';
		contact.LastName = 'Kyohere';
		insert contact;
		
		Person__c person = new Person__c();
		person.Contact__c = contact.Id;
		person.First_Name__c = contact.FirstName;
		person.Last_Name__c = contact.LastName;
		insert person;
		
		LAC_Farmer_Details__c farmer = new LAC_Farmer_Details__c();
		
		farmer.Person__c = person.Id;
		farmer.Contact__c = contact.Id;
		insert farmer;
		
		new LacMapMarkers.LacFarmerMarker(farmer);
		
		Contact contact2 = new Contact();
		contact2.FirstName = 'Luke2';
		contact2.LastName = 'Kyohere2';
		insert contact2;
		
		Person__c person2 = new Person__c();
		person2.Contact__c = contact2.Id;
		person2.First_Name__c = contact2.FirstName;
		person2.Last_Name__c = contact2.LastName;
		insert person2;
		
		CKW__c ckw = new CKW__c();
		ckw.Person__c = person2.Id;
		insert ckw;
		
		new LacMapMarkers.LacCkwMarker(ckw);
	}
}