src/objects/CKW_Cluster_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>Any_Banana_GAPS_discussed__c</fullName>
        <label>Any Banana GAPS discussed</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CKW_Full_Name__c</fullName>
        <label>CKW Full Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FO__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>FO</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 CKW Cluster Meetings</relationshipLabel>
        <relationshipName>X3_0_CKW_Cluster_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_information_discussed__c</fullName>
        <label>Market information discussed</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Meeting_date__c</fullName>
        <label>Meeting date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Weather_information_discussed__c</fullName>
        <label>Weather information discussed</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>3.0 CKW Cluster Meeting</label>
    <nameField>
        <displayFormat>CCM{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>CKW Cluster Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 CKW Cluster Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FO__c.object
<CustomObject>
    <label>3.0 FO</label>
    <nameField>
        <displayFormat>FO-{YYYY}{MM}-{0}</displayFormat>
        <label>FO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 FOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Monthly_CKW_Visit__c.object
<CustomObject>
    <description>This object represents a unique interaction between an FO and a CKW per month. Each CKW is meant to meet their FO once every month.</description>
    <fields>
        <fullName>FO__c</fullName>
        <label>FO Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 Monthly CKW Visits</relationshipLabel>
        <relationshipName>Monthly_CKW_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>3.0 Monthly CKW Visit</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>3.0 Monthly CKW Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Monthly CKW Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCreateMonthlyCkwVisit.cls
@isTest
public class TestCreateMonthlyCkwVisit {

    @isTest static void testCreateVisit() {
        Contact focontact = new Contact(FirstName = 'Brown', LastName = 'Amooti');
        insert focontact;
        Contact ckwcontact = new Contact(FirstName = 'White', LastName = 'Araali');
        insert ckwcontact;
        
        CKW_Cluster_Meeting__c meeting = new CKW_Cluster_Meeting__c();
        meeting.FO__c = focontact.id;
        meeting.CKW_Full_Name__c= 'White Araali';
        meeting.Meeting_date__c = date.today().addDays(-1);
        meeting.Any_Banana_GAPS_discussed__c = 'No';
        meeting.Any_Banana_GAPS_discussed__c = 'No';
        meeting.Any_Banana_GAPS_discussed__c = 'No';
        meeting.Market_information_discussed__c = 'Yes';
        meeting.Weather_information_discussed__c = 'Yes';
        insert meeting;
        
        test.startTest();
        Date thisDate = date.today().addDays(1);
        CreateMonthlyCkwVisit.createVisit(thisDate);
        List<Monthly_CKW_Visit__c> visits = [Select Id from Monthly_CKW_Visit__c];
        System.assertEquals(1, visits.size());
        test.stopTest();
    }
}