src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Registered_By__c</fullName>
        <label>Registered By</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers Registered</relationshipLabel>
        <relationshipName>Farmers_Registered</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>M&amp;E Metrics</relationshipLabel>
        <relationshipName>M_E_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Divide__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this to allow this metric to be divided in to smaller sub metrics</description>
        <label>Sub Divide</label>
        <type>Checkbox</type>
    </fields>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Actual_Value__c</fullName>
        <description>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</description>
        <inlineHelpText>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</inlineHelpText>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>The district that this metric is for. Allows us to split the metrics by district when showing them on the dashboard</description>
        <inlineHelpText>Select the district that this metric is for</inlineHelpText>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Cumulative__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this is a cumulative metric</description>
        <label>Is Cumulative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>The person that this metric data belongs to</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Current_Poverty_Scorecard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The most recent poverty scorecard for this person</description>
        <label>Current Poverty Scorecard</label>
        <referenceTo>Poverty_Scorecard__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person_Organisation_Association__c.object
<CustomObject>
    <description>Links a person to an organisation/partner/farmer group/account/whatever the hell we are calling them</description>
    <fields>
        <fullName>Organisation__c</fullName>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Person Organisation Associations</relationshipLabel>
        <relationshipName>Person_Organisation_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Person Organisation Associations</relationshipLabel>
        <relationshipName>Person_Organisation_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person Organisation Association</label>
    <nameField>
        <displayFormat>POA-{0000000}</displayFormat>
        <label>Person Organisation Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Organisation Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Poverty_Scorecard__c.object
<CustomObject>
    <description>Poverty scorecard data for a person in our system</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Person with whom this poverty data is associated</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Poverty Scorecards</relationshipLabel>
        <relationshipName>Poverty_Scorecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Poverty_Percentage__c</fullName>
        <description>Calculate the poverty percentage based on the score</description>
        <formula>CASE( Score__c ,
    0, 97.20,
    1, 97.20,
    2, 97.20,
    3, 97.20,
    4, 97.20,
    5, 95.20,
    6, 95.20,
    7, 95.20,
    8, 95.20,
    9, 95.20,
    10, 93.60,
    11, 93.60,
    12, 93.60,
    13, 93.60,
    14, 93.60,
    15, 80.60,
    16, 80.60,
    17, 80.60,
    18, 80.60,
    19, 80.60,
    20, 76.10,
    21, 76.10,
    22, 76.10,
    23, 76.10,
    24, 76.10,
    25, 71.20,
    26, 71.20,
    27, 71.20,
    28, 71.20,
    29, 71.20,
    30, 62.50,
    31, 62.50,
    32, 62.50,
    33, 62.50,
    34, 62.50,
    35, 47.70,
    36, 47.70,
    37, 47.70,
    38, 47.70,
    39, 47.70,
    40, 44.00,
    41, 44.00,
    42, 44.00,
    43, 44.00,
    44, 44.00,
    45, 38.70,
    46, 38.70,
    47, 38.70,
    48, 38.70,
    49, 38.70,
    50, 27.00,
    51, 27.00,
    52, 27.00,
    53, 27.00,
    54, 27.00,
    55, 26.20,
    56, 26.20,
    57, 26.20,
    58, 26.20,
    59, 26.20,
    60, 13.30,
    61, 13.30,
    62, 13.30,
    63, 13.30,
    64, 13.30,
    65, 8.10,
    66, 8.10,
    67, 8.10,
    68, 8.10,
    69, 8.10,
    70, 6.50,
    71, 6.50,
    72, 6.50,
    73, 6.50,
    74, 6.50,
    75, 3.10,
    76, 3.10,
    77, 3.10,
    78, 3.10,
    79, 3.10,
    80, 2.70,
    81, 2.70,
    82, 2.70,
    83, 2.70,
    84, 2.70,
    85, 1.30,
    86, 1.30,
    87, 1.30,
    88, 1.30,
    89, 1.30,
    90, 0.70,
    91, 0.70,
    92, 0.70,
    93, 0.70,
    94, 0.70,
    0.00)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Poverty Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Poverty Scorecard</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Poverty Scorecard ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Poverty Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Submission_Answer__c.object
<CustomObject>
    <description>Object to hold one answer to a survey</description>
    <fields>
        <fullName>Submission_Meta_Data__c</fullName>
        <description>The submission data that this answer is related to</description>
        <label>Submission Meta Data</label>
        <referenceTo>Submission_Meta_Data__c</referenceTo>
        <relationshipLabel>Submission Answers</relationshipLabel>
        <relationshipName>Submission_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Answer</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Submission Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Submission_Meta_Data__c.object
<CustomObject>
    <description>Contains the data that every submission requires. Every submission will have one of these irrelevant of the submission object that corresponds to the submission</description>
    <fields>
        <fullName>Interviewer__c</fullName>
        <description>The person who conducted the survey</description>
        <label>Interviewer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>Submission_Meta_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Poverty_Scorecard__c</fullName>
        <description>The poverty scorecard of the interviewee at the time of the submission</description>
        <label>Poverty Scorecard</label>
        <referenceTo>Poverty_Scorecard__c</referenceTo>
        <relationshipName>Submission_Meta_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The survey that this submission is for</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipName>Submission_Meta_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SMD-{0000000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <description>Surveys run by CKWs. There is one entry here for each type of survey. Survey questions (and responses) are NOT stored here.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that ordered to run the survey</description>
        <inlineHelpText>Select the customer who ordered to run the survey</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PartnerMetrics.cls
global class PartnerMetrics implements Database.Batchable<sObject>, Database.Stateful {

    // The query that gets the people who will be included in the metrics
    global final String partnerQuery;

    // The name of the parter who this run of the batch is for
    global final Account partner;

    // A map of the metric data objects that are to be updated in this batch
    global final Map<String, M_E_Metric_Data__c> currentQuarterMetricDatas;

    // A list of the metrics that the partner has
    global final List<M_E_Metric__c> partnerMetrics;

    // A map of all the metrics that we are to calculate for this partner
    global final Map<String, MetricDataCalculationParameters> metricCalculationParameters;
    global final Map<String, MetricDataCalculationTracker> metricCalculationTracker;

    // The global date values that define the period we are looking at
    global final Date ckwQuarterStartDate;
    global final Date ckwQuarterEndDate;
    global final Date ckwPreviousQuarterStartDate;
    global final Date ckwPreviousQuarterEndDate;
    global final String ckwQuarterString;

    // Some totals that need to be kept track of
    // Search hit totals
    global final Map<String, Integer> searchTotals;

    // Total interactions
    global final Map<String, Integer> totalInteractions;

    // The total submissions for each survey for this partner. Note the key here should be Survey__c.Name
    global final Map<String, Integer> surveyTotals;
    global final Map<String, Survey__c> surveyMap;
    global final List<String> partnerSurveyNames;
    global final Map<String, District__c> districts;

    // The number of CKWs that this partner has active. Should only pass active People to this class.
    global final Map<String, MetricDataCalculationGeneralTracker> generalMetrics;

    global PartnerMetrics (
            String query,
            Account account,
            Map<String, MetricDataCalculationParameters> parameters,
            Map<String, Survey__c> surveyNames
    ) {

        partnerQuery = query;
        partner = account;
        metricCalculationParameters = parameters;
        partnerSurveyNames = new List<String>();
        for (String key : surveyNames.keySet()) {
            partnerSurveyNames.add(surveyNames.get(key).Name);
        }
        surveyMap = surveyNames;
        districts = new Map<String, District__c>();
        searchTotals = new Map<String, Integer>();
        surveyTotals = new Map<String, Integer>();
        totalInteractions = new Map<String, Integer>();

        // We look at the date yesterday as this is run as a scheduled job so we want to look at the previous quarter if we are on the first day of a new quarter
        ckwQuarterString = MetricHelpers.getCurrentQuarterAsString(-1);
        ckwQuarterStartDate = MetricHelpers.getQuarterFirstDay(ckwQuarterString);
        ckwQuarterEndDate = MetricHelpers.getQuarterLastDay(ckwQuarterString);
        ckwPreviousQuarterStartDate = ckwQuarterStartDate.addMonths(-3);
        ckwPreviousQuarterEndDate = ckwQuarterEndDate.addMonths(-3);

        // Get the metrics for the partner
        partnerMetrics = MetricHelpers.getMetrics(null, partner.Name);
        if (partnerMetrics == null) {

            // TODO - Make this throw an exception
            // No metrics assigned to this partner. Don't continue as they have no reason to be here
            return;
        }

        // Initialise the general metric tracker map
        generalMetrics = new Map<String, MetricDataCalculationGeneralTracker>();

        // Get all the metric datas for this quarter and create a map to store them in. Also create the temporary calculation storage
        currentQuarterMetricDatas = new Map<String, M_E_Metric_Data__c>();
        metricCalculationTracker = new Map<String, MetricDataCalculationTracker>();
        for (M_E_Metric_Data__c metricData : MetricHelpers.getMetricDatas(null, ckwQuarterStartDate, ckwQuarterEndDate, partner.Name)) {
            String districtString = null;
            if (metricData.District__r.Name != null) {
                districtString = metricData.District__r.Name;
            }
            String metricDataName = MetricHelpers.createMetricLabelString(metricData.M_E_Metric__r.Name, districtString);
            if (metricData.Is_Cumulative__c != null && metricData.Is_Cumulative__c) {
                metricDataName = metricDataName + '_cumulative';
            }
            currentQuarterMetricDatas.put(metricDataName, metricData);

            // Check the district id so we can create a list of the districts and the create the metric tracker objects
            if (metricData.District__r.Name != null && !districts.containsKey(metricData.District__r.Name)) {
                if (MetricHelpers.checkForOranistationDistrictLink(partner, metricData.District__c, true)) {

                    // Load the District
                    District__c district = database.query(SoqlHelpers.getDistrict(metricData.District__r.Name));
                    districts.put((String)district.Name, district);
                    generalMetrics.put(district.Name, new MetricDataCalculationGeneralTracker());

                    // Make sure that we have the MetricDataCalculationTracker objects created for this district.
                    for (M_E_Metric__c metric : partnerMetrics) {

                        // Only create if this metric is split by something
                        if (metric.Sub_Divide__c)  {
                            String metricTrackerName = MetricHelpers.createMetricLabelString(metric.Name, district.Name);
                            if (!metricCalculationTracker.containsKey(metricTrackerName) && metricCalculationParameters.containsKey(metric.Name)) {
                                metricCalculationTracker.put(metricTrackerName, new MetricDataCalculationTracker(metric.Name, metricCalculationParameters.get(metric.Name).getFunction(), district, metricCalculationParameters.get(metric.Name).getSurvey()));
                            }
                        }

                        // Check that the general metric is there as well
                        if (!metricCalculationTracker.containsKey(metric.Name) && metricCalculationParameters.containsKey(metric.Name)) {
                            metricCalculationTracker.put(metric.Name, new MetricDataCalculationTracker(metric.Name, metricCalculationParameters.get(metric.Name).getFunction(), null, metricCalculationParameters.get(metric.Name).getSurvey()));
                        }
                    }
                }
            }
        }

    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(partnerQuery);
    }

    global void execute(Database.BatchableContext BC, List<Person__c> people) {

        // Generate a list of Id for each Person in this batch. Also take the general counters for the CKWs
        List<String> personIds = new List<String>();
        for (Person__c person : people) {

            // The person is invalid if they have no district so we don't count them
            if (person.District__r.Name == null) {
                continue;
            }
            personIds.add((String)person.Id);

            // Check the district id so we can create a list of the districts and the create the metric tracker objects
            if (!districts.containsKey(person.District__r.Name)) {
                if (person.District__c != null && MetricHelpers.checkForOranistationDistrictLink(partner, person.District__c, true)) {

                    // Load the District
                    District__c district = database.query(SoqlHelpers.getDistrict(person.District__r.Name));
                    districts.put((String)district.Name, district);
                    generalMetrics.put(person.District__r.Name, new MetricDataCalculationGeneralTracker());

                    // Make sure that we have the MetricDataCalculationTracker objects created for this district.
                    for (M_E_Metric__c metric : partnerMetrics) {

                        // Only create if this metric is split by something
                        if (metric.Sub_Divide__c)  {
                            String metricDataName = MetricHelpers.createMetricLabelString(metric.Name, person.District__r.Name);
                            if (!metricCalculationTracker.containsKey(metricDataName) && metricCalculationParameters.containsKey(metric.Name)) {
                                metricCalculationTracker.put(metricDataName, new MetricDataCalculationTracker(metric.Name, metricCalculationParameters.get(metric.Name).getFunction(), district, metricCalculationParameters.get(metric.Name).getSurvey()));
                            }
                        }

                        // Check that the general metric is there as well
                        if (!metricCalculationTracker.containsKey(metric.Name) && metricCalculationParameters.containsKey(metric.Name)) {
                            metricCalculationTracker.put(metric.Name, new MetricDataCalculationTracker(metric.Name, metricCalculationParameters.get(metric.Name).getFunction(), null, metricCalculationParameters.get(metric.Name).getSurvey()));
                        }
                    }
                }
            }

            MetricDataCalculationGeneralTracker generalMetric = generalMetrics.get(person.District__r.Name);
            if (generalMetric == null) {
                continue;
            }
            generalMetric.setTotalActivePeople(1.0);
            if (person.Current_Poverty_Scorecard__r.Poverty_Percentage__c != null) {
                generalMetric.setSumPovertyScore(person.Current_Poverty_Scorecard__r.Poverty_Percentage__c);
            }
            if (person.Gender__c != null && person.Gender__c.equalsIgnoreCase('Female')) {
                generalMetric.setTotalFemalePeople(1.0);
            }
            generalMetrics.put(person.District__r.Name, generalMetric);
        }

        if (personIds.isEmpty()) {
            return;
        }

        // Calculate the number of surveys that have been done by these people.
        Map<String, String> variables = new Map<String, String>();
        variables.put('ckws', MetricHelpers.generateCommaSeperatedString(personIds, true));
        variables.put('submissionStartDate', MetricHelpers.convertDateTimeToString(MetricHelpers.convertToStartDate(this.ckwQuarterStartDate), false));
        variables.put('submissionEndDate', MetricHelpers.convertDateTimeToString(MetricHelpers.convertToEndDate(this.ckwQuarterEndDate), false));
        variables.put('surveyName', MetricHelpers.generateCommaSeperatedString(this.partnerSurveyNames, true));
        variables.put('dataCollectionStatusNot', 'Rejected');
        variables.put('customerCareStatusNot', 'Rejected');
        SoqlHelpers.countSurveyTotals(variables, this.surveyTotals, 'Interviewer__r.District__r.Name', surveyMap);
        variables.remove('surveyName');

        // Calculate the number of searches for these people
        variables.put('searchStartDate', this.ckwQuarterStartDate.format());
        variables.put('searchEndDate', this.ckwQuarterEndDate.format());
        SoqlHelpers.getSearchTotals(variables, this.searchTotals, 'Interviewer__r.District__r.Name');

        // Loop through the metrics that we are looking to calculate and get the data for these people
        for (MetricDataCalculationParameters metricDataCalculationParameters : this.metricCalculationParameters.values()) {
            variables.put('surveyName', '\'' + metricDataCalculationParameters.getSurvey().Name + '\'');
            variables.put('binding', metricDataCalculationParameters.getBinding());

            String questionType = metricDataCalculationParameters.getQuestionType();
            variables.put('questionType', questionType);
            variables.put('function', metricDataCalculationParameters.getFunction());

            String metricName = metricDataCalculationParameters.getMetricGeneralName();

            // Multiple select questions need to be handled in a slightly different way from the others
            if (questionType.equals('multiSelect')) {
                variables.put('multipleOptions', metricDataCalculationParameters.getSelectOptions());
            }
            else if (questionType.equals('singleSelect')) {
                variables.put('selectOptions', metricDataCalculationParameters.getSelectOptions());
            }
            AggregateResult[] results = database.query(SoqlHelpers.getSurveyStats(variables, metricDataCalculationParameters.getGroupList()));
            for (AggregateResult result : results) {

                // TODO - support grouping by more than one field.
                String groupField = (String)result.get('groupField0');
                Decimal total = (Decimal)result.get('total');
                String metricDataName = MetricHelpers.createMetricLabelString(metricName, groupField);
                if (metricCalculationTracker.get(metricDataName) == null) {
                    System.debug(LoggingLevel.INFO, 'MetricCalclationTracker for ' + metricDataName + ' is missing. Total was ' + total);
                }
                else {
                    metricCalculationTracker.get(metricDataName).setTotal(total);
                }
            }
            variables.remove('surveyName');
            variables.remove('binding');
            variables.remove('questionType');
            variables.remove('function');
            variables.remove('multipleOptions');
            variables.remove('selectOptions');
        }
    }

    global void finish(Database.BatchableContext BC) {


        List<M_E_Metric_Data__c> metricsDatas = new List<M_E_Metric_Data__c>();

        // Go through the general metrics and update the M_E_Metric_Data__c objects. The key here should be the item that
        // We are splitting the data by
        Decimal totalWorkers = 0.0;
        Decimal totalFemaleWorkers = 0.0;
        Decimal totalPoorWorkers = 0.0;
        Decimal totalDistricts = 0.0;

        for (String key : generalMetrics.keySet()) {

            // Check that there are actually people for this district
            MetricDataCalculationGeneralTracker metricDataCalculationGeneralTracker = generalMetrics.get(key);
            if (metricDataCalculationGeneralTracker.getTotalActivePeople() == 0) {
                continue;
            }
            totalDistricts++;

            // Start with the total workers
            String metricDataName = MetricHelpers.createMetricLabelString(partner.Name + '_total_workers', key);
            M_E_Metric_Data__c metric = currentQuarterMetricDatas.get(metricDataName);
            if (metric == null) {

                // Create the metric data if it does not exist
                metric = MetricHelpers.createNewMetric(partner.Name + '_total_workers', ckwQuarterStartDate, metricDataCalculationGeneralTracker.getTotalActivePeople(), null, districts.get(key).Id, partner.Name, false);
            }
            else { 

                // Add the total
                metric.Actual_Value__c = metricDataCalculationGeneralTracker.getTotalActivePeople();
            }
            if (metric != null) {
                metricsDatas.add(metric);
            }
            totalWorkers += metricDataCalculationGeneralTracker.getTotalActivePeople();

            // Then the female workers
            metricDataName = MetricHelpers.createMetricLabelString(partner.Name + '_total_female_workers', key);
            metric = currentQuarterMetricDatas.get(metricDataName);
            Decimal female = 0.0;
            if (metricDataCalculationGeneralTracker.getTotalFemalePeople() != 0) {
                female = (metricDataCalculationGeneralTracker.getTotalFemalePeople() / totalWorkers) * 100;
            }
            if (metric == null) {

                // Create the metric data if it does not exist
                metric = MetricHelpers.createNewMetric(partner.Name + '_total_female_workers', ckwQuarterStartDate, female, null, districts.get(key).Id, partner.Name, false);
            }
            else {

                // Add the total
                metric.Actual_Value__c = female;
            }
            totalFemaleWorkers += female;
            if (metric != null) {
                metricsDatas.add(metric);
            }

            // Then the poor workers
            metricDataName = MetricHelpers.createMetricLabelString(partner.Name + '_total_poor_workers', key);
            metric = currentQuarterMetricDatas.get(metricDataName);
            Decimal poor = metricDataCalculationGeneralTracker.getSumPovertyScore() / totalWorkers;
            if (metric == null) {

                // Create the metric data if it does not exist
                metric = MetricHelpers.createNewMetric(partner.Name + '_total_poor_workers', ckwQuarterStartDate, poor, null, districts.get(key).Id, partner.Name, false);
            }
            else {

                // Add the total
                metric.Actual_Value__c = poor;
            }
            if (metric != null) {
                metricsDatas.add(metric);
            }

            totalPoorWorkers += poor;
        }

        // Go through the calculated metrics and save the results to the DB
        for (String key : metricCalculationTracker.keySet()) {

            MetricDataCalculationTracker tracker = metricCalculationTracker.get(key);

            // Check that some data has been added to the tracker. Otherwise there is no point saving it
            if (tracker == null || tracker.getNoDataAdded()) {
                continue;
            }

            // Perform the calculation required to get the actual value that should be displayed
            Decimal actualValue = MetricHelpers.calculateSurveyTotal(tracker, this.surveyTotals);
            M_E_Metric_Data__c metric = currentQuarterMetricDatas.get(key);
            if (metric == null) {

                // Create the metric
                metric = MetricHelpers.createNewMetric(tracker.getMetricName(), ckwQuarterStartDate, actualValue, null, tracker.getDistrict().Id, partner.Name, false);
            }
            else {

                // Update the existing metric
                metric.Actual_Value__c = actualValue;
            }
            if (metric != null) {
                metricsDatas.add(metric);
            }
        }

        // Go through the search totals and add the metrics. The key should be the district name
        for (String key : this.searchTotals.keySet()) {
            Integer total = this.searchTotals.get(key);
            String districtId = districts.get(key).Id;
            String metricName = partner.Name + '_total_searches';
            M_E_Metric_Data__c metric = currentQuarterMetricDatas.get(metricName + '_' + key);
            if (metric == null) {

                // Create the metric
                metric = MetricHelpers.createNewMetric(metricName, ckwQuarterStartDate, total, null, districtId, partner.Name, false);
            }
            else {

                // Update the existing metric
                metric.Actual_Value__c = total;
            }
            if (metric != null) {
                metricsDatas.add(metric);
            }

            // Also add the search totals to the total interactions
            Integer totalInteraction = this.totalInteractions.get(key);
            if (totalInteraction == null) {
                totalInteraction = 0;
            }
            this.totalInteractions.put(key, totalInteraction + total);
        }

        // Go through the survey totals and sort the total metric datas
        for (String key : this.surveyTotals.keySet()) {

            String[] keys = key.split('_splitter_');
            Integer total = this.surveyTotals.get(key);

            // If only one key then this is the total metric
            M_E_Metric_Data__c metric;
            String metricName = partner.Name + '_' + keys[0] + '_total';
            String districtId = null;
            if (keys.size() == 1) {
                metric = currentQuarterMetricDatas.get(metricName);
            }
            else {
                districtId = districts.get(keys[1]).Id;
                metric = currentQuarterMetricDatas.get(metricName + '_' + keys[1]);
            }
            if (metric == null) {

                // Create the metric
                metric = MetricHelpers.createNewMetric(metricName, ckwQuarterStartDate, total, null, districtId, partner.Name, false);
            }
            else {

                // Update the existing metric
                metric.Actual_Value__c = total;
            }
            if (metric != null) {
                metricsDatas.add(metric);
            }

            // Also add the search totals to the total interactions
            if (keys.size() == 2) {
                Integer totalInteraction = this.totalInteractions.get(keys[1]);
                if (totalInteraction == null) {
                    totalInteraction = 0;
                }
                this.totalInteractions.put(keys[1], totalInteraction + total);
            }
        }

        // Now go through the total interactions and add the metrics. Key is the district name
        for (String key : this.totalInteractions.keySet()) {

            Integer total = this.totalInteractions.get(key);
            String districtId = districts.get(key).Id;
            String metricName = partner.Name + '_total_interactions';
            M_E_Metric_Data__c metric = currentQuarterMetricDatas.get(metricName + '_' + key);
            if (metric == null) {

                // Create the metric
                metric = MetricHelpers.createNewMetric(metricName, ckwQuarterStartDate, total, null, districtId, partner.Name, false);
            }
            else {

                // Update the existing metric
                metric.Actual_Value__c = total;
            }
            if (metric != null) {
                metricsDatas.add(metric);
            }
        }

        // Batch up the metric datas and save to the db
        MetricHelpers.saveMetricDatas(metricsDatas);
        metricsDatas.clear();

        // Calcualte the totals for all the districts
        for (MetricDataCalculationTracker tracker : MetricHelpers.getTotals(partner.Name)) {

            if (tracker.getNoDataAdded()) {
                continue;
            }

            Decimal actualValue = tracker.getTotal();

            M_E_Metric_Data__c metric = currentQuarterMetricDatas.get(tracker.getMetricName());
            if (metric == null) {

                // Create the metric
                metric = MetricHelpers.createNewMetric(tracker.getMetricName(), ckwQuarterStartDate, actualValue, null, null, partner.Name, false);
            }
            else {

                // Update the existing metric
                metric.Actual_Value__c = actualValue;
            }
            if (metric != null) {
                metricsDatas.add(metric);
            }
        }

        // Batch up the metric datas and save to the db
        MetricHelpers.saveMetricDatas(metricsDatas);
        metricsDatas.clear();

        // Now that we have added all the metrics for this partner calculate the cumulative metrics.
        // Must be done here so we include the newest values
        for (MetricDataCalculationTracker tracker : MetricHelpers.getCumulativeValues(partner.Name, districts)) {

            if (tracker.getNoDataAdded()) {
                continue;
            }

            Decimal actualValue = tracker.getTotal();

            String districtName = '';
            Id districtId = null;
            District__c district = tracker.getDistrict();
            if (district != null) {
                districtName = district.Name;
                districtId = district.Id;
            }
            String key = MetricHelpers.createMetricLabelString(tracker.getMetricName(), districtName);
            key = key + '_cumulative';

            M_E_Metric_Data__c metric = currentQuarterMetricDatas.get(key);
            if (metric == null) {

                // Create the metric
                metric = MetricHelpers.createNewMetric(tracker.getMetricName(), ckwQuarterStartDate, actualValue, null, districtId, partner.Name, true);
            }
            else {

                // Update the existing metric
                metric.Actual_Value__c = actualValue;
            }
            if (metric != null) {
                metricsDatas.add(metric);
            }
        }

        MetricHelpers.saveMetricDatas(metricsDatas);
    }

    public static testMethod void testPartnerBatch() {

        Date startDate = MetricHelpers.getQuarterFirstDay(MetricHelpers.getCurrentQuarterAsString(0));
        Time startTime = time.newInstance(12, 30, 30, 0);
        DateTime submissionDateTime = datetime.newInstance(startDate.addDays(15), startTime);

        // Create a test Organisation
        Account org = Utils.createTestOrganisation('TestOrg1');
        database.insert(org);

        // Create a test survey
        Map<String, Survey__c> surveyMap = new Map<String, Survey__c>();
        Survey__c survey = Utils.createTestSurvey(org, 'Test1');
        survey.Account__c = org.Id;
        database.insert(survey);
        Survey__c surveySaved = [SELECT Name, Id FROM Survey__c WHERE Id = :survey.Id];
        surveyMap.put((String)surveySaved.Id, surveySaved);

        // Create two test districts.
        District__c district1 = Utils.createTestDistrict('Here');
        database.insert(district1);
        District__c district2 = Utils.createTestDistrict('There');
        database.insert(district2);

        //Create two test CKWs
        CKW__c ckw1 = Utils.createTestCkw(null, 'TestCKW1', true, district1.Id, 'Female');
        database.insert(ckw1);
        CKW__c ckw2 = Utils.createTestCkw(null, 'TestCKW2', true,district2.Id, 'Male');
        database.insert(ckw2);

        // Give the CKWs a poverty scorecard
        Poverty_Scorecard__c povertyScorecard1 = Utils.createTestPovertyScorecard('RICH', ckw1.Person__c, false, '');
        database.insert(povertyScorecard1);
        Poverty_Scorecard__c povertyScorecard2 = Utils.createTestPovertyScorecard('VERYPOOR', ckw2.Person__c, false, '');
        database.insert(povertyScorecard2);

        // Link the CKWs to the organisation;
        database.insert(Utils.creatTestPersonOrgLink(ckw1.Person__c, org.Id));
        database.insert(Utils.creatTestPersonOrgLink(ckw2.Person__c, org.Id));

        // Create a farmer or two
        Farmer__c farmer1 = Utils.createTestFarmer('OD99999', null, 'TestFarmer1', true, null, null);
        farmer1.Registered_By__c = ckw1.Person__c;
        database.insert(farmer1);

        Farmer__c farmer2 = Utils.createTestFarmer('OD99998', null, 'TestFarmer2', true, null, null);
        farmer2.Registered_By__c = ckw2.Person__c;
        database.insert(farmer2);

        // Create some test submissions
        Submission_Meta_Data__c sub1 = Utils.createTestSubmission(ckw1.Person__c, farmer1.Person__c, survey.Id, submissionDateTime, 'Sub1');
        database.insert(sub1);
        Submission_Meta_Data__c sub2 = Utils.createTestSubmission(ckw1.Person__c, farmer1.Person__c, survey.Id, submissionDateTime, 'Sub2');
        database.insert(sub2);
        Submission_Meta_Data__c sub3 = Utils.createTestSubmission(ckw2.Person__c, farmer2.Person__c, survey.Id, submissionDateTime, 'Sub3');
        database.insert(sub3);
        Submission_Meta_Data__c sub4 = Utils.createTestSubmission(ckw2.Person__c, farmer2.Person__c, survey.Id, submissionDateTime, 'Sub4');
        database.insert(sub4);

        // Add some answers to submissions
        List<Submission_Answer__c> answers = new List<Submission_Answer__c>();
        Submission_Answer__c answer1 = Utils.createTestSubmissionAnswer(sub1.Id, 'Boolean_Answer__c', 'yes', 'Select1', 'qestion1', 0);
        answers.add(answer1);
        Submission_Answer__c answer2 = Utils.createTestSubmissionAnswer(sub2.Id, 'Boolean_Answer__c', 'no', 'Select1', 'qestion1', 0);
        answers.add(answer2);
        Submission_Answer__c answer3 = Utils.createTestSubmissionAnswer(sub3.Id, 'Boolean_Answer__c', 'yes', 'Select1', 'qestion1', 0);
        answers.add(answer3);
        Submission_Answer__c answer4 = Utils.createTestSubmissionAnswer(sub4.Id, 'Boolean_Answer__c', 'no', 'Select1', 'qestion1', 0);
        answers.add(answer4);

        Submission_Answer__c answer5 = Utils.createTestSubmissionAnswer(sub1.Id, 'Integer_Answer__c', '3', 'Input', 'qestion2', 0);
        answers.add(answer5);
        Submission_Answer__c answer6 = Utils.createTestSubmissionAnswer(sub2.Id, 'Integer_Answer__c', '5', 'Input', 'qestion2', 0);
        answers.add(answer6);
        Submission_Answer__c answer7 = Utils.createTestSubmissionAnswer(sub3.Id, 'Integer_Answer__c', '2', 'Input', 'qestion2', 0);
        answers.add(answer7);
        Submission_Answer__c answer8 = Utils.createTestSubmissionAnswer(sub4.Id, 'Integer_Answer__c', '9', 'Input', 'qestion2', 0);
        answers.add(answer8);
        database.insert(answers);

        // Create some metrics
        List<M_E_Metric__c> metrics = new List<M_E_Metric__c>();
        M_E_Metric__c metric1 = Utils.createTestMetric(org, 'Average', 'Scale', true, 'TestBoolean');
        metrics.add(metric1);
        M_E_Metric__c metric2 = Utils.createTestMetric(org, 'Cumulative', 'Scale', true, 'TestSum');
        metrics.add(metric2);
        M_E_Metric__c metric3 = Utils.createTestMetric(org, 'Cumulative', 'Scale', true, 'total_workers');
        metrics.add(metric3);
        M_E_Metric__c metric4 = Utils.createTestMetric(org, 'Average', 'Scale', true, 'total_female_workers');
        metrics.add(metric4);
        M_E_Metric__c metric5 = Utils.createTestMetric(org, 'Average', 'Scale', true, 'total_poor_workers');
        metrics.add(metric5);
        M_E_Metric__c metric6 = Utils.createTestMetric(org, 'Cumulative', 'Scale', true, 'total_districts');
        metrics.add(metric6);
        database.insert(metrics);

        String query=
            'SELECT '                                                  +
                'Id, '                                                 +
                'District__r.Name, '                                   +
                'Current_Poverty_Scorecard__r.Poverty_Percentage__c, ' +
                'Gender__c '                                           +
            'FROM '                                                    +
                'Person__c '                                           +
            'WHERE '                                                   +
                'Id IN ('                                              +
                    'SELECT '                                          +
                        'Person__c '                                   +
                    'FROM '                                            +
                        'Person_Organisation_Association__c '          +
                    'WHERE '                                           +
                        'Organisation__r.Name = \''                    +
                            'TestOrg_TestOrg1'                         +
                        '\''                                           +
                ')';

        // Generate the metric calculation params
        Map<String, MetricDataCalculationParameters> parameters = new Map<String, MetricDataCalculationParameters>();
        List<String> groupList = new List<String>();
        groupList.add('District__r.Name');
        parameters.put(metric1.Name, new MetricDataCalculationParameters(metric1.Name, 'boolean', 'percentage', 'Boolean_Answer__c', surveySaved, groupList));
        parameters.put(metric2.Name, new MetricDataCalculationParameters(metric2.Name, 'input', 'average', 'Integer_Answer__c', surveySaved, groupList));

        // Run the batch
        Test.StartTest();
        PartnerMetrics partnerMetric = new PartnerMetrics(query, org, parameters, surveyMap);
        ID batchprocessid = Database.executeBatch(partnerMetric);
        Test.StopTest();
    }
}