src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CKW_Cluster_Meeting__c.object
<CustomObject>
    <fields>
        <fullName>CKW__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CKW</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 CKW Cluster Meetings (Contact)</relationshipLabel>
        <relationshipName>X3_0_CKW_Cluster_Meetings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FO__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>FO</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 CKW Cluster Meetings</relationshipLabel>
        <relationshipName>X3_0_CKW_Cluster_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>3.0 CKW Cluster Meeting</label>
    <nameField>
        <displayFormat>CCM{YYYY}{MM}{DD}{0000}</displayFormat>
        <label>CKW Cluster Meeting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 CKW Cluster Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FO__c.object
<CustomObject>
    <label>3.0 FO</label>
    <nameField>
        <displayFormat>FO-{YYYY}{MM}-{0}</displayFormat>
        <label>FO Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 FOs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Monthly_CKW_Visit__c.object
<CustomObject>
    <description>This object represents a unique interaction between an FO and a CKW per month. Each CKW is meant to meet their FO once every month.</description>
    <fields>
        <fullName>CKW__c</fullName>
        <label>CKW Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 Monthly CKW Visits (CKW Contact)</relationshipLabel>
        <relationshipName>CKW_Monthly_CKW_Visits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FO__c</fullName>
        <label>FO Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>3.0 Monthly CKW Visits</relationshipLabel>
        <relationshipName>Monthly_CKW_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Visit Date</description>
        <inlineHelpText>Visit Date</inlineHelpText>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>3.0 Monthly CKW Visit</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>3.0 Monthly CKW Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Monthly CKW Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateMonthlyCkwVisit.cls
public class CreateMonthlyCkwVisit {
    
    public static void createVisit(Date aDay) {
        Date thisDay = aDay;
        Date previousDay = aDay.addDays(-1);
        
        List<Monthly_CKW_Visit__c> visits = new List<Monthly_CKW_Visit__c>();
        
        List<String> contactIds = new List<String>();
        if (thisDay.day() != 1) {
            for (Monthly_CKW_Visit__c thisMonthVisit : [SELECT Id, CKW__c from Monthly_CKW_Visit__c
                  where Visit_Date__c = THIS_MONTH]) {
                if (null != thisMonthVisit) {
                    contactIds.add(thisMonthVisit.CKW__c);
                }
            }
        }
        else {
            for (Monthly_CKW_Visit__c thisMonthVisit : [SELECT Id, CKW__c from Monthly_CKW_Visit__c
                  where Visit_Date__c = LAST_MONTH]) {
                contactIds.add(thisMonthVisit.CKW__c);
            }
        }
        Map<String, CKW_Cluster_Meeting__c> contactMeets = new Map<String, CKW_Cluster_Meeting__c>();
        for (CKW_Cluster_Meeting__c clusterMeet : [Select FO__c, CKW__c, CreatedDate from CKW_Cluster_Meeting__c
            where CreatedDate >=: previousDay and CreatedDate <: thisDay and CKW__c not in:contactIds]) {
            
            if (null != clusterMeet) {
                contactMeets.put(clusterMeet.CKW__c, clusterMeet);
            }
        }
        for (String contactId : contactMeets.keyset()) {
            CKW_Cluster_Meeting__c meet = contactMeets.get(contactId);
            Monthly_CKW_Visit__c visit = new Monthly_CKW_Visit__c();
            visit.FO__c= meet.FO__c;
            visit.CKW__c = contactId;
            visit.Visit_Date__c = date.newinstance(meet.CreatedDate.year(), meet.CreatedDate.month(), meet.CreatedDate.day());
            visits.add(visit);
        }
        insert visits; 
    }
}