src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>gfsurveys__mobilesurveys_Id__c</fullName>
        <externalId>true</externalId>
        <label>Respondent ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>gfsurveys__mobilesurveys_Status__c</fullName>
        <label>Surveyor Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <fields>
        <fullName>Latitude__c</fullName>
        <description>The central latitude of the district. This is where maps will center if this district is the focus of the map.</description>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <description>The central longitude of the district</description>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EMP_Consultant__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Consultant_contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EMP Consultants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Consultant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Consultant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Consultants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Cell_Phone_Number__c</fullName>
        <label>Cell Phone Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entrance_Into_Programme__c</fullName>
        <label>Entrance Into Programme</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Farmer_Code__c</fullName>
        <label>Farmer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Farmer_Cooperative__c</fullName>
        <description>The name of the cooperative associated with the farmer</description>
        <label>Farmer Cooperative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>We have a gender field here because the options in LAC surveys are in Spanish and IBT doesn&apos;t yet (v 2.22 and earlier) support different labels and values for options</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Has_Cellphone__c</fullName>
        <label>Has Cellphone</label>
        <picklist>
            <picklistValues>
                <fullName>Si</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Has_Data_Plan__c</fullName>
        <label>Has Data Plan</label>
        <picklist>
            <picklistValues>
                <fullName>Si</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <formula>submision__r.gfsurveys__gps_y__c</formula>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <formula>submision__r.gfsurveys__gps_x__c</formula>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Municipality__c</fullName>
        <label>Municipality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registered_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Registered By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Registered LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details_Registered_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LacCkwController.cls
public with sharing class LacCkwController {

    private List<List<String>> farmerGPSAddresses = new List<List<String>>();
    private List<LAC_Farmer_Details__c> ckwFarmers = new List<LAC_Farmer_Details__c>();
    private Contact contact;
    private Person__c person;
    private LAC_Farmer_Details__c lacFarmer;
    private CKW__c ckw;
    private ApexPages.StandardController stdController;

    public LacCkwController(ApexPages.StandardController controller) {
        this.stdController = controller;
        ckw = (CKW__c)stdController.getRecord();
        ckw = [Select Id, Person__c from CKW__c where Id =:ckw.Id];
        person = [Select id, First_Name__c, Contact__c, Contact__r.gfsurveys__mobilesurveys_Status__c 
            from Person__c where Id=:ckw.Person__c ];
        lacFarmer = [Select Id, 
                        Contact__c,
                        Contact__r.FirstName,
                        Contact__r.LastName,
                        Contact__r.Birthdate,
                        Contact__r.gfsurveys__mobilesurveys_Id__c,
                        Name,
                        Country__c,
                        Community__c,
                        Department__c,
                        District__c,
                        Gender__c,
                        Municipality__c,
                        Farmer_Cooperative__c,
                        Entrance_Into_Programme__c,
                        Has_Cellphone__c,
                        Has_Data_Plan__c,
                        Latitude__c,
                        Longitude__c,
                        Cell_Phone_Number__c
                    from LAC_Farmer_Details__c
                    where Contact__c=:person.Contact__c];
    }

    public LAC_Farmer_Details__c getLacFarmer() {
        return this.lacFarmer;
    }

    public Person__c getPerson() {
        return this.person;
    }

    public List<List<String>> getAssignedFarmers() {
        if (person == null) {
            person = [Select id, First_Name__c, Contact__c, Contact__r.gfsurveys__mobilesurveys_Status__c
                from Person__c where Id=:ckw.Person__c];
        }
        LAC_Farmer_Details__c[] farmers = [Select Id,
                                                    Contact__c,
                                                    Contact__r.FirstName,
                                                    Contact__r.LastName,
                                                    Name,
                                                    Farmer_code__c,
                                                    Registered_By__c,
                                                    Latitude__c,
                                                    Longitude__c
                                            FROM LAC_Farmer_Details__c
                                            WHERE Registered_By__c=:person.Contact__c];
        ckwFarmers = farmers;
        farmerGPSAddresses.add(new String[]{ String.valueOf(lacFarmer.Latitude__c), String.valueOf(lacFarmer.Longitude__c)});
        for (LAC_Farmer_Details__c farmer : farmers) {
            String[] addressList = new String[]{ String.valueOf(farmer.Latitude__c), String.valueOf(farmer.Longitude__c)};
            farmerGPSAddresses.add(addressList);
        }
        return farmerGPSAddresses;
    }

    public DateTime getEnrollmentDate() {
        Contact[] contact = [Select CreatedDate from Contact where Id =:person.Contact__c];
        return contact[0].CreatedDate;
    }
    
    public DateTime getLastSurveyDate(){
        gfsurveys__Submission__c submission = [Select CreatedDate from gfsurveys__Submission__c where 
            gfsurveys__Surveyor__c=:person.Contact__c order by CreatedDate desc limit 1];
        return submission.CreatedDate;
    }

    public Integer getNumberOfAssignedFarmers() {
        LAC_Farmer_Details__c[] farmers = [Select Id,
                                                Contact__c,
                                                Contact__r.FirstName,
                                                Contact__r.LastName,
                                                Name,
                                                Farmer_code__c,
                                                Registered_By__c,
                                                Latitude__c,
                                                Longitude__c,
                                                Municipality__c,
                                                Community__c
                                        FROM LAC_Farmer_Details__c
                                        WHERE Registered_By__c=:person.Contact__c];
        ckwFarmers = farmers;
        return farmers.size();
    }

    public Integer getAssignedCommunities() {
        Set<String> communities = new Set<String>();
        for (LAC_Farmer_Details__c farmer : ckwFarmers) {
            communities.add(farmer.Community__c);
        }
        return communities.size();
    }

    public Integer getAssignedMunicipalities() {
        Set<String> municipalities = new Set<String>();
        for (LAC_Farmer_Details__c farmer : ckwFarmers) {
            municipalities.add(farmer.Municipality__c);
        }
        return municipalities.size();
    }

    public List<LAC_Farmer_Details__c> getCkwFarmers() {
        getNumberOfAssignedFarmers();
        return ckwFarmers;
    }

}