src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Registered_By__c</fullName>
        <label>Registered By</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers Registered</relationshipLabel>
        <relationshipName>Farmers_Registered</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Search_Log__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CKW/Interviewer as obtained from Salesforce using handset id</description>
        <label>Interviewer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Done)</relationshipLabel>
        <relationshipName>Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Log</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CkwDetailMiniStartsController.cls
/**
 * Controller class for CkwDetailMiniStarts page
 * Tests in GumutindoDashboardTests.cls
 */
public with sharing class CkwDetailMiniStartsController {
	
	private CKW__c obj;
	private Decimal totalSearches = null;
	private Decimal totalSurveys = null;
	private Decimal totalFarmers = null;
	
	private ApexPages.StandardController controller = null;
	
	public CkwDetailMiniStartsController(ApexPages.StandardController controller) {
		this.obj = (CKW__c)controller.getRecord();
		this.controller = controller;
	}
	
	public String getTotalFarmers() {
		if(this.totalFarmers == null) {
			try {
				if(obj.Person__c != null) {
					this.totalFarmers = [SELECT COUNT() FROM Farmer__c WHERE Registered_By__c =: obj.Person__c];
				} else {
					return 'N/A';
				}
			}catch (Exception e) {
				return 'ERROR';
			}
		}
		
		return String.valueOf(this.totalFarmers);
	}
	
	public String getTotalSearches() {
		if(this.totalSearches == null) {
			try {
				this.totalSearches = [SELECT COUNT() FROM Search_Log__c WHERE Interviewer__c =: obj.Person__c];
			} catch (Exception e) {
				return 'ERROR';
			}
		}
		return String.valueOf(this.totalSearches);
	}
	/*
	public String getTotalSurveys() {
		
		//TODO: callout and count survey submissions
		if(this.totalSurveys == null) {
			try {
				if(obj.Person__c != null) {
					//this.totalSurveys = [SELECT COUNT() FROM gfsurveys__Submission__c WHERE gfsurveys__Surveyor__c =: obj.Person__r.Contact__c];
					return 'N/A';
				} else {
					return 'N/A';
				}
			} catch (Exception e) {
				return 'ERROR';
			}
		}
		
		return String.valueOf(this.totalSurveys);
	}
	
	public Decimal getInteractionsPerFarmerPerQuarter() {
		
		Decimal searches = null;
		try {
			searches = Decimal.valueOf(this.getTotalSearches());
		} catch (Exception e) {
			searches = 0;
		}
		
		Decimal surveys = null;
		try {
			surveys = Decimal.valueOf(this.getTotalSurveys());
		} catch (Exception e) {
			surveys = 0;
		}
		
		Decimal interactions = searches + surveys;
		
		Decimal farmers = null;
		try {
			farmers = Decimal.valueOf(this.getTotalFarmers());
		} catch (Exception e) {
			farmers = 0;
		} 
		
		Decimal interactionsPerFarmer = 0;
		if(farmers > 0) {
			interactionsPerFarmer = interactions / farmers;
		}
		
		// Quarters quarters since registration
		CKW__c ckw = [SELECT CreatedDate from CKW__c where id =: obj.id];
		Decimal quarters = ckw.CreatedDate.date().daysBetween(Date.today())/91;
		
		// InteractionsPerFarmerPerQuarter
		if(quarters > 0)
			return (interactionsPerFarmer / quarters).setScale(2);
		else 
			return interactionsPerFarmer.setScale(2);
	}*/
}