src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CKW_Performance_Review__c.object
<CustomObject>
    <description>Summary of performance of each CKW in a given week or month, per different targets</description>
    <fields>
        <fullName>CKW_c__c</fullName>
        <description>Links to the CKW object</description>
        <label>CKW</label>
        <referenceTo>CKW__c</referenceTo>
        <relationshipLabel>CKW Monthly Performance Records</relationshipLabel>
        <relationshipName>CKW_Performance_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Incentive_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The incentive structure that is active for this performance review.</description>
        <label>Incentive Structure</label>
        <referenceTo>Incentive_Structure__c</referenceTo>
        <relationshipName>CKW_Performance_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The monthly target object associated with this performance review</description>
        <label>Monthly Target</label>
        <referenceTo>Monthly_Target__c</referenceTo>
        <relationshipName>CKW_Performance_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_Of_Searches_Running_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Stores the searches that have been recorded in the search log. This is updated every day and the searches for that day are added to the existing one</description>
        <label>Searches::New System (Updated Daily)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The month to be monitored</description>
        <inlineHelpText>Select First day of the month/year you want to monitor</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Surveys_Approved__c</fullName>
        <description>Stores the number surveys that have been approved for a particular CKW in a given month</description>
        <label>Surveys::Approved</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CKW Monthly Performance</label>
    <nameField>
        <displayFormat>PR-{YY}-{MM}-{000000}</displayFormat>
        <label>CKW Monthly Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKW Monthly Performance Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Incentive_Structure__c.object
<CustomObject>
    <description>Incentive Structure contains several constants that specify the current CKW payment scheme. The Start Date field indicates when this version of the incentive structure goes into effect. Formulas that calculate CKW payments are expected to look up the newest version of the Incentive Structure for their calculations.</description>
    <fields>
        <fullName>Airtime_Compensation__c</fullName>
        <description>The standard amount that all CKWs are compensated for airtime</description>
        <label>Airtime Compensation</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_A_Compensation__c</fullName>
        <description>The compensation awarded for Level A performance</description>
        <label>Level A Compensation</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_A_Threshold__c</fullName>
        <description>The percentage of target that must be reached to qualify for Level A compensation</description>
        <label>Level A Threshold</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Level_B_Compensation__c</fullName>
        <description>The compensation awarded for Level B performance</description>
        <label>Level B Compensation</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_B_Threshold__c</fullName>
        <description>The percentage of target that must be reached to qualify for Level B compensation</description>
        <label>Level B Threshold</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Level_C_Compensation__c</fullName>
        <description>The compensation awarded for Level C performance</description>
        <label>Level C Compensation</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_C_Threshold__c</fullName>
        <description>The percentage of target that must be reached to qualify for Level C compensation</description>
        <label>Level C Threshold</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Level_D_Compensation__c</fullName>
        <description>The compensation awarded for Level D performance</description>
        <label>Level D Compensation</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Long_Term_Airtime_Bonus__c</fullName>
        <description>The amount of airtime that the current incentive scheme awards for long term bonuses (based on six months of performance). If there is no long term airtime bonus this month, then the value should be 0.</description>
        <label>Long Term Airtime Bonus</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Long_Term_Cash_Bonus__c</fullName>
        <description>The amount of cash that the current incentive scheme awards for long term bonuses (based on six months of performance). If there is no long term cash bonus this month, then the value should be 0.</description>
        <label>Long Term Cash Bonus</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Medium_Term_Airtime_Bonus__c</fullName>
        <description>The amount of airtime that the current incentive scheme awards for medium term bonuses (based on three months of performance). If there is no medium term airtime bonus this month, then the value should be 0.</description>
        <label>Medium Term Airtime Bonus</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Medium_Term_Cash_Bonus__c</fullName>
        <description>The amount of cash that the current incentive scheme awards for medium term bonuses (based on three months of performance). If there is no medium term cash bonus this month, then the value should be 0.</description>
        <label>Medium Term Cash Bonus</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Short_Term_Airtime_Bonus__c</fullName>
        <description>The amount of airtime that the current incentive scheme awards for short term bonuses (based on one month of performance). If there is no short term airtime bonus this month, then the value should be 0.</description>
        <label>Short Term Airtime Bonus</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Short_Term_Cash_Bonus__c</fullName>
        <description>The amount of cash that the current incentive scheme awards for short term bonuses (based on one month of performance). If there is no short term cash bonus this month, then the value should be 0.</description>
        <label>Short Term Cash Bonus</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that this version of the incentive structure goes into effect. We need this field because we may change the incentive structure over time, and we want to keep track of the historical changes. Our algorithm for calculating payment will always look up the most recent version of the incentive structure.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Incentive Structure</label>
    <nameField>
        <label>Incentive Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Structures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Monthly_Target__c.object
<CustomObject>
    <description>This object contains the monthly search and survey targets. It is global for all CKWs. The Start Date field indicates when these targets go into effect. Payment calculations are expected to use the Monthly Target object with the newest Start Date.</description>
    <fields>
        <fullName>Search_Target__c</fullName>
        <description>The number of searches that CKWs are expected to perform this month.</description>
        <label>Search Target</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that these targets go into effect. We need this field because we may change the targets over time, and we want to keep track of the historical changes. Our algorithm for calculating payment will always look up the most recent version of the targets.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Target__c</fullName>
        <description>The number of survey points that CKWs are expected to earn this month.</description>
        <label>Survey Target</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Target</label>
    <nameField>
        <label>Monthly Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Search_Log__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Accuracy__c</fullName>
        <label>Accuracy</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Altitude__c</fullName>
        <label>Altitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handset_Submit_Time__c</fullName>
        <description>Time the phone sent the request</description>
        <label>Handset Submit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person who requests information</description>
        <label>Interviewee</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Administered)</relationshipLabel>
        <relationshipName>Interviewee_Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CKW/Interviewer as obtained from Salesforce using handset id</description>
        <label>Interviewer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Done)</relationshipLabel>
        <relationshipName>Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Server_Entry_Time__c</fullName>
        <description>Time the server received the request</description>
        <label>Server Entry Time</label>
        <type>DateTime</type>
    </fields>
    <label>Search Log</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AdministrationUtilities.cls
public with sharing class AdministrationUtilities {

     public static void updateSearchLogs(Date startDate, Date endDate, Boolean increase) {


        // Get the count of the search log. Annoyingly cant group by Interviewer__r.Name.
        // This is why we need to go throug the long process below
        Map<Id, CkwDailySearches> logCountId   = new Map<Id, CkwDailySearches>();

        // The sub-query below alows us to only include CKWs in the results. Also take in to account
        // searches from the test farmer.
        if (startDate == null) {
            startDate = date.newInstance(2011, 03, 24);
        }
        if (endDate == null) {
            endDate = date.newInstance(2011, 03, 24);
        }
        datetime startTimestamp = MetricHelpers.convertToStartDate(startDate);
        datetime endTimestamp = MetricHelpers.convertToEndDate(endDate);
        Search_Log__c[] searchLogs = [SELECT
                Interviewer__c,
                Handset_Submit_Time__c
            FROM
                Search_Log__c
            WHERE 
                Server_Entry_Time__c >= :startTimestamp
                AND Server_Entry_Time__c <= :endTimestamp
                AND Interviewer__c != null
                AND Interviewer__c IN (SELECT Person__c FROM CKW__c)];
 
        // Leave this section out until TCH-257 is fixed
        /*
        AND Interviewee__c != null
        AND (NOT Interviewee__r.First_Name__c LIKE 'TEST')];
        */

        // Build up the query to get the Ckw.Name    	
        // Get the list of CKW__c.Person__r.Id's that are returned and use them to search for the CKW__c.Name
        List<String> personIds = new List<String>();	

        for (Search_Log__c searchLog : searchLogs) {
            CkwDailySearches dailySearches;
            if(logCountId.containsKey(searchLog.Interviewer__c)) {
                dailySearches = logCountId.get(searchLog.Interviewer__c);
            } else {
                dailySearches = new CkwDailySearches();
            }

            if(thisMonth(searchLog.Handset_Submit_Time__c.date())) {
                dailySearches.currentMonthSearches++;
            }
            else {
                dailySearches.previousMonthSearches++;
            }

            logCountId.put(searchLog.Interviewer__c, dailySearches);

            personIds.add(searchLog.Interviewer__c);
        }

        // Get the performance records for this month.
        String baseString =
            'SELECT '                                                       +
                'Number_Of_Searches_Running_Total__c, '                     +
                'CKW_c__r.Person__r.Id '                                      +
            'FROM '                                                         +
                'CKW_Performance_Review__c '                                +
            'WHERE '                                                        +
                'CKW_c__r.Person__r.Id IN ('                                  +
                MetricHelpers.generateCommaSeperatedString(personIds, true) +
                ')'                                                         +
                'AND Start_Date__c = ';

        CKW_Performance_Review__c[] thisMonthsReviews = database.query(baseString + 'THIS_MONTH');
        CKW_Performance_Review__c[] lastMonthsReviews = database.query(baseString + 'LAST_MONTH');

        // Generate the maps for the reviews
        Map<String, CKW_Performance_Review__c> thisMonthsReviewsMap = new Map<String, CKW_Performance_Review__c>();
        for (CKW_Performance_Review__c review : thisMonthsReviews) {
            thisMonthsReviewsMap.put(review.CKW_c__r.Person__r.Id, review);
        }
        Map<String, CKW_Performance_Review__c> lastMonthsReviewsMap = new Map<String, CKW_Performance_Review__c>();
        for (CKW_Performance_Review__c review : lastMonthsReviews) {
            lastMonthsReviewsMap.put(review.CKW_c__r.Person__r.Id, review);
        }

        // Loop through the search log map and add to the performanc reviews
        for (String id : logCountId.keySet()) {
            CkwDailySearches searches = logCountId.get(id);
            if (thisMonthsReviewsMap.containsKey(id)) {
                CKW_Performance_Review__c thisMonth = thisMonthsReviewsMap.get(id);
                if (thisMonth != null) {
                    if (increase) {
                        thisMonth.Number_Of_Searches_Running_Total__c = thisMonth.Number_Of_Searches_Running_Total__c + searches.currentMonthSearches;
                    } else {
                        thisMonth.Number_Of_Searches_Running_Total__c = thisMonth.Number_Of_Searches_Running_Total__c - searches.currentMonthSearches;
                    }
                    thisMonthsReviewsMap.put(id, thisMonth);
                }
            }
            if (lastMonthsReviewsMap.containsKey(id)) {
                CKW_Performance_Review__c lastMonth = lastMonthsReviewsMap.get(id);
                if (lastMonth != null) {
                    if (increase) {
                        lastMonth.Number_Of_Searches_Running_Total__c = lastMonth.Number_Of_Searches_Running_Total__c + searches.previousMonthSearches;
                    } else {
                        lastMonth.Number_Of_Searches_Running_Total__c = lastMonth.Number_Of_Searches_Running_Total__c - searches.previousMonthSearches;
                    }
                    lastMonthsReviewsMap.put(id, lastMonth);
                }
            }
        }

        // Loop through the reviews and create a list
        List<CKW_Performance_Review__c> thisMonthsReviewsList = new List<CKW_Performance_Review__c>();
        for (String id : thisMonthsReviewsMap.keySet()) {
            thisMonthsReviewsList.add(thisMonthsReviewsMap.get(id));
        }
        List<CKW_Performance_Review__c> lastMonthsReviewsList = new List<CKW_Performance_Review__c>();
        for (String id : lastMonthsReviewsMap.keySet()) {
            lastMonthsReviewsList.add(lastMonthsReviewsMap.get(id));
        }

        // Update the reviews
        if (thisMonthsReviewsList.size() > 0) {
            database.update(thisMonthsReviewsList);
        }
        if (lastMonthsReviewsList.size() > 0) {
            database.update(lastMonthsReviewsList);
        }
    }

    private static boolean thisMonth(Date testDate) {
        date now = date.today();
        if (testDate.month() == now.month()) {
            return true;
        } 
        return false;
    }

    /*
     * Need this class to keep track of when the searches in the Search_Log__c are for. Since the CKW may synchronize at any time.
     */
    class CkwDailySearches {

        public Integer currentMonthSearches;
        public Integer previousMonthSearches;

        public CkwDailySearches() {
            this.currentMonthSearches = 0;
            this.previousMonthSearches = 0;
        }
    }

    static testMethod void testUpdateSearch() {

        // Set up the dates that are required for this test
        Date searchDate = date.today();
        Date reviewStartDate = searchDate.toStartOfMonth();

        // Create a test CKW and perf review
        Person__c testPerson = new Person__c();
        testPerson.First_Name__c = 'FirstName';
        testPerson.Last_Name__c = 'LastName';
        database.insert(testPerson);

        CKW__c testCkw = new CKW__c();
        testCkw.Person__c = testPerson.id;

        database.insert(testCkw);

        // Create a performance review for this CKW
        Monthly_Target__c target = new Monthly_Target__c();
        target.Search_Target__c = 5.0;
        target.Survey_Target__c = 5.0;
        target.Start_Date__c = Date.today();
        database.insert(target);

        Incentive_Structure__c structure = new Incentive_Structure__c();
        structure.Level_A_Compensation__c = 15000.00;
        structure.Level_A_Threshold__c = 100;
        structure.Level_B_Compensation__c = 10000.00;
        structure.Level_B_Threshold__c = 75;
        structure.Level_C_Compensation__c = 5000.00;
        structure.Level_C_Threshold__c = 50;
        structure.Level_D_Compensation__c = 1000.00;
        structure.Airtime_Compensation__c = 2000.00;
        structure.Long_Term_Airtime_Bonus__c = 2000.00;
        structure.Long_Term_Cash_Bonus__c = 2000.00;
        structure.Short_Term_Airtime_Bonus__c = 2000.00;
        structure.Short_Term_Cash_Bonus__c = 2000.00;
        structure.Start_Date__c = date.today().addDays(-10);
        structure.Name = 'My_test';
        structure.Medium_Term_Airtime_Bonus__c = 2000.00;
        structure.Medium_Term_Cash_Bonus__c = 2000.00;
        database.insert(structure); 

        CKW_Performance_Review__c review = new CKW_Performance_Review__c();
        review.Surveys_Approved__c = 3.0;
        review.Number_Of_Searches_Running_Total__c = 3.0;
        review.CKW_c__c = testCkw.id;
        review.Incentive_Structure__c = structure.id;
        review.Monthly_Target__c = target.id;
        review.Start_Date__c = reviewStartDate;
        database.insert(review);

        // Create some searches for this ckw
        Person__c testPerson2 = new Person__c();
        testPerson2.First_Name__c = 'FirstName';
        testPerson2.Last_Name__c = 'LastName';
        testPerson2.Gender__c = 'Male';
        database.insert(testPerson2);
        List<Search_Log__c> logs = new List<Search_Log__c>();
        for (Integer i = 0; i < 10; i++) {
            Search_Log__c log = new Search_Log__c();
            log.Interviewer__c = testPerson.id;
            log.Interviewee__c = testPerson2.Id;
            log.Server_Entry_Time__c = MetricHelpers.convertToStartDate(searchDate).addHours(1);
            log.Handset_Submit_Time__c = MetricHelpers.convertToStartDate(searchDate).addHours(1);
            log.Latitude__c = 0.00;
            log.Longitude__c = 0.00;
            log.Altitude__c = 0.00;
            log.Accuracy__c = 0.00;
            log.Category__c = 'Category';
            log.Query__c = 'Query';
            log.Response__c = 'Content';
            logs.add(log);
        }
        database.insert(logs);

        // Run the update.
        updateSearchLogs(searchDate, searchDate, true);

        // Check that the record has been updated
        CKW_Performance_Review__c[] checkReview = [
            SELECT
                Number_Of_Searches_Running_Total__c
            FROM
                CKW_Performance_Review__c
            WHERE
                Start_Date__c = :reviewStartDate
                AND CKW_c__c = :testCkw.id
            ];
       System.assertEquals(checkReview[0].Number_Of_Searches_Running_Total__c, 13.0);
    }
}