src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>FLOOR((TODAY() - Birthdate)/365)</formula>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>We have a gender field here because the options in LAC surveys are in Spanish and IBT doesn&apos;t yet (v 2.22 and earlier) support different labels and values for options</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>interviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC_Farmer_Details_interviewer</relationshipLabel>
        <relationshipName>LAC_Farmer_Details_interviewer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>The age of a person</description>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_E__c</fullName>
        <description>GPS Location E. Must be in Decimal format</description>
        <label>GPS Location E</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_N__c</fullName>
        <description>GPS Location N. Must be in Decimal forma</description>
        <label>GPS Location N</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Search_Log__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Handset_Submit_Time__c</fullName>
        <description>Time the phone sent the request</description>
        <label>Handset Submit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person who requests information</description>
        <label>Interviewee</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Administered)</relationshipLabel>
        <relationshipName>Interviewee_Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CKW/Interviewer as obtained from Salesforce using handset id</description>
        <label>Interviewer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Done)</relationshipLabel>
        <relationshipName>Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission_Latitude__c</fullName>
        <description>The latitude that the log was submitted from</description>
        <label>Submission Latitude</label>
        <precision>18</precision>
        <scale>13</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Longitude__c</fullName>
        <description>The longitude that the log was submitted from</description>
        <label>Submission Longitude</label>
        <precision>18</precision>
        <scale>13</scale>
        <type>Number</type>
    </fields>
    <label>Search Log</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LacMapMarkers.cls
// This class is a namespace for all Lac Related Map Markers
public with sharing class LacMapMarkers {
	
	// Lac Farmer Map Marker
	public with sharing class LacFarmerMarker extends MapMarkers {
		private Lac_Farmer_Details__c farmer;
		 
		private String parentRegistered;
	    public String getParentRegistered() {
	        return this.parentRegistered;
	    }
	    
	    public void setParentRegistered(String value) {
	        this.parentRegistered = value;
	    }
	    
		public LacFarmerMarker(Lac_Farmer_Details__c farmer) {
	        this.farmer = farmer;
	        this.setLatitude(farmer.Person__r.GPS_Location_N__c);
	        this.setLongitude(farmer.Person__r.GPS_Location_E__c);
	        this.setMarkerColour('FF0000'); // Red
	    }
	    
	    public override String getMarkerInfoContentString() {
	    	String profile = 'Type: Farmer <br/>';
	    	profile += 'Id: ' + this.farmer.Name + '<br/>';
	    	profile += 'Name: ' + this.farmer.Person__r.First_Name__c + ' ' + this.farmer.Person__r.Last_Name__c + '<br/>';
	    	profile += (this.farmer.Person__r.Gender__c != NULL)?'Gender: ' + this.farmer.Person__r.Gender__c + '<br/>':'';
	    	profile += (this.farmer.Person__r.Age__c != NULL)?'Age: ' + this.farmer.Person__r.Age__c + '<br/>':'';
	    	
	    	PageReference ref = new PageReference('/'+this.farmer.Id);
	    	profile += '<a href=\'' + ref.getUrl() + '\'>Go to Profile</a>';
	    	
	    	return profile;
	    }
	    
	    public override String getLocation() {
	    	return '';
	    }
	}
	
	// Lac Ckw Map Marker
	public with sharing class LacCkwMarker extends MapMarkers {
		private CKW__c ckw;
		 
		private String parentRegistered;
	    public String getParentRegistered() {
	        return this.parentRegistered;
	    }
	    
	    public void setParentRegistered(String value) {
	        this.parentRegistered = value;
	    }
	    
		public LacCkwMarker(CKW__c ckw) {
	        this.ckw = ckw;
	        this.setLatitude(ckw.Person__r.GPS_Location_N__c);
	        this.setLongitude(ckw.Person__r.GPS_Location_E__c);
	        this.setDefaultColour('0000FF'); // Blue
	    }
	    
	    public override String getMarkerInfoContentString() {
	    	String profile = 'Type: CKW <br/>';
	    	profile += 'Id: ' + this.ckw.Name + '<br/>';
	    	profile += 'Name: ' + this.ckw.Person__r.First_Name__c + ' ' + this.ckw.Person__r.Last_Name__c + '<br/>';
	    	profile += (this.ckw.Person__r.Gender__c != NULL)?'Gender: ' + this.ckw.Person__r.Gender__c + '<br/>':'';
	    	profile += (this.ckw.Person__r.Age__c != NULL)?'Age: ' + this.ckw.Person__r.Age__c + '<br/>':'';
	    	
	    	PageReference ref = new PageReference('/'+this.ckw.Id);
	    	profile += '<a href=\'' + ref.getUrl() + '\'>Go to Profile</a>';
	    	return profile;
	    }
	    
	    public override String getLocation() {
	    	return '';
	    }
	}
	
	// Lac Search Map Marker
	public with sharing class LacSearchMarker extends MapMarkers {
		private Search_Log__c searchLog;
		 
		private String parentRegistered;
	    public String getParentRegistered() {
	        return this.parentRegistered;
	    }
	    
	    public void setParentRegistered(String value) {
	        this.parentRegistered = value;
	    }
	    
		public LacSearchMarker(Search_Log__c searchLog) {
	        this.searchLog = searchLog;
	        this.setLatitude(String.valueOf(searchLog.Submission_Latitude__c));
	        this.setLongitude(String.valueOf(searchLog.Submission_Longitude__c));
	        this.setDefaultColour('00FF00'); // Green
	    }
	    
	    public override String getMarkerInfoContentString() {
	    	String profile = 'Type: Search Query <br/>';
	    	profile += 'Date: ' + this.searchLog.Handset_Submit_Time__c + ' <br/>';
	    	profile += 'Interviewer: ' + this.searchLog.Interviewer__r.First_Name__c + ' ' + this.searchLog.Interviewer__r.Last_Name__c + '<br/>';
	    	profile += 'Interviewee: ' + this.searchLog.Interviewee__r.First_Name__c + ' ' + this.searchLog.Interviewee__r.Last_Name__c + '<br/>';
	    	profile += 'Query: ' + this.searchLog.Query__c + '<br/>';
	    	
	    	PageReference ref = new PageReference('/'+this.searchLog.Id);
	    	profile += '<a href=\'' + ref.getUrl() + '\'>Go to Details</a>';
	    	return profile;
	    }
	    
	    public override String getLocation() {
	    	return '';
	    }
	}
}