src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region</description>
        <inlineHelpText>Region</inlineHelpText>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Western Uganda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Western Uganda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Uganda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Western Uganda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Eastern Uganda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lake Victoria Basin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eastern Uganda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Uganda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mbugo_CKW__c.object
<CustomObject>
    <description>Mbugo CKW</description>
    <fields>
        <fullName>Mbugo_Field_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mbugo Field Officer</label>
        <referenceTo>Mbugo_Field_Officer__c</referenceTo>
        <relationshipLabel>Mbugo CKWs</relationshipLabel>
        <relationshipName>Mbugo_CKWs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Mbugo CKWs</relationshipLabel>
        <relationshipName>Mbugo_CKWs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mbugo CKW</label>
    <nameField>
        <label>Mbugo CKW Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mbugo CKWs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mbugo_Field_Officer__c.object
<CustomObject>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Mbugo Field Officers</relationshipLabel>
        <relationshipName>Mbugo_Field_Officers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mbugo Field Officer</label>
    <nameField>
        <label>Mbugo Field Officer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mbugo Field Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Organisation_District_Association__c.object
<CustomObject>
    <description>Link a partner to a district that they are working in.</description>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Organisation District Associations</relationshipLabel>
        <relationshipName>Organisation_District_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Organisation District Associations</relationshipLabel>
        <relationshipName>Organisation_District_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Organisation District Association</label>
    <nameField>
        <label>Organisation District Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisation District Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physical handset assigned to this Person (in the case of GF-managed assets)</description>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Assignee</relationshipLabel>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The region that the person is in. Not required if the person has a district set</description>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person_Group_Association__c.object
<CustomObject>
    <description>Junction object used for many-to-many relationship between Person and Group objects. The existence of a Person-Group Association is what defines a single &quot;membership&quot;.</description>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group associated with this junction object</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person-Group Association</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Person Group Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person-Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>A region in a given country</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The display name of the region</description>
        <label>Display Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <displayFormat>REG-{000000000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission_Answer__c.object
<CustomObject>
    <description>Object to hold one answer to a survey</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Select1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repeat</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission Answer</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Submission Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MbugoDashboardTests.cls
@isTest
public with sharing class MbugoDashboardTests {
	public MbugoDashboardTests() {
	
	
	}

	static testMethod void testController()
    {
        
        
        District__c testDistrict = new District__c();
        testDistrict.Name = 'TestMasaka';
        testDistrict.Region__c = 'Central';
        insert testDistrict;

        Subcounty__c testSubcounty = new Subcounty__c();
        testSubcounty.Display_Name__c = 'TestLukaya-TC';
        testSubcounty.District__c = testDistrict.Id;
        insert testSubcounty;      

       


        


        Phone__c testHandset = new Phone__c();
        testHandset.IMEI__c = '123456789101112';
        testHandset.Serial_Number__c = '123456789101112';
        testHandset.Purchase_Value_USD__c = 100.00;
        insert testHandset;


        Person__c testPerson = new Person__c();
        testPerson.First_Name__c = 'John';
        testPerson.Last_Name__c = 'Lu' ;
        testPerson.Gender__c = 'Male';
        testPerson.District__c = testDistrict.Id;
        //testPerson.Handset__c = testHandset.Id;
        testPerson.Type__c = 'CKW';
        testPerson.Handset__c = testHandset.Id;
        insert testPerson;

        


        CKW__c testCkw = new CKW__c();
        testCkw.Person__c = testPerson.Id;
        insert(testCkw);




        Person__c testFOPerson = new Person__c();
        testFOPerson.First_Name__c = 'John FO';
        testFOPerson.Last_Name__c = 'Lu FO' ;
        testFOPerson.Gender__c = 'Male';
        testFOPerson.District__c = testDistrict.Id;
        //testPerson.Handset__c = testHandset.Id;
        testFOPerson.Type__c = 'CKW';
        insert testFOPerson;


        //Create FO
        Mbugo_Field_Officer__c mbugoFO = new Mbugo_Field_Officer__c();
        mbugoFO.Person__c = testFOPerson.Id;
        insert(mbugoFO);

        Mbugo_CKW__c mbugoCkw = new Mbugo_CKW__c();
        mbugoCkw.Mbugo_Field_Officer__c = mbugoFO.Id;
        mbugoCkw.Person__c = testPerson.Id;        
        insert(mbugoCkw);




        Group__c testGroup = new Group__c();
        testGroup.Name = 'Mbugo CKWs';
        insert(testGroup);

        Person_Group_Association__c testPersonGroupAssociation = new Person_Group_Association__c();
        testPersonGroupAssociation.Group__c = testGroup.Id;
        testPersonGroupAssociation.Person__c = testPerson.Id;
        insert(testPersonGroupAssociation);




         

        PageReference resultPage =  new PageReference('/a00/e');
        resultPage.getParameters().put('district', String.valueOf(testDistrict.Id));
        resultPage.getParameters().put('subcounty', String.valueOf(testSubcounty.Id));
        resultPage.getParameters().put('dateFrom', '1987-12-18');
        resultPage.getParameters().put('dateTo', '2013-12-18');
        resultPage.getParameters().put('cbt', String.valueOf(testPerson.Id));
        resultPage.getParameters().put('sfdc.tabName', 'a00');


        Account testOrg = new Account();
        testOrg.Name = MbugoHelpers.ORG_NAME;
        testOrg.BillingState = 'CA';
        insert testOrg;

        Organisation_District_Association__c orgAssocTest = new Organisation_District_Association__c();
        orgAssocTest.District__c = testDistrict.Id;
         orgAssocTest.Organisation__c = testOrg.Id;
        insert(orgAssocTest);
        



        MbugoDashboardController controller = new MbugoDashboardController();
        //controller.setOrgName(testOrg.Name);
        controller.setUp(resultPage);
        controller.setIsUpdateable('true');


        //Create test surveys
        Survey__c acesurvey = new Survey__c();
        acesurvey.Post_Processing_Method__c = 'MBUGO';
        acesurvey.Survey_Name__c = 'Mbugo ACE';
        acesurvey.Survey_Status__c = 'Published';
        acesurvey.Start_Date__c = Date.valueOf(date.today().year() + '-01-01');
        acesurvey.End_Date__c = Date.valueOf((date.today().year() + 4) + '-01-01');
        insert acesurvey;


        //Create test surveys
        Survey__c vslasurvey = new Survey__c();
        vslasurvey.Post_Processing_Method__c = 'MBUGO';
        vslasurvey.Survey_Name__c = 'Mbugo VSLA';
        vslasurvey.Survey_Status__c = 'Published';
        vslasurvey.Start_Date__c = Date.valueOf(date.today().year() + '-01-01');
        vslasurvey.End_Date__c = Date.valueOf((date.today().year() + 4) + '-01-01');
        insert vslasurvey;


        Map<String, Submission_Answer__c> answers = new Map<String, Submission_Answer__c>();
        List<String> returnValues = new List<String>();
        

        
        Test.startTest();
        
        List<MetricDataWrapper> wrappers = controller.getFarmersReachedData();
        System.assert(wrappers != null);

        wrappers = controller.getFarmerGroupsData();
        System.assert(wrappers.size() == 4);

        wrappers = controller.getCooperativeGroupsData();
        System.assert(wrappers.size() == 2);
		System.assert(controller.getDistrictList() != null);

		System.assert(controller.getCkwPerfomanceData() != null);
		System.assert(controller.getIsUpdateable().equals('true'));
		System.assert(controller.getSubcountiesList() != null);
        System.assert(controller.changeFilters() != null);

        System.assert(MbugoHelpers.getCKWMapMarkers().size() == 1);
        System.assert(MbugoHelpers.getFOMapMarkers().size() == 1);


        //Test survey post processing
        ProcessSurveySubmission.SurveySubmission submission = new ProcessSurveySubmission.SurveySubmission();
        submission.handsetSubmitTime = Datetime.now().getTime().format().replace(',', '');
        submission.submissionStartTime = Datetime.now().addMinutes(30).getTime().format().replace(',', '');
        submission.imei = testHandset.IMEI__c;
        submission.resultHash = '1';
        submission.surveyId = [select Id, Name from Survey__c where Id = :acesurvey.Id].Name;
        answers.put('q12_0', Utils.createTestSubmissionAnswer(null, 'q12', '3 4', null, null, null));

        returnValues = MbugoHelpers.surveysPostProcessing(submission, answers, testPerson);
        System.assert(returnValues.get(0).equals('1'));
        System.assert(returnValues.get(1).contains('success'));
        System.assert(MbugoHelpers.getMetricData(MbugoHelpers.NUMBER_OF_COOPERATIVES_REGISTERED).Manual_Value__c == 1);
        System.assert(MbugoHelpers.getMetricData(MbugoHelpers.PERCENTAGE_OF_FARMERS_PURCHASING_INPUTS_FROM_MBUGO_ACE).Manual_Value__c == 1);



        submission = new ProcessSurveySubmission.SurveySubmission();
        submission.handsetSubmitTime = Datetime.now().getTime().format().replace(',', '');
        submission.submissionStartTime = Datetime.now().addMinutes(30).getTime().format().replace(',', '');
        submission.imei = testHandset.IMEI__c;
        submission.resultHash = '1';
        submission.surveyId = [select Id, Name from Survey__c where Id = :vslasurvey.Id].Name;
        answers.put('q24_0', Utils.createTestSubmissionAnswer(null, 'q24', '90', null, null, null));
        answers.put('q22_0', Utils.createTestSubmissionAnswer(null, 'q22', '40', null, null, null));
        answers.put('q23_0', Utils.createTestSubmissionAnswer(null, 'q23', '50', null, null, null));

        returnValues = MbugoHelpers.surveysPostProcessing(submission, answers, testPerson);
        System.assert(returnValues.get(0).equals('1'));
        System.assert(returnValues.get(1).contains('success'));
        System.assert(MbugoHelpers.getMetricData(MbugoHelpers.NUMBER_OF_VSLAS_REGISTERED).Manual_Value__c == 1);
        System.assert(MbugoHelpers.getMetricData(MbugoHelpers.TOTAL_NUMBER_OF_FARMERS_IN_VSLAS).Manual_Value__c == 90);
        System.assert(MbugoHelpers.getMetricData(MbugoHelpers.TOTAL_NUMBER_OF_MALE_FARMERS_IN_VSLAS).Manual_Value__c == 40);
        System.assert(MbugoHelpers.getMetricData(MbugoHelpers.TOTAL_NUMBER_OF_FEMALE_FARMERS_IN_VSLAS).Manual_Value__c == 50);
        
        Test.stopTest();


    }



}