src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Current_Performance_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CKW&apos;s current performance review. Used to generate the message that appears in Pulse&apos;s performance tab.</description>
        <label>Current Performance</label>
        <referenceTo>CKW_Performance_Review__c</referenceTo>
        <relationshipLabel>CKWs</relationshipLabel>
        <relationshipName>CKWs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Poverty_Status__c</fullName>
        <description>CKW Poverty Status</description>
        <label>Poverty Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Poor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Poor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Previous_Performance_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A link to last month&apos;s performance review. This is used to generate the payment message that appears in Pulse for the first few days of the month.</description>
        <label>Previous Month&apos;s Performance</label>
        <referenceTo>CKW_Performance_Review__c</referenceTo>
        <relationshipLabel>CKW (Previous Month&apos;s Performance)</relationshipLabel>
        <relationshipName>CKW_Previous_Month</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of CKW</description>
        <label>CKW Status</label>
        <picklist>
            <picklistValues>
                <fullName>Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CKW_Performance_Review__c.object
<CustomObject>
    <description>Summary of performance of each CKW in a given week or month, per different targets</description>
    <fields>
        <fullName>Monthly_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The monthly target object associated with this performance review</description>
        <label>Monthly Target</label>
        <referenceTo>Monthly_Target__c</referenceTo>
        <relationshipName>CKW_Performance_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Performance_Level__c</fullName>
        <formula>CASE( Performance_Pay__c , Incentive_Structure__r.Level_A_Compensation__c, &apos;A&apos;, Incentive_Structure__r.Level_B_Compensation__c, &apos;B&apos;,Incentive_Structure__r.Level_C_Compensation__c, &apos;C&apos;, &apos;D&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Performance Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Searches__c</fullName>
        <formula>Number_of_6001_Queries__c  +  Number_Of_Searches__c +  Number_Of_Searches_Running_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Searches::Total Valid</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Surveys__c</fullName>
        <formula>Surveys_Not_Reviewed__c + Surveys_Pending__c + Surveys_Approved__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Surveys::Total Valid</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CKW Monthly Performance</label>
    <nameField>
        <displayFormat>PR-{YY}-{MM}-{000000}</displayFormat>
        <label>CKW Monthly Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKW Monthly Performance Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Monthly_Target__c.object
<CustomObject>
    <description>This object contains the monthly search and survey targets. It is global for all CKWs. The Start Date field indicates when these targets go into effect. Payment calculations are expected to use the Monthly Target object with the newest Start Date.</description>
    <label>Monthly Target</label>
    <nameField>
        <label>Monthly Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>GPS_Location_E__c</fullName>
        <description>GPS Location E. Must be in Decimal format</description>
        <label>GPS Location E</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_N__c</fullName>
        <description>GPS Location N. Must be in Decimal forma</description>
        <label>GPS Location N</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parish__c</fullName>
        <description>Parish</description>
        <label>Parish</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Village__c</fullName>
        <description>Village that the person lives in</description>
        <label>Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CkwMapMarker.cls
/**
 *  Class to represent a map marker that contains details about a CKW
 */

public with sharing class CkwMapMarker extends MapMarkers {

    private CKW__c ckw;

    public CkwMapMarker(CKW__c ckw) {
        this.ckw = ckw;
        this.setLatitude(ckw.Person__r.GPS_Location_E__c);
        this.setLongitude(ckw.Person__r.GPS_Location_N__c);
        this.setMarkerTitle(ckw.Name);
        setDefaultColour('Red');
    }

    // Generate the content string for a CKW
    public override String getMarkerInfoContentString() {

        String content = '<div>' +
            this.ckw.Name + '<br />' +
            getGender(this.ckw.Person__r.Gender__c) + '<br />' +
            getLocation() +
            getPerformanceLevel() +
            getThisMonthsPerformance() +
            getProjectString();

        // This needs to be changed to add links to the ectra details for the CKW
        // Will implement when this feature is required
        if (getShowMoreDetails()) {
        }
        return content;
    }

    // Create the location string
    public override String getLocation() {

        String location = '';
        if (this.ckw.Person__r.Parish__c != null) {
            location = 'Parish: ' + this.ckw.Person__r.Parish__c + '<br />';
        }
        if (this.ckw.Person__r.Village__c != null) {
            location = location + 'Village: ' + this.ckw.Person__r.Village__c + '<br />';
        }
        return location;
    }

    // Create the Performance level string for last month
    private String getPerformanceLevel() {

        String performance = 'Last months performance level is unavailable';
        if (ckw.Previous_Performance_Review__c != null) {
            performance = 'Last months performance level was: ' + ckw.Previous_Performance_Review__r.Performance_Level__c;
        }
        return performance;
    }

    // Create the performance level string for this month
    private String getThisMonthsPerformance() {

        String thisMonthPerformance = 'No performance record for this month<br />';
        if (ckw.Current_Performance_Review__c != null) {
            thisMonthPerformance = 'This months search target is: ' + ckw.Current_Performance_Review__r.Monthly_Target__r.Search_Target__c + '<br />' +
                'Searches performed this month: ' + ckw.Current_Performance_Review__r.Total_Searches__c + '<br />' +
                'This months surveys target is: ' + ckw.Current_Performance_Review__r.Monthly_Target__r.Survey_Target__c + '<br />' +
                'Surveys carried out this month: '+ ckw.Current_Performance_Review__r.Total_Surveys__c + '<br />';
        }
        return thisMonthPerformance;
    }

    /**
     *  Generate the marker name for this map marker
     *  This will also set the colour of the marker if the splitter is of a certain value
     *
     *  @param splitter - The field used to split the markers into different colours
     */
    public override void generateMarkerName(String splitter) {

        String fieldValue = '';
        setColour(getDefaultColour());

        // Set the colours for a gender split
        if (splitter.equals('Gender')) {
            fieldValue = this.ckw.Person__r.Gender__c;
            setColour('Pink');
            if (fieldValue == null) {
                setColour('Black');
                fieldValue = 'Missing';
            }
            else if (fieldValue.equals('Male')) {
                setColour('Blue');
            }
        }

        // Set the colours for a status split
        else if (splitter.equals('Status')) {
            fieldValue = this.ckw.Status__c;
            setColour('Yellow');
            if (fieldValue == null) {
                setColour('Black');
                fieldValue = 'Missing';
            }
            else if (fieldValue.equals('Active')) {
                setColour('White');
            }
            else {
                fieldValue = 'Inactive';
            }
        }

        // Set the colours for a poverty level split
        else if (splitter.equals('Poverty')) {
            fieldValue = this.ckw.Poverty_Status__c;
            setColour('Green');
            if (fieldValue == null) {
                setColour('Black');
                fieldValue = 'Missing';
            }
            else if (fieldValue.equals('Not Poor')) {
                setColour('Yellow');
                fieldValue = 'Poor';
            }
            else {
                fieldValue = 'Very Poor';
            }
        }
        setMarkerName(joinMarkerName('CKW', getColour(), fieldValue));
    }

    static testMethod void testMarker() {

        CKW__c ckw = Utils.createTestCkw(null, 'Y', true, null, 'Female');
        Database.insert(ckw);
        CkwMapMarker marker = new CkwMapMarker(ckw);
        marker.getMarkerInfoContentString();
        marker.generateMarkerName('Gender');
        marker.generateMarkerName('Poverty');
        marker.generateMarkerName('Status');
    }
}