src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>We have a gender field here because the options in LAC surveys are in Spanish and IBT doesn&apos;t yet (v 2.22 and earlier) support different labels and values for options</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_E__c</fullName>
        <description>GPS Location E. Must be in Decimal format</description>
        <label>GPS Location E</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_N__c</fullName>
        <description>GPS Location N. Must be in Decimal forma</description>
        <label>GPS Location N</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LacMapMarkerSources.cls
// This class is a namespace for all the Classes that will generate lists of MapMarkers for the different Lac Map Parameters
public with sharing class LacMapMarkerSources {
  
  // Returns a list of Lac Farmer Map Markers
  public with sharing class Farmers implements MapComponentController.IMapMarkerSource {
    public List<MapMarkers> loadMapMarkers(Map <String, String> parameters) {
      String query = 'SELECT Id, ' +
              'Person__r.GPS_Location_E__c,' + 
              'Person__r.GPS_Location_N__c, ' +
              'Person__r.First_Name__c, ' +
              'Person__r.Last_Name__c, ' +
              'Person__r.Gender__c ' +
              'from Lac_Farmer_Details__c';
      
      List<String> queryWhereClause = new List<String>();
      if(parameters.containsKey('quarter')) {
        String quarter = parameters.get('quarter');
        Date quarterLastDay = MetricHelpers.getQuarterLastDay(quarter);
        queryWhereClause.add('(createdDate <=: quarterLastDay)');
      }
      
      if(queryWhereClause.size() > 0) {
        query += ' WHERE ' + String.join(queryWhereClause, ' AND ');
      }
      
      // Prevent over 50,000
      query += ' LIMIT 50000';
      
      Lac_Farmer_Details__c[] farmers = Database.query(query);
      
      List<MapMarkers> mapMarkers = new List<MapMarkers>();
      for (Lac_Farmer_Details__c farmer : farmers) {
          mapMarkers.add(new LacMapMarkers.LacFarmerMarker(farmer));
      }
        return mapMarkers;  
    }
  }
  
  // Return a list of Lac Ckw Map Markers
  public with sharing class CKWs implements MapComponentController.IMapMarkerSource {
    public List<MapMarkers> loadMapMarkers(Map <String, String> parameters) {
      
      String query = 'SELECT Id, ' +
              'Person__r.GPS_Location_E__c,' + 
              'Person__r.GPS_Location_N__c, ' +
              'Person__r.First_Name__c, ' +
              'Person__r.Last_Name__c, ' +
              'Person__r.Gender__c ' +
              'from CKW__c';
      
      List<String> queryWhereClause = new List<String>();
      queryWhereClause.add(' Person__r.Country__r.Name = \'Colombia\'');
      
      if(parameters.containsKey('quarter')) {
        String quarter = parameters.get('quarter');
        Date quarterLastDay = MetricHelpers.getQuarterLastDay(quarter);
        queryWhereClause.add('(createdDate <=: quarterLastDay)');
      }
      
      if(queryWhereClause.size() > 0) {
        query += ' WHERE ' + String.join(queryWhereClause, ' AND ');
      }
      
      // Prevent over 50,000
      query += ' LIMIT 50000';
      
      CKW__c[] ckws = Database.query(query);
      
      List<MapMarkers> mapMarkers = new List<MapMarkers>();
      for (CKW__c ckw : ckws) {
          mapMarkers.add(new LacMapMarkers.LacCkwMarker(ckw));
      }
        return mapMarkers;  
    }
  }
  
  // Return a list of Lac Ckw Map Markers
  public with sharing class AllPeople implements MapComponentController.IMapMarkerSource {
    public List<MapMarkers> loadMapMarkers(Map <String, String> parameters) {
      List<MapMarkers> mapMarkers = new List<MapMarkers>();
      
      LacMapMarkerSources.Farmers farmers = new LacMapMarkerSources.Farmers();
      mapMarkers.addAll(farmers.loadMapMarkers(parameters));
    
      LacMapMarkerSources.CKWs ckws = new LacMapMarkerSources.CKWs();
      mapMarkers.addAll(ckws.loadMapMarkers(parameters));
      
        return mapMarkers;  
    }
  }
  
  static TestMethod void testAll() {
    LacMapMarkerSources.Farmers farmers = new LacMapMarkerSources.Farmers();
    farmers.loadMapMarkers(new Map<String, String>());
    
    LacMapMarkerSources.CKWs ckws = new LacMapMarkerSources.CKWs();
    ckws.loadMapMarkers(new Map<String, String>());
    
    LacMapMarkerSources.AllPeople allPeople = new LacMapMarkerSources.AllPeople();
    allPeople.loadMapMarkers(new Map<String, String>());
  }
}