src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Registered_By__c</fullName>
        <label>Registered By</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers Registered</relationshipLabel>
        <relationshipName>Farmers_Registered</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Construct that represents a group of People. Used by features including Agriculture Information channel, survey assignment, bulk SMS.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>District__c</fullName>
        <description>The district that this metric is for. Allows us to split the metrics by district when showing them on the dashboard</description>
        <inlineHelpText>Select the district that this metric is for</inlineHelpText>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>The person that this metric data belongs to</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Mbugo_CKW__c.object
<CustomObject>
    <description>Mbugo CKW</description>
    <fields>
        <fullName>Mbugo_Field_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mbugo Field Officer</label>
        <referenceTo>Mbugo_Field_Officer__c</referenceTo>
        <relationshipLabel>Mbugo CKWs</relationshipLabel>
        <relationshipName>Mbugo_CKWs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Mbugo CKWs</relationshipLabel>
        <relationshipName>Mbugo_CKWs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mbugo CKW</label>
    <nameField>
        <label>Mbugo CKW Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mbugo CKWs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mbugo_Field_Officer__c.object
<CustomObject>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Mbugo Field Officers</relationshipLabel>
        <relationshipName>Mbugo_Field_Officers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Mbugo Field Officer</label>
    <nameField>
        <label>Mbugo Field Officer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mbugo Field Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Organisation_District_Association__c.object
<CustomObject>
    <description>Link a partner to a district that they are working in.</description>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Organisation District Associations</relationshipLabel>
        <relationshipName>Organisation_District_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Organisation District Associations</relationshipLabel>
        <relationshipName>Organisation_District_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Organisation District Association</label>
    <nameField>
        <label>Organisation District Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisation District Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_E__c</fullName>
        <description>GPS Location E. Must be in Decimal format</description>
        <label>GPS Location E</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_N__c</fullName>
        <description>GPS Location N. Must be in Decimal forma</description>
        <label>GPS Location N</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person_Group_Association__c.object
<CustomObject>
    <description>Junction object used for many-to-many relationship between Person and Group objects. The existence of a Person-Group Association is what defines a single &quot;membership&quot;.</description>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group associated with this junction object</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person-Group Association</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Person Group Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person-Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MbugoHelpers.cls
public with sharing class MbugoHelpers {

	public static final String ORG_NAME = 'MBUGO';


	public static String getSubcounties(){
        String inclause =
                ' AND '                                             +
                    'District__c IN ('                              +
                        'SELECT '                                   +
                            'District__c '                          +
                        'FROM '                                     +
                            'Organisation_District_Association__c ' +
                        'WHERE '                                    +
                            'Organisation__r.Name = \'MBUGO\''       +
                    ') ';
        return 'SELECT Id, '                    +
                    'Display_Name__c, '         +
                    'District__c '              +
                'FROM Subcounty__c '            +
                'WHERE District__c != NULL '    +
                '   AND  District__c != \'\' '  +
                    inclause                    +
                'ORDER BY Display_Name__c ';
    }





    public static List<MetricDataWrapper> getFarmersReachedData()
    {
        List<MetricDataWrapper> farmersReachedData = new List<MetricDataWrapper>();

        M_E_Metric_Data__c metricData;
       
        
        Person_Group_Association__c[] associations = Database.query('select id, Person__c, Group__c, Person__r.GPS_Location_E__c, Person__r.GPS_Location_N__c  from Person_Group_Association__c where Group__r.Name=\'Mbugo CKWs\' and Person__r.Type__c=\'CKW\'');

        List<String> personIds = new List<String>();
        for(Person_Group_Association__c p : associations) {
            personIds.add(p.Person__r.Id);
        }

        //These are the ckw person ids

    List<Farmer__c> farmersRegisteredByMbugoCkws = [select Registered_by__C, Person__r.id, Person__r.Gender__c, Person__r.First_Name__c, Person__r.Last_Name__c from Farmer__c where Registered_by__C in :personIds and Person__r.First_Name__c<>'Not Registered'  limit 10000];

    MetricDataWrapper farmersReachedMetricWrapper = new MetricDataWrapper();
    farmersReachedMetricWrapper.setLabel('Total Farmers Reached');
    farmersReachedMetricWrapper.setCurrentRealValue(0);


    MetricDataWrapper maleFarmersReachedMetricWrapper = new MetricDataWrapper();
    maleFarmersReachedMetricWrapper.setLabel('Total Male Farmers Reached');
    maleFarmersReachedMetricWrapper.setCurrentRealValue(0);


    MetricDataWrapper femaleFarmersReachedMetricWrapper = new MetricDataWrapper();
    femaleFarmersReachedMetricWrapper.setLabel('Total Female Farmers Reached');
    femaleFarmersReachedMetricWrapper.setCurrentRealValue(0);

    Decimal totalFarmerCount = 0;
    Decimal totalMaleFarmerCount = 0;
    Decimal totalFemaleFarmerCount = 0;

    for(Farmer__c farmer : farmersRegisteredByMbugoCkws)
    {
        totalFarmerCount += 1;

        if('male'.equalsIgnoreCase(farmer.Person__r.Gender__c))
        {
            totalMaleFarmerCount += 1;
        }
        else {
            totalFemaleFarmerCount += 1;
        }
    }

    farmersReachedMetricWrapper.setCurrentRealValue(totalFarmerCount);
    maleFarmersReachedMetricWrapper.setCurrentRealValue(totalMaleFarmerCount);
    femaleFarmersReachedMetricWrapper.setCurrentRealValue(totalFemaleFarmerCount);

    List<MetricDataWrapper> wrapper = new List<MetricDataWrapper> {farmersReachedMetricWrapper, maleFarmersReachedMetricWrapper, femaleFarmersReachedMetricWrapper};
    
    return wrapper;
    }



    public static MetricMapWrapper[] getFOMapMarkers()
    {
    	//Field officers
    	Map<String, MetricMapWrapper> markers = new Map<String, MetricMapWrapper>();
            Mbugo_Field_Officer__c[] fieldOfficers = [SELECT Person__r.Id, Person__r.GPS_Location_E__c, Person__r.GPS_Location_N__c, Person__r.First_Name__c, Person__r.Last_Name__c from Mbugo_Field_Officer__C];
            for (Mbugo_Field_Officer__c fo : fieldOfficers) {

                MetricMapWrapper marker = null;
                marker = new MetricMapWrapper('CKW', '00FF11', fo.Person__r.Id, true);
                marker.gpsLatitude = fo.Person__r.GPS_Location_N__c;
                marker.gpsLongitude = fo.Person__r.GPS_Location_E__c;
                
                
                String profile = '<div width="304px" height="500px" scrolling="no" seamless="seamless" style="overflow:hidden">Field Officer Name: '+fo.Person__r.First_Name__c+' '+fo.Person__r.Last_Name__c+'<br/>';
                    //Show CKWs under this field officer
                    Mbugo_CKW__c[] mbugoCkws = [SELECT Person__r.First_Name__c, Person__r.Last_Name__c from Mbugo_CKW__c where Mbugo_Field_Officer__r.Person__r.Id =:fo.Person__r.Id];
                    if(mbugoCkws.size() == 0) {
                        profile += 'Field officer has no CKWs attached';
                    }
                    else {
                        profile += '<hr><b>Ckws attached to FO</b><br/>';
                        for (Mbugo_CKW__c gckw : mbugoCkws) {
                            profile += gckw.Person__r.First_Name__c + ' '+ gckw.Person__r.Last_Name__c +'<br/>';

                        }
                    }
                    profile += '</div>';
                
                marker.addName(profile);
                marker.markerTitle = fo.Person__r.First_Name__c+' '+fo.Person__r.Last_Name__c;
                markers.put(fo.Person__r.Id, marker);
            }

            return markers.values();
    }



    public static MetricMapWrapper[] getCKWMapMarkers()
    {
      Map<String, MetricMapWrapper> markers = new Map<String, MetricMapWrapper>();
      Person_Group_Association__c[] associations = Database.query('select id, Person__c, Group__c,  Person__r.GPS_Location_E__c, Person__r.GPS_Location_N__c  from Person_Group_Association__c where Group__r.Name=\'Mbugo Ckws\' and Person__r.Type__c=\'CKW\'');
        List<String> personIds = new List<String>();
        for(Person_Group_Association__c assoc : associations) {
            personIds.add(assoc.Person__r.Id);
        }

        
        CKW__c[] ckws = [SELECT id, Name, Person__r.First_Name__c, Person__r.Last_Name__c, Person__r.GPS_Location_E__c, Person__r.GPS_Location_N__c from CKW__c where Person__r.Id in :personIds];
            for (CKW__c ckw : ckws) {
                MetricMapWrapper marker = null;
                marker = new MetricMapWrapper('CKW', '0000FF', ckw.Id, true);
                marker.gpsLatitude = ckw.Person__r.GPS_Location_N__c;
                marker.gpsLongitude = ckw.Person__r.GPS_Location_E__c;
                
                PageReference ref = new PageReference('/apex/CkwDetailMini?id='+ckw.Id);
                String content = '<iframe src="'+ ref.getUrl()+'" frameBorder="0" width="304px" height="500px" scrolling="no" seamless="seamless" style="overflow:hidden"></iframe>';

                
                marker.addName(content);
                marker.markerTitle = ckw.Person__r.First_Name__c+' '+ckw.Person__r.Last_Name__c;
                markers.put(ckw.Id, marker);

            }


            
            System.debug(markers.size()+' map markers found'); 
            return markers.values();
    }

}