src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Current_Performance_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CKW&apos;s current performance review. Used to generate the message that appears in Pulse&apos;s performance tab.</description>
        <label>Current Performance</label>
        <referenceTo>CKW_Performance_Review__c</referenceTo>
        <relationshipLabel>CKWs</relationshipLabel>
        <relationshipName>CKWs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of CKW</description>
        <label>CKW Status</label>
        <picklist>
            <picklistValues>
                <fullName>Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CKW_Performance_Review__c.object
<CustomObject>
    <description>Summary of performance of each CKW in a given week or month, per different targets</description>
    <fields>
        <fullName>Number_Of_Searches_Running_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Stores the searches that have been recorded in the search log. This is updated every day and the searches for that day are added to the existing one</description>
        <label>Searches::New System (Updated Daily)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The month to be monitored</description>
        <inlineHelpText>Select First day of the month/year you want to monitor</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Surveys_Submitted__c</fullName>
        <formula>Surveys_Approved__c  + Surveys_Rejected__c + Surveys_Pending__c + Surveys_Not_Reviewed__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Surveys::Submitted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CKW Monthly Performance</label>
    <nameField>
        <displayFormat>PR-{YY}-{MM}-{000000}</displayFormat>
        <label>CKW Monthly Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKW Monthly Performance Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ActivePerformingCkwCalculator.cls
public class ActivePerformingCkwCalculator {

	public List<PieWedgeData> getPieData() {

		List<PieWedgeData> data = new List<PieWedgeData>();
		List<CKW__c> currentPerformances = [Select Id, 
														Current_Performance_Review__c,
														Current_Performance_Review__r.Number_Of_Searches_Running_Total__c,
														Current_Performance_Review__r.Total_Surveys_Submitted__c 
														from CKW__c where Status__c = 'Active' 
														and 
														Current_Performance_Review__r.Start_Date__c = THIS_MONTH];
		Integer count = 0;
		for (CKW__c ckw : currentPerformances) {
			if (ckw.Current_Performance_Review__r.Number_Of_Searches_Running_Total__c >= 5
				 && ckw.Current_Performance_Review__r.Total_Surveys_Submitted__c >= 1) {
				count ++;
			}
		}
		data.add(new PieWedgeData('Active CKWs', count));
		data.add(new PieWedgeData('Inactive CKWs', currentPerformances.size() - count));
		return data;
	}
	public class PieWedgeData {  
        public String name { get; set; }  
        public Integer data { get; set; }  
        
        public PieWedgeData(String name, Integer data) {  
            this.name = name;  
            this.data = data;  
        }  
    }
}