src/objects/CKW__c.object
<CustomObject>
    <description>Profile of CKWs</description>
    <fields>
        <fullName>Active_Date__c</fullName>
        <description>The date that the ckw passed their training</description>
        <label>Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>CKW Details</relationshipLabel>
        <relationshipName>CKW_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of CKW</description>
        <label>CKW Status</label>
        <picklist>
            <picklistValues>
                <fullName>Hired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dropped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CKW</label>
    <nameField>
        <displayFormat>CKW-{YY}-{000000}</displayFormat>
        <label>CKW ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKWs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CKW_Performance_Review__c.object
<CustomObject>
    <description>Summary of performance of each CKW in a given week or month, per different targets</description>
    <fields>
        <fullName>Incentive_Structure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The incentive structure that is active for this performance review.</description>
        <label>Incentive Structure</label>
        <referenceTo>Incentive_Structure__c</referenceTo>
        <relationshipName>CKW_Performance_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monthly_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The monthly target object associated with this performance review</description>
        <label>Monthly Target</label>
        <referenceTo>Monthly_Target__c</referenceTo>
        <relationshipName>CKW_Performance_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The month to be monitored</description>
        <inlineHelpText>Select First day of the month/year you want to monitor</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CKW Monthly Performance</label>
    <nameField>
        <displayFormat>PR-{YY}-{MM}-{000000}</displayFormat>
        <label>CKW Monthly Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CKW Monthly Performance Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Incentive_Structure__c.object
<CustomObject>
    <description>Incentive Structure contains several constants that specify the current CKW payment scheme. The Start Date field indicates when this version of the incentive structure goes into effect. Formulas that calculate CKW payments are expected to look up the newest version of the Incentive Structure for their calculations.</description>
    <fields>
        <fullName>Airtime_Compensation__c</fullName>
        <description>The standard amount that all CKWs are compensated for airtime</description>
        <label>Airtime Compensation</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_A_Compensation__c</fullName>
        <description>The compensation awarded for Level A performance</description>
        <label>Level A Compensation</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_A_Threshold__c</fullName>
        <description>The percentage of target that must be reached to qualify for Level A compensation</description>
        <label>Level A Threshold</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Level_B_Compensation__c</fullName>
        <description>The compensation awarded for Level B performance</description>
        <label>Level B Compensation</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_B_Threshold__c</fullName>
        <description>The percentage of target that must be reached to qualify for Level B compensation</description>
        <label>Level B Threshold</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Level_C_Compensation__c</fullName>
        <description>The compensation awarded for Level C performance</description>
        <label>Level C Compensation</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level_C_Threshold__c</fullName>
        <description>The percentage of target that must be reached to qualify for Level C compensation</description>
        <label>Level C Threshold</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Level_D_Compensation__c</fullName>
        <description>The compensation awarded for Level D performance</description>
        <label>Level D Compensation</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Long_Term_Airtime_Bonus__c</fullName>
        <description>The amount of airtime that the current incentive scheme awards for long term bonuses (based on six months of performance). If there is no long term airtime bonus this month, then the value should be 0.</description>
        <label>Long Term Airtime Bonus</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that this version of the incentive structure goes into effect. We need this field because we may change the incentive structure over time, and we want to keep track of the historical changes. Our algorithm for calculating payment will always look up the most recent version of the incentive structure.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Incentive Structure</label>
    <nameField>
        <label>Incentive Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentive Structures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date of the quarter to which this metric belongs</description>
        <inlineHelpText>This can simply be any date falling in the quarter to which this metric belongs. We shall calculate the quarter dynamically. It defaults to the current date.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>The person that this metric data belongs to</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Monthly_Target__c.object
<CustomObject>
    <description>This object contains the monthly search and survey targets. It is global for all CKWs. The Start Date field indicates when these targets go into effect. Payment calculations are expected to use the Monthly Target object with the newest Start Date.</description>
    <fields>
        <fullName>Search_Target__c</fullName>
        <description>The number of searches that CKWs are expected to perform this month.</description>
        <label>Search Target</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that these targets go into effect. We need this field because we may change the targets over time, and we want to keep track of the historical changes. Our algorithm for calculating payment will always look up the most recent version of the targets.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Target__c</fullName>
        <description>The number of survey points that CKWs are expected to earn this month.</description>
        <label>Survey Target</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Target</label>
    <nameField>
        <label>Monthly Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Current_Poverty_Scorecard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The most recent poverty scorecard for this person</description>
        <label>Current Poverty Scorecard</label>
        <referenceTo>Poverty_Scorecard__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physical handset assigned to this Person (in the case of GF-managed assets)</description>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Assignee</relationshipLabel>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Poverty_Scorecard__c.object
<CustomObject>
    <description>Poverty scorecard data for a person in our system</description>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>The date/time that the poverty data was created.</description>
        <label>Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>Person with whom this poverty data is associated</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Poverty Scorecards</relationshipLabel>
        <relationshipName>Poverty_Scorecards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Poverty_Percentage__c</fullName>
        <description>Calculate the poverty percentage based on the score</description>
        <formula>CASE( Score__c ,
    0, 97.20,
    1, 97.20,
    2, 97.20,
    3, 97.20,
    4, 97.20,
    5, 95.20,
    6, 95.20,
    7, 95.20,
    8, 95.20,
    9, 95.20,
    10, 93.60,
    11, 93.60,
    12, 93.60,
    13, 93.60,
    14, 93.60,
    15, 80.60,
    16, 80.60,
    17, 80.60,
    18, 80.60,
    19, 80.60,
    20, 76.10,
    21, 76.10,
    22, 76.10,
    23, 76.10,
    24, 76.10,
    25, 71.20,
    26, 71.20,
    27, 71.20,
    28, 71.20,
    29, 71.20,
    30, 62.50,
    31, 62.50,
    32, 62.50,
    33, 62.50,
    34, 62.50,
    35, 47.70,
    36, 47.70,
    37, 47.70,
    38, 47.70,
    39, 47.70,
    40, 44.00,
    41, 44.00,
    42, 44.00,
    43, 44.00,
    44, 44.00,
    45, 38.70,
    46, 38.70,
    47, 38.70,
    48, 38.70,
    49, 38.70,
    50, 27.00,
    51, 27.00,
    52, 27.00,
    53, 27.00,
    54, 27.00,
    55, 26.20,
    56, 26.20,
    57, 26.20,
    58, 26.20,
    59, 26.20,
    60, 13.30,
    61, 13.30,
    62, 13.30,
    63, 13.30,
    64, 13.30,
    65, 8.10,
    66, 8.10,
    67, 8.10,
    68, 8.10,
    69, 8.10,
    70, 6.50,
    71, 6.50,
    72, 6.50,
    73, 6.50,
    74, 6.50,
    75, 3.10,
    76, 3.10,
    77, 3.10,
    78, 3.10,
    79, 3.10,
    80, 2.70,
    81, 2.70,
    82, 2.70,
    83, 2.70,
    84, 2.70,
    85, 1.30,
    86, 1.30,
    87, 1.30,
    88, 1.30,
    89, 1.30,
    90, 0.70,
    91, 0.70,
    92, 0.70,
    93, 0.70,
    94, 0.70,
    0.00)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Poverty Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Poverty Scorecard</label>
    <nameField>
        <displayFormat>PS-{00000000}</displayFormat>
        <label>Poverty Scorecard ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Poverty Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CKWMetrics.cls
global class CKWMetrics implements Database.Batchable<sObject>, Database.Stateful {

    /**
     *  The class implements Database.Stateful as that allows us to remember the global variables accross
     *  each time this class is run as a batch job.
     *  As this class implements Database.Batchable<sObject> all methods and variables must be public as this
     *  is a requirement of batched apex.
     *
     */
    global final String ckwQuery;
    global final List<String> ckwMetricsList;

    global final Date ckwQuarterStartDate;
    global final Date ckwQuarterEndDate;
    global final Date ckwPreviousQuarterStartDate;
    global final Date ckwPreviousQuarterEndDate;
    global final Date ckwPrevious2QuarterStartDate;
    global final Date ckwPrevious2QuarterEndDate;
    global final String ckwQuarterString;

    // Global variables to update the current quarters metrics
    global final Map<String, Decimal> ckwMetricValues;

    // The global variables needed to tidy up the previous quarters data    
    global final Boolean updateLastQuarter;
    global final Map<String, Decimal> ckwPreviousMetricValues;

    // The name of the parter who this run of the batch is for
    global final Account partner;

    global CKWMetrics (
            String query,
            List<String> metricsList,
            Boolean forcePreviousUpdate,
            Account account
    ) {

        ckwQuery = query;
        ckwMetricsList = metricsList;
        partner = account;
        ckwMetricValues = new Map<String, Decimal>();
        for (String metric : metricsList) {
            ckwMetricValues.put(metric, 0.0);
        }

        // We look at the date yesterday as this is run as a scheduled job so we want to look at the previous quarter if we are on the first day of a new quarter
        ckwQuarterString = MetricHelpers.getCurrentQuarterAsString(-1);
        ckwQuarterStartDate = MetricHelpers.getQuarterFirstDay(ckwQuarterString);
        ckwQuarterEndDate = MetricHelpers.getQuarterLastDay(ckwQuarterString);
        ckwPreviousQuarterStartDate = ckwQuarterStartDate.addMonths(-3);
        ckwPreviousQuarterEndDate = ckwQuarterEndDate.addMonths(-3);

        // Decide if we want to clean up the previous quarters data
        Integer gap = ckwQuarterStartDate.daysBetween(Date.today());
        if ((gap > 1 && gap < 15) || forcePreviousUpdate) {
            updateLastQuarter = true;
            ckwPreviousMetricValues = new Map<String, Decimal>();
            for (String metric : metricsList) {
                ckwPreviousMetricValues.put(metric, 0.0);
            }

            // Get the dates for the previous quarter but 1     
            ckwPrevious2QuarterStartDate = ckwQuarterStartDate.addMonths(-6);
            ckwPrevious2QuarterEndDate = ckwQuarterEndDate.addMonths(-6);
        }
        else {
            updateLastQuarter = false;
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(ckwQuery);
    }

    global void execute(Database.BatchableContext BC, List<CKW__c> ckws){

        // Loop through the CWKs and dig out the IDs so we can get the performance records
        List<String> ckwIds = new List<String>();
        List<String> previousCkwIds = new List<String>();
        List<String> personIds = new List<String>();
        List<String> previousPersonIds = new List<String>();
        Map<string, String> variables = new Map<String, String>();
        for (CKW__c ckw : ckws) {
            if (ckw.Status__c != null && ckw.Status__c.equals('Active')) {
                ckwMetricValues.put('total_ckws', ckwMetricValues.get('total_ckws') + 1);
                personIds.add(ckw.Person__c);
            }
            ckwIds.add(ckw.Id);
            if (updateLastQuarter && ckw.Active_Date__c != null && ckwQuarterStartDate.daysBetween(ckw.Active_Date__c) < 0) {
                ckwPreviousMetricValues.put('total_ckws', ckwPreviousMetricValues.get('total_ckws') + 1);
                previousCkwIds.add(ckw.Id);
                previousPersonIds.add(ckw.Person__c);
            }
        }
        if (ckwIds.size() > 0) {
            MetricHelpers.getPerformanceDetails(ckwIds, ckwMetricValues, ckwQuarterStartDate, ckwQuarterEndDate);
            variables.put('persons', MetricHelpers.generateCommaSeperatedString(personIds, true));
            variables.put('gender', 'Female');
            ckwMetricValues.put('percent_woman_ckws', ckwMetricValues.get('percent_woman_ckws')  + SoqlHelpers.getNumberOfPeople(variables, true));
            ckwMetricValues.put('percent_poor_ckws', ckwMetricValues.get('percent_poor_ckws') + SoqlHelpers.getSumOfPeople('Current_Poverty_Scorecard__r.Poverty_Percentage__c', variables, true));
        }
        if (updateLastQuarter && previousCkwIds.size() > 0) {
            MetricHelpers.getPerformanceDetails(previousCkwIds, ckwPreviousMetricValues, ckwPreviousQuarterStartDate, ckwPreviousQuarterEndDate);
            variables.put('persons', MetricHelpers.generateCommaSeperatedString(previousPersonIds, true));
            variables.put('gender', 'Female');
            ckwPreviousMetricValues.put('percent_woman_ckws', ckwPreviousMetricValues.get('percent_woman_ckws')  + SoqlHelpers.getNumberOfPeople(variables, true));
            ckwPreviousMetricValues.put('percent_poor_ckws', ckwPreviousMetricValues.get('percent_poor_ckws') + SoqlHelpers.getSumOfPeople('Current_Poverty_Scorecard__r.Poverty_Percentage__c', variables, true));
        }
    }

    global void finish(Database.BatchableContext BC) {

        if (ckwMetricValues.get('total_ckws') == 0.0) {
            return;
        }

        // List of cumulative metrics that require us to look at last quarter to get the results
        List<String> previousMetricsRequired = new List<String>();
        previousMetricsRequired.add('total_interactions_surveys');
        previousMetricsRequired.add('total_interactions_searches');
        previousMetricsRequired.add('total_complete_interactions_ussd_searches');
        previousMetricsRequired.add('total_complete_interactions_call_center');        

        // List of the metric names that are used to calculate the total info services
        List<String> totalMetrics = new List<String>();
        totalMetrics.add('total_interactions_surveys');
        totalMetrics.add('total_interactions_searches');
        totalMetrics.add('total_complete_interactions_ussd_searches');
        totalMetrics.add('total_complete_interactions_call_center');
        totalMetrics.add('total_interactions_channels');
        
        // Lists to store the metric data for the DML actions
        List<M_E_Metric_Data__c> updateMetrics = new List<M_E_Metric_Data__c>();
        List<M_E_Metric_Data__c> newMetrics = new List<M_E_Metric_Data__c>();

        // If required update the previous quarter
        if (updateLastQuarter) {

            // Get the SMS interactions
            ckwPreviousMetricValues.put('total_interactions_channels', MetricHelpers.getSmsInteractions(ckwPreviousQuarterStartDate, ckwPreviousQuarterEndDate));

            // Calculate the remaining metrics
            // Convert to a %
            ckwPreviousMetricValues.put('percent_ckws_high_performance', (ckwPreviousMetricValues.get('percent_ckws_high_performance')/ckwPreviousMetricValues.get('total_ckws'))*100);
            ckwPreviousMetricValues.put('percent_poor_ckws', ckwPreviousMetricValues.get('percent_poor_ckws')/ckwPreviousMetricValues.get('total_ckws'));
            ckwPreviousMetricValues.put('percent_woman_ckws', (ckwPreviousMetricValues.get('percent_woman_ckws')/ckwPreviousMetricValues.get('total_ckws'))*100);

            // Get the baseline numbers from the previous quarter if required.
            Map<String, Decimal> previous2Totals = MetricHelpers.getMetricValues(previousMetricsRequired, ckwPrevious2QuarterStartDate, ckwPrevious2QuarterEndDate);
            ckwPreviousMetricValues.put('total_info_services_offered', MetricHelpers.calculateTotal(totalMetrics, ckwPreviousMetricValues, previous2Totals, ckwPreviousQuarterStartDate, ckwPreviousQuarterEndDate));

            // Check that we have the M_E_Metric_Data__c object created already
            M_E_Metric_Data__c[] previousMetrics = MetricHelpers.getMetricDatas(ckwMetricsList, ckwPreviousQuarterStartDate, ckwPreviousQuarterEndDate, null);

            // Generate the metrics that need to be updated
            Map<String, M_E_Metric_Data__c> updatePreviousMetricMap = MetricHelpers.generateUpdateMetricMap(previousMetrics, ckwPreviousMetricValues, previous2Totals);

            // Generate any new metric if required
            Map<String, M_E_Metric_Data__c> newPreviousMetricMap = new Map<String, M_E_Metric_Data__c>();
            for (String id : ckwMetricsList) {
                M_E_Metric_Data__c metric = updatePreviousMetricMap.get(id);
                if (metric == null) {
                    Decimal prevValue = previous2Totals.get(id);
                    Decimal value = ckwPreviousMetricValues.get(id);
                    if (prevValue != null) {
                        value = value + prevValue;
                    }
                    M_E_Metric_Data__c newMetric = MetricHelpers.createNewMetric(id, ckwPreviousQuarterStartDate, value, 0.0, null, null, false);
                    if (newMetric != null) {
                        newPreviousMetricMap.put(id, newMetric);
                    }
                }
            }
            for (String id : updatePreviousMetricMap.keySet()) {
                updateMetrics.add(updatePreviousMetricMap.get(id));
            }
            for (String id : newPreviousMetricMap.keySet()) {
                newMetrics.add(newPreviousMetricMap.get(id));
            }

            // Save previous quarters data. Must do here so that the calculations for the next quarter
            // pick up the changes.
            if (updateMetrics.size() > 0) {
                update updateMetrics;
            }
            if (newMetrics.size() > 0) {
                insert newMetrics;
            }
        }

        // Sort out the current quarters data
        // Clear the DML lists
        updateMetrics.clear();
        newMetrics.clear();

        // Get the SMS interactions
        ckwMetricValues.put('total_interactions_channels', MetricHelpers.getSmsInteractions(ckwQuarterStartDate, ckwQuarterEndDate));

        // Convert to a %
        ckwMetricValues.put('percent_ckws_high_performance', (ckwMetricValues.get('percent_ckws_high_performance')/ckwMetricValues.get('total_ckws'))*100);
        ckwMetricValues.put('percent_poor_ckws', ckwMetricValues.get('percent_poor_ckws')/ckwMetricValues.get('total_ckws'));
        ckwMetricValues.put('percent_woman_ckws', (ckwMetricValues.get('percent_woman_ckws')/ckwMetricValues.get('total_ckws'))*100);

        // Get the baseline numbers from the previous quarter if the metric is cumulative since the start
        // of the project
        Map<String, Decimal> previousTotals = MetricHelpers.getMetricValues(previousMetricsRequired, ckwPreviousQuarterStartDate, ckwQuarterStartDate);

        // Check that we have the M_E_Metric_Data__c object created already
        M_E_Metric_Data__c[] metrics = MetricHelpers.getMetricDatas(ckwMetricsList, ckwQuarterStartDate, ckwQuarterEndDate, null);

        // Calculate the total interactions.
        ckwMetricValues.put('total_info_services_offered', MetricHelpers.calculateTotal(totalMetrics, ckwMetricValues, previousTotals, ckwQuarterStartDate, ckwQuarterEndDate));

        // Generate the metrics that need to be updated
        Map<String, M_E_Metric_Data__c> updateMetricMap = MetricHelpers.generateUpdateMetricMap(metrics, ckwMetricValues, previousTotals);

        // Generate any new metric if required
        Map<String, M_E_Metric_Data__c> newMetricMap = new Map<String, M_E_Metric_Data__c>();
        for (String id : ckwMetricsList) {
            M_E_Metric_Data__c metric = updateMetricMap.get(id);
            if (metric == null) {
                Decimal prevValue = previousTotals.get(id);
                Decimal value = ckwMetricValues.get(id);
                if (prevValue != null) {
                    value = value + prevValue;
                }
                M_E_Metric_Data__c newMetric = MetricHelpers.createNewMetric(id, ckwQuarterStartDate, value, 0.0, null, null, false);
                if (newMetric != null) {
                    newMetricMap.put(id, newMetric);
                }
            }
        }

        // Add the metrics to the correct list
        for (String id : updateMetricMap.keySet()) {
            updateMetrics.add(updateMetricMap.get(id));
        }
        for (String id : newMetricMap.keySet()) {
            newMetrics.add(newMetricMap.get(id));
        }

        // Save the new details to the database
        if (updateMetrics.size() > 0) {
            update updateMetrics;
        }
        if (newMetrics.size() > 0) {
            insert newMetrics;
        }
    }

    public static testMethod void testCKWBatch() {

        // Generate the dates required
        Date thisMonth = Date.today();
        thisMonth = thisMonth.toStartOfMonth();
        Date month1 = thisMonth.addMonths(-1);
        Date month2 = thisMonth.addMonths(-2);
        Date month3 = thisMonth.addMonths(-3);
        Date month4 = thisMonth.addMonths(-4);
        Date month5 = thisMonth.addMonths(-5);
        List<Date> dates = new List<Date>();
        dates.add(thisMonth);
        dates.add(month1);
        dates.add(month2);
        dates.add(month3);
        dates.add(month4);
        dates.add(month5);

        // Create a handset
        Phone__c testHandset = new Phone__c();
        testHandset.IMEI__c = 'TestIMEI';
        testHandset.Serial_Number__c = '325246263253462';
        testHandset.Purchase_Value_USD__c = 100.00;
        database.insert(testHandset);

        // Create a test CKW
        Person__c testPerson = new Person__c();
        testPerson.First_Name__c = 'FirstName';
        testPerson.Last_Name__c = 'LastName';
        testPerson.Handset__c = testHandset.Id;
        database.insert(testPerson);

        CKW__c testCkw = new CKW__c();
        testCkw.Person__c = testPerson.id;
        testCkw.Status__c = 'Active';
        testCkw.Active_Date__c = date.today().addMonths(-3);
        database.insert(testCkw);
        CKW__c testCkw2 = [SELECT name from CKW__c where id =:testCkw.id];

        List<CKW_Performance_Review__c> reviews = new List<CKW_Performance_Review__c>();

        Monthly_Target__c target = new Monthly_Target__c();
        target.Search_Target__c = 5.0;
        target.Survey_Target__c = 5.0;
        target.Start_Date__c = Date.today();
        database.insert(target);

        Incentive_Structure__c structure = new Incentive_Structure__c();
        structure.Level_A_Compensation__c = 15000.00;
        structure.Level_A_Threshold__c = 100;
        structure.Level_B_Compensation__c = 10000.00;
        structure.Level_B_Threshold__c = 75;
        structure.Level_C_Compensation__c = 5000.00;
        structure.Level_C_Threshold__c = 50;
        structure.Level_D_Compensation__c = 1000.00;
        structure.Airtime_Compensation__c = 2000.00;
        structure.Long_Term_Airtime_Bonus__c = 2000.00;
        structure.Long_Term_Cash_Bonus__c = 2000.00;
        structure.Short_Term_Airtime_Bonus__c = 2000.00;
        structure.Short_Term_Cash_Bonus__c = 2000.00;
        structure.Start_Date__c = date.today().addDays(-10);
        structure.Name = 'My_test';
        structure.Medium_Term_Airtime_Bonus__c = 2000.00;
        structure.Medium_Term_Cash_Bonus__c = 2000.00;
        database.insert(structure);

        // Create some performance records for this CKW
        for (Integer i = 0; i < 6; i++) {
            CKW_Performance_Review__c review = new CKW_Performance_Review__c();
            review.Surveys_Approved__c = 3.0;
            review.Number_Of_Searches_Running_Total__c = 3.0;
            review.CKW_c__c = testCkw2.id;
            review.Incentive_Structure__c = structure.id;
            review.Monthly_Target__c = target.id;
            review.Start_Date__c = dates.get(i);
            reviews.add(review);
        }

        // Create a handset
        Phone__c testHandset2 = new Phone__c();
        testHandset2.IMEI__c = 'TestIMEI2';
        testHandset2.Serial_Number__c = '322246263253462';
        testHandset2.Purchase_Value_USD__c = 100.00;
        database.insert(testHandset2);

        // Create a 2nd CKW
        Person__c testPerson2 = new Person__c();
        testPerson2.First_Name__c = 'FirstName';
        testPerson2.Last_Name__c = 'LastName';
        testPerson2.Handset__c = testHandset2.Id;
        database.insert(testPerson2);

        CKW__c testCkw3 = new CKW__c();
        testCkw3.Status__c = 'Active';
        testCkw3.Active_Date__c = date.today().addMonths(-3);
        testCkw3.Person__c = testPerson2.id;
        database.insert(testCkw3);
        CKW__c testCkw4 = [SELECT name from CKW__c where id =:testCkw3.id];

        // Create some performance records for this CKW
        CKW_Performance_Review__c goodRev = new CKW_Performance_Review__c();
        goodRev.Surveys_Approved__c = 5.0;
        goodRev.Number_Of_Searches_Running_Total__c = 5.0;
        goodRev.Incentive_Structure__c = structure.Id;
        goodRev.Monthly_Target__c = target.id;
        goodRev.CKW_c__c = testCkw4.id;
        goodRev.Start_Date__c = dates.get(0);
        reviews.add(goodRev);
        for (Integer i = 1; i < 6; i++) {
            CKW_Performance_Review__c review = new CKW_Performance_Review__c();
            review.Surveys_Approved__c = 3.0;
            review.Number_Of_Searches_Running_Total__c = 3.0;
            review.CKW_c__c = testCkw4.id;
            review.Incentive_Structure__c = structure.id;
            review.Monthly_Target__c = target.id;
            review.Start_Date__c = dates.get(i);
            reviews.add(review);
        }

        // Save the reviews
        database.insert(reviews);

        // Run the batch
        Test.StartTest();
        String query = 'SELECT Id, Status__c, Active_Date__c, Person__c  FROM CKW__c WHERE id IN (\'' + testCkw.id + '\', \'' + testCkw3.id + '\')';
        List<String> metricList = new List<String>();
        metricList.add('total_interactions_surveys');
        metricList.add('total_interactions_searches');
        metricList.add('total_interactions_channels');
        metricList.add('total_complete_interactions_ussd_searches');
        metricList.add('percent_ckws_high_performance');
        metricList.add('total_info_services_offered');
        metricList.add('total_ckws');
        metricList.add('percent_poor_ckws');
        metricList.add('percent_woman_ckws');

        // Get the organisation
        Account partner = [
            SELECT
                Name
            FROM
                Account
            WHERE
                Name = 'Grameen Foundation'
            ];
        CKWMetrics ckwMetric = new CKWMetrics(query, metricList, true, partner);
        ID batchprocessid = Database.executeBatch(ckwMetric);
        Test.StopTest();
        System.Assert(database.countquery('SELECT count() FROM M_E_Metric_Data__c WHERE M_E_Metric__r.Name IN (\'percent_ckws_high_performance\', \'total_interactions_searches\', \'total_interactions_surveys\', \'total_info_services_offered\', \'total_interactions_channels\', \'total_ckws\') AND Date__c = THIS_QUARTER') >= 6);
    }
}