src/objects/Client_Location__c.object
<CustomObject>
    <description>A location of a piece of infrastructure for a client (or us). This could be a FVR radio station or a WFP Warehouse etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account for the client who owns this location</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Locations</relationshipLabel>
        <relationshipName>Client_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>The description of the location</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name that will be displayed on a map of this location</description>
        <label>Display Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <description>Must include if this is to show up on a map</description>
        <label>Latitude</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <description>Must be added if this is to show up on a map</description>
        <label>Longitude</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An optional person object that has control of the location</description>
        <inlineHelpText>Leave blank if this location is not tied to a specific person</inlineHelpText>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Client Locations</relationshipLabel>
        <relationshipName>Client_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of location for this record</description>
        <inlineHelpText>If you do not see the type you are looking for then contact tech to add it for you.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Radio Station</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC Health Branch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rain gauge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client Location</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Client Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <description>Latitude</description>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <description>Longitude</description>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClientLocationMapMarker.cls
/**
 *  Class to generate map markers for the Client_LOcation__c sObject.
 *  Extends MapMarker
 */
public with sharing class ClientLocationMapMarker extends MapMarkers {

    private Client_Location__c location;

    public ClientLocationMapMarker(Client_Location__c location) {
        this.location = location;
        this.setLatitude(location.Latitude__c);
        this.setLongitude(location.Longitude__c);
        this.setMarkerTitle(location.Name);
        setDefaultColour('Green');
    }

    // Create the content string for the marker pop up
    public override String getMarkerInfoContentString() {

        String content = '<div>' +
            this.location.Display_Name__c + '<br />' +
            this.location.Type__c + '<br />' +
            'For: ' + this.location.Account__r.Name + '<br />' +
            this.location.Description__c + '<br />' +
            getPersonDetails() +
            '</div>';
        return content;
    }

    public override void generateMarkerName(String splitter) {
        setColour(getDefaultColour());
        setMarkerName(joinMarkerName(location.Type__c, getColour(), ''));
    }

    public override String getColour() {
        return this.colour;
    }

    private String getPersonDetails() {

        String content = '';
        if (location.Person__c != null) {
            content = '<br />Name: ' + location.Person__r.First_Name__c + ' ' + location.Person__r.Last_Name__c + '<br />' +
                'Subcounty: ' + location.Person__r.Subcounty__r.Display_Name__c + '<br />';
        }
        return content;
    }

    static testMethod void testMarker() {

        Client_Location__c location = new Client_Location__c();
        location.Display_Name__c = 'lk';
        location.Latitude__c = '';
        location.Longitude__c = '';
        location.Type__c = 'Rain Gauge';
        Database.insert(location);

        ClientLocationMapMarker marker = new ClientLocationMapMarker(location);
        marker.getMarkerInfoContentString();
        marker.generateMarkerName('');
    }
}