src/objects/Client_Event__c.object
<CustomObject>
    <description>An event for a client that may or may not be happening at a client location</description>
    <fields>
        <fullName>Client_Location__c</fullName>
        <description>The location that the event is taking place at</description>
        <label>Client Location</label>
        <referenceTo>Client_Location__c</referenceTo>
        <relationshipLabel>Client Events</relationshipLabel>
        <relationshipName>Client_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the event</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The display name for the event that will show on maps and dashboards to identify it</description>
        <label>Display Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>The time that the event is to end</description>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>The date time of the start of the event</description>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of event</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>FVR Radio Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer Voice Radio</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client Event</label>
    <nameField>
        <displayFormat>CE-{0000000000}</displayFormat>
        <label>Client Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Client_Location__c.object
<CustomObject>
    <description>A location of a piece of infrastructure for a client (or us). This could be a FVR radio station or a WFP Warehouse etc</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>The description of the location</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name that will be displayed on a map of this location</description>
        <label>Display Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district that this location is in</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Client Locations</relationshipLabel>
        <relationshipName>Client_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of location for this record</description>
        <inlineHelpText>If you do not see the type you are looking for then contact tech to add it for you.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Radio Station</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC Health Branch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rain gauge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Client Location</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Client Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FvrDashboardControllerExtension.cls
public class FvrDashboardControllerExtension {

    private DashboardController dashboardController;

    public List<Client_Event__c> radioShows;
    public List<Client_Event__c> getRadioShows() {

        DateTime quarterFirstDay = DateTime.newInstance(MetricHelpers.getQuarterFirstDay(this.dashboardController.quarter), Time.newInstance(00, 00, 00, 00));
        DateTime quarterLastDay = DateTime.newInstance(MetricHelpers.getQuarterLastDay(this.dashboardController.quarter), Time.newInstance(23, 59, 59, 59));
        if ((this.dashboardController.district == null
                || this.dashboardController.district.equals(''))
                && this.dashboardController.getIsCurrentQuarter().equals('true')
        ) {
                quarterLastDay = DateTime.newInstance(Date.today(), Time.newInstance(23, 59, 59, 59));
        }
        List<Client_Event__c> shows = Database.query(generateRadioShowQuery());
        if (shows.size() < 1) {
            return null;
        }
        return shows;
    }
    public void setRadioShows(List<Client_Event__c> shows) {
        this.radioShows = shows;
    }

    public FvrDashboardControllerExtension(DashboardController dashboardController) {

        this.dashboardController = dashboardController;
    }

    private String generateRadioShowQuery() {


        String endString;
        String districtString = '';
        if (this.dashboardController.district != null && !this.dashboardController.district.equals('')) {
            districtString = 'AND Client_Location__r.District__r.Name = \'' + this.dashboardController.district + '\'';
            endString = 'AND End_Time__c <= :quarterLastDay ';
        }
        else {
            endString = 'AND Start_Time__c <= :quarterLastDay ';
        }

        String query =
            'SELECT '                                     +
                'Display_Name__c, '                       +
                'Description__c , '                       +
                'Type__c, '                               +
                'Start_Time__c, '                         +
                'End_Time__c, '                           +
                'Client_Location__r.Name, '               +
                'Client_Location__r.Display_Name__c '     +
            'FROM '                                       +
                'Client_Event__c '                        +
            'WHERE '                                      +
                'Type__c = \'Farmer Voice Radio\' '       +
                districtString                            +
                ' AND Start_Time__c >= :quarterFirstDay ' +
                endString                                 +
            'ORDER BY '                                   +
                'Start_Time__c, '                         +
                'Client_Location__r.District__r.Name';
        System.debug(LoggingLevel.INFO, query);
        return query;
    }

    public static testMethod void testController() {
        FvrDashboardControllerExtension controller = new FvrDashboardControllerExtension(new DashboardController());
        controller.setRadioShows(controller.getRadioShows());
    }
}