src/objects/Coffee_Farmer__c.object
<CustomObject>
    <fields>
        <fullName>Amount_spent_on_chemicals_last_12months__c</fullName>
        <label>Amount spent on chemicals last 12months</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_spent_on_herbicides_last_12months__c</fullName>
        <label>Amount spent on herbicides last 12months</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Focus_Farmer__c</fullName>
        <label>Focus Farmer</label>
        <referenceTo>Focus_Farmer__c</referenceTo>
        <relationshipLabel>Coffee Farmers</relationshipLabel>
        <relationshipName>Coffee_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Registered_By__c</fullName>
        <label>Registered By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Coffee Farmers</relationshipLabel>
        <relationshipName>Coffee_Farmers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_amount_spent_on_fertilizers__c</fullName>
        <description>total amount you spent in Ugandan shillings for the fertilizers used</description>
        <inlineHelpText>In the last 12 months, what was the total amount you spent in Ugandan shillings for the fertilizers used on your coffee garden[s]?</inlineHelpText>
        <label>Total amount spent on fertilizers</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Coffee Farmer</label>
    <nameField>
        <displayFormat>CF{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Farmer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coffee Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <fields>
        <fullName>ISO_Standard_Code__c</fullName>
        <label>ISO Standard Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Focus_Farmer__c.object
<CustomObject>
    <fields>
        <fullName>Farmer_Type__c</fullName>
        <label>Farmer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Banana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Focus Farmers</relationshipLabel>
        <relationshipName>Focus_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Focus Farmer</label>
    <nameField>
        <displayFormat>FFN{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Focus Farmer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Focus Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Food_Security_Detail__c.object
<CustomObject>
    <description>Food Security Details for the CKW 3.0 Focus Farmers</description>
    <fields>
        <fullName>Focus_Farmer__c</fullName>
        <label>Focus Farmer</label>
        <referenceTo>Focus_Farmer__c</referenceTo>
        <relationshipLabel>Food Security Details</relationshipLabel>
        <relationshipName>Food_Security_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Food Security Detail</label>
    <nameField>
        <displayFormat>FSN{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Food Security Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Food Security Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestAssignCoffeeFarmersToContactTrigger.cls
@isTest
public class TestAssignCoffeeFarmersToContactTrigger {

    @isTest static void TestAssignSingleCoffeeFarmerToContact() {
        

        Coffee_Farmer__c CoffeeFarmer = createSingleFarmer();
        insert CoffeeFarmer;
        Test.startTest();
        List<gfsurveys__SObjectContactAssociation__c> scas = [Select Id, 
                                                                gfsurveys__AssociatedIds__c 
                                                              from 
                                                                    gfsurveys__SObjectContactAssociation__c
                                                              where 
                                                                gfsurveys__SObjectApiName__c='Coffee_Farmer__c'
                                                              and
                                                                gfsurveys__Contact__c =:CoffeeFarmer.Registered_By__c];
        System.assertEquals(CoffeeFarmer.Id, scas[0].gfsurveys__AssociatedIds__c);
        Test.stopTest();
    }
    
    @isTest static void testAssignMultipleFarmersToContacts() {
        List<Coffee_Farmer__c> CoffeeFarmers = createMultipleFarmers();
        insert CoffeeFarmers;
        Test.startTest();
        List<gfsurveys__SObjectContactAssociation__c> scas = [Select Id, 
                                                                gfsurveys__AssociatedIds__c 
                                                              from 
                                                                    gfsurveys__SObjectContactAssociation__c
                                                              where 
                                                                gfsurveys__SObjectApiName__c='Coffee_Farmer__c'];
        System.assertEquals(2, scas.size());
        Test.stopTest();
    }
    
    @isTest static void testAssignMultipleFarmersOneAtaTime() {
        List<Coffee_Farmer__c> CoffeeFarmers = createMultipleFarmers();
        for (Coffee_Farmer__c CoffeeFarmer : CoffeeFarmers) {
            insert CoffeeFarmer;
        }
        Test.startTest();
        List<gfsurveys__SObjectContactAssociation__c> scas = [Select Id, 
                                                                gfsurveys__AssociatedIds__c 
                                                              from 
                                                                    gfsurveys__SObjectContactAssociation__c
                                                              where 
                                                                gfsurveys__SObjectApiName__c='Coffee_Farmer__c'];
        System.assertEquals(2, scas.size());
        Test.stopTest();
    }
    
    private static Coffee_Farmer__c createSingleFarmer() {
    
        // Create the Country record for Uganda
        Country__c uganda = new Country__c();
        uganda.Name = 'Uganda';
        uganda.ISO_Standard_Code__c = 'UG';
        uganda.Language__c = 'ENglish';
        insert uganda;
        
        // Create the contact who registers the Coffee farmer
        Contact ckw = new Contact();
        ckw.FirstName = 'test';
        ckw.LastName = 'ckw';
        insert ckw;

        // Create a test person
        Person__c person = new Person__c();
        person.First_Name__c = 'Test1';
        person.Last_Name__c = 'Test2';
        person.Gender__c = 'Female';
        person.Type__c = 'Focus Farmer';
        insert person;

        // Create a focus farmer
        Focus_Farmer__c focusFarmer = new Focus_Farmer__c();
        focusFarmer.Person__c = person.id;
        focusFarmer.Farmer_Type__c = 'Coffee';
        insert focusFarmer;

        // Create a food security detail
        Food_Security_Detail__c foodSecurity = new Food_Security_Detail__c();
        foodSecurity.Focus_Farmer__c = focusFarmer.Id;
        insert foodSecurity;

        // Create a Coffee farmer object
        Coffee_Farmer__c coffeeFarmer = new Coffee_Farmer__c();
        coffeeFarmer.Focus_Farmer__c = focusFarmer.Id;
        coffeeFarmer.Registered_By__c = ckw.Id;
        coffeeFarmer.Total_amount_spent_on_fertilizers__c = 50000;
        coffeeFarmer.Amount_spent_on_herbicides_last_12months__c = 80000;
        coffeeFarmer.Amount_spent_on_chemicals_last_12months__c = 90000;
        return coffeeFarmer;
    }
    
    private static List<Coffee_Farmer__c> createMultipleFarmers() {
    
        Country__c uganda = new Country__c();
        uganda.Name = 'Uganda';
        uganda.ISO_Standard_Code__c = 'UG';
        uganda.Language__c = 'ENglish';
        insert uganda;
        
        Contact ckw = new Contact();
        ckw.FirstName = 'test';
        ckw.LastName = 'ckw';
        insert ckw;
        
        Contact ckw2 = new Contact();
        ckw2.FirstName = 'test2';
        ckw2.LastName = 'ckw2';
        insert ckw2;
        
        Person__c person = new Person__c();
        person.First_Name__c = 'Test1';
        person.Last_Name__c = 'Test2';
        person.Gender__c = 'Female';
        person.Type__c = 'Focus Farmer';
        insert person;
        
        Person__c person2 = new Person__c();
        person2.First_Name__c = 'Test12';
        person2.Last_Name__c = 'Test22';
        person2.Gender__c = 'Male';
        person2.Type__c = 'Focus Farmer';
        insert person2;
        
        Person__c person3 = new Person__c();
        person3.First_Name__c = 'Test13';
        person3.Last_Name__c = 'Test23';
        person3.Gender__c = 'Female';
        person3.Type__c = 'Focus Farmer';
        insert person3;
        
        Focus_Farmer__c focusFarmer = new Focus_Farmer__c();
        focusFarmer.Person__c = person.id;
        focusFarmer.Farmer_Type__c = 'Coffee';
        insert focusFarmer;
        
        Focus_Farmer__c focusFarmer2 = new Focus_Farmer__c();
        focusFarmer2.Person__c = person2.id;
        focusFarmer2.Farmer_Type__c = 'Coffee';
        insert focusFarmer2;
        
        Focus_Farmer__c focusFarmer3 = new Focus_Farmer__c();
        focusFarmer3.Person__c = person3.id;
        focusFarmer3.Farmer_Type__c = 'Coffee';
        insert focusFarmer3;
        
        Food_Security_Detail__c foodSecurity = new Food_Security_Detail__c();
        foodSecurity.Focus_Farmer__c = focusFarmer.Id;
        insert foodSecurity;
        
        Food_Security_Detail__c foodSecurity2 = new Food_Security_Detail__c();
        foodSecurity2.Focus_Farmer__c = focusFarmer2.Id;
        insert foodSecurity2;
        
        Food_Security_Detail__c foodSecurity3 = new Food_Security_Detail__c();
        foodSecurity3.Focus_Farmer__c = focusFarmer3.Id;
        insert foodSecurity3;
        
        Coffee_Farmer__c coffeeFarmer = new Coffee_Farmer__c();
        coffeeFarmer.Focus_Farmer__c = focusFarmer.Id;
        coffeeFarmer.Registered_By__c = ckw.Id;
        coffeeFarmer.Total_amount_spent_on_fertilizers__c = 50000;
        coffeeFarmer.Amount_spent_on_herbicides_last_12months__c = 80000;
        coffeeFarmer.Amount_spent_on_chemicals_last_12months__c = 90000;
        
        Coffee_Farmer__c coffeeFarmer2 = new Coffee_Farmer__c();
        coffeeFarmer2.Focus_Farmer__c = focusFarmer2.Id;
        coffeeFarmer2.Registered_By__c = ckw.Id;
        coffeeFarmer2.Total_amount_spent_on_fertilizers__c = 40000;
        coffeeFarmer2.Amount_spent_on_herbicides_last_12months__c = 40000;
        coffeeFarmer2.Amount_spent_on_chemicals_last_12months__c = 40000;
        
        Coffee_Farmer__c coffeeFarmer3 = new Coffee_Farmer__c();
        coffeeFarmer3.Focus_Farmer__c = focusFarmer3.Id;
        coffeeFarmer3.Registered_By__c = ckw2.Id;
        coffeeFarmer3.Total_amount_spent_on_fertilizers__c = 70000;
        coffeeFarmer3.Amount_spent_on_herbicides_last_12months__c = 60000;
        coffeeFarmer3.Amount_spent_on_chemicals_last_12months__c = 70000;
        
        return new List<Coffee_Farmer__c>{coffeeFarmer, coffeeFarmer2, coffeeFarmer3};
    }
}