src/objects/Coffee_Farmer__c.object
<CustomObject>
    <fields>
        <fullName>Focus_Farmer__c</fullName>
        <label>Focus Farmer</label>
        <referenceTo>Focus_Farmer__c</referenceTo>
        <relationshipLabel>Coffee Farmers</relationshipLabel>
        <relationshipName>Coffee_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Registered_By__c</fullName>
        <label>Registered By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Coffee Farmers</relationshipLabel>
        <relationshipName>Coffee_Farmers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Coffee Farmer</label>
    <nameField>
        <displayFormat>CF{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Farmer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coffee Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Coffee_Farmer_GAPs_Selection__c.object
<CustomObject>
    <fields>
        <fullName>CKW_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Contact to whom the Coffee Farmer is assigned. This is the same Contact who registered this farmer</description>
        <inlineHelpText>The Contact to whom the Coffee Farmer is assigned. This is the same Contact who registered this farmer</inlineHelpText>
        <label>CKW Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Coffee Farmer GAPs Selections</relationshipLabel>
        <relationshipName>Coffee_Farmer_GAPs_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coffee_Farmer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Coffee Farmer</label>
        <referenceTo>Coffee_Farmer__c</referenceTo>
        <relationshipLabel>Coffee Farmer GAPs Selections</relationshipLabel>
        <relationshipName>Coffee_Farmer_GAPs_Selections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Soil_and_Water_Conservation__c</fullName>
        <formula>IF(INCLUDES( Top_5_Preferred_GAPs_for_Support__c , &quot;Soil and water conservation&quot;), &apos;Yes&apos;,&apos;No&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Soil and Water Conservation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_of_coffee_stumping__c</fullName>
        <formula>IF (INCLUDES(Pruning_desuckering_Targets__c,&apos;Time of coffee stumping&apos;), &apos;Yes&apos;, &apos;No&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time of coffee stumping</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_of_pruning__c</fullName>
        <formula>IF (INCLUDES(Pruning_desuckering_Targets__c,&apos;Time of pruning&apos;), &apos;Yes&apos;, &apos;No&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time of pruning</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_5_Preferred_GAPs_for_Support__c</fullName>
        <label>Top 5 Preferred GAPs for Support</label>
        <picklist>
            <picklistValues>
                <fullName>Soil fertility management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proper and timely weed control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee desuckering, pruning and stumping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee pests and disease control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soil and water conservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Easily access agro-inputs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee processing (pulping)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On farm coffee value addition (PHH)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group production and marketing of coffee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proper Coffee farm record keeping</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Coffee Farmer GAPs Selection</label>
    <nameField>
        <displayFormat>CG{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Coffee Farmer GAPs Selection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coffee Farmer GAPs Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Coffee_GAP_Adoption__c.object
<CustomObject>
    <fields>
        <fullName>Coffee_Farmer__c</fullName>
        <label>Coffee Farmer</label>
        <referenceTo>Coffee_Farmer__c</referenceTo>
        <relationshipLabel>3.0 Coffee GAP Adoptions</relationshipLabel>
        <relationshipName>Coffee_GAP_Adoptions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coffee_GAPs_Adoption__c</fullName>
        <label>Coffee GAPs Adoption</label>
        <referenceTo>Coffee_GAPs_Adoption__c</referenceTo>
        <relationshipLabel>3.0 Coffee GAP Adoptions</relationshipLabel>
        <relationshipName>Coffee_GAP_Adoptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>3.0 Coffee GAP Adoption</label>
    <nameField>
        <displayFormat>CGA{YYYY}{MM}{0000}</displayFormat>
        <label>3.0 Coffee GAP Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3.0 Coffee GAP Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Coffee_GAPs_Adoption__c.object
<CustomObject>
    <fields>
        <fullName>Coffee_Farmer_GAPs_Selection__c</fullName>
        <label>Coffee Farmer GAPs Selection</label>
        <referenceTo>Coffee_Farmer_GAPs_Selection__c</referenceTo>
        <relationshipLabel>Coffee GAPs Adoptions</relationshipLabel>
        <relationshipName>Coffee_GAPs_Adoptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Coffee_Farmer__c</fullName>
        <formula>Coffee_Farmer_GAPs_Selection__r.Coffee_Farmer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Coffee Farmer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Desuckering_Pruning_Stumping_Discussed__c</fullName>
        <label>Desuckering Pruning Stumping Discussed</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Frequency_of_Desuckering__c</fullName>
        <label>GAP 2.1 Frequency of Desuckering</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>More than 3 times a month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Once a month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twice a month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thrice a month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level_at_which_stumping_is_done__c</fullName>
        <label>GAP 2.7 Level at which stumping is done</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1ft above ground level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Below the knee height</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-1½ft. above soil level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 ft. above ground level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Soil_Water_Conservation_Discussed__c</fullName>
        <label>GAP 3 Soil Water Conservation Discussed?</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Soil_and_Water_Conservation__c</fullName>
        <label>GAP 3 Soil &amp; Water Conservation Measures</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>None done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digging trenches or terraces</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mulching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plant grass across the slope</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plant shade trees or wind breakers</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Time_of_Coffee_Stumping__c</fullName>
        <label>GAP 2.6 Time of Coffee Stumping</label>
        <picklist>
            <picklistValues>
                <fullName>NA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>6 to 7 years old</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 years and above</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Coffee GAPs Adoption</label>
    <nameField>
        <displayFormat>CGA{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Coffee GAPs Adoption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coffee GAPs Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <fields>
        <fullName>ISO_Standard_Code__c</fullName>
        <label>ISO Standard Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Focus_Farmer__c.object
<CustomObject>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Focus Farmers</relationshipLabel>
        <relationshipName>Focus_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Focus Farmer</label>
    <nameField>
        <displayFormat>FFN{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Focus Farmer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Focus Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCreateSpecificCoffeeAdoptions.cls
@isTest
public class TestCreateSpecificCoffeeAdoptions {
    @isTest static void testCreateSpecificAdoptions() {
        Contact ckwContact = new Contact(FirstName='Bob', LastName='Zaabu');
        insert ckwContact;
        
        // Create a Coffee Farmer, along with its parent objects
        Country__c country = new Country__c(Name='Uganda', ISO_Standard_Code__c='UG');
        insert country;
        Person__c person = new Person__c();
        person.First_Name__c = 'Suubi';
        person.Last_Name__c = 'Ggoonya';
        insert person;
        Focus_Farmer__c focusFarmer = new Focus_Farmer__c();
        focusFarmer.Person__c = person.id;
        insert focusFarmer;
        Coffee_Farmer__c coffeeFarmer = new Coffee_Farmer__c();
        coffeeFarmer.Focus_Farmer__c = focusFarmer.Id;
        coffeeFarmer.Registered_By__c = ckwContact.Id;
        insert coffeeFarmer;

        // Create a Coffee Farmer GAPs object
        Coffee_Farmer_GAPs_Selection__c gap = new Coffee_Farmer_GAPs_Selection__c();
        gap.Top_5_Preferred_GAPs_for_Support__c = 'Soil fertility management;Coffee pests and disease control;Proper and timely weed control;Soil and water conservation;Coffee desuckering, pruning and stumping';
        gap.CKW_Contact__c = ckwContact.Id;
        gap.Coffee_Farmer__c = coffeeFarmer.Id;
        gap.Location__latitude__s = 30.117334;
        gap.Location__longitude__s = 0.396258;
        insert gap;

        // Create a Coffee GAPs Adoption object
        Coffee_GAPs_Adoption__c gapsAdoption = new Coffee_GAPs_Adoption__c();
        gapsAdoption.Coffee_Farmer_GAPs_Selection__c = gap.id;
        gapsAdoption.Date__c = date.today();
        gapsAdoption.Soil_Water_Conservation_Discussed__c = 'Yes';
        gapsAdoption.Soil_and_Water_Conservation__c = 'Mulching';
        gapsAdoption.Desuckering_Pruning_Stumping_Discussed__c = 'Yes';
        gapsAdoption.Frequency_of_Desuckering__c = 'Several times/as soon as shoots come';
        gapsAdoption.Time_of_Coffee_Stumping__c = '6 to 7 years old';
        gapsAdoption.Level_at_which_stumping_is_done__c = '1ft above ground level';
        gapsAdoption.Time_of_Pruning__c = 'After harvesting the main crop';
        gapsAdoption.No_of_Stems_per_Tree_after_Prune__c = '3-4 stems';
        gapsAdoption.Tool_used_for_Pruning__c = 'Pruning saw';
        gapsAdoption.Group_Production_Marketing_Discussed__c = 'Yes';
        gapsAdoption.Group_Production_and_Marketing__c = 'Yes';
        gapsAdoption.Value_Addition__c = 'Yes';
        gapsAdoption.Obtain_Quality_Agro_Chemicals__c = 'Buy from registered input dealers';
        // on farm value addition
        gapsAdoption.On_farm_Value_Addition_Discussed__c = 'Yes';
        gapsAdoption.Method_of_Drying_Coffee__c = 'Tarpaulins';
        gapsAdoption.Method_of_on_farm_processing__c = 'Wet processing';
        gapsAdoption.Harvesting_and_PHH_Practices__c = 'Drying;Sorting;Grading;Cleaning';
        gapsAdoption.Steps_in_Wet_Processing__c = 'Wash fermented beans';
        insert gapsAdoption;

        test.startTest();
        List<Coffee_GAP_Adoption__c> coffeeGapAdoptions = [Select Id from Coffee_GAP_Adoption__c];
        System.assert(coffeeGapAdoptions.size() > 0);
        test.stopTest();
    }
}