src/objects/Commodity__c.object
<CustomObject>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Ewarehouse_Market__c</referenceTo>
        <relationshipLabel>Commodities</relationshipLabel>
        <relationshipName>Commodities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Commodity</label>
    <nameField>
        <label>Commodity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commodities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ewarehouse_Farmer__c.object
<CustomObject>
    <description>This is the farmer that is registered by the VKW at the field.</description>
    <label>Ewarehouse Farmer</label>
    <nameField>
        <label>Ewarehouse Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ewarehouse_Harvest__c.object
<CustomObject>
    <fields>
        <fullName>Ewarehouse_Farmer__c</fullName>
        <label>Ewarehouse Farmer</label>
        <referenceTo>Ewarehouse_Farmer__c</referenceTo>
        <relationshipLabel>Ewarehouse Harvests</relationshipLabel>
        <relationshipName>Ewarehouse_Harvests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notification_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <label>Ewarehouse Harvest</label>
    <nameField>
        <label>Ewarehouse Harvest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Harvests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ewarehouse_Harvest_Crop__c.object
<CustomObject>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <picklist>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cow peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black beans(Dolichos)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green grams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pigeon peas</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Harvest__c</fullName>
        <label>Ewarehouse Harvest</label>
        <referenceTo>Ewarehouse_Harvest__c</referenceTo>
        <relationshipLabel>Ewwarehouse Harvest Crops</relationshipLabel>
        <relationshipName>Ewwarehouse_Harvest_Crops</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ewarehouse Harvest Crop</label>
    <nameField>
        <label>Ewarehouse Harvest Crop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewwarehouse Harvest Crops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ewarehouse_Market__c.object
<CustomObject>
    <label>Ewarehouse Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market_Price__c.object
<CustomObject>
    <fields>
        <fullName>Buying__c</fullName>
        <label>Buying Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commodity__c</fullName>
        <label>Commodity</label>
        <referenceTo>Commodity__c</referenceTo>
        <relationshipLabel>Market Prices</relationshipLabel>
        <relationshipName>Market_Prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Notification_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field used to determine if the market price notification has been sent out to the Ewarehouse Farmers</description>
        <label>Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Selling_Price__c</fullName>
        <label>Selling Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Market Price</label>
    <nameField>
        <displayFormat>MP-{000000}</displayFormat>
        <label>Market Price ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EwarehouseHelpers.cls
public class EwarehouseHelpers {

    public static String generateMessage(String commodity) {
        String message = 'The price of ' + commodity.uncapitalize() + ' in the different markets is: ';
        for (Market_Price__c marketPrice: [SELECT Commodity__r.Market__r.Name, Name, Commodity__r.Name, Effective_Date__c, Buying__c, Selling_Price__c, CreatedDate FROM Market_Price__c WHERE Market_Price__c.Notification_Sent__c = false AND Commodity__r.Name=: commodity]) {
            message += 'IN ' + marketPrice.Commodity__r.Market__r.Name + '- ' + marketPrice.Buying__c + 'KES per 90kg bag,';
        }
        message = message.trim();
        message = message.removeEnd(',');
        return message;
    }

    public static List<Id> generateRecipients(String commodity) {
        List<Id> recipients = new List<Id>();
        for (Ewarehouse_Harvest_Crop__c harvest: [SELECT Ewarehouse_Harvest__r.Ewarehouse_Farmer__r.Ewarehouse_Person__r.Id FROM Ewarehouse_Harvest_Crop__c WHERE Crop__c INCLUDES(:commodity)]) {
            recipients.add(harvest.Ewarehouse_Harvest__r.Ewarehouse_Farmer__r.Ewarehouse_Person__r.Id);
        }
        return recipients;
    }
    
    public static List<Market_Price__c> setNotificationFlag(String commodity) {
        List<Market_Price__c> marketPricesToUpdate = new List<Market_Price__c>();
        for (Market_Price__c marketPrice: [SELECT Id, Notification_Sent__c FROM Market_Price__c WHERE Market_Price__c.Notification_Sent__c = false AND Commodity__r.Name=: commodity]) {
            marketPrice.Notification_Sent__c = true;
            marketPricesToUpdate.add(marketPrice);
        }
        return marketPricesToUpdate;
    }
}