src/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>The label for this metric. Will be displayed on the dashboard.</description>
        <inlineHelpText>The label for this metric. Will be displayed on the dashboard.</inlineHelpText>
        <label>Label</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Actual_Value__c</fullName>
        <description>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</description>
        <inlineHelpText>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</inlineHelpText>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <description>Comment for this particular metric for this quarter</description>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manual_Value__c</fullName>
        <description>Manually set value for a metric. Will override the actual value in display</description>
        <label>Manual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually.</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MetricEditController.cls
public with sharing class MetricEditController {
	String recordId;
	String quarter;
	Boolean saved = false;
	M_E_Metric_Data__c metric;
	
	public MetricEditController() {
        PageReference pageRef = ApexPages.currentPage();
        this.recordId = pageRef.getParameters().get('recordId');
        this.quarter = MetricHelpers.getCurrentQuarterAsString(0);
        if(this.recordId != null && this.recordId != '') {
        	loadMetric();
        }
    }
    
    public void loadMetric() {
    	M_E_Metric_Data__c metric = [Select M_E_Metric__r.Name, 
    									M_E_Metric__r.Label__c, Projected_Value__c, Manual_Value__c,
    									Actual_Value__c, Comment__c from M_E_Metric_Data__c where Id =: this.recordId];
    	this.metric = metric;
    }
    
    public String getQuarter() {
		return this.quarter;    	
    }

    public String getRecordId() {
    	return this.recordId;
    }
    
    public void setRecordId(String id) {
    	this.recordId = id;
    }
    
    public M_E_Metric_Data__c getMetric() {
    	return this.metric;
    }
    
    public void save() {
    	update this.metric;
    	this.saved = true;
    }
    
    public Boolean getSaved() {
    	return this.saved;
    }
    
    static testMethod void testMetricEdit() {
    	M_E_Metric_Data__c metric = [Select Id from M_E_Metric_Data__c limit 1];
    	MetricEditController controller = new MetricEditController();
    	controller.setRecordId(metric.Id);
    	controller.loadMetric();
    	controller.save();
    	System.assertEquals(metric.Id, controller.getMetric().Id);
 		System.assertEquals(true, controller.getSaved());
 		   	
    }
}