src/objects/Community_Based_Trainer_Target__c.object
<CustomObject>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Based Trainer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Community Based Trainer Targets</relationshipLabel>
        <relationshipName>Community_Based_Trainer_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Activity</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Community Based Trainer Targets</relationshipLabel>
        <relationshipName>Community_Based_Trainer_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Value__c</fullName>
        <label>Target Value</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Community Based Trainer Target</label>
    <nameField>
        <label>Community Based Trainer Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Based Trainer Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <description>Surveys run by CKWs. There is one entry here for each type of survey. Survey questions (and responses) are NOT stored here.</description>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <description>A unique name for the survey</description>
        <inlineHelpText>Please select a friendly name for the survey</inlineHelpText>
        <label>Survey Name</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IGDashboardTargetsController.cls
/**
 *
 * Copyright (c) 2013 AppLab, Grameen Foundation
 *
 *  This is the controller class for IG/NUSAF Dashboard pop-up page that updates targets
 *  Its test methods are in the IGDashboardTests class 
 **/
public class IGDashboardTargetsController {
    private Boolean saved = false;
    private Community_Based_Trainer_Target__c target; 
    private Person__c trainer;
    private List<SelectOption> activities;
    private List<SelectOption> communityBasedTrainers;
    
    public IGDashboardTargetsController(){
        setUp();
    }
    
    public void setUp(){
        target = new Community_Based_Trainer_Target__c();
        trainer = new Person__c();
    }
    
    /*
    * Fetches all Person__c objects of type IG/NUSAF - these are the Field Staff 
    * and avails then to the dropdown list on the page as list-options
    */
    public List<SelectOption> getCommunityBasedTrainers(){
        List<SelectOption> options = new List<SelectOption>();
        Person__c[] trainers = database.query(IGDashboardHelpers.getCommunityBasedTrainers());
        options.add(new SelectOption('','-- SET FOR ALL Community Based Trainers --'));
        for (Person__c trainer1 : trainers) {
           options.add(new SelectOption(string.valueOf(trainer1.Id), trainer1.First_Name__c + ' ' + trainer1.Last_Name__c));
        } 
        return options;
    }
    
    /*
    * Fetches surveys for IG/NUSAF monitoring that are supposed to feed into this dashboard 
    * The surveys are known by the post-processing method and are generally referred to as
    * activities. (Each activity is a survey)
    */
    public List<SelectOption> getActivities(){
        List<SelectOption> options = new List<SelectOption>();
        Survey__c[] surveys = database.query(IGDashboardHelpers.getActivities());
        options.add(new SelectOption('','-- Select Activity --'));
        for (Survey__c survey : surveys) {
           options.add(new SelectOption(string.valueOf(survey.Id), survey.Survey_Name__c));
        } 
        return options;
    }
    
    /*
    * gets the target object for binding to UI controller
    * also a setter method for use in testing
    */
    public Community_Based_Trainer_Target__c getTarget(){
        return this.target;
    }
    public void setTarget(Community_Based_Trainer_Target__c target){
        this.target = target;
    }
    
    /*
    * gets the trainer person object for binding to UI controller
    * also a setter method for use in testing
    */
    public Person__c getTrainer(){
    return this.trainer;
    }
    public void setTrainer(Person__c trainer){
        this.trainer = trainer;
    }

    public Boolean getSaved() {
        return this.saved;
    }
    public void setSaved(Boolean saved) {
        this.saved = saved;
    }
    
    public void save() {
        if(target.Survey__c != null && target.Target_Value__c > 0.0){
            Community_Based_Trainer_Target__c[] currentTargets = database.query(IGDashboardHelpers.getCurrentTargets(target.Survey__c));
            //no existing targets
            if(currentTargets.isEmpty()){
                //for all CBTs
                if(trainer.Id == null){
                    IGDashboardHelpers.setNewTargetsForAll(target.Survey__c, target.Target_Value__c);
                    this.saved = true;
                }
                else{
                    //for one CBT
                    IGDashboardHelpers.setNewTargetForCBT(target.Survey__c, target.Target_Value__c, trainer.Id);
                    this.saved = true;
                }
            }
            else{
                //there are existing targets
                //for all CBTs
                if(trainer.Id == null){
                    Person__c[] trainers = database.query(IGDashboardHelpers.getCommunityBasedTrainers());
                    for(Person__c trainer2 : trainers){
                        Community_Based_Trainer_Target__c foundTarget = IGDashboardHelpers.getTarget(trainer2.Id, currentTargets);
                        if(foundTarget == null){
                            //not found, create new 
                            IGDashboardHelpers.setNewTargetForCBT(target.Survey__c, target.Target_Value__c, trainer2.Id);
                        }
                        else{
                            //IGDashboardHelpers.updateTargetForCBT(target.Survey__c, target.Target_Value__c, trainer2.Id);
                            foundTarget.Target_Value__c = target.Target_Value__c;
                            update foundTarget;
                        }
                    }
                    this.saved = true;
                }
                else{
                    //for one CBT
                    Community_Based_Trainer_Target__c updateTarget = currentTargets[0];
                    updateTarget.Target_Value__c = target.Target_Value__c;
                    update updateTarget;
                    this.saved = true;
                }
            }
        }
    }
}