src/objects/Commodities__c.object
<CustomObject>
    <fields>
        <fullName>Lowest_Retail_Price__c</fullName>
        <label>Lowest Retail Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lowest_Wholesale_Price__c</fullName>
        <label>Lowest Wholesale Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Markets__c</referenceTo>
        <relationshipName>Commodities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commodities</label>
    <nameField>
        <label>Commodity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commodities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Crops__c</fullName>
        <description>Top crops grown by the farmer</description>
        <label>Crops</label>
        <picklist>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wheat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cassava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irish Potatoes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groundnuts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sorghum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bananas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cotton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <description>Stores details of a market. Most importantly it stores the region that the market is in.</description>
    <fields>
        <fullName>Market__c</fullName>
        <description>Stores details of a market. Most importantly it stores the region that the market is in.</description>
        <inlineHelpText>This must be written in the same format as the feed supplies. i.e. as a proper noun e.g. Kalerwe</inlineHelpText>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>Market-{0000}</displayFormat>
        <label>Market Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Markets__c.object
<CustomObject>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Markets</relationshipLabel>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Markets</label>
    <nameField>
        <label>Markets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Menu__c.object
<CustomObject>
    <description>Used to develop ckw search menus</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>The Name/Label for this menu</description>
        <inlineHelpText>The Name/Label for this menu</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Menu</label>
    <nameField>
        <displayFormat>M-{0000000000}</displayFormat>
        <label>Menu Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Menu_Item__c.object
<CustomObject>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Menu__c</fullName>
        <label>Menu</label>
        <referenceTo>Menu__c</referenceTo>
        <relationshipLabel>Menu Items</relationshipLabel>
        <relationshipName>Menu_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Item__c</fullName>
        <label>Parent Item</label>
        <referenceTo>Menu_Item__c</referenceTo>
        <relationshipName>Sub_Article_Menu_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Menu Item</label>
    <nameField>
        <displayFormat>MI-{0000000000}</displayFormat>
        <label>Menu Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Menu Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <description>Mobile phone number calculated based on Mobile Phone and Raw Mobile Number fields</description>
        <formula>/* If we have a Handset, use the number from its SIM Card */
IF( NOT( ISBLANK( Handset__c)),  
     Handset__r.SIM__r.Name, 
/* otherwise use the raw mobile number */
       Raw_Mobile_Number__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raw_Mobile_Number__c</fullName>
        <description>(optional) Phone number provided for non GF-assets</description>
        <label>Raw Mobile Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GetFarmersAndMarketPrices.cls
global class GetFarmersAndMarketPrices {
	
	webservice static String[] getFarmersAndMarketPrices (String selectedDistrict, String selectedCrop) {
		selectedDistrict = selectedDistrict.trim();
		selectedCrop = selectedCrop.trim();
		List<SelectedFarmerObject> farmers = getFarmers(selectedDistrict, selectedCrop);
		List<MarketPricesObject> marketPrices = getMarketPrices(selectedDistrict, selectedCrop);
		
		String[] farmersAndMarketPrices = new String[] {JSON.serialize(farmers), JSON.serialize(marketPrices)} ;

		return farmersAndMarketPrices;
	}
	
	private static List<SelectedFarmerObject> getFarmers (String selectedDistrict, String selectedCrop) {
		List<SelectedFarmerObject> selectedFarmers = new List<SelectedFarmerObject>();
		
		for (Farmer__c farmers: [
			SELECT 
				Farmer__c.Name, 
				Person__r.First_Name__c, 
				Person__r.Last_Name__c,
				Person__r.Mobile_Number__c 
			FROM 
				Farmer__c 
			WHERE 
				Farmer__c.Crops__c INCLUDES (:selectedCrop) 
			AND 
				Person__r.District__r.Name = :selectedDistrict ]) {
					
			selectedFarmers.add(new SelectedFarmerObject(farmers.Name, farmers.Person__r.First_Name__c,
								farmers.Person__r.Last_Name__c, farmers.Person__r.Mobile_Number__c));
				}
		return selectedFarmers;
	}
	
	private static List<MarketPricesObject> getMarketPrices (String selectedDistrict, String selectedCrop) {
		List<MarketPricesObject> selectedMarketPrices = new List<MarketPricesObject>();


        String pricePattern = 'Retail price:\\s*(\\d{1,}\\,{0,1}\\d{1,}).*Wholesale Price:\\s*(\\d{1,}\\,{0,1}\\d{1,})';
		Pattern searchPrice = Pattern.compile(pricePattern);

		for (Menu_Item__c menuItems: [
			SELECT 
				Content__c,
                Label__c
            
			FROM
				Menu_Item__c 
			WHERE 
				(Parent_Item__r.Parent_Item__r.Parent_Item__r.Parent_Item__r.Label__c = 'Subcounty Market Prices')// OR Parent_Item__r.Parent_Item__r.Parent_Item__r.Parent_Item__r.Parent_Item__r.Label__c = 'Subcounty Market Prices')
			AND 
				Parent_Item__r.Parent_Item__r.Label__c = :selectedDistrict 
			AND 
				Menu__r.Label__c='CKW Search']) {
                    for (Menu_Item__c marketMenuItems: [
                        SELECT 
                        	Content__c, 
                        	Label__c
                        FROM
							Menu_Item__c 
                        WHERE 
                        Parent_Item__r.Label__c =: menuItems.Label__c
                    AND
                        Label__c =: selectedCrop]) {
                            if (null != marketMenuItems.Content__c) {
                                    Matcher matchPrice = searchPrice.matcher(marketMenuItems.Content__c);
                                if(matchPrice.find()) {
                                		selectedMarketPrices.add(new MarketPricesObject(menuItems.Label__c, matchPrice.group(1).replace(',',''),
									matchPrice.group(2).replace(',','')));
                                }
                                                 
                            }
                        }
		}
		
		return selectedMarketPrices;
	}
	
	global class SelectedFarmerObject {
		String Id;
		String Name;
		String MobileNumber;
		
		SelectedFarmerObject (String farmerId, String firstName, String lastName, String mobileNumber) {
			this.Id = farmerId;
			this.Name = firstName +' '+ lastName;
			this.MobileNumber = mobileNumber;
		}
		
	}
	
	global class MarketPricesObject {
		String MarketName;
		String RetailPrice;
		String WholesalePrice;
		
		MarketPricesObject (String marketName, String lowestRetailPrice, String lowestWholesalePrice) {
			this.MarketName = marketName;
			this.RetailPrice = lowestRetailPrice;
			this.WholesalePrice = lowestWholesalePrice;
		}
	}
	
    static testMethod void canCreateMarketPricesObject(){
    	MarketPricesObject testMarketPrices = new MarketPricesObject('TestMarket', '1500', '1000');
    	system.assertEquals('TestMarket', testMarketPrices.MarketName);
    	system.assertEquals('1500', testMarketPrices.RetailPrice);
    	system.assertEquals('1000', testMarketPrices.WholesalePrice);
    }
    
    static testMethod void canCreateSelectedFarmerObject() {
    	SelectedFarmerObject testFarmer = new SelectedFarmerObject('UA12345', 'Testing', 'Farmer', '0770123456');
    	system.assertEquals('UA12345', testFarmer.Id);
    	system.assertEquals('Testing Farmer', testFarmer.Name);
    	system.assertEquals('0770123456', testFarmer.MobileNumber);
    }
    
    static testMethod void canGetFarmersAndMarketPrices() {
        District__c district = Utils.createTestDistrict('Nakapiripit');
        database.SaveResult districtResult = database.insert(district);
        
        Markets__c market = new Markets__c();
        market.Name = 'TestMarket';
        market.District__c = districtResult.getId();
        database.SaveResult marketResult = database.insert(market);
        
        Commodities__c commodity = new Commodities__c();
        commodity.Name = 'TestCommodity';
        commodity.Lowest_Retail_Price__c = 2000;
        commodity.Lowest_Wholesale_Price__c = 1500;
        commodity.Market__c = marketResult.getId();
        database.insert(commodity);
        
        Person__c person = new Person__c();
        person.First_Name__c = 'Testing';
        person.Last_Name__c = 'Farmer';
        person.Raw_Mobile_Number__c = '0770123456';
        person.District__c = districtResult.getId();
        database.SaveResult personResult = database.insert(person);
        
        Farmer__c farmer = new Farmer__c();
        farmer.Name = 'UA12345';
        farmer.Person__c = personResult.getId();
        farmer.Crops__c = 'TestCommodity';
        
        String[] testJson = GetFarmersAndMarketPrices.getFarmersAndMarketPrices('TestDistrict_Nakapiripit', 'TestCommodity');
        for (String s: testJson) {
        	system.assertNotEquals(s, '');
        }
    } 
    
}