src/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <fields>
        <fullName>Automated__c</fullName>
        <description>Is this value automated or not? This will determine whether it is editable on the Metric Admin page.</description>
        <inlineHelpText>Is this value automated or not? This will determine whether it is editable on the Metric Admin page.</inlineHelpText>
        <label>Automated</label>
        <picklist>
            <picklistValues>
                <fullName>False</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>True</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Calculation_Type__c</fullName>
        <description>The type of calcualtion that this metric is</description>
        <label>Calculation Type</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cumulative</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Header__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This metric is a header. This means that it is a dummy metric that is used to have a header for another set of metrics below it. Will have no values other than a Label, area and order</description>
        <label>Is Header</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_On_Fly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this metrics value should be calculated on the fly</description>
        <inlineHelpText>Only check this if you know what you are doing</inlineHelpText>
        <label>Is On Fly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>The label for this metric. Will be displayed on the dashboard.</description>
        <inlineHelpText>The label for this metric. Will be displayed on the dashboard.</inlineHelpText>
        <label>Label</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Metric_Section__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The section that the metric belongs to</description>
        <inlineHelpText>Leave blank if this metric is in the old style dashboard</inlineHelpText>
        <label>Metric Section</label>
        <referenceTo>Metric_Section__c</referenceTo>
        <relationshipLabel>M&amp;E Metrics</relationshipLabel>
        <relationshipName>M_E_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Not_For_Public__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should the metric be on the public dashboards</description>
        <inlineHelpText>Select true if this metric should not be shown on the public dashboard</inlineHelpText>
        <label>Not For Public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>On_The_Fly_Calculation_Type__c</fullName>
        <description>The type of on the fly calculation that this metric requires</description>
        <inlineHelpText>Choose one of these if the metric is to be calculated on the fly</inlineHelpText>
        <label>On The Fly Calculation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sum</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Ordering in list</description>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Area__c</fullName>
        <description>Add an extra label to the metric</description>
        <label>Sub Area</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subdivider__c</fullName>
        <description>The item that subdivides these metrics</description>
        <inlineHelpText>Select what the metrics are to be subdivided by</inlineHelpText>
        <label>Subdivider</label>
        <picklist>
            <picklistValues>
                <fullName>District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcounty</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Actual_Value__c</fullName>
        <description>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</description>
        <inlineHelpText>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</inlineHelpText>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <description>Comment for this particular metric for this quarter</description>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date of the quarter to which this metric belongs</description>
        <inlineHelpText>This can simply be any date falling in the quarter to which this metric belongs. We shall calculate the quarter dynamically. It defaults to the current date.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Denumerator__c</fullName>
        <description>The Denumerator for the on the fly calculation</description>
        <label>Denumerator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>The district that this metric is for. Allows us to split the metrics by district when showing them on the dashboard</description>
        <inlineHelpText>Select the district that this metric is for</inlineHelpText>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manual_Value__c</fullName>
        <description>Manually set value for a metric. Will override the actual value in display</description>
        <label>Manual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numerator__c</fullName>
        <description>Numerator for the on the fly calc</description>
        <label>Numerator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually.</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Metric_Section__c.object
<CustomObject>
    <description>A section that holds metrics to be shown on a dashboard</description>
    <fields>
        <fullName>Allow_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow the users of this section to update the metrics if their user has permission to do so</description>
        <inlineHelpText>Check if users should be allowed to update the metrics</inlineHelpText>
        <label>Allow Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the section still active to be displayed on a dashboard</description>
        <inlineHelpText>Uncheck this to indicate that the metric section should be displayed</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Break_Down__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows the link to break down of metrics. Can be overriden if the user does not have permission to see this link</description>
        <inlineHelpText>Check if the section should show the break down link</inlineHelpText>
        <label>Show Break Down</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Targets__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allow the targets to be displayed in the section</description>
        <inlineHelpText>Check if the targets for the metric period should be shown</inlineHelpText>
        <label>Show Targets</label>
        <type>Checkbox</type>
    </fields>
    <label>Metric Section</label>
    <nameField>
        <displayFormat>MS{0000000000}</displayFormat>
        <label>Metric Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metric Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MetricSectionComponentController.cls
global with sharing class MetricSectionComponentController {

    private List<M_E_Metric__c> metrics;
    private List<MetricDataWrapper> metricDatas;
    private static M_E_Metric_Data__c loadMetricData;

    public String regionName { get; set; }
    public Id districtId { get; set; }
    public Id subcountyId { get; set; }
    public Date fromdate { get; set; }
    public Date todate { get; set; }
    public Id metricId { get; set; }
    public String tabName { get; set; }
    public Metric_Section__c thisSection { get; set; }

    public MetricSectionComponentController(){  
    }

    public List<M_E_Metric__c> getMetrics(){
        if(metrics == null) {
            metrics = [
                SELECT
                    Id,
                    Name, 
                    Label__c, 
                    Automated__c, 
                    Projected_Value__c,
                    Order__c, 
                    Is_Header__c, 
                    Is_On_Fly__c, 
                    Calculation_Type__c,
                    On_The_Fly_Calculation_Type__c, 
                    Subdivider__c ,
                    Sub_Area__c
                FROM 
                    M_E_Metric__c 
                WHERE 
                    Metric_Section__r.Id = :metricId AND
                    Not_For_Public__c = false
                ORDER BY Order__c
            ];
        }
        return metrics;
    }

    public List<MetricDataWrapper> getMetricDatas(){
        if(metricDatas == null) {
            if(thisSection == null){
                if(metricId != null) {
                    thisSection = [
                       SELECT
                            Name,
                            Allow_Update__c,
                            Is_Active__c,
                            Show_Targets__c,
                            Default_Show__c,
                            Show_Break_Down__c
                        FROM
                            Metric_Section__c
                        WHERE
                            Id = :metricId 
                    ];
                }
            }
            metricDatas = new List<MetricDataWrapper>();
            List<M_E_Metric__c> metrics =  getMetrics();
            for(M_E_Metric__c metric : metrics) {
                MetricDataWrapper data = new MetricDataWrapper();
                data.setLabel(metric.Label__c);
                data.isHeader = metric.Is_Header__c;
                data.setOnFly(metric.Is_On_Fly__c);
                data.setCalculation(metric.On_The_Fly_Calculation_Type__c);
                data.setCurrentTarget(String.valueOf(metric.Projected_Value__c));
                data.setOrderNumber(metric.Order__c);
                if(!metric.Is_Header__c){
                    String query = '';
                    //get values
                    if(metric.On_The_Fly_Calculation_Type__c == 'Count'){
                        query = 'SELECT M_E_Metric__c, Sum(Denumerator__c) realValue FROM M_E_Metric_Data__c WHERE Denumerator__c > 0 AND M_E_Metric__c = \'' + metric.Id + '\' ';
                    }
                    else if (metric.On_The_Fly_Calculation_Type__c == 'Sum'){
                        query = 'SELECT M_E_Metric__c, Sum(Denumerator__c) realValue FROM M_E_Metric_Data__c WHERE Denumerator__c > 0 AND M_E_Metric__c = \'' + metric.Id + '\' ';
                    }
                    else if (metric.On_The_Fly_Calculation_Type__c == 'Percentage'){
                        query = 'SELECT M_E_Metric__c, Sum(Denumerator__c) denumerator, Sum(Numerator__c) numerator FROM M_E_Metric_Data__c WHERE M_E_Metric__c = \'' + metric.Id + '\' ';
                    }
                    else if (metric.On_The_Fly_Calculation_Type__c == 'Average'){
                        query = 'SELECT M_E_Metric__c, Sum(Denumerator__c) denumerator, Sum(Numerator__c) numerator FROM M_E_Metric_Data__c WHERE M_E_Metric__c = \'' + metric.Id + '\' ';
                    }
                    else if(metric.Automated__c == 'False') {
                        query = 'SELECT Id, Manual_Value__c, Projected_Value__c FROM M_E_Metric_Data__c WHERE M_E_Metric__c = \'' + metric.Id + '\' ';
                    }
                    //build where clause
                    String whereClause = '';
                    List<String> clauses = new List<String>();
                    String subdivider = metric.Subdivider__c == 'District' && districtId != null ? ' District__c = \'' + districtId + '\' ' : '';
                    subdivider = metric.Subdivider__c == 'Subcounty' && subcountyId != null ? ' Subcounty__c = \'' + subcountyId + '\' ' : subdivider;
                    String dateRange = fromdate != null && todate != null ? ' Date__c >= ' + datetime.newInstance(fromdate.year(), fromdate.month(), fromdate.day()).format('yyyy-MM-dd') + ' AND Date__c <= ' + datetime.newInstance(todate.year(), todate.month(), todate.day()).format('yyyy-MM-dd') + ' ' : '';
                    String regionFilter = metric.Subdivider__c == 'District' && String.isNotEmpty(regionName) ? ' District__r.Name IN (' + MetricHelpers.generateCommaSeperatedString(FHISurveysHelpers.getDistrictsInRegion(regionName), true) + ') ' : '';
                    regionFilter = metric.Subdivider__c == 'Subcounty' && String.isNotEmpty(regionName) ? ' Subcounty__r.District__r.Name IN (' + MetricHelpers.generateCommaSeperatedString(FHISurveysHelpers.getDistrictsInRegion(regionName), true) + ') ' : regionFilter;
                    clauses.add(subdivider);
                    clauses.add(dateRange);
                    clauses.add(regionFilter);
                    whereClause = joinClauses(clauses);
                    whereClause = String.isNotBlank(whereClause) ? ' ' + whereClause : whereClause;
                    query = query.contains('Sum') || query.contains('Count') ? query + whereClause + ' GROUP BY M_E_Metric__c' : query;
                    System.debug(query);

                    Decimal value;
                    if (metric.On_The_Fly_Calculation_Type__c == 'Percentage' || metric.On_The_Fly_Calculation_Type__c == 'Average') {
                        List<AggregateResult> result = database.query(query);
                        value = result.size() > 0 ? (Decimal)result.get(0).get('denumerator') : 1;
                        Decimal value1 = result.size() > 0 ? (Decimal)result.get(0).get('numerator') : 0;
                        data.setCurrentDenumerator(value);
                        data.setCurrentNumerator(value1);
                    } 
                    else if (metric.On_The_Fly_Calculation_Type__c == 'Sum' || metric.On_The_Fly_Calculation_Type__c == 'Count') {
                        List<AggregateResult> result = database.query(query);
                        value = result.size() > 0 ? (Decimal)result.get(0).get('realValue') : 0;
                        value = value == null ? 0 : value;
                        data.setCurrentDenumerator(value);
                    }
                    else {
                        List<M_E_Metric_Data__c> result = database.query(query);
                        value = result.size() > 0 ? (Decimal)result.get(0).Manual_Value__c : 0;
                        Decimal value1 = result.size() > 0 ? (Decimal)result.get(0).Projected_Value__c : 0;
                        data.setCurrentRealValue(value);
                        data.setCurrentTarget(value1);
                        data.setCurrentId(String.valueOf(result.get(0).Id));
                    }
                    //set current total submissions
                    //this is the count of all submission made minus rejected ones
                    if(thisSection.Show_Break_Down__c){
                        String value1 = metric.Sub_Area__c;
                        value1 = value1 == null || value1.equalsIgnoreCase('Sub Area is not set') ? '' : value1;
                        data.setSubArea(value1);
                    }
                }
                metricDatas.add(data);
            }
        }
        return metricDatas;
    }

    @RemoteAction
    global static M_E_Metric_Data__c getMetricData(String id) {
        if(loadMetricData == null) {
            loadMetricData = loadMetricData(id);
        }
        return loadMetricData;
    }

    private static M_E_Metric_Data__c loadMetricData(String id) {

        return [SELECT
                Id,
                Name,
                Comment__c,
                Manual_Value__c,
                Actual_Value__c,
                Projected_Value__c,
                Date__c,
                Person__c,
                Person__r.District__c,
                District__c,
                M_E_Metric__r.Label__c,
                M_E_Metric__r.Name,
                M_E_Metric__r.Propagate_Targets__c,
                M_E_Metric__r.Metric_Section__r.RollOver_Time__c
            FROM
                M_E_Metric_Data__c
            WHERE
                id = :id];
    }

    public String joinClauses(List<String> clauses){
        String joined = '';
        for(String clause : clauses){
            if(String.isNotEmpty(clause)){
                joined += ' AND ' + clause;
            }
        }
        return joined;
    }
}