src/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>The label for this metric. Will be displayed on the dashboard.</description>
        <inlineHelpText>The label for this metric. Will be displayed on the dashboard.</inlineHelpText>
        <label>Label</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Actual_Value__c</fullName>
        <description>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</description>
        <inlineHelpText>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</inlineHelpText>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <description>Comment for this particular metric for this quarter</description>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>The district that this metric is for. Allows us to split the metrics by district when showing them on the dashboard</description>
        <inlineHelpText>Select the district that this metric is for</inlineHelpText>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manual_Value__c</fullName>
        <description>Manually set value for a metric. Will override the actual value in display</description>
        <label>Manual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually.</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UpdateMetricComponentController.cls
global with sharing class UpdateMetricComponentController {

    public static M_E_Metric_Data__c metricData { get; set; }
    public static String message { get; set; }

    public UpdateMetricComponentController() { }

    @RemoteAction
    global static M_E_Metric_Data__c getMetricData(String id) {
        return loadMetricData(id);
    }

    @RemoteAction
    global static void saveMetricData(String id, String comment, String manualValue, String target) {

        // Note that the validation on the data is done on the client side
        M_E_Metric_Data__c metric = loadMetricData(id);
        if (!comment.equals('')) {
            metric.Comment__c = comment;
        }
        if (!manualValue.equals('')) {
            metric.Manual_Value__c = Double.valueOf(manualValue);
        }
        if (!target.equals('')) {
            metric.Projected_Value__c = Double.valueOf(target);
        }
        Database.update(metric);
    }

    private static M_E_Metric_Data__c loadMetricData(String id) {

        return [SELECT
                Id,
                Name,
                Comment__c,
                Manual_Value__c,
                Actual_Value__c,
                Projected_Value__c,
                M_E_Metric__r.Label__c
            FROM
                M_E_Metric_Data__c
            WHERE
                id = :id];
    }

    static testMethod void testAll() {

        Account testOrg = Utils.createTestOrganisation('We');
        Database.insert(testOrg);

        M_E_Metric__c metric = Utils.createTestMetric(testOrg, 'sum', 'scale', false, 'were');
        Database.insert(metric);

        District__c district = Utils.createTestDistrict('at');
        Database.insert(district);

        M_E_Metric_Data__c metricDataTest = Utils.createTestMetricData(district, metric, 1.0, 1.0, Date.today());
        Database.insert(metricDataTest);

        saveMetricData((String)metricDataTest.Id, 'a', '5.0', '50.0');
        M_E_Metric_Data__c metricData2 = getMetricData(metricDataTest.Id);
        System.assertEquals(metricData2.Manual_Value__c, 5.0);
        System.assert(metricData2.Comment__c.equals('a'));
        System.assertEquals(metricData2.Projected_Value__c, 50.0);

    }
}