src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <fields>
        <fullName>ISO_Standard_Code__c</fullName>
        <label>ISO Standard Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LAC_Cooperative__c.object
<CustomObject>
    <description>Object that contains details about the cooperatives that farmers can belong to</description>
    <label>LAC Cooperative</label>
    <nameField>
        <label>LAC Cooperative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Cooperatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Farm_Area__c</fullName>
        <label>Farm Area</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cooperativeProfile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>cooperativeProfile</label>
        <referenceTo>LAC_Cooperative__c</referenceTo>
        <relationshipLabel>LAC_Farmer_Details_cooperative</relationshipLabel>
        <relationshipName>LAC_Farmer_Details_cooperative</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/cooperative_AreaFarmersChartTest.cls
@isTest
public class cooperative_AreaFarmersChartTest {

    static Country__c country;
    static Contact contact1;
    static LAC_Cooperative__c cooperative;
    static LAC_Farmer_Details__c farmer1;
    static LAC_Farmer_Details__c farmer2;
    static cooperative_AreaFarmersChart coopArea;

    /**
    * Create the objects needed to run the tests.
    * This includes:
    *    - One cooperative
    *    - Two LAC_Farmer_Details__c 
    *    
    */
    private static void prepareTest() {
            
        country = new Country__c(
            Name = 'country1',
            ISO_Standard_Code__c = 'COL'
        );
        insert country;
        
        contact1 = new Contact(
            LastName = 'lastname1'
        );
        Insert contact1;
        
        cooperative = new LAC_Cooperative__c(
            Name = 'coop1'
        );
        insert cooperative;
        
        farmer1 = new LAC_Farmer_Details__c(
            Name = 'farm1', 
            Farm_Area__c = 2
        );
        farmer1.cooperativeProfile__c = cooperative.Id;
        farmer1.Contact__c = contact1.Id;
        insert farmer1;
        
        farmer2 = new LAC_Farmer_Details__c(
            Name = 'farm2', 
            Farm_Area__c = 4
        );
        farmer2.cooperativeProfile__c = cooperative.Id;
        farmer2.Contact__c = contact1.Id;
        insert farmer2;
    }
    
    /**
    * Test amount of points to draw and maximum farm area 
    *
    */
    static testMethod void testGetFarmArea() {
        prepareTest();
        //validate farmers y cooperative created
        System.assertEquals(2, database.countquery('SELECT COUNT() FROM LAC_Farmer_Details__c'));
        System.assertEquals(1, database.countquery('SELECT COUNT() FROM LAC_Cooperative__c '));
        //validate farmers with assigned cooperative
        System.assertEquals(2, database.countquery('SELECT COUNT() FROM LAC_Farmer_Details__c where cooperativeProfile__c <> null '));
        coopArea = new cooperative_AreaFarmersChart(null);
        coopArea.cooperativeProp = cooperative;
        coopArea.getMaxFarmArea();
        //validate max farm area
        System.assertEquals(4.0, coopArea.maxFarmArea);
        //validate quantity of farms areas related to cooperative
        System.assertEquals(2, coopArea.getAreaFarmers().size());
        //validate amount of points to draw (barSerieData)
        System.assertEquals(5, coopArea.getCategories().size());
    }

}