src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <fields>
        <fullName>ISO_Standard_Code__c</fullName>
        <label>ISO Standard Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Construct that represents a group of People. Used by features including Agriculture Information channel, survey assignment, bulk SMS.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <description>A message sent to a user in our system</description>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of the message</description>
        <label>Subject</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>MSG-{00000000}</displayFormat>
        <label>Message ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>(optional) middle name for the person</description>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <description>Mobile phone number calculated based on Mobile Phone and Raw Mobile Number fields</description>
        <formula>/* If we have a Handset, use the number from its SIM Card */
IF( NOT( ISBLANK( Handset__c)),  
     Handset__r.SIM__r.Name, 
/* otherwise use the raw mobile number */
       Raw_Mobile_Number__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile Number</label>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Scheduled_Message_Queue__c.object
<CustomObject>
    <description>object to hold messages that are meant to be sent at a time in the future</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <defaultValue>NOW() + 30</defaultValue>
        <label>Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Group to which the message is directed</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Scheduled Message Queues</relationshipLabel>
        <relationshipName>Scheduled_Message_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>The message to be sent</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person to whom the message is directed</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Scheduled Message Queues</relationshipLabel>
        <relationshipName>Scheduled_Message_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Date_Time__c</fullName>
        <description>The date and time at which the message should be sent.</description>
        <label>Send Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_Via_Pulse__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Send message via pulse</description>
        <label>Send_Via_Pulse</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Via_Sms__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Send message via SMS</description>
        <label>Send_Via_Sms</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sender__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person sending the message</description>
        <label>Sender</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scheduled_Message_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <defaultValue>&quot;No Subject&quot;</defaultValue>
        <description>The subject or theme of the message</description>
        <label>Subject</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scheduled Message Queue</label>
    <nameField>
        <label>Scheduled Message Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Message Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduledMessageSender.cls
global class ScheduledMessageSender implements Schedulable {
 
   // CronExpression = Seconds Minutes Hours Day_of_month Month Day_of_week optional_year
     public static String cronExpression = '0 0 1-23 * * ?'; // run every hour, daily

     global void execute(SchedulableContext sc) {

        DateTime startTime = DateTime.now();
        String queryString = 
        	'SELECT ' 											+
                'Id, ' 											+
                'Group__c, ' 									+
                'Person__c, ' 									+
                'Person__r.First_Name__c, ' 					+
                'Person__r.Middle_Name__c, ' 					+
                'Person__r.Last_Name__c, ' 						+
                'Person__r.Mobile_Number__c, ' 					+
                'Person__r.Country__r.ISO_Standard_Code__c, ' 	+
                'Message__c, ' 									+
                'Sender__c, ' 									+
                'Sender__r.Name, ' 								+
                'Subject__c, ' 									+
                'Send_Date_Time__c, ' 							+
                'Expiration_Date__c, ' 							+
                'Send_Via_Pulse__c, ' 							+
                'Category__c, ' 								+
                'Send_Via_Sms__c ' 								+
            'FROM ' 											+
                'Scheduled_Message_Queue__c ' 					+
            'WHERE ' 											+
                'Send_Date_Time__c <= ' + MetricHelpers.convertDateTimeToString(startTime, false);
        ID batchprocessid = Database.executeBatch(new SendSMS(queryString, startTime), 10);
        //Message.sendScheduledMessages();
        //ErorLog.flush();r
     }
}