src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <description>Stores details of a market. Most importantly it stores the region that the market is in.</description>
    <fields>
        <fullName>Market__c</fullName>
        <description>Stores details of a market. Most importantly it stores the region that the market is in.</description>
        <inlineHelpText>This must be written in the same format as the feed supplies. i.e. as a proper noun e.g. Kalerwe</inlineHelpText>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>The region that the market is in</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central_Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eastern_Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western_Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern_Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern_Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Market</label>
    <nameField>
        <displayFormat>Market-{0000}</displayFormat>
        <label>Market Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Menu__c.object
<CustomObject>
    <description>Used to develop ckw search menus</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>The Name/Label for this menu</description>
        <inlineHelpText>The Name/Label for this menu</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Menu</label>
    <nameField>
        <displayFormat>M-{0000000000}</displayFormat>
        <label>Menu Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>A region in a given country</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country that the region is in</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Regions</relationshipLabel>
        <relationshipName>Regions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The display name of the region</description>
        <label>Display Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Region</label>
    <nameField>
        <displayFormat>REG-{000000000}</displayFormat>
        <label>Region Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MisLoadFitRss3_oTest.cls
/**
* Copyright (c) 2015 AppLab, Grameen Foundation
*
* Two classes are tested herein for 3.0 search;
* MisLoadFitRss3_o in which we test Loading of the RSS XML
* ScheduledMisLoadFitRss3_o where we test the scheduling
* Class List
* MisLoadFitRss3_o,
* ScheduledMisLoadFitRss3_o
*/
@isTest
private class MisLoadFitRss3_oTest {

    static MisLoadFitRss3_o batchKeywordsExporter = new MisLoadFitRss3_o();
    /**
    *   tests scheduling of the data loading operation*/

    static testmethod void testBatchScheduling() {
        //test scheduling
        String cronID = System.scheduleBatch(batchKeywordsExporter, 'Batch Load FIT Prices', 1);
        CronTrigger ct = [SELECT Id, TimesTriggered, NextFireTime
                          FROM CronTrigger
                          WHERE Id = :cronID];
        System.assertEquals(0, ct.TimesTriggered);
        System.debug('Next fire time: ' + ct.NextFireTime);
    }

    static testmethod void testBatchDataLoading() {
        Test.startTest();
        Menu__c menu = null;
        Integer result = [SELECT Count() FROM Menu__c WHERE Label__c = 'CKW 3.0 Search'];
        if (result == 0) {
            menu = new Menu__c(Label__c = 'CKW 3.0 Search');
            insert(menu);
        } else {
            menu = [SELECT Id, Label__c FROM Menu__c WHERE Label__c = 'CKW 3.0 Search'];
        }
        Country__c country = new Country__c();
        insert(country);
        Region__c region = new Region__c(Country__c = country.Id, Display_Name__c = 'North_Region');
        insert(region);
        Market__c market = new Market__c(Market__c = 'AmuruMarket', Region__c = 'North_Region');
        insert(market);
        Database.executeBatch(batchKeywordsExporter, 53);
        System.debug(LoggingLevel.DEBUG, 'New Menu Label ' + menu.Label__c);
        Test.stopTest();
    }
}