src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <fields>
        <fullName>ISO_Standard_Code__c</fullName>
        <label>ISO Standard Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physical handset assigned to this Person (in the case of GF-managed assets)</description>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Assignee</relationshipLabel>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SearchGetCountryCodeHelper.cls
/**
 *
 * Copyright (c) 2014 AppLab, Grameen Foundation
 *
 *  This class is a part of the CKW Search 3.0 Bundle
 *  Tests are in SearchServerTests class 
 **/
 public class SearchGetCountryCodeHelper {
 
    public static String getCountryCode(String jsonString) {
        // The response wrapper
        CountryCodeResponseWrapper response = new CountryCodeResponseWrapper();
        
        // Build the request object
        CountryCodeRequestWrapper request = null;
        try {
            request = (CountryCodeRequestWrapper)JSON.deserialize(jsonString, CountryCodeRequestWrapper.class);
            String countryCode = getPersonCountryCode(request);
            response.resultCode = '0';
            response.resultMessage = 'Country Code found';
            response.countryCode = countryCode;
            return JSON.serializePretty(response);
        }
        catch(Exception e) {
            response.resultCode = '10';
            response.resultMessage = 'Request could not be decoded';
            return JSON.serializePretty(response);
        }
    }
    
    private static String getPersonCountryCode(CountryCodeRequestWrapper request) {
        List<Person__c> people = new List<Person__c>();
        people = [Select Country__r.ISO_Standard_Code__c from Person__c where Handset__r.IMEI__c =:request.imei];
        if (people.size() > 0) {System.debug('countrycode='+people[0].Country__r.ISO_Standard_Code__c);
            String countryCode = people[0].Country__r.ISO_Standard_Code__c;
            if (countryCode == null) {
                return 'UG';
            }
            return countryCode;
        }
        else {
            // No person found, return UG by default
            return 'UG';
        }
    }
    
    class CountryCodeRequestWrapper {
        String request {get; set;}
        String imei {get; set;}
    }
    
    class CountryCodeResponseWrapper {
        String resultCode {get;set;}
        String resultMessage {get;set;}
        String countryCode {get; set;}
    }
 }