src/objects/Country__c.object
<CustomObject>
    <description>Store details about a country</description>
    <fields>
        <fullName>ISO_Standard_Code__c</fullName>
        <label>ISO Standard Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Construct that represents a group of People. Used by features including Agriculture Information channel, survey assignment, bulk SMS.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <description>A message sent to a user in our system</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>The body of the message</description>
        <label>Body</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Expiration_Time__c</fullName>
        <defaultValue>NOW() + 30</defaultValue>
        <description>The date/time that this message expires and will no longer be displayed. We will also periodically purge expired messages from the system.</description>
        <label>Expiration Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <description>The Salesforce user who sent the message</description>
        <label>From</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <description>The recipient of the message</description>
        <label>Recipient</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sent_Time__c</fullName>
        <defaultValue>Now()</defaultValue>
        <description>The time that the message was sent</description>
        <label>Sent Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of the message</description>
        <label>Subject</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>MSG-{00000000}</displayFormat>
        <label>Message ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Country where person comes from</description>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>(optional) middle name for the person</description>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <description>Mobile phone number calculated based on Mobile Phone and Raw Mobile Number fields</description>
        <formula>/* If we have a Handset, use the number from its SIM Card */
IF( NOT( ISBLANK( Handset__c)),  
     Handset__r.SIM__r.Name, 
/* otherwise use the raw mobile number */
       Raw_Mobile_Number__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mobile Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person_Group_Association__c.object
<CustomObject>
    <description>Junction object used for many-to-many relationship between Person and Group objects. The existence of a Person-Group Association is what defines a single &quot;membership&quot;.</description>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group associated with this junction object</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person-Group Association</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Person Group Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person-Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendSMSBatches.cls
/**
 *	For UGANDA SMSs
 *  This class attempts to resolve the limits you meet when sending a message to a group that
 *  consists of too many people - to be more specific, more than 1000 members 
 *
 */
global class SendSMSBatches implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
		
	Message message;
	String countryCode;
	String successMessage;
	String className;
    String pulse = 'PULSE';
    SendSMSViaEdnetUg sender;
	
	global SendSMSBatches(Message message, String countryCode) {
		this.successMessage = '';
		this.message = message;
		this.countryCode = countryCode;
        this.sender = new SendSMSViaEdnetUg();
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator(
            'SELECT '												+
                'Person__c, '										+
                'Person__r.Last_Name__c, '							+
                'Person__r.Middle_Name__c, '						+
                'Person__r.First_Name__c, '							+
                'Person__r.Country__r.ISO_Standard_Code__c, '		+
                'Person__r.Mobile_Number__c '						+
            'FROM '													+
                'Person_Group_Association__c '						+
            'WHERE '												+
                'Group__c = \'' + this.message.groupId + '\''
    	);
	}
	
	global void execute(Database.BatchableContext BC, List<Person_Group_Association__c> people) {
        
        List<Message__c> messages = new List<Message__c>();
    	String requestBody = sender.MESSAGE_XML_REQUEST_FORMAT;
    	String recipients = '';
        for (Person_Group_Association__c recipient : people) {
        	String pnumber = recipient.Person__r.Mobile_Number__c;
            if (pnumber == null || pnumber == '' || pnumber == 'null') {
                continue;
            }
            if (pnumber.startsWith('0')) {
                pnumber = pnumber.substring(1);
            }
        	recipients += String.format(sender.MESSAGE_XML_RECIPIENT_FORMAT, new String[]{ recipient.Person__c, countryCode + pnumber });
        	
        	
			Message__c mesge = new Message__c();
			mesge.Recipient__c = recipient.Person__c;
			mesge.Body__c = message.body;
			mesge.Subject__c = message.subject;
			mesge.Sent_Time__c = Datetime.now();
			mesge.Expiration_Time__c = message.expirationTime;
			mesge.Category__c = message.catgory;
			mesge.From__c = message.senderId;
			mesge.OwnerId = message.senderId;
			mesge.Type__c = 'SMS';
			messages.add(mesge);
        }
        
        requestBody = String.format(requestBody, new String[]{ sender.setting.Username__c, sender.setting.Password__c, sender.senderName, message.body, '', recipients });
        
		HttpRequest request = new HttpRequest();
        request.setMethod('POST');
        request.setBodyAsBlob(Blob.valueOf('XML=' + EncodingUtil.urlEncode(requestBody, 'UTF-8')));
        request.setHeader('Content-Type', 'application/xml');
        request.setHeader('Content-Length', String.valueOf(EncodingUtil.urlEncode(requestBody, 'UTF-8').length()));
        request.setEndpoint(sender.setting.Bulk_End_Point__c);
        System.debug(LoggingLevel.INFO, requestBody);
        
        HttpResponse resp = new Http().send(request);

		if(resp.getStatusCode() == 200) {
			
			String response = '';
	        Dom.XMLNode res = resp.getBodyDocument().getRootElement();
	        
	        String status = res.getChildElement('status', null).getText();
	        String credits = res.getChildElement('credits', null).getText();
	        String result = 'status=' + status + ',credits=' + credits;
        	System.debug(LoggingLevel.INFO, result);
	        if(!status.contains('-')) {
				insert messages;
        		System.debug(LoggingLevel.INFO, '*** Message Logs Created ***');
	        }
	        else {
	        	successMessage += '\N System failed to send ' + messages.size() + ' messages in this batch. Reason : ' + sender.RESPONSE_MAP.get(Integer.valueOf(status));
	        }
		}
		else {
	        successMessage += '\N System failed to send ' + messages.size() + ' messages in this batch. Reason : Failed request with status code ' + resp.getStatusCode();
		}
	}
	
	global void finish(Database.BatchableContext BC) {
		
		if(successMessage.length() > 0) {
			SendSMSViaEdnetUg.notify(successMessage);
		}
	}
}