src/objects/CQT_Taster__c.object
<CustomObject>
    <description>Coffee Quality Toolkit - Conected coffee producers</description>
    <fields>
        <fullName>eMail__c</fullName>
        <label>eMail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>firstName__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lastName__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>phoneNumber__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>CQT_Taster</label>
    <nameField>
        <label>CQT_Taster National ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CQT_Tasters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CQT_TasterEditDeleteController.cls
public class CQT_TasterEditDeleteController {

	public String editTasterid {get;set;} // commandlink edit property
    public String delTasterid {get;set;} // commandlink delete property
    
    list<CQT_Taster__c> listTasters = new list<CQT_Taster__c>();
   	list<CQT_Taster__c> listTasters1 = new list<CQT_Taster__c>();
    
    // Displaying tasters on vfpage
    public list<CQT_Taster__c> getlistTasters() {
      listTasters = [select Name, firstName__c, lastName__c, phoneNumber__c, eMail__c from CQT_Taster__c];
      return listTasters;
    }
    
     // To redirect to editpage.
     public PageReference editTaster() {
       pagereference ref = new pagereference('/apex/CQT_SaveTasterPage?id='+editTasterid);
       ref.setRedirect(False);
       return ref;   
    }
    
    // to delete the selected record
    public pagereference deleteTaster() {
        listTasters1 = [Select id, Name from CQT_Taster__c where id=: delTasterid];
        delete listTasters1;
        pagereference ref = new pagereference('/apex/CQT_TasterEditDeletePage');
        ref.setredirect(True);
        return ref;   
        //return null;
        //return new pagereference(page.CQT_TasterEditDeletePage.getUrl());
    }
    
    // to redirect to insert page.
    public PageReference insertNewTaster() {
        pagereference ref = new pagereference('/apex/CQT_InsertNewTasterPage');
        ref.setRedirect(True);
        return ref;
    }   
    
}