src/objects/CQT_Analysis__c.object
<CustomObject>
    <fields>
        <fullName>CoffeeSample__c</fullName>
        <label>CoffeeSample</label>
        <referenceTo>CQT_CoffeeSample__c</referenceTo>
        <relationshipLabel>CQT_Analysis</relationshipLabel>
        <relationshipName>CQT_Analysis</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dry__c</fullName>
        <description>Seco</description>
        <label>Dry</label>
        <picklist>
            <picklistValues>
                <fullName>6.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.00</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FraganceAroma__c</fullName>
        <description>Fragancia/Aroma</description>
        <label>Fragance/Aroma</label>
        <picklist>
            <picklistValues>
                <fullName>6.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.00</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RoastLevelOfSample__c</fullName>
        <description>Nivel de Muestra</description>
        <label>Roast level of sample</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Taster__c</fullName>
        <label>Taster</label>
        <referenceTo>CQT_Taster__c</referenceTo>
        <relationshipLabel>CQT_Analysis_Taster</relationshipLabel>
        <relationshipName>CQT_Analysis_Taster</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CQT_Analysis</label>
    <nameField>
        <displayFormat>CQA-{00000}</displayFormat>
        <label>CQT_Analysis Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CQT_Analysis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CQT_CoffeeSample__c.object
<CustomObject>
    <fields>
        <fullName>CoffeeBerryBorerPercent__c</fullName>
        <label>% Coffee Berry Borer</label>
        <picklist>
            <picklistValues>
                <fullName>0.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.00</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4.75</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.00</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GrainFirstGroupPercent__c</fullName>
        <label>% Grain First Group</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Humidity__c</fullName>
        <label>% Humidity</label>
        <picklist>
            <picklistValues>
                <fullName>8.0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.0</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LAC_Farmer__c</fullName>
        <label>LAC Farmer</label>
        <referenceTo>LAC_Farmer_Details__c</referenceTo>
        <relationshipLabel>CQT_CoffeeSamples_LAC_FD</relationshipLabel>
        <relationshipName>CQT_CoffeeSamples_LAC_FD</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;new&quot;</defaultValue>
        <description>values: new and analyzed</description>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variety__c</fullName>
        <label>Variety</label>
        <picklist>
            <picklistValues>
                <fullName>Blue Mountain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bourbon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Castillo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catimor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catuai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catuai 44</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caturra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garnica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geisha</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Icatu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jackson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Java</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lempira</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maragogipe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mondo Novo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montecristo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N39</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacamara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pache</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pache Colis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ruiru11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sarchimor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SL28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SL34</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sumatra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tabi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tekisisc</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CQT_CoffeeSample</label>
    <nameField>
        <label>CQT_CoffeeSample Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CQT_CoffeeSamples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>National_ID__c</fullName>
        <label>National ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Activo</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactivo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CQT_AnalysisPageController.cls
public class CQT_AnalysisPageController {
  
    public integer AnalysisAmount { get; set; }
    public CQT_Analysis__c[] AnalysisList { get; set; }
    public String Text { get; set; }
    public CQT_Analysis__c Analysis { get; set; }
    public CQT_Analysis__c Analysis2 { get; set; }
    public CQT_Analysis__c Analysis3 { get; set; }
    public CQT_Analysis__c Analysis4 { get; set; }
    
    private List<CQT_CoffeeSample__c> SampleList;
    transient public Component.Apex.pageBlockSection dynCustomCom {get;set;}
        
    public CQT_AnalysisPageController(){
        //Analysis = new CQT_Analysis__c(PerformanceFactor__c = 'PerformanceFactor_muestra1');
        //Analysis2 = new CQT_Analysis__c(PerformanceFactor__c = 'PerformanceFactor_muestra2');
        LoadSamplestoAnalysis();
    }
    
    private void LoadSamplestoAnalysis(){
        integer count = 0;
        SampleList = [SELECT Id, LAC_Farmer__r.National_ID__c, Humidity__c, CoffeeBerryBorerPercent__c, GrainFirstGroupPercent__c, Variety__c FROM CQT_CoffeeSample__c WHERE Status__c = 'new'];
        //List<CQT_Analysis__c> 
        AnalysisList = new List<CQT_Analysis__c>();
        //CQT_Analysis__c[] AnalysisList; 
        dynCustomCom = new Component.Apex.pageBlockSection(columns = 1);
        //dynCustomCom.title = 'prueba: ' + SampleList.size();
        CQT_Analysis__c tmpAnalysis;
        String str;
        for(CQT_CoffeeSample__c sample: SampleList){
            tmpAnalysis = new CQT_Analysis__c(CoffeeSample__c=sample.Id);
            AnalysisList.add(tmpAnalysis);
            //str = string.format('[Cédula productor:{0}] - [Humedad:{1}] - [%Broca:{2}] - [%GranoPG:{3}] - [Variedad:{4}]', new String[] {sample.LAC_Farmer__r.National_ID__c , sample.Humidity__c, sample.CoffeeBerryBorerPercent__c, String.valueOf(sample.GrainFirstGroupPercent__c), sample.Variety__c});
            if(tmpAnalysis.CoffeeSample__c != null)
            	dynCustomCom.childComponents.add(new Component.CQT_Analysis_v2Component(sObjAnalysis=tmpAnalysis, sObjAnalysisList=AnalysisList, CoffeeSample=sample, AdditionalInfo=string.valueOf(++count)));
        }
        if(SampleList.size() == 0)
            Text = 'No existen muestras para analizar';
        //dynCustomCom.childComponents.add(new Component.CQT_Analysis_v2Component(sObjAnalysis=Analysis, sObjAnalysisList=AnalysisList));
    }
    
    public PageReference SaveAllAnalysis() {
        
        try{
            String str;
            CQT_CoffeeSample__c tmpSample;
            integer count = 0;
            //data validation
        	for(CQT_Analysis__c cqtAnalysis: AnalysisList){
                str = DataValidation(cqtAnalysis);
                count++;
                if(!string.isEmpty(str)){
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'Campos a obligatorios análisis # ' + count + ': ' + str);
                    ApexPages.addMessage(myMsg);
                    return null;
                }
	        }
            //insert analysis and update each coffee sample
            for(CQT_Analysis__c cqtAnalysis: AnalysisList){
                Database.insert(cqtAnalysis);
                tmpSample = changeStatusSampleCoffee(cqtAnalysis.CoffeeSample__c);
                if(tmpSample != null)
                    Database.update(tmpSample);
            }
            PageReference pageRef = new PageReference('/apex/CQT_AnalysisPage');
            pageRef.setRedirect(true);
            return pageRef;
        }
        catch(Exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());
            ApexPages.addMessage(myMsg);
        }        
        return null;
    }

    private CQT_CoffeeSample__c changeStatusSampleCoffee(id idSample){
        for(CQT_CoffeeSample__c sample: SampleList){
            if(sample.Id == idSample){
                sample.Status__c = 'analyzed';
                return sample;
            }                
        }
        return null;
    }
    
    private String DataValidation(CQT_Analysis__c AnalysisVal){
    	String str = '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Taster__c))? 'Catador, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.RoastLevelOfSample__c))? 'Nivel de la muestra, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.FraganceAroma__c))? 'Fragancia/Aroma, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Dry__c))? 'Seco, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Break__c))? 'Espuma, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Flavor__c))? 'Sabor, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.AfterTaste__c))? 'S. Residual, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Acidity__c))? 'Acidez, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Intensity__c))? 'Intensidad, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Body__c))? 'Cuerpo, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Level__c))? 'Intensidad, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Uniformity__c))? 'Uniformidad, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Balance__c))? 'Balance, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.CleanCup__c))? 'Taza Limpia, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Sweetness__c))? 'Dulzor, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.Overall__c))? 'Puntaje Catador, ': '';
        str += (FieldIsEmptyOrNull(AnalysisVal.IntensityDefect__c))? 'Intensidad Defectos, ': '';
        return str;
    }
    
    private boolean FieldIsEmptyOrNull(object obj){
        if (obj == null)
            return true;
        else if (string.isEmpty(string.valueOf(obj)))
            return true;
        else return false;
    }
}