src/objects/Dashboard_Section__c.object
<CustomObject>
    <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
    <fields>
        <fullName>Dashboard__c</fullName>
        <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
        <inlineHelpText>Select the dashboard that this section belongs to</inlineHelpText>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Sections</relationshipLabel>
        <relationshipName>Dashboard_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this section is active i.e. should be displayed on the dashboard</description>
        <inlineHelpText>Uncheck if this section should not be on the dashboard</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title to display on the page section that contains this section</description>
        <inlineHelpText>Enter the title that will head this section on the dashboard</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Dashboard Section</label>
    <nameField>
        <displayFormat>DS{0000000000}</displayFormat>
        <label>Dashboard Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dashboard_Selector__c.object
<CustomObject>
    <description>Controls what selectors are to go on a dashboard selector</description>
    <fields>
        <fullName>Dashboard_Section__c</fullName>
        <label>Dashboard Section</label>
        <referenceTo>Dashboard_Section__c</referenceTo>
        <relationshipLabel>Dashboard Selectors</relationshipLabel>
        <relationshipName>Dashboard_Selectors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Period__c</fullName>
        <description>The time period that each metric data lasts for</description>
        <inlineHelpText>Select how often you want the metrics to change</inlineHelpText>
        <label>Date Period</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_CKW__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the CKW selector</description>
        <inlineHelpText>Check to include the CKW selector in the dashboard selector</inlineHelpText>
        <label>Show CKW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Country__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the country selector</description>
        <inlineHelpText>Check to display the country selector</inlineHelpText>
        <label>Show Country</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Data_Validator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the data validator selector</description>
        <inlineHelpText>Check to include the Data Validator selector in the dashboard selector</inlineHelpText>
        <label>Show Data Validator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Dates__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the date selectors</description>
        <inlineHelpText>Check to show the date range selectors</inlineHelpText>
        <label>Show Dates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_District__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to include the district selector.</description>
        <inlineHelpText>Show the district selector</inlineHelpText>
        <label>Show District</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Farmer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the farmer selector</description>
        <inlineHelpText>Check to include the farmer selector in the dashboard selector</inlineHelpText>
        <label>Show Farmer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Field_Officer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the field officer selector</description>
        <inlineHelpText>Check to include the field officer selector in the dashboard selector</inlineHelpText>
        <label>Show Field Officer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_MTN_Chan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the MTN Channels selector</description>
        <inlineHelpText>Check to include the MTN Channels selector</inlineHelpText>
        <label>Show MTN Chan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Metric_Date_Selector__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the metric date selector</description>
        <inlineHelpText>Check to show the metric date selector. Only check if not showing the normal date selector</inlineHelpText>
        <label>Show Metric Date Selector</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Person__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to show the person selector</description>
        <inlineHelpText>Check to show the person selector</inlineHelpText>
        <label>Show Person</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Region__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the region selector</description>
        <inlineHelpText>Check to include the region selector</inlineHelpText>
        <label>Show Region</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Subcounty__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the subcounty selector</description>
        <inlineHelpText>Check to show the subcounty selector</inlineHelpText>
        <label>Show Subcounty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Submit_Button__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Show the submit button on the selector. Not always needed if the selector is embedded on none dashboard page</description>
        <inlineHelpText>Uncheck to hide the submit button on the selector</inlineHelpText>
        <label>Show Submit Button</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that the selector should start from. Will not allow any dates to be input earlier that this</description>
        <inlineHelpText>Choose the date that is the earliest you wish to see data from</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Dashboard Selector</label>
    <nameField>
        <displayFormat>DSC{0000000000}</displayFormat>
        <label>Dashboard Selector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Selectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FieldOfficerBreakDownController.cls
/**
 * Controller for the break down page for the field office dashboard.
 * Decides what type of break down it is and then allow the correct component to load
 */
public with sharing class FieldOfficerBreakDownController extends ParentComponentBase {

    public override void rebuildParameters() {
        this.getParentMap().get('DashboardSelectorKey').rebuildParameters();
        this.setParameters(this.getParentMap().get('DashboardSelectorKey').getParameters());
    }

    public String getAccountName() {
        return 'AppLab Uganda';
    }

    private Dashboard_Selector__c selector;
    public Dashboard_Selector__c getSelector() {
        return this.selector;
    }

    private Boolean showSelector = true;
    public Boolean getShowSelector() {
        return this.showSelector;
    }
    public void setShowSelector(Boolean value) {
        this.showSelector = value;
    }

    private Boolean showGraph = false;
    public Boolean getShowGraph() {
        return this.showGraph;
    }
    public void setShowGraph(Boolean value) {
        this.showGraph = value;
    }

    private Boolean showComment = false;
    public Boolean getShowComment() {
        return this.showComment;
    }
    public void setShowComment(Boolean value) {
        this.showComment = value;
    }

    private String isRefresh;
    public String getIsRefresh() {
        return 'false';
    }

    private String dateToShow;
    public String id { get; set; }
    public String getObjectName()  {
        return '';
    }
    public Integer getRowCount() {
        return 50;
    }

    private String personId;

    public FieldOfficerBreakDownController() {

        PageReference pageRef = ApexPages.currentPage();

        // Get the url params
        this.dateToShow = pageRef.getParameters().get('date');
         if (this.dateToShow != null && !this.dateToShow.equals('')) {
                this.dateToShow = this.dateToShow.replace('sp', ' ');
        }
 
        this.id = pageRef.getParameters().get('id');
        this.personId = pageRef.getParameters().get('foId');

        fetchSelector(pageRef.getParameters().get('selector'));

        // Get the section to display based on what is passed in
        String typeToLoad = pageRef.getParameters().get('type');
        if (typeToLoad != null && typeToLoad.equals('graph')) {
            setShowGraph(true);
        }
        else if (typeToLoad != null && typeToLoad.equals('comment')) {
            setShowComment(true);
        }
        else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'The type of break down you are trying to view does not exist. Please contact support'));
        }
    }

    private void fetchSelector(String id) {

        if (id == null || id.equals('')) {
            setShowSelector(false);
            return;
        }

        List<Dashboard_Selector__c> selectors = 
            [SELECT
                Show_Dates__c,
                Show_Metric_Date_Selector__c,
                Show_Country__c,
                Show_Region__c,
                Show_District__c,
                Show_Subcounty__c,
                Show_Person__c,
                Show_Data_Validator__c,
                Show_CKW__c,
                Show_Farmer__c,
                Show_Field_Officer__c,
                Show_MTN_Chan__c,
                Date_Period__c,
                Start_Date__c,
                Dashboard_Selector__c.Show_Submit_Button__c
            FROM
                Dashboard_Selector__c
            WHERE
                Is_Active__c = true
                AND Id = :id
            ORDER BY
                CreatedDate DESC];

        if (selectors.size() == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No selector exists for the id passed in. Check that the selector is still active'));
            return;
        }
        this.selector = selectors[0];
    }

    public PageReference refreshData() {
        return null;
    }

    static testMethod void testGraphController() {

        // Create the dashboard selector
        Account account = new Account();
        account.Name = 'Account';
        account.BillingState = 'CA';
        Database.insert(account);

        Dashboard__c dash = new Dashboard__c();
        dash.Account__c = account.Id;
        dash.Title__c = 'Title';
        dash.Description__c = 'Description';
        Database.insert(dash);

        Dashboard_Section__c section = new Dashboard_Section__c();
        section.Dashboard__c = dash.Id;
        section.Title__c = 'Title';
        Database.insert(section);

        Dashboard_Selector__c selector = new Dashboard_Selector__c();
        selector.Show_Person__c = true;
        selector.Show_Metric_Date_Selector__c = true;
        selector.Show_Dates__c = true;
        selector.Show_Subcounty__c = true;
        selector.Show_District__c = true;
        selector.Dashboard_Section__c = section.id;
        selector.Start_Date__c = Date.today();
        Database.insert(selector);


        PageReference pageRef = Page.FieldOfficerBreakDown;
        pageRef.getParameters().put('type', 'graph');
        pageRef.getParameters().put('selector', selector.Id);
        Test.setCurrentPageReference(pageRef);
        Test.startTest();

        FieldOfficerBreakDownController controller = new FieldOfficerBreakDownController();
        controller.getAccountName();
        controller.setShowGraph(controller.getShowGraph());
        controller.setShowSelector(controller.getShowSelector());
        controller.setShowComment(controller.getShowComment());
        controller.getRowCount();
        controller.getObjectName();
        controller.getIsRefresh();
    }
}