src/objects/Dashboard_Section__c.object
<CustomObject>
    <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
    <fields>
        <fullName>Dashboard__c</fullName>
        <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
        <inlineHelpText>Select the dashboard that this section belongs to</inlineHelpText>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Sections</relationshipLabel>
        <relationshipName>Dashboard_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Selector__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this section should have a selector in it</description>
        <inlineHelpText>Check if this selection has a selector in it that controls the metrics, maps, graphs, etc displayed</inlineHelpText>
        <label>Has Selector</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title to display on the page section that contains this section</description>
        <inlineHelpText>Enter the title that will head this section on the dashboard</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Dashboard Section</label>
    <nameField>
        <displayFormat>DS{0000000000}</displayFormat>
        <label>Dashboard Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dashboard_Selector__c.object
<CustomObject>
    <description>Controls what selectors are to go on a dashboard selector</description>
    <fields>
        <fullName>Dashboard_Section__c</fullName>
        <label>Dashboard Section</label>
        <referenceTo>Dashboard_Section__c</referenceTo>
        <relationshipLabel>Dashboard Selectors</relationshipLabel>
        <relationshipName>Dashboard_Selectors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Period__c</fullName>
        <description>The time period that each metric data lasts for</description>
        <inlineHelpText>Select how often you want the metrics to change</inlineHelpText>
        <label>Date Period</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Dashboard Selector</label>
    <nameField>
        <displayFormat>DSC{0000000000}</displayFormat>
        <label>Dashboard Selector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Selectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Graph_Parameter__c.object
<CustomObject>
    <description>Definition of a graph. This includes all the parameters that can go into the graph</description>
    <fields>
        <fullName>Dashboard_Section__c</fullName>
        <description>The section of a dashboard that this graph belongs to</description>
        <inlineHelpText>Choose the dashboard section that this graph will be displayed in</inlineHelpText>
        <label>Dashboard Section</label>
        <referenceTo>Dashboard_Section__c</referenceTo>
        <relationshipLabel>Graph Parameters</relationshipLabel>
        <relationshipName>Graph_Parameters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Period__c</fullName>
        <description>The gap between dates on the xAxis. Only used if xAxisSeries is Date</description>
        <inlineHelpText>Select the time period between values on the xAxis if the xAxis is of type date</inlineHelpText>
        <label>Date Period</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Year</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Default_Show__c</fullName>
        <defaultValue>3</defaultValue>
        <description>The number of points to show on a graphs xAxis by default</description>
        <inlineHelpText>Choose how many points on the xAxis should be shown by default. Defaults to 3</inlineHelpText>
        <label>Default Show</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Legend_Color__c</fullName>
        <description>The colour that the legend on the graph will display as</description>
        <inlineHelpText>Select the colour that the legend on the graph will be displayed in</inlineHelpText>
        <label>Legend Color</label>
        <picklist>
            <picklistValues>
                <fullName>Black</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Show_Data_Inline__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show a table of the data inline with the graph. Will only show up on when a graph is part of a dashboard as opposed to being shown on its own</description>
        <inlineHelpText>Check to show the data on the graph in a table next to the graph</inlineHelpText>
        <label>Show Data Inline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title_Color__c</fullName>
        <description>The colour that the title will be displayed as</description>
        <inlineHelpText>Select the colour that the title will be displayed as</inlineHelpText>
        <label>Title Color</label>
        <picklist>
            <picklistValues>
                <fullName>Black</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The title for the graph</description>
        <inlineHelpText>Enter a title that will be displayed on this graph</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type_Of_Graph__c</fullName>
        <description>The type of graph to be displayed</description>
        <inlineHelpText>Pick the display method that this graph has</inlineHelpText>
        <label>Type Of Graph</label>
        <picklist>
            <picklistValues>
                <fullName>BarChart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ColumnChart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LineChart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PieChart</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>xAxis_Color__c</fullName>
        <description>The colour that the title of the xAxis will be displayed in</description>
        <inlineHelpText>Select the colour that the title of the xAxis will be displayed in</inlineHelpText>
        <label>xAxis Color</label>
        <picklist>
            <picklistValues>
                <fullName>Black</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>xAxis_Series__c</fullName>
        <description>The series that is along the xAxis</description>
        <inlineHelpText>Select what is to be displayed along the xAxis</inlineHelpText>
        <label>xAxis Series</label>
        <picklist>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Keywords</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcounty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BVAT Farming Types</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BVAT Content Areas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BVAT Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BVAT Crop Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BVAT Animal Keeping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BVAT Human Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BVAT Other Content</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>xAxis_Title__c</fullName>
        <description>The title to go on the xAxis of a graph</description>
        <inlineHelpText>Enter the title that is for the xAxis of this graph</inlineHelpText>
        <label>xAxis Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>yAxis_Color__c</fullName>
        <description>The colour that the yAxis title is displayed as</description>
        <inlineHelpText>Select the colour that the yAxis title is displayed as</inlineHelpText>
        <label>yAxis Color</label>
        <picklist>
            <picklistValues>
                <fullName>Black</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>yAxis_Title__c</fullName>
        <description>The title to be displayed on the yAxis of the graph</description>
        <inlineHelpText>Enter the title for the yAxis</inlineHelpText>
        <label>yAxis Title</label>
        <type>TextArea</type>
    </fields>
    <label>Graph Parameter</label>
    <nameField>
        <displayFormat>GP{0000000000}</displayFormat>
        <label>Graph Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graph Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MTN_Channels_Activity__c.object
<CustomObject>
    <description>A representation of one activity carried out be a Channels Staff member.</description>
    <fields>
        <fullName>Outlet_Type__c</fullName>
        <description>The type of outlet that the staff member visited</description>
        <label>Outlet Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel station</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kiosk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Money shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supermarket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>MTN Channels Activity</label>
    <nameField>
        <displayFormat>MCA{YY}{MM}{DD}{0000000000}</displayFormat>
        <label>MTN Channels Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MTN Channels Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MtnChannelsExpandedController.cls
public with sharing class MtnChannelsExpandedController extends ParentComponentBase {


    public MtnChannelsExpandedController() {
        PageReference pageRef = ApexPages.currentPage();
        this.graph = pageRef.getParameters().get('id');
        String typeOfPage = pageRef.getParameters().get('type');

        if (this.graph == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'An id has not been provided so cannot display a visual'));
            System.debug(LoggingLevel.INFO, 'No id provided so cannot continue');
        }
        else {

            if (typeOfPage.equals('graph')) {
                loadGraph();
            }
            else {
                System.debug(LoggingLevel.INFO, 'Unrecognised type: ' + typeOfPage);
            }
            loadSelector();
            setxAxisType('1');
        }
    }

    public String graph { get; set; }

    public Dashboard_Selector__c selector { get; set; }
    private String sectionId;

    public override void rebuildParameters() {
        this.getParentMap().get('DashboardSelectorKey').rebuildParameters();
        this.setParameters(this.getParentMap().get('DashboardSelectorKey').getParameters());
        addParameter('outletType' + getSectionKey(), this.getOutletType());
        addParameter('stockType' + getSectionKey(), this.getStockType());
        addParameter('merchandiseType' + getSectionKey(), this.getMerchandiseType());
    }

    // Store the selected outlet type
    private String outletType;
    public String getOutletType() {
        return this.outletType;
    }
    public void setOutletType(String value) {
        this.outletType = value;
    }

    // Get the available outlet types
    private List<SelectOption> outletTypes;
    public List<SelectOption> getOutletTypes() {

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '---All--'));
        Schema.DescribeFieldResult field = MTN_Channels_Activity__c.Outlet_Type__c.getDescribe();
        for (Schema.PicklistEntry f : field.getPicklistValues()) {
            options.add(new SelectOption(f.getLabel(), f.getLabel()));
        }
        return options;
    }

    // Store the selected stock type
    private String stockType;
    public String getStockType() {
        return this.stockType;
    }
    public void setStockType(String value) {
        this.stockType = value;
    }

    // Get the available types of stock
    private List<SelectOption> stockTypes;
    public List<SelectOption> getStockTypes() {

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '---All--'));
        options.add(new SelectOption('Modems', 'Modems'));
        options.add(new SelectOption('Phones', 'Phones'));
        options.add(new SelectOption('Easy_Load', 'Easy Load'));
        options.add(new SelectOption('Scratch_Cards', 'Scratch Cards'));
        options.add(new SelectOption('Sim_Packs', 'SIM Packs'));
        return options;
    }

    // Store the selected merchandise type
    private String merchandiseType;
    public String getMerchandiseType() {
        return this.merchandiseType;
    }
    public void setMerchandiseType(String value) {
        this.merchandiseType = value;
    }

    // Get the available types of merchandise
    private List<SelectOption> merchandiseTypes;
    public List<SelectOption> getMerchandiseTypes() {

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '---All--'));
        options.add(new SelectOption('Poster', 'Poster'));
        options.add(new SelectOption('Placard', 'Placards'));
        options.add(new SelectOption('SIM', 'SIM Pack Holder'));
        options.add(new SelectOption('Light_Box', 'Light Box'));
        options.add(new SelectOption('Co_Brand', 'Co-branded Box'));
        options.add(new SelectOption('Wall', 'Wall Branding'));
        options.add(new SelectOption('Dangler', 'Dangler'));
        options.add(new SelectOption('Other', 'Other'));
        options.add(new SelectOption('None', 'None'));
        return options;
    }

    private String xAxisType;
    public String getxAxisType() {
        return this.xAxisType;
    }
    public void setxAxisType(String value) {
        this.xAxisType = value;
    }

    public sObject graphParameter { get; set; }
    public Boolean showGraph { get; set; }

    private String accountName;
    public String getAccountName() {
        return this.accountName;
    }
    private void setAccountName(String value) {
        this.accountName = value;
    }

    private void loadGraph() {

        Graph_Parameter__c loadedGraphParameter = [SELECT
                Id,
                Name,
                Title__c,
                Title_Color__c,
                Legend_Color__c,
                Type_Of_Graph__c,
                xAxis_Series__c,
                xAxis_Title__c,
                xAxis_Color__c,
                yAxis_Color__c,
                yAxis_Title__c,
                Date_Period__c,
                Default_Show__c,
                Show_Data_Inline__c,
                Dashboard_Section__r.Has_Selector__c,
                Dashboard_Section__c,
                Dashboard_Section__r.Dashboard__r.Account__r.Name
            FROM 
                Graph_Parameter__c
            WHERE
                xAxis_Title__c = :this.graph];
        this.accountName = loadedGraphParameter.Dashboard_Section__r.Dashboard__r.Account__r.Name;
        this.graphParameter = loadedGraphParameter;
        this.sectionId = loadedGraphParameter.Dashboard_Section__c;
        this.showGraph = true;
    }

    private void loadSelector() {

        Dashboard_Selector__c[] selectors = [
            SELECT
                Name,
                Id,
                Show_Dates__c,
                Show_Metric_Date_Selector__c,
                Show_Country__c,
                Show_Region__c,
                Show_District__c,
                Show_Subcounty__c,
                Show_Person__c,
                Show_CKW__c,
                Show_Farmer__c,
                Show_MTN_Chan__c,
                Date_Period__c,
                Show_Submit_Button__c,
                Start_Date__c
            FROM
                Dashboard_Selector__c
            WHERE
                Dashboard_Section__c = :this.sectionId];

        if (selectors.size() != 0) {
            this.selector = selectors[0];
        }
    }

    /**
     * Refresh all the graphs on the dashboard
     */
    public PageReference refreshAll() {

        this.setOutletType(Apexpages.currentPage().getParameters().get('outletType'));
        this.setStockType(Apexpages.currentPage().getParameters().get('stockType'));
        this.setMerchandiseType(Apexpages.currentPage().getParameters().get('merchandiseType'));
        this.setxAxisType(Apexpages.currentPage().getParameters().get('xAxisType'));
        return null;
    }
}