src/objects/Dashboard_Section__c.object
<CustomObject>
    <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
    <fields>
        <fullName>Dashboard__c</fullName>
        <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
        <inlineHelpText>Select the dashboard that this section belongs to</inlineHelpText>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Sections</relationshipLabel>
        <relationshipName>Dashboard_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dashboard Section</label>
    <nameField>
        <displayFormat>DS{0000000000}</displayFormat>
        <label>Dashboard Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dashboard_Selector__c.object
<CustomObject>
    <description>Controls what selectors are to go on a dashboard selector</description>
    <fields>
        <fullName>Dashboard_Section__c</fullName>
        <label>Dashboard Section</label>
        <referenceTo>Dashboard_Section__c</referenceTo>
        <relationshipLabel>Dashboard Selectors</relationshipLabel>
        <relationshipName>Dashboard_Selectors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Period__c</fullName>
        <description>The time period that each metric data lasts for</description>
        <inlineHelpText>Select how often you want the metrics to change</inlineHelpText>
        <label>Date Period</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Show_CKW__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the CKW selector</description>
        <inlineHelpText>Check to include the CKW selector in the dashboard selector</inlineHelpText>
        <label>Show CKW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Country__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the country selector</description>
        <inlineHelpText>Check to display the country selector</inlineHelpText>
        <label>Show Country</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Data_Validator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the data validator selector</description>
        <inlineHelpText>Check to include the Data Validator selector in the dashboard selector</inlineHelpText>
        <label>Show Data Validator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Dates__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the date selectors</description>
        <inlineHelpText>Check to show the date range selectors</inlineHelpText>
        <label>Show Dates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_District__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to include the district selector.</description>
        <inlineHelpText>Show the district selector</inlineHelpText>
        <label>Show District</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Farmer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the farmer selector</description>
        <inlineHelpText>Check to include the farmer selector in the dashboard selector</inlineHelpText>
        <label>Show Farmer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Field_Officer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the field officer selector</description>
        <inlineHelpText>Check to include the field officer selector in the dashboard selector</inlineHelpText>
        <label>Show Field Officer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_MTN_Chan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the MTN Channels selector</description>
        <inlineHelpText>Check to include the MTN Channels selector</inlineHelpText>
        <label>Show MTN Chan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Metric_Date_Selector__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the metric date selector</description>
        <inlineHelpText>Check to show the metric date selector. Only check if not showing the normal date selector</inlineHelpText>
        <label>Show Metric Date Selector</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Person__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to show the person selector</description>
        <inlineHelpText>Check to show the person selector</inlineHelpText>
        <label>Show Person</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Region__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the region selector</description>
        <inlineHelpText>Check to include the region selector</inlineHelpText>
        <label>Show Region</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Subcounty__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the subcounty selector</description>
        <inlineHelpText>Check to show the subcounty selector</inlineHelpText>
        <label>Show Subcounty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Submit_Button__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Show the submit button on the selector. Not always needed if the selector is embedded on none dashboard page</description>
        <inlineHelpText>Uncheck to hide the submit button on the selector</inlineHelpText>
        <label>Show Submit Button</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that the selector should start from. Will not allow any dates to be input earlier that this</description>
        <inlineHelpText>Choose the date that is the earliest you wish to see data from</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Dashboard Selector</label>
    <nameField>
        <displayFormat>DSC{0000000000}</displayFormat>
        <label>Dashboard Selector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Selectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MTN_Channels_Activity__c.object
<CustomObject>
    <description>A representation of one activity carried out be a Channels Staff member.</description>
    <fields>
        <fullName>Outlet_Type__c</fullName>
        <description>The type of outlet that the staff member visited</description>
        <label>Outlet Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel station</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kiosk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Money shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pharmacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Street vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supermarket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <formula>DATEVALUE(Start_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>MTN Channels Activity</label>
    <nameField>
        <displayFormat>MCA{YY}{MM}{DD}{0000000000}</displayFormat>
        <label>MTN Channels Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MTN Channels Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MtnChannelsSelector.cls
public with sharing class MtnChannelsSelector extends ParentComponentBase {

    private Boolean selectorLoaded = false;

    // The selector object that controls the display
    private Dashboard_Selector__c selector;
    public Dashboard_Selector__c getSelector() {

        if (!this.selectorLoaded) {
            this.selector = [
                SELECT
                    Name,
                    Id,
                    Show_Dates__c,
                    Show_Metric_Date_Selector__c,
                    Show_Country__c,
                    Show_Region__c,
                    Show_District__c,
                    Show_Subcounty__c,
                    Show_Person__c,
                    Show_Data_Validator__c,
                    Show_CKW__c,
                    Show_Farmer__c,
                    Show_Field_Officer__c,
                    Show_MTN_Chan__c,
                    Date_Period__c,
                    Show_Submit_Button__c,
                    Start_Date__c
                FROM
                    Dashboard_Selector__c
                WHERE
                    Dashboard_Section__r.Dashboard__r.Name = 'MTN Channels'
            ];
        }
        return this.selector;
    }

    // Get the parameters out from the selector on the page
    public override void rebuildParameters() {
        this.getParentMap().get('DashboardSelectorKey').rebuildParameters();
        this.setParameters(this.getParentMap().get('DashboardSelectorKey').getParameters());
        addParameter('outletTypekey', this.getOutletType());
        addParameter('stockTypekey', this.getStockType());
        addParameter('merchandiseTypekey', this.getMerchandiseType());
    }

    // Store the selected outlet type
    private String outletType;
    public String getOutletType() {
        return this.outletType;
    }
    public void setOutletType(String value) {
        this.outletType = value;
    }

    // Get the available outlet types
    private List<SelectOption> outletTypes;
    public List<SelectOption> getOutletTypes() {

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '---All---'));
        Schema.DescribeFieldResult field = MTN_Channels_Activity__c.Outlet_Type__c.getDescribe();
        for (Schema.PicklistEntry f : field.getPicklistValues()) {
            options.add(new SelectOption(f.getLabel(), f.getLabel()));
        }
        return options;
    }

    // Store the selected stock type
    private String stockType;
    public String getStockType() {
        return this.stockType;
    }
    public void setStockType(String value) {
        this.stockType = value;
    }

    // Get the available types of stock
    private List<SelectOption> stockTypes;
    public List<SelectOption> getStockTypes() {

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '---All---'));
        options.add(new SelectOption('Modems', 'Modems'));
        options.add(new SelectOption('Phones', 'Phones'));
        options.add(new SelectOption('Easy_Load', 'Easy Load'));
        options.add(new SelectOption('Scratch_Cards', 'Scratch Cards'));
        options.add(new SelectOption('Sim_Packs', 'SIM Packs'));
        return options;
    }

    // Store the selected merchandise type
    private String merchandiseType;
    public String getMerchandiseType() {
        return this.merchandiseType;
    }
    public void setMerchandiseType(String value) {
        this.merchandiseType = value;
    }

    // Get the available types of merchandise
    private List<SelectOption> merchandiseTypes;
    public List<SelectOption> getMerchandiseTypes() {

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '---All---'));
        options.add(new SelectOption('Poster', 'Poster'));
        options.add(new SelectOption('Placard', 'Placards'));
        options.add(new SelectOption('SIM', 'SIM Pack Holder'));
        options.add(new SelectOption('Light_Box', 'Light Box'));
        options.add(new SelectOption('Co_Brand', 'Co-branded Box'));
        options.add(new SelectOption('Wall', 'Wall Branding'));
        options.add(new SelectOption('Dangler', 'Dangler'));
        options.add(new SelectOption('Other', 'Other'));
        options.add(new SelectOption('None', 'None'));
        return options;
    }

    // Booleans to indicate the graphs that should be show
    private Boolean showOutlet;
    public Boolean getShowOutlet() {
        return this.showOutlet;
    }
    public void setShowOutlet(Boolean value) {
        this.showOutlet = value;
    }

    private Boolean showPromotion;
    public Boolean getShowPromotion() {
        return this.showPromotion;
    }
    public void setShowPromotion(Boolean value) {
        this.showPromotion = value;
    }

    private Boolean showStockGraph;
    public Boolean getShowStockGraph() {
        return this.showStockGraph;
    }
    public void setShowStockGraph(Boolean value) {
        this.showStockGraph = value;
    }

    private Boolean showDSD;
    public Boolean getShowDSD() {
        return this.showDSD;
    }
    public void setShowDSD(Boolean value) {
        this.showDSD = value;
    }

    private Boolean showCompetitorGraph;
    public Boolean getShowCompetitorGraph() {
        return this.showCompetitorGraph;
    }
    public void setShowCompetitorGraph(Boolean value) {
        this.showCompetitorGraph = value;
    }

    private Boolean showCompetitorStockGraph;
    public Boolean getShowCompetitorStockGraph() {
        return this.showCompetitorStockGraph;
    }
    public void setShowCompetitorStockGraph(Boolean value) {
        this.showCompetitorStockGraph = value;
    }

    private String xAxisType;
    public String getxAxisType() {
        return this.xAxisType;
    }
    public void setxAxisType(String value) {
        this.xAxisType = value;
    }

    /**
     * Refresh all the graphs on the dashboard
     */
    public PageReference refreshAll() {

        this.setShowOutlet(Boolean.valueOf(Apexpages.currentPage().getParameters().get('showOutlet')));
        this.setShowPromotion(Boolean.valueOf(Apexpages.currentPage().getParameters().get('showPromotion')));
        this.setShowStockGraph(Boolean.valueOf(Apexpages.currentPage().getParameters().get('showStockGraph')));
        this.setShowDSD(Boolean.valueOf(Apexpages.currentPage().getParameters().get('showDSD')));
        this.setShowCompetitorGraph(Boolean.valueOf(Apexpages.currentPage().getParameters().get('showCompetitorGraph')));
        this.setShowCompetitorStockGraph(Boolean.valueOf(Apexpages.currentPage().getParameters().get('showCompetitorStockGraph')));
        this.setOutletType(Apexpages.currentPage().getParameters().get('outletType'));
        this.setStockType(Apexpages.currentPage().getParameters().get('stockType'));
        this.setMerchandiseType(Apexpages.currentPage().getParameters().get('merchandiseType'));
        this.setxAxisType(Apexpages.currentPage().getParameters().get('xAxisType'));
        return null;
    }
    
    static testmethod void testAll() {
        MtnChannelsSelector controller = new MtnChannelsSelector();
        //controller.refreshAll();
        controller.getStockTypes();
        controller.getStockType();
        controller.getMerchandiseTypes();
        controller.getMerchandiseType();
        controller.getShowDSD();
        controller.getShowOutlet();
        controller.getShowCompetitorGraph();
        controller.getxAxisType();
    }
}