src/objects/Dashboard_Section__c.object
<CustomObject>
    <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
    <fields>
        <fullName>Dashboard__c</fullName>
        <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
        <inlineHelpText>Select the dashboard that this section belongs to</inlineHelpText>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Sections</relationshipLabel>
        <relationshipName>Dashboard_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The order in which the sections should be displayed</description>
        <inlineHelpText>Sorted in ascending order</inlineHelpText>
        <label>Display Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Has_Graphs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this section contains graphs</description>
        <inlineHelpText>Check if this section has graphs in it</inlineHelpText>
        <label>Has Graphs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Maps__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this section contains maps</description>
        <inlineHelpText>Check if the section contains any maps</inlineHelpText>
        <label>Has Maps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Metrics__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this section contains metrics</description>
        <inlineHelpText>Check if this section contains any metrics</inlineHelpText>
        <label>Has Metrics</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Selector__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this section should have a selector in it</description>
        <inlineHelpText>Check if this selection has a selector in it that controls the metrics, maps, graphs, etc displayed</inlineHelpText>
        <label>Has Selector</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this section is active i.e. should be displayed on the dashboard</description>
        <inlineHelpText>Uncheck if this section should not be on the dashboard</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title to display on the page section that contains this section</description>
        <inlineHelpText>Enter the title that will head this section on the dashboard</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Dashboard Section</label>
    <nameField>
        <displayFormat>DS{0000000000}</displayFormat>
        <label>Dashboard Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dashboard_Selector__c.object
<CustomObject>
    <description>Controls what selectors are to go on a dashboard selector</description>
    <fields>
        <fullName>Dashboard_Section__c</fullName>
        <label>Dashboard Section</label>
        <referenceTo>Dashboard_Section__c</referenceTo>
        <relationshipLabel>Dashboard Selectors</relationshipLabel>
        <relationshipName>Dashboard_Selectors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Period__c</fullName>
        <description>The time period that each metric data lasts for</description>
        <inlineHelpText>Select how often you want the metrics to change</inlineHelpText>
        <label>Date Period</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_BVAT_CIW__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays a dropdown box to select the CIW for the BVAT Dashboard</description>
        <inlineHelpText>Displays a dropdown box to select the CIW for the BVAT Dashboard</inlineHelpText>
        <label>Show BVAT CIW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Brac_Area__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Brac Area</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Brac_PA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show Brac PA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_CKW__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the CKW selector</description>
        <inlineHelpText>Check to include the CKW selector in the dashboard selector</inlineHelpText>
        <label>Show CKW</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Country__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the country selector</description>
        <inlineHelpText>Check to display the country selector</inlineHelpText>
        <label>Show Country</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Data_Validator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the data validator selector</description>
        <inlineHelpText>Check to include the Data Validator selector in the dashboard selector</inlineHelpText>
        <label>Show Data Validator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Dates__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the date selectors</description>
        <inlineHelpText>Check to show the date range selectors</inlineHelpText>
        <label>Show Dates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_District__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to include the district selector.</description>
        <inlineHelpText>Show the district selector</inlineHelpText>
        <label>Show District</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Farmer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the farmer selector</description>
        <inlineHelpText>Check to include the farmer selector in the dashboard selector</inlineHelpText>
        <label>Show Farmer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Field_Officer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the field officer selector</description>
        <inlineHelpText>Check to include the field officer selector in the dashboard selector</inlineHelpText>
        <label>Show Field Officer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Kenyan_County__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays Kenyan Counties used for the BVAT Dashboard</description>
        <inlineHelpText>Displays Kenyan Counties used for the BVAT Dashboard</inlineHelpText>
        <label>Show Kenyan County</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_MTN_Chan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the MTN Channels selector</description>
        <inlineHelpText>Check to include the MTN Channels selector</inlineHelpText>
        <label>Show MTN Chan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Metric_Date_Selector__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the metric date selector</description>
        <inlineHelpText>Check to show the metric date selector. Only check if not showing the normal date selector</inlineHelpText>
        <label>Show Metric Date Selector</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Opportunity_Farmer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the opportunity farmer selector</description>
        <inlineHelpText>Check to include the opportunity farmer selector in the dashboard selector</inlineHelpText>
        <label>Show Opportunity Farmer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Person__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to show the person selector</description>
        <inlineHelpText>Check to show the person selector</inlineHelpText>
        <label>Show Person</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Region__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the region selector</description>
        <inlineHelpText>Check to include the region selector</inlineHelpText>
        <label>Show Region</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Subcounty__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the subcounty selector</description>
        <inlineHelpText>Check to show the subcounty selector</inlineHelpText>
        <label>Show Subcounty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Submit_Button__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Show the submit button on the selector. Not always needed if the selector is embedded on none dashboard page</description>
        <inlineHelpText>Uncheck to hide the submit button on the selector</inlineHelpText>
        <label>Show Submit Button</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that the selector should start from. Will not allow any dates to be input earlier that this</description>
        <inlineHelpText>Choose the date that is the earliest you wish to see data from</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Dashboard Selector</label>
    <nameField>
        <displayFormat>DSC{0000000000}</displayFormat>
        <label>Dashboard Selector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Selectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Map_Parameter__c.object
<CustomObject>
    <description>Defines the starting point for a map that can be shown on a dashboard</description>
    <fields>
        <fullName>Dashboard_Section__c</fullName>
        <description>The section of a dashboard that this map is to be displayed on</description>
        <inlineHelpText>Select the dashboard section that this map belongs to</inlineHelpText>
        <label>Dashboard Section</label>
        <referenceTo>Dashboard_Section__c</referenceTo>
        <relationshipLabel>Map Parameters</relationshipLabel>
        <relationshipName>Map_Parameters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <description>The latitude that this map will start its display on</description>
        <inlineHelpText>Enter the latitude that the map should start on</inlineHelpText>
        <label>Latitude</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The title for the map</description>
        <inlineHelpText>Enter the title for the map</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Map Parameter</label>
    <nameField>
        <displayFormat>MP{0000000000}</displayFormat>
        <label>Map Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Metric_Section__c.object
<CustomObject>
    <description>A section that holds metrics to be shown on a dashboard</description>
    <fields>
        <fullName>Dashboard_Section__c</fullName>
        <description>The section of a dashboard that this metric section belongs to</description>
        <inlineHelpText>Please select the section of the dashboard that the metrics will be displayed in</inlineHelpText>
        <label>Dashboard Section</label>
        <referenceTo>Dashboard_Section__c</referenceTo>
        <relationshipLabel>Metric Sections</relationshipLabel>
        <relationshipName>Metric_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the section still active to be displayed on a dashboard</description>
        <inlineHelpText>Uncheck this to indicate that the metric section should be displayed</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that data started being collected for this dashboard. Will be the earliest option that shows up in the date selector for the selector</description>
        <inlineHelpText>Set to the date that data collection started. Should be the start of the time period i.e. if collection started 02/02/2012 and the roll over period is quarterly then the start date is 01/01/2012</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>The title for the metric section</description>
        <inlineHelpText>Enter a title for this section</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Metric Section</label>
    <nameField>
        <displayFormat>MS{0000000000}</displayFormat>
        <label>Metric Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metric Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GumutindoDashboardController.cls
/**
 *  Controller to load the settings for the Gumutindo Dashboard
 */

public with sharing class GumutindoDashboardController extends ParentComponentBase {

    private String dashboardName;
    private List<Dashboard_Section__c> sections;
    private Dashboard_Section__c section;
    
    public GumutindoDashboardController() {
        setDashboardName('a13b0000000lZem');
        setSections(loadSections());
    }

    public override void rebuildParameters() {

        if (this.getParentMap() != null && this.getParentMap().get('DashboardSelectora13b0000000lZemAAE') != null) {
            this.getParentMap().get('DashboardSelectora13b0000000lZemAAE').rebuildParameters();
            this.setParameters(this.getParentMap().get('DashboardSelectora13b0000000lZemAAE').getParameters());
        }
    }
 
    public String getDashboardName() {
        return this.dashboardName;
    }
    public void setDashboardName(String value) {
        this.dashboardName = value;
    }

    public void setSection(Dashboard_Section__c section) {
        this.section = section;
    }
    
    public Dashboard_Section__c getSection() {
        return this.section;
    }
    public List<Dashboard_Section__c> getSections() {
        return this.sections;
    }
    public void setSections(List<Dashboard_Section__c> values) {
        this.sections = values;
    }
    public List<Dashboard_Section__c> loadSections() {

        List<Dashboard_Section__c> sectionsToLoad = [SELECT
                Name,
                Id,
                Title__c,
                Has_Graphs__c,
                Has_Metrics__c,
                Has_Maps__c,
                Has_Selector__c,
                Dashboard__r.Account__r.Name
            FROM
                Dashboard_Section__c
            WHERE
                Dashboard__r.Name = :dashboardName
                AND Is_Active__c = true
            ORDER BY
                Display_Order__c];
        return sectionsToLoad;
    }
    
    private Dashboard_Selector__c selector;
    public Dashboard_Selector__c getSelector() {
        List<Dashboard_Selector__c> selectors = 
            [SELECT
                Show_Dates__c,
                Show_Metric_Date_Selector__c,
                Show_Country__c,
                Show_Region__c,
                Show_District__c,
                Show_Subcounty__c,
                Show_Person__c,
                Show_Opportunity_Farmer__c,
                Show_Data_Validator__c,
                Show_CKW__c,
                Show_Farmer__c,
                Show_Field_Officer__c,
                Show_MTN_Chan__c,
                Date_Period__c,
                Start_Date__c,
                Show_Submit_Button__c,
                Show_Brac_PA__c,
                Show_Brac_Area__c,
                Show_Kenyan_County__c,
                Show_BVAT_CIW__c
            FROM
                Dashboard_Selector__c
            WHERE
                Is_Active__c = true
                AND Dashboard_Section__r.Name = 'DS0000003855'
            ORDER BY
                CreatedDate DESC];

        if (selectors.size() == 0) {
            return null;
        }
        return selectors[0];

    }
    public void setSelector(Dashboard_Selector__c value) {
        this.selector = value;
    }
    
     private List<Map_Parameter__c> ciwMaps;
    public List<Map_Parameter__c> getCiwMaps() {
        this.ciwMaps = [SELECT
                Id,
                Name,
                Title__c,
                Latitude__c,
                Longitude__c,
                Type_Of_sObject__c,
                Zoom__c,
                Splitter__c
            FROM
                Map_Parameter__c
            WHERE 
                Name = 'MP0000000000'];
        return this.ciwMaps;
    }
    public void setCiwMaps(List<Map_Parameter__c> maps) {
        this.ciwMaps = maps;
    }
    
    private List<Metric_Section__c> ciwMetrics;
    public List<Metric_Section__c> getCiwMetrics() {
        this.ciwMetrics = [SELECT
                Id,
                Name,
                Title__c,
                Dashboard_Section__r.Dashboard__r.Account__r.Name,
                Description__c,
                RollOver_Time__c,
                Start_Date__c,
                Show_RollOver_Selector__c,
                Show_Targets__c,
                Show_Previous_Quarter__c,
                Show_Comments__c,
                Show_Break_Down__c,
                Show_Spark_Line__c,
                Show_Further_Link__c,
                Default_Show__c,
                Allow_Update__c,
                View_Mode__c
            FROM
                Metric_Section__c
            WHERE
                Name = 'MS0000000577'];
        return this.ciwMetrics;
    }
    public void setCiwMetrics(List<Metric_Section__c> metrics) {
        this.ciwMetrics = metrics;
    }

    
              

    @isTEst
    static testMethod void testGumutindoDashboardController() {

        DashboardController dashboard = new DashboardController();
        MetricHelpers.getQuarterStartMonth(3);
        MetricHelpers.getQuarterEndMonth(3);
        dashboard.getQuarters();
        dashboard.setQuarter('Jan - Mar 2010');
        System.assertEquals(dashboard.getQuarter(),'Jan - Mar 2010');
        MetricHelpers.getQuarterFirstDay('Jan - Mar 2010');
        MetricHelpers.getQuarterLastDay('Jan - Mar 2010');
        dashboard.setQuarter(MetricHelpers.getCurrentQuarterAsString(0));
        dashboard.getIsCurrentQuarter();
        dashboard.getIsEditMode();
        dashboard.getIsUpdateable();
        dashboard.setCurrentQuarter('Jan - Mar 2010');
        System.assertEquals(dashboard.getCurrentQuarter(),'Jan - Mar 2010');
        dashboard.setShowPreviousQuarter('Jan - Mar 2010');
        System.assertEquals(dashboard.getShowPreviousQuarter(),'true');
        
        System.assertNotEquals(null, dashboard.getQuarter());
        System.assertNotEquals(null, dashboard.getDistrictList());
        System.assertNotEquals(null, dashboard.getImpactData());
        System.assertNotEquals(null, dashboard.getQualityData());
        System.assertNotEquals(null, dashboard.getScaleData());
        System.assertNotEquals(null, dashboard.getSustainabilityData());
        System.assertNotEquals(null, dashboard.getServicesData());
        System.assertNotEquals(null, dashboard.getTechnologyData());
    }                     
}