src/objects/Dashboard_Section__c.object
<CustomObject>
    <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
    <fields>
        <fullName>Dashboard__c</fullName>
        <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
        <inlineHelpText>Select the dashboard that this section belongs to</inlineHelpText>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Sections</relationshipLabel>
        <relationshipName>Dashboard_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Graphs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this section contains graphs</description>
        <inlineHelpText>Check if this section has graphs in it</inlineHelpText>
        <label>Has Graphs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Maps__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this section contains maps</description>
        <inlineHelpText>Check if the section contains any maps</inlineHelpText>
        <label>Has Maps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Metrics__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this section contains metrics</description>
        <inlineHelpText>Check if this section contains any metrics</inlineHelpText>
        <label>Has Metrics</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Selector__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this section should have a selector in it</description>
        <inlineHelpText>Check if this selection has a selector in it that controls the metrics, maps, graphs, etc displayed</inlineHelpText>
        <label>Has Selector</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this section is active i.e. should be displayed on the dashboard</description>
        <inlineHelpText>Uncheck if this section should not be on the dashboard</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title to display on the page section that contains this section</description>
        <inlineHelpText>Enter the title that will head this section on the dashboard</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Dashboard Section</label>
    <nameField>
        <displayFormat>DS{0000000000}</displayFormat>
        <label>Dashboard Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StevenDashboardController.cls
/**
 *  Controller to load the settings for the Steven dashboard
 */

public with sharing class StevenDashboardController extends DynamicDashboardBaseController {

    public StevenDashboardController() {
        
    }

    // Remove the below and uncomment the above when the bug in SFDC is fixed by them.
    public Dashboard_Section__c getSection0() {
        return [SELECT
                Name,
                Id,
                Title__c,
                Has_Graphs__c,
                Has_Metrics__c,
                Has_Maps__c,
                Has_Selector__c,
                Dashboard__r.Account__r.Name
            FROM
                Dashboard_Section__c
            WHERE
                Name = 'DS0000000057'
                AND Is_Active__c = true];
    }
    public Dashboard_Section__c getSection1() {
        return [SELECT
                Name,
                Id,
                Title__c,
                Has_Graphs__c,
                Has_Metrics__c,
                Has_Maps__c,
                Has_Selector__c,
                Dashboard__r.Account__r.Name
            FROM
                Dashboard_Section__c
            WHERE
                Name = 'DS0000000058'
                AND Is_Active__c = true];
    }
    

    static testMethod void testAll() {

        StevenDashboardController controller = new StevenDashboardController();
        Dashboard_Section__c section = controller.getSection0();
        section = controller.getSection1();
        
    }
}