src/objects/Dashboard_Section__c.object
<CustomObject>
    <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
    <fields>
        <fullName>Dashboard__c</fullName>
        <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
        <inlineHelpText>Select the dashboard that this section belongs to</inlineHelpText>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Sections</relationshipLabel>
        <relationshipName>Dashboard_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title to display on the page section that contains this section</description>
        <inlineHelpText>Enter the title that will head this section on the dashboard</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Dashboard Section</label>
    <nameField>
        <displayFormat>DS{0000000000}</displayFormat>
        <label>Dashboard Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dashboard_Selector__c.object
<CustomObject>
    <description>Controls what selectors are to go on a dashboard selector</description>
    <fields>
        <fullName>Dashboard_Section__c</fullName>
        <label>Dashboard Section</label>
        <referenceTo>Dashboard_Section__c</referenceTo>
        <relationshipLabel>Dashboard Selectors</relationshipLabel>
        <relationshipName>Dashboard_Selectors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Period__c</fullName>
        <description>The time period that each metric data lasts for</description>
        <inlineHelpText>Select how often you want the metrics to change</inlineHelpText>
        <label>Date Period</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Show_Data_Validator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the data validator selector</description>
        <inlineHelpText>Check to include the Data Validator selector in the dashboard selector</inlineHelpText>
        <label>Show Data Validator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Dates__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the date selectors</description>
        <inlineHelpText>Check to show the date range selectors</inlineHelpText>
        <label>Show Dates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_District__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to include the district selector.</description>
        <inlineHelpText>Show the district selector</inlineHelpText>
        <label>Show District</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Field_Officer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the field officer selector</description>
        <inlineHelpText>Check to include the field officer selector in the dashboard selector</inlineHelpText>
        <label>Show Field Officer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_MTN_Chan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the MTN Channels selector</description>
        <inlineHelpText>Check to include the MTN Channels selector</inlineHelpText>
        <label>Show MTN Chan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Metric_Date_Selector__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the metric date selector</description>
        <inlineHelpText>Check to show the metric date selector. Only check if not showing the normal date selector</inlineHelpText>
        <label>Show Metric Date Selector</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Person__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to show the person selector</description>
        <inlineHelpText>Check to show the person selector</inlineHelpText>
        <label>Show Person</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Region__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the region selector</description>
        <inlineHelpText>Check to include the region selector</inlineHelpText>
        <label>Show Region</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Subcounty__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show the subcounty selector</description>
        <inlineHelpText>Check to show the subcounty selector</inlineHelpText>
        <label>Show Subcounty</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Submit_Button__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Show the submit button on the selector. Not always needed if the selector is embedded on none dashboard page</description>
        <inlineHelpText>Uncheck to hide the submit button on the selector</inlineHelpText>
        <label>Show Submit Button</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date that the selector should start from. Will not allow any dates to be input earlier that this</description>
        <inlineHelpText>Choose the date that is the earliest you wish to see data from</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Dashboard Selector</label>
    <nameField>
        <displayFormat>DSC{0000000000}</displayFormat>
        <label>Dashboard Selector Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Selectors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DashboardSelectorComponentController.cls
/**
 *  Controller for a dashboard selector.
 *  Controls what is to be displayed on a given selector.
 *  This can be inserted inside a dashboard section to control the display on that section
 */
public with sharing class DashboardSelectorComponentController extends ParentComponentBase {

    private Dashboard_Selector__c selector;
    public Dashboard_Selector__c getSelector() {
        return this.selector;
    }
    public void setSelector(Dashboard_Selector__c value) {
        this.selector = value;
        this.addParameter('DatePeriod' + getSectionKey(), value.Date_Period__c);
        this.addParameter('SelectorId' + getSectionKey(), value.Id);
    }

    public Boolean getShowRegion() {
        return this.selector.Show_Region__c;
    }

    public Boolean getShowDistrict() {
        return this.selector.Show_District__c;
    }

    public Boolean getShowSubcounty() {
        return this.selector.Show_Subcounty__c;
    }

    public Boolean getShowDates() {
        return this.selector.Show_Dates__c;
    }

    public Boolean getShowMetricDates() {
        return this.selector.Show_Metric_Date_Selector__c;
    }

    public Boolean getShowPerson() {
        return this.selector.Show_Person__c;
    }

    public Boolean getShowDataValidator() {
        return this.selector.Show_Data_Validator__c;
    }

    public Boolean getShowMtnChan() {
        return this.selector.Show_MTN_Chan__c;
    }

    public Boolean getShowFieldOfficer() {
        return this.selector.Show_Field_Officer__c;
    }

    public Date getStartDate() {
        return this.selector.Start_Date__c;
    }

    public String getDatePeriod() {
        return this.selector.Date_Period__c;
    }

    public Boolean getShowSubmitButton() {
        return this.selector.Show_Submit_Button__c;
    }

    private String accountName;
    public String getAccountName() {
        return this.accountName;
    }
    public void setAccountName(String value) {
        this.accountName = value;
        addParameter('Organisation' + getSectionKey(), value);
    }

    private Boolean expanded;
    public Boolean getExpanded() {
        return this.expanded;
    }
    public void setExpanded(Boolean value) {
        this.expanded = value;
    }

    public override String getHandle() {
        return 'SELECTOR';
    }

    static testMethod void testStuff() {

        DashboardSelectorComponentController controller = new DashboardSelectorComponentController();

        Account account = new Account();
        account.Name = 'Account';
        account.BillingState = 'CA';
        Database.insert(account);

        Dashboard__c dash = new Dashboard__c();
        dash.Account__c = account.Id;
        dash.Title__c = 'Title';
        dash.Description__c = 'Description';
        Database.insert(dash);

        Dashboard_Section__c section = new Dashboard_Section__c();
        section.Dashboard__c = dash.Id;
        section.Title__c = 'Title';
        Database.insert(section);

        Dashboard_Selector__c selector = new Dashboard_Selector__c();
        selector.Show_Person__c = true;
        selector.Show_Metric_Date_Selector__c = true;
        selector.Show_Dates__c = true;
        selector.Show_Subcounty__c = true;
        selector.Show_District__c = true;
        selector.Dashboard_Section__c = section.id;
        controller.setSelector(selector);

        controller.setAccountName('HELLO');
        controller.getAccountName();
        controller.setExpanded(true);
        controller.getExpanded();
        System.assert(controller.getShowDates());
        System.assert(controller.getShowDistrict());
        System.assert(controller.getShowSubcounty());
        System.assert(controller.getShowMetricDates());
        System.assert(controller.getShowPerson());
    }
}