src/objects/Dashboard_Section__c.object
<CustomObject>
    <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
    <fields>
        <fullName>Dashboard__c</fullName>
        <description>A section of a dashboard that contains the maps, graphs, selectors, etc. Allows for independent sections to be in the same dashboard</description>
        <inlineHelpText>Select the dashboard that this section belongs to</inlineHelpText>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Sections</relationshipLabel>
        <relationshipName>Dashboard_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Graphs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this section contains graphs</description>
        <inlineHelpText>Check if this section has graphs in it</inlineHelpText>
        <label>Has Graphs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Maps__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this section contains maps</description>
        <inlineHelpText>Check if the section contains any maps</inlineHelpText>
        <label>Has Maps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Metrics__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this section contains metrics</description>
        <inlineHelpText>Check if this section contains any metrics</inlineHelpText>
        <label>Has Metrics</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_Selector__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this section should have a selector in it</description>
        <inlineHelpText>Check if this selection has a selector in it that controls the metrics, maps, graphs, etc displayed</inlineHelpText>
        <label>Has Selector</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this section is active i.e. should be displayed on the dashboard</description>
        <inlineHelpText>Uncheck if this section should not be on the dashboard</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Title to display on the page section that contains this section</description>
        <inlineHelpText>Enter the title that will head this section on the dashboard</inlineHelpText>
        <label>Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Dashboard Section</label>
    <nameField>
        <displayFormat>DS{0000000000}</displayFormat>
        <label>Dashboard Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DynamicDashboardBaseController.cls
/**
 *  Virtual class to provide common methods required for all dashboards
 */
public with sharing virtual class DynamicDashboardBaseController {

    private String dashboardName;
    public String getDashboardName() {
        return this.dashboardName;
    }
    public void setDashboardName(String value) {
        this.dashboardName = value;
    }

    // Get the sections for the dashboard to display (Cannot be used until bug in SFDC is fixed!!!)
    // Called by extending class and must be called after setDashboardName is called
    private List<Dashboard_Section__c> sections;
    public List<Dashboard_Section__c> getSections() {
        return this.sections;
    }
    public void setSections(List<Dashboard_Section__c> values) {
        this.sections = values;
    }
    public List<Dashboard_Section__c> loadSections() {

        List<Dashboard_Section__c> sectionsToLoad = [SELECT
                Name,
                Id,
                Title__c,
                Has_Graphs__c,
                Has_Metrics__c,
                Has_Maps__c,
                Has_Selector__c
            FROM
                Dashboard_Section__c
            WHERE
                Dashboard__r.Name = :dashboardName
                AND Is_Active__c = true];
        return sectionsToLoad;
    }

    static testMethod void testController() {

        Account account = new Account();
        account.Name = 'Account';
        account.BillingState = 'CA';
        Database.insert(account);

        Dashboard__c dash = new Dashboard__c();
        dash.Account__c = account.Id;
        dash.Title__c = 'Title';
        dash.Description__c = 'Description';
        Database.insert(dash);

        Dashboard__c dash2 = [SELECT Name FROM Dashboard__c WHERE Id = :dash.id];

        Dashboard_Section__c section = new Dashboard_Section__c();
        section.Dashboard__c = dash.Id;
        section.Title__c = 'Title';
        Database.insert(section);

        DynamicDashboardBaseController controller = new DynamicDashboardBaseController();
        controller.setDashboardName(dash.Name);
        controller.getDashboardName();
        controller.setSections(controller.loadSections());
        controller.getSections();
    }
}