src/objects/Date_Picker__c.object
<CustomObject>
    <description>Dummy object to capture date input from a VF page. Required until SF allows a generic date selector in VF</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Date Picker</label>
    <nameField>
        <label>Date Picker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Date Pickers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>District__c</fullName>
        <description>The district that this metric is for. Allows us to split the metrics by district when showing them on the dashboard</description>
        <inlineHelpText>Select the district that this metric is for</inlineHelpText>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Map_Parameter__c.object
<CustomObject>
    <description>Defines the starting point for a map that can be shown on a dashboard</description>
    <label>Map Parameter</label>
    <nameField>
        <displayFormat>MP{0000000000}</displayFormat>
        <label>Map Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MbugoDashboardController.cls
public with sharing class MbugoDashboardController {


    public List<District__c> mbugoDistricts;
    public List<Subcounty__c> mbugoSubCounties;
    private Boolean isEditMode = false;
    private String isUpdateable = 'true';
    private String orgName = 'null';
    private Transient Map<String, M_E_Metric_Data__c> allMetricDatas;

    private List<SelectOption> districtList;  
    private List<SelectOption> subcountiesList;
    private Transient Map<String, M_E_Metric__c> allMetrics;

    //Maps list
    private List<Map_Parameter__c> maps;


    public String tabName { get; set; }
    public District__c district { get; set; }
    public Subcounty__c subcounty { get; set; }
    public String dateFrom { get; set; }
    public String dateTo { get; set; }
    public Date_Picker__c dummyObject { get; set; }


    public MbugoDashboardController() {
      dummyObject = new Date_Picker__c();
      district = new District__c();
      subcounty = new Subcounty__c();
      setUp(ApexPages.currentPage());
     
    }


 	public void setUp(PageReference pageRef) {

        // Try to keep the tab we're on
        String tabName = pageRef.getParameters().get('sfdc.tabName');
        this.tabName = tabName != null ? tabName : tabName;
        this.isEditMode = (pageRef.getParameters().get('editMode') == 'true'); 

        //this.dateFrom = pageRef.getParameters().get('dateFrom');
        //this.dateTo = pageRef.getParameters().get('dateTo');
        
    } 
    

	public String getIsUpdateable() {
        return this.isUpdateable;
    }
    
    
    public void setIsUpdateable(String value) {
        this.isUpdateable = value;
    }
        
        
    public String getIsEditMode() {
        String isEditing = 'false';
        isEditing = this.isEditMode ? 'true' : 'false';
        return isEditing;
    }  
    

	public void setDistrictList(List<SelectOption> option) {
        this.districtList = option;
    }
    
    
    public List<SelectOption> getDistrictList() {
        List<SelectOption> options = new List<SelectOption>();
        District__c[] districts = database.query(SoqlHelpers.getDistricts(orgName));
        options.add(new SelectOption('','-- In All Districts --'));
        
        //Add all districts to list
        for (District__c district : districts) {
               options.add(new SelectOption(district.Name, district.Name));
               } 
        return options;
    }


    public void setSubcountiesList(List<SelectOption> option) {
        this.districtList = option;
    }


    public List<SelectOption> getSubcountiesList() {
        List<SelectOption> options = new List<SelectOption>();
        Subcounty__c[] subcounties = database.query(MbugoHelpers.getSubcounties());
        options.add(new SelectOption('','-- In All Subcounties --'));

        //Add all subcounties to list
        for (Subcounty__c subcounty : subcounties) {
           options.add(new SelectOption(subcounty.Display_Name__c, subcounty.Display_Name__c));
        } 
        return options;
    }


    public List<MetricDataWrapper> getFarmersReachedData(){
        return MbugoHelpers.getFarmersReachedData();
    }


    public List<MbugoHelpers.CkwPerformanceWrapper> getCkwPerfomanceData(){
        return MbugoHelpers.getCkwPerfomanceData();
    }


    public PageReference changeFilters() {    
        PageReference resultPage = ApexPages.currentPage(); 
        resultPage.getParameters().put('subcounty', subcounty.Display_Name__c);
        resultPage.getParameters().put('district', district.Name);
        resultPage.getParameters().put('dateFrom', dummyObject.Start_Date__c == null? '': 
            Datetime.newInstance(dummyObject.Start_Date__c.year(), dummyObject.Start_Date__c.month(), dummyObject.Start_Date__c.day()).format('yyyy-MM-dd'));
        resultPage.getParameters().put('dateTo', dummyObject.End_Date__c == null? '': 
            Datetime.newInstance(dummyObject.End_Date__c.year(), dummyObject.End_Date__c.month(), dummyObject.End_Date__c.day()).format('yyyy-MM-dd'));
        resultPage.getParameters().put('sfdc.tabName', this.tabName);
        resultPage.setRedirect(true);
        return resultPage;
    }


	public List<MetricDataWrapper> getVslaServicesData(){    
        return MbugoHelpers.getVslaServicesData();
    }
    
    
	public List<MbugoHelpers.FinancialServicesUsageData> getFinancialServicesChartData(){
            return MbugoHelpers.getFinancialServicesChartData();
    }
  

    public List<MetricDataWrapper> getFarmerGroupsData(){
    	return MbugoHelpers.getFarmerGroupsData();
    }
    
    
      public  List<MetricDataWrapper> getCooperativeGroupsData(){
      	return MbugoHelpers.getCooperativeGroupsData();
    }
    