src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FieldOfficerSelectorController.cls
/**
 *  Controller for the component that controls the field officer selector.
 *  Should be the child on a DashboardSelectorComponent.
 */
public with sharing class FieldOfficerSelectorController extends ChildComponentBase {
    private Boolean loaded = false;

    public override PageReference refreshData() {

        if (getShowData()) {
            setFieldOfficers(loadFieldOfficers());
        }
        return null;
    }

    // Override method to return the controllers chosen value.
    public override String getValues() {

        if (this.fieldOfficer == null) {
            return '';
        }
        return getFieldOfficer();
    }

    public String getActionFunctionName() {
        return 'fieldOfficerSelectorComponentController';
    }

    public String fieldOfficer;
    public String getFieldOfficer() {
        return this.fieldOfficer;
    }
    public void setFieldOfficer(String fieldOfficer) {
        addParameterToParent(fieldOfficer);
        this.fieldOfficer = fieldOfficer;
    }
    public List<SelectOption> fieldOfficers;
    public List<SelectOption> getFieldOfficers() {

        if (!loaded && getShowData()) {
            setFieldOfficers(loadFieldOfficers());
        }
        return this.fieldOfficers;
    }
    public void setFieldOfficers(List<SelectOption> options) {
        this.fieldOfficers = options;
    }
    private List<SelectOption> loadFieldOfficers() {

        List<SelectOption> options = new List<SelectOption>();

        Person__c[] fieldOfficers = database.query(buildFieldOfficerQueryString());
        if (fieldOfficers.size() > 1) {
            options.add(new SelectOption('All', '---All Field Officer---'));
        }
        else {
            options.add(new SelectOption('', '---No Field Officer available---'));
            return options;
        }

        for (Person__c fieldOfficer : fieldOfficers) {
            options.add(new SelectOption(fieldOfficer.Id, fieldOfficer.Name + ' - ' + fieldOfficer.Last_Name__c + ' ' + fieldOfficer.First_Name__c));
        }
        loaded = true;
        return options;
    }

    private String buildFieldOfficerQueryString() {

        String query = 'SELECT ' +
                'Name, ' +
                'id, ' +
                'First_Name__c, ' +
                'Last_Name__c ' +
            'FROM ' +
                'Person__c ' +
            getWhereClause() +
            ' ORDER BY ' +
                'Last_Name__c, ' +
                'First_Name__c ';
        System.debug(LoggingLevel.INFO, query);
        return query;
    }

    private String getWhereClause() {

        List<String> whereClauses = new List<String>();
        if (!getParentValue('District__c').equals('')) {
            whereClauses.add(' District__c = \'' + getParentValue('District__c') + '\'');
        }
        if (!getParentValue('Subcounty__c').equals('')) {
            whereClauses.add(' Subcounty__c = \'' + getParentValue('Subcounty__c') + '\'');
        }
        String clause = '';
        if (whereClauses.size() > 0) {
            clause = SoqlHelpers.joinWhereClause(whereClauses, true);
        }
        return ' WHERE Type__c = \'Field Officer\' ' + clause;
    }
    
    static testMethod void testFieldOfficerSelectorController() {
    	FieldOfficerSelectorController fieldOfficerSelectorController = new FieldOfficerSelectorController();
    	fieldOfficerSelectorController.getFieldOfficers();
    	fieldOfficerSelectorController.refreshData();
    	fieldOfficerSelectorController.getValues();
    	fieldOfficerSelectorController.getActionFunctionName();
    }

}