src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Organisation_District_Association__c.object
<CustomObject>
    <description>Link a partner to a district that they are working in.</description>
    <fields>
        <fullName>District__c</fullName>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Organisation District Associations</relationshipLabel>
        <relationshipName>Organisation_District_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Organisation District Associations</relationshipLabel>
        <relationshipName>Organisation_District_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Organisation District Association</label>
    <nameField>
        <label>Organisation District Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organisation District Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SubcountySelectorController.cls
/**
 *  Controller for the component that controls the subcounty selector.
 *  Should be the child on a DashboardSelectorComponent.
 */
public with sharing class SubcountySelectorController extends ChildComponentBase {

    private Boolean loaded = false;

    public String getActionFunctionName() {
        return 'subcountySelectorComponentController' + getParentKey();
    }

    // Override method to return the controllers chosen value.
    public override String getValues() {
        return getSubcounty();
    }

    public override PageReference refreshData() {

        if (getShowData()) {
            setSubcounties(loadSubcounties());
        }
        return null;
    }

    // Get the available subcounties. This can take into account a country that has been selected
    public String subcounty;
    public String getSubcounty() {
        return this.subcounty;
    }
    public void setSubcounty(String subcounty) {
        addParameterToParent(subcounty);
        this.subcounty = subcounty;
    }
    public List<SelectOption> subcounties;
    public List<SelectOption> getSubcounties() {
        if (!this.loaded && getShowData()) {
            setSubcounties(loadSubcounties());
        }
        return this.subcounties;
    }
    public void setSubcounties(List<SelectOption> options) {
        this.subcounties = options;
    }
    public List<SelectOption> loadSubcounties() {

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '---Please Select a Subcounty---'));
        Subcounty__c[] subcounties = database.query(buildSubcountyQueryString());
        for (Subcounty__c subcounty : subcounties) {
            options.add(new SelectOption(subcounty.Id, subcounty.Display_Name__c));
        }
        this.loaded = true;
        return options;
    }

    private String buildSubcountyQueryString() {
        String query =  'SELECT ' +
                'Id, ' +
                'Display_Name__c ' +
            'FROM ' +
                'Subcounty__c ' +
            buildWhereClause() +
            ' ORDER BY ' +
                'Display_Name__c';

        System.debug(LoggingLevel.INFO, query);
        return query;
    }

    private String buildWhereClause() {

        List<String> clauses = new List<String>();
        if (!getParentValue('District__c').equals('')) {
            clauses.add(' District__c = \'' + getParentValue('District__c') + '\'');
        }
        if (!getParentValue('Organisation').equals('')) {
            clauses.add(' District__c IN (SELECT District__c FROM Organisation_District_Association__c WHERE Organisation__r.Name = \'' + getParentValue('Organisation') + '\') ');
        }
        if (clauses.size() == 0) {
            return '';
        }
        return ' WHERE ' + SoqlHelpers.joinWhereClause(clauses, false);
    }

    static testMethod void testController() {

        SubcountySelectorController controller = new SubcountySelectorController();
        controller.getSubcounties();
        controller.getActionFunctionName();
        controller.getValues();
        controller.refreshData();
    }
}