src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission_Meta_Data__c.object
<CustomObject>
    <description>Contains the data that every submission requires. Every submission will have one of these irrelevant of the submission object that corresponds to the submission</description>
    <fields>
        <fullName>Handset_Submit_Time__c</fullName>
        <description>The time that the submission was entered on the handset</description>
        <label>Handset Submit Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interviewer_Name__c</fullName>
        <formula>Interviewer__r.First_Name__c &amp;
IF(ISBLANK( Interviewer__r.First_Name__c ),&quot;&quot;, &quot; &quot;) &amp;
Interviewer__r.Middle_Name__c &amp;
IF(ISBLANK( Interviewer__r.Middle_Name__c ),&quot;&quot;, &quot; &quot;) &amp;
Interviewer__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Interviewer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <description>The person who conducted the survey</description>
        <label>Interviewer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>Submission_Meta_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result_Hash__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>unique hash created using SHA1 to ensure that this submission has not been entered into the system already</description>
        <label>Result Hash</label>
        <length>160</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Submission_Latitude__c</fullName>
        <description>The latitude that the survey was submitted from</description>
        <label>Submission Latitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Longitude__c</fullName>
        <description>The longitude that the survey was submitted from</description>
        <label>Submission Longitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Size__c</fullName>
        <description>The size in bytes of the submission</description>
        <label>Submission Size (Bytes)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <formula>Survey__r.Survey_Name__c</formula>
        <label>Survey Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The survey that this submission is for</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipName>Submission_Meta_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SMD-{0000000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <description>Surveys run by CKWs. There is one entry here for each type of survey. Survey questions (and responses) are NOT stored here.</description>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <description>A unique name for the survey</description>
        <inlineHelpText>Please select a friendly name for the survey</inlineHelpText>
        <label>Survey Name</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SubmissionMapMarker.cls
/**
 *  Class to generate map markers for the Submission_Meta_Data__c sObject.
 *  Extends MapMarker
 */
public with sharing class SubmissionMapMarker extends MapMarkers {

    private Submission_Meta_Data__c submission;

    public SubmissionMapMarker(Submission_Meta_Data__c submission) {
        this.submission = submission;
        this.setLatitude(String.valueOf(submission.Submission_Latitude__c));
        this.setLongitude(String.valueOf(submission.Submission_Longitude__c));
        this.setMarkerTitle(submission.Survey_Name__c);
        setDefaultColour('Green');
    }

    // Create the content string for the marker pop up
    public override String getMarkerInfoContentString() {

        String content = '<div>' +
            this.submission.Survey_Name__c + '<br />' +
            //this.submission.Client_Location__r.Display_Name__c + '<br />' +
            getPersonDetails() +
            '</div>';
        return content;
    }

    public override void generateMarkerName(String splitter) {
        setColour(getDefaultColour());
        setMarkerName(joinMarkerName(submission.Interviewer__r.Name, getColour(), ''));
    }

    public override String getColour() {
        return this.colour;
    }

    private String getPersonDetails() {

        String content = '';

        // This not working getting  Invalid foreign key relationship: Submission_Meta_Data__c.Interveiwer__r
        if (this.submission.Interviewer__c != null) {   
            content = '<br />Name: ' + this.submission.Interviewer__r.First_Name__c + ' ' + this.submission.Interviewer__r.Last_Name__c + '<br />' +
                'Subcounty: ' + this.submission.Interviewer__r.Subcounty__r.Display_Name__c + '<br />';
                
        }
        //content = '<br/>Name: ' + submission.Interviewer_Name__c + '<br/>';
        return content;
    }

    static testMethod void testMarker() {
        District__c testDistrict = Utils.createTestDistrict('Test District');
        database.insert(testDistrict);

        Subcounty__c testSubCounty = Utils.createTestSubcounty('Test Subcounty', testDistrict.Id);
        database.insert(testSubCounty);
        
        Phone__c testPhone = Utils.createTestHandset('23423423111');
        database.insert(testPhone);

        Person__c testPerson = Utils.createTestPerson(testPhone.Id, '', false, testDistrict.Id, 'Male');
        Database.insert(testPerson);
        
        Account testAccount = Utils.createTestOrganisation('testorg');
        database.insert(testAccount);
        
        Survey__c testSurvey = Utils.createTestSurvey(testAccount, 'Test Survey');
        database.insert(testSurvey);
        
        Submission_Meta_Data__c submission = new Submission_Meta_Data__c();
        submission.Interviewer__c = testPerson.Id;
        submission.Submission_Latitude__c = 0.3;
        submission.Submission_Longitude__c = 32.5;
        submission.Survey__c = testSurvey.Id;
        submission.Handset_Submit_Time__c = datetime.now();
        submission.Result_Hash__c = 'sw324';
        submission.Submission_Size__c = 12.0;
        Database.insert(submission);

        SubmissionMapMarker marker = new SubmissionMapMarker(submission);
        marker.getMarkerInfoContentString();
        marker.generateMarkerName('');
    }
}