src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DataValidatorController.cls
/**
 * Controller for the component that creates a dop down list of all the available DVs
 */
public with sharing class DataValidatorController extends ChildComponentBase {

    private Boolean loaded = false;

    public override PageReference refreshData() {

        if (getShowData()) {
            setDataValidators(loadDataValidators());
        }
        return null;
    }

    // Override method to return the controllers chosen value.
    public override String getValues() {

        if (this.dataValidator == null) {
            return '';
        }
        return getDataValidator();
    }

    public String getActionFunctionName() {
        return 'dataValidatorSelectorComponentController';
    }

    public String dataValidator;
    public String getDataValidator() {
        return this.dataValidator;
    }
    public void setDataValidator(String dataValidator) {
        addParameterToParent(dataValidator);
        this.dataValidator = dataValidator;
    }
    public List<SelectOption> dataValidators;
    public List<SelectOption> getDataValidators() {

        if (!loaded && getShowData()) {
            setDataValidators(loadDataValidators());
        }
        return this.dataValidators;
    }
    public void setDataValidators(List<SelectOption> options) {
        this.dataValidators = options;
    }
    private List<SelectOption> loadDataValidators() {

        List<SelectOption> options = new List<SelectOption>();
        if (getParentValue('District__c').equals('')) {
            options.add(new SelectOption('', '---Please Select a District first---'));
            return options;
        }

        Person__c[] dataValidators = database.query(buildDataValidatorQueryString());
        if (dataValidators.size() > 1) {
            options.add(new SelectOption('', '---Please Select a Data Validator---'));
        }
        else {
            options.add(new SelectOption('', '---No Data Validators available---'));
            return options;
        }

        for (Person__c dataValidator : dataValidators) {
            options.add(new SelectOption(dataValidator.Id, dataValidator.Name + ' ' + dataValidator.Last_Name__c + ' ' + dataValidator.First_Name__c));
        }
        loaded = true;
        return options;
    }

    private String buildDataValidatorQueryString() {

        String query = 'SELECT ' +
                'Name, ' +
                'id, ' +
                'First_Name__c, ' +
                'Last_Name__c ' +
            'FROM ' +
                'Person__c ' +
            getWhereClause() +
            ' ORDER BY ' +
                'Last_Name__c, ' +
                'First_Name__c ';
        System.debug(LoggingLevel.INFO, query);
        return query;
    }

    private String getWhereClause() {

        List<String> whereClauses = new List<String>();
        if (!getParentValue('District__c').equals('')) {
            whereClauses.add(' District__c = \'' + getParentValue('District__c') + '\'');
        }
        if (!getParentValue('Subcounty__c').equals('')) {
            whereClauses.add(' Subcounty__c = \'' + getParentValue('Subcounty__c') + '\'');
        }
        String clause = '';
        if (whereClauses.size() > 0) {
            clause = ' WHERE Type__c = \'Data Validator\' ' + SoqlHelpers.joinWhereClause(whereClauses, true);
        }
        return clause;
    }

    static testMethod void testController() {

        // Create a test district
        District__c district = Utils.createTestDistrict('Test');
        Database.insert(district);

       // Create a test Test Field Officer
        Person__c person1 = Utils.createTestPerson(null, 'TestingDV', true, district.Id, 'Female');
        person1.Type__c = 'Data Validator';
        database.insert(person1);

        Test.startTest();
        DashboardSelectorComponentController parent = new DashboardSelectorComponentController();
        parent.addParameter('District__ckey', district.Id);

        DataValidatorController controller = new DataValidatorController();
        controller.setKey('graph');
        controller.setSectionKey('key');
        controller.setParentComponentController(parent);

        controller.setDataValidators(controller.getDataValidators());
        controller.setShowData(true);
        controller.refreshData();
        controller.getValues();
        controller.setDataValidator('hi');
        controller.getValues();
    }
}