src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>M&amp;E Metrics</relationshipLabel>
        <relationshipName>M_E_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission_Answer__c.object
<CustomObject>
    <description>Object to hold one answer to a survey</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Select1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repeat</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission Answer</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Submission Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestProcessNaadsSurveys.cls
/**
 * A test class for the ProcessNaadsSurveys class methods
 */
@isTest
private class TestProcessNaadsSurveys {

    /**
     * Test method for the processNaadsBaseline method
     */
    private static TestMethod void testProcessNaadsBaselineSurvey(){
        Account testAccount = new Account();
        testAccount.BillingState = 'CA';
        testAccount.Name = 'NAADS'; 
        database.SaveResult accountSaveResult = database.insert(testAccount);

        M_E_Metric__c metric1 = new M_E_Metric__c();
        metric1.Name = 'Farmer_group_trainings_meetings_or_attended';
        metric1.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric2= new M_E_Metric__c();
        metric2.Name = 'Number_of_farmer_supervisory_visits_conducted';
        metric2.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric3= new M_E_Metric__c();
        metric3.Name = 'Number_of_farmers_attending_group_trainings_meetings';
        metric3.Organisation__c = accountSaveResult.getId();
        database.insert(new M_E_Metric__c[] { metric1,  metric2, metric3});

        ProcessSurveySubmission.SurveySubmission submission = new ProcessSurveySubmission.SurveySubmission();
        submission.handsetSubmitTime = Datetime.now().getTime().format().replace(',', '');
        submission.submissionStartTime = Datetime.now().addMinutes(30).getTime().format().replace(',', '');
        submission.imei = '32432443253';
        submission.resultHash = '1';
            
        Map<String, Submission_Answer__c> answers = new Map<String, Submission_Answer__c>();
        answers.put('q3_0', Utils.createTestSubmissionAnswer(null, 'q3', '2', null, null, null));
        answers.put('q32_0', Utils.createTestSubmissionAnswer(null, 'q32', '1', null, null, null));
        answers.put('q41_0', Utils.createTestSubmissionAnswer(null, 'q41', '1', null, null, null));
        answers.put('q60_0', Utils.createTestSubmissionAnswer(null, 'q60', '1', null, null, null));
        answers.put('q37_0', Utils.createTestSubmissionAnswer(null, 'q37', '1', null, null, null));
        answers.put('q71_0', Utils.createTestSubmissionAnswer(null, 'q71', '3', null, null, null));
        answers.put('q60_0', Utils.createTestSubmissionAnswer(null, 'q67', '2', null, null, null));
        answers.put('q50_0', Utils.createTestSubmissionAnswer(null, 'q50', '5', null, null, null));

        Person__c person = Utils.createTestPerson(null, 'TestingNAADS', true, null, 'Female');
        District__c district = new District__c();
        district.Name = 'Serere';
        database.SaveResult saveResult = database.insert(district);
        
        // Create subcounty
        Subcounty__c kyere = new Subcounty__c();
        kyere.District__c = saveResult.getId();
        kyere.Display_Name__c = 'Kyere';
        database.insert(kyere);
        List<String> returnValues = new List<String>();
        test.startTest();
        returnValues = ProcessNaadsSurveys.processNaadsBaselineSurvey(submission, answers, person);
        System.assert(returnValues.get(0).equals('1'));
        
        // Test failure
        answers.put('q3_0', Utils.createTestSubmissionAnswer(null, 'q3', '4', null, null, null));
        returnValues = ProcessNaadsSurveys.processNaadsBaselineSurvey(submission, answers, person);
        System.assert(returnValues.get(0).equals('0'));
        test.stopTest();
    }

    /**
     * Test method for the processAdvisoryServicesSurvey method
     */    
    private static TestMethod void testProcessAdvisoryServicesSurvey() {
    
        // Create a NAADS ASP
        Person__c person = Utils.createTestPerson(null, 'NAADS', true, null, 'Female');
        person.Type__c = 'ASP';
        database.insert(person);
        District__c district = new District__c();
        district.Name = 'Serere';
        database.SaveResult saveResult = database.insert(district);
        
        // Create subcounty
        Subcounty__c kateta = new Subcounty__c();
        kateta.District__c = saveResult.getId();
        kateta.Display_Name__c = 'Kateta';
        database.insert(kateta);
        Account testAccount = new Account();
        testAccount.BillingState = 'CA';
        testAccount.Name = 'NAADS'; 
        database.SaveResult accountSaveResult = database.insert(testAccount);

        M_E_Metric__c metric1 = new M_E_Metric__c();
        metric1.Name = 'Percentage_of_beneficiaries_satisfied_with_advisory_services';
        metric1.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric2= new M_E_Metric__c();
        metric2.Name = 'Percentage_of_farmers_noticing_improvement_in_NAADS_extension_services';
        metric2.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric3= new M_E_Metric__c();
        metric3.Name = 'Percentage_of_farmers_reporting_a_feedback_channel_for_NAADS';
        metric3.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric4= new M_E_Metric__c();
        metric4.Name = 'Percentage_of_farmers_satisfied_with_feedback_channel_for_NAADS';
        metric4.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric5= new M_E_Metric__c();
        metric5.Name = 'Percentage_of_beneficiaries_perceiving_involvement_in_group_decision_making';
        metric5.Organisation__c = accountSaveResult.getId();
        
        database.insert(new M_E_Metric__c[] { metric1,  metric2, metric3, metric4, metric5});
        
        ProcessSurveySubmission.SurveySubmission submission = new ProcessSurveySubmission.SurveySubmission();
        submission.handsetSubmitTime = Datetime.now().getTime().format().replace(',', '');
        submission.submissionStartTime = Datetime.now().addMinutes(30).getTime().format().replace(',', '');
        submission.imei = '32432443253';
        submission.resultHash = '1';
        
        // Test Farmer group training
        Map<String, Submission_Answer__c> answers = new Map<String, Submission_Answer__c>();
        answers.put('q1_0', Utils.createTestSubmissionAnswer(null, 'q1', '2', null, null, null));
        answers.put('q19_0', Utils.createTestSubmissionAnswer(null, 'q19', '9', null, null, null));
        answers.put('q3_0', Utils.createTestSubmissionAnswer(null, 'q3', '6', null, null, null));
        List<String> returnValues = new List<String>();
        test.startTest();
        returnValues = ProcessNaadsSurveys.processAdvisoryServiceSurvey(submission, answers, person);         
        System.assert(returnValues.get(0).equals('1'));
         
        // Test Supervisory visiting report
        Map<String, Submission_Answer__c> supervisoryAnswers = new Map<String, Submission_Answer__c>();
        supervisoryAnswers .put('q1_0', Utils.createTestSubmissionAnswer(null, 'q1', '3', null, null, null));
        supervisoryAnswers .put('q3_0', Utils.createTestSubmissionAnswer(null, 'q3', '6', null, null, null));
        returnValues = ProcessNaadsSurveys.processAdvisoryServiceSurvey(submission, supervisoryAnswers, person);         
        System.assert(returnValues.get(0).equals('1'));
        test.stopTest();
    }
}