src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>M&amp;E Metrics</relationshipLabel>
        <relationshipName>M_E_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Actual_Value__c</fullName>
        <description>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</description>
        <inlineHelpText>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</inlineHelpText>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date of the quarter to which this metric belongs</description>
        <inlineHelpText>This can simply be any date falling in the quarter to which this metric belongs. We shall calculate the quarter dynamically. It defaults to the current date.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Denumerator__c</fullName>
        <description>The Denumerator for the on the fly calculation</description>
        <label>Denumerator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>The district that this metric is for. Allows us to split the metrics by district when showing them on the dashboard</description>
        <inlineHelpText>Select the district that this metric is for</inlineHelpText>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Cumulative__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this is a cumulative metric</description>
        <label>Is Cumulative</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manual_Value__c</fullName>
        <description>Manually set value for a metric. Will override the actual value in display</description>
        <label>Manual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numerator__c</fullName>
        <description>Numerator for the on the fly calc</description>
        <label>Numerator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>The person that this metric data belongs to</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually.</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Real_Value__c</fullName>
        <formula>IF( OR(ISNULL(Manual_Value__c),  ISBLANK(Manual_Value__c) ) ,  Actual_Value__c ,  Manual_Value__c)</formula>
        <label>Real Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Naads_Advisory_Form_Metrics__c.object
<CustomObject>
    <description>Keeps track of certain metrics based on the Advisory service forms survey</description>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Naads Advisory Form Metrics</relationshipLabel>
        <relationshipName>Naads_Advisory_Form_Metrics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <label>Subcounty</label>
        <picklist>
            <picklistValues>
                <fullName>Atiira</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kadungulu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pingire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Olio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bugondo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kateta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kyere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labori</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serere Town Council</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kasilo Town council</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Service provider monthly visit schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer group training record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervisory visiting report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attendance sheet</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Naads Advisory Form Metrics</label>
    <nameField>
        <displayFormat>MN-{0000}</displayFormat>
        <label>Metric Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Naads Advisory Form Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission_Answer__c.object
<CustomObject>
    <description>Object to hold one answer to a survey</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Select</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Select1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repeat</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission Answer</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Submission Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcessNaadsSurveys.cls
public with sharing class ProcessNaadsSurveys {

    /**
     * A class to deal with NAADs surveys
     */
     
     /**
     *  Fill in the Naads_Baseline_Info objects for this ASP
     *
     *  @param submission - The submission object being processed
     *  @param answers    - A map containing the values for the registration
     *                       The keys are <binding>_<instance> for compatibility
     *  @param person     - The Person__c object who submitted the form
     *
     *  @return - A three element list of Strings with the following format
     *              element 1 - Binary indicator of success (0 = fail, 1 = success)
     *              element 2 - Error message if required for the logs and tech team
     *              element 3 - Message body to the CKW if required.
     */
     public static List<String>  processNaadsBaselineSurvey(ProcessSurveySubmission.SurveySubmission submission, Map<String, Submission_Answer__c> answers, Person__c person) {

         List<String> metricNames = new List<String> {
         'Percentage_of_beneficiaries_satisfied_with_advisory_services',
         'Percentage_of_farmers_noticing_improvement_in_NAADS_extension_services',
         'Percentage_of_farmers_reporting_a_feedback_channel_for_NAADS',
         'Percentage_of_farmers_satisfied_with_feedback_channel_for_NAADS',
         'Percentage_of_beneficiaries_perceiving_involvement_in_group_decision_making'
         };     

         Subcounty__c subcounty = [Select Id from Subcounty__c where Display_Name__c =:subcountyMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q3_0')))];
         String subcountyId = subcounty.Id;

         boolean satisfiedWithReportingFeedback = false;
         boolean voiceTakenIntoAccount = false;
         boolean belongsToNaadsFarmerGroup = ProcessSubmissionHelpers.checkIfYes(ProcessSubmissionHelpers.getAnswerString(answers.get('q32_0')));
         boolean attendsTraining = ProcessSubmissionHelpers.checkIfYes(ProcessSubmissionHelpers.getAnswerString(answers.get('q41_0')));
         boolean hasSomewhereToReport = ProcessSubmissionHelpers.checkIfYes(ProcessSubmissionHelpers.getAnswerString(answers.get('q60_0')));
         boolean isNAADSBeneficiary = ProcessSubmissionHelpers.checkIfYes(ProcessSubmissionHelpers.getAnswerString(answers.get('q37_0')));
         boolean satisfiedWithNaadsServices = servicesSatisfactionMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q71_0')));
         if (hasSomewhereToReport) {
             satisfiedWithReportingFeedback = servicesSatisfactionMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q67_0')));
         }
         if (belongsToNaadsFarmerGroup ) {
             voiceTakenIntoAccount = servicesSatisfactionMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q50_0')));
         }

         DateTime handsetSubmitTime = ProcessSurveySubmission.getTimestamp(submission.handsetSubmitTime);
         Date currentDate = handsetSubmitTime.date();

         M_E_Metric_Data__c[] datas = [
             SELECT
                 Id,
                 Name,
                 Real_Value__c,
                 Actual_Value__c,
                 Manual_Value__c,
                 District__c,
                 Denumerator__c,
                 Numerator__c,
                 Subcounty__c,
                 M_E_Metric__r.Name
             FROM
                 M_E_Metric_Data__c
             WHERE
                 (
                     Subcounty__c = :subcounty.Id
                 )
             AND Date__c >= :currentDate
             AND M_E_Metric__r.Name IN :metricNames
        ];
        if (datas == null || datas.isEmpty()) {
            for (String metricName : metricNames) {
                M_E_Metric_Data__c mData = createNewMetricData(metricName, currentDate, subcounty.Id);
                datas.add(mdata);
            }
        }

        // Loop through the data and see which ones we have already got. If they are not there already create them
        Map<String, M_E_Metric_Data__c> dataMap = new Map<String, M_E_Metric_Data__c>();
        for (M_E_Metric_Data__c mData : datas) {  
             dataMap.put(mData.M_E_Metric__r.Name, mData);
        }

        // Loop through the list of metrics and check that they all exist and then update them
        for (String key : metricNames) {

            // Check that the three metrics for each metric name exists
            M_E_Metric_Data__c totalNewData = dataMap.get(key);
            system.debug('Checking for metric name: ' + key);
            if (totalNewData == null) {
                totalNewData = createNewMetricData(key, currentDate, subcounty.Id);
            }
            Decimal farmerCount = 0.0;

            // Update the metric based on the key
            if (key.equals('Percentage_of_beneficiaries_perceiving_involvement_in_group_decision_making') ) {
                 totalNewData.Denumerator__c += 1;
                 if (voiceTakenIntoAccount) {
                     totalNewData.Numerator__c += 1;
                 }
                 totalNewData.Actual_Value__c = 100*(totalNewData.Numerator__c/totalNewData.Denumerator__c);
            }
            else if (key.equals('Percentage_of_beneficiaries_satisfied_with_advisory_services')) {
                 totalNewData.Denumerator__c += 1;
                 if (satisfiedWithNaadsServices) {
                     totalNewData.Numerator__c += 1;
                 }
                 totalNewData.Actual_Value__c = 100*(totalNewData.Numerator__c/totalNewData.Denumerator__c);
            }
            else if (key.equals('Percentage_of_farmers_noticing_improvement_in_NAADS_extension_services')) {
                 totalNewData.Denumerator__c += 1;
                 if (satisfiedWithNaadsServices) {
                     totalNewData.Numerator__c += 1;
                 }
                 totalNewData.Actual_Value__c = 100*(totalNewData.Numerator__c/totalNewData.Denumerator__c);
            }
            else if (key.equals('Percentage_of_farmers_reporting_a_feedback_channel_for_NAADS')) {
                 totalNewData.Denumerator__c+= 1;
                 if (hasSomewhereToReport) {
                     totalNewData.Numerator__c += 1;
                 }
                 totalNewData.Actual_Value__c = 100*(totalNewData.Numerator__c/totalNewData.Denumerator__c);
            }
            else if (key.equals('Percentage_of_farmers_satisfied_with_feedback_channel_for_NAADS')) {
                 totalNewData.Denumerator__c+= 1;
                 if (satisfiedWithReportingFeedback) {
                     totalNewData.Numerator__c += 1;
                 }
                 totalNewData.Actual_Value__c = 100*(totalNewData.Numerator__c/totalNewData.Denumerator__c);
            }
            dataMap.put(key, totalNewData);
        }
        List<Database.upsertResult> uResults = Database.upsert(dataMap.values());
        for(Database.upsertResult result : uResults) {
            if (result.isSuccess()) {
                system.debug('succeeded ' + result.getId());
            }
            else {
                for (Database.Error error : result.getErrors()) {
                    system.debug('Error: ' + error.getMessage()); 
                }
                return new String[] { '0', 'Error in submission', 'SUPRESSMSG' };
            }
        }
        return new String[] { '1', 'Naads baseline visit processed successfully', 'SUPRESSMSG' };
     }
     
     private static Map<String, String> subcountyMap = new Map<String, String> {
     
        '1' => 'Kateta',
        '2' => 'Kyere',
        '3' => 'Olio',
        '4' => 'Bugondo',
        '5' => 'Pingire',
        '6' => 'Kadungulu',
        '7' => 'Atiira',
        '8' => 'Labori',
        '9' => 'Serere Town Council',
        '10' => 'Kasilo Town council'     
     };
     
     private static Map<String, Boolean> servicesSatisfactionMap = new Map<String, Boolean> {
     
        '1' => true,
        '2' => true,
        '3' => true,
        '4' => false,
        '5' => false,
        '6' => false     
     };
     
     private static Map<String, String> voiceConsideredMap = new Map<String, String> {
     
        '1' => 'Strongly agree',
        '2' => 'Agree',
        '3' => 'Somewhat agree',
        '4' => 'Somewhat disagree',
        '5' => 'Disagree',
        '6' => 'Strongly disagree' 
     };

     /**
     *  Fill in the Naads_Baseline_Info objects for this ASP
     *
     *  @param submission - The submission object being processed
     *  @param answers    - A map containing the values for the registration
     *                       The keys are <binding>_<instance> for compatibility
     *  @param person     - The Person__c object who submitted the form
     *
     *  @return - A three element list of Strings with the following format
     *              element 1 - Binary indicator of success (0 = fail, 1 = success)
     *              element 2 - Error message if required for the logs and tech team
     *              element 3 - Message body to the CKW if required.
     */
     public static List<String> processAdvisoryServiceSurvey(ProcessSurveySubmission.SurveySubmission submission, Map<String, Submission_Answer__c> answers, Person__c person) {        
         
         List<String> metricNames = new List<String> {
         'Farmer_group_trainings_meetings_or_attended',
         'Number_of_farmer_supervisory_visits_conducted', 
         'Number_of_farmers_attending_group_trainings_meetings'
         };

         String subcountyName = advisorySubcountyMap.get(ProcessSubmissionHelpers.getAnswerString(answers.get('q3_0')));
         System.debug('subcounty '+subcountyName);
         Decimal farmerCount = ProcessSubmissionHelpers.getAnswerNumber(answers.get('q19_0'), 'q19_0', true);
         String visitType = ProcessSubmissionHelpers.getAnswerString(answers.get('q1_0'));
         Subcounty__c subcounty = [Select Id from Subcounty__c where Display_Name__c =:subcountyName];
         DateTime handsetSubmitTime = ProcessSurveySubmission.getTimestamp(submission.handsetSubmitTime);
         Date currentDate = handsetSubmitTime.date();
         
         Naads_Advisory_Form_Metrics__c naadsMetric = new Naads_Advisory_Form_Metrics__c();
         naadsMetric.Subcounty__c = subcountyName;
         naadsMetric.Person__c = person.Id;
         naadsMetric.Type__c = visitType;
         naadsMetric.Visit_Date__c = ProcessSubmissionHelpers.getAnswerDate(answers.get('q6_0'), currentDate);
         database.insert(naadsMetric);

         M_E_Metric_Data__c[] datas = [
             SELECT
                 Id,
                 Name,
                 Actual_Value__c,
                 Manual_Value__c,
                 District__c,
                 Denumerator__c,
                 Numerator__c,
                 Subcounty__c,
                 M_E_Metric__r.Name
             FROM
                 M_E_Metric_Data__c
             WHERE
                 (
                     Subcounty__c = :subcounty.Id
                 )
             AND Date__c >= :currentDate
             AND M_E_Metric__r.Name IN (
                     'Farmer_group_trainings_meetings_or_attended',
                     'Number_of_farmer_supervisory_visits_conducted',
                     'Number_of_farmers_attending_group_trainings_meetings')
        ];
        if (datas == null || datas.isEmpty()) {
            for (String metricName : metricNames) {
                M_E_Metric_Data__c mData = createNewMetricData(metricName, currentDate, subcounty.Id);
                datas.add(mdata);
            }
        }
        
        // Loop through the data and see which ones we have already got. If they are not there already create them
        Map<String, M_E_Metric_Data__c> dataMap = new Map<String, M_E_Metric_Data__c>();
        for (M_E_Metric_Data__c mData : datas) {
             dataMap.put(mData.M_E_Metric__r.Name, mData);
        }

        // Loop through the list of metrics and check that they all exist and then update them
        for (String key : metricNames) {

            // Check that the three metrics for each metric name exists
            M_E_Metric_Data__c totalNewData = dataMap.get(key);
            system.debug('Checking for metric name: ' + key);
            if (totalNewData == null) {
                totalNewData = createNewMetricData(key, currentDate, subcounty.Id);
            }

            // Update the metric based on the key
            if (key.equals('Farmer_group_trainings_meetings_or_attended') && visitType == '2') {
                 totalNewData.Denumerator__c += 1;
                 totalNewData.Actual_Value__c = totalNewData.Denumerator__c;
            }
            else if (key.equals('Number_of_farmer_supervisory_visits_conducted') && visitType == '3') {
                 totalNewData.Denumerator__c+= 1;
                 totalNewData.Actual_Value__c = totalNewData.Denumerator__c;
            }
            else if (key.equals('Number_of_farmers_attending_group_trainings_meetings') && visitType == '2') {
                 totalNewData.Denumerator__c += farmerCount;
                 totalNewData.Actual_Value__c = totalNewData.Denumerator__c;
            }
            dataMap.put(key, totalNewData);
        }
        List<Database.upsertResult> uResults = Database.upsert(dataMap.values());
        for(Database.upsertResult result : uResults) {
            if (result.isSuccess()) {
                system.debug('succeeded ' + result.getId());
            }
            else {
                for (Database.Error error : result.getErrors()) {
                    system.debug('Error: ' + error.getMessage());
                }
                return new String[] { '0', 'Error in submission', 'SUPRESSMSG' };
            }
        }
        return new String[] { '1', 'Naads baseline visit processed successfully', 'SUPRESSMSG' };
     }

     private static Map<String, String> advisorySubcountyMap = new Map<String, String> {
     
        '1' => 'Atiira',
        '2' => 'Kadungulu',
        '3' => 'Pingire',
        '4' => 'Olio',
        '5' => 'Bugondo',
        '6' => 'Kateta',
        '7' => 'Kyere',
        '8' => 'Labori',
        '9' => 'Serere Town Council',
        '10' => 'Kasilo Town council'     
     };
     
    /**
     *  Create a new metric data for a given person, start date and metric. Assume that the metric is created on the box
     *
     *  @param key       - The M_E_Metric.Name value that is being created
     *  @param startDate - The date that the metric period starts
     *  @param subcountyId   - The divider that the metric is split by
     *
     *  @return - The newly created M_E_Metric_Data object
     */
     private static M_E_Metric_Data__c createNewMetricData(String key, Date startDate, String subcountyId) {

         M_E_Metric__c[] metrics = MetricHelpers.getMetrics(key, null);
         M_E_Metric__c metric = metrics[0];

         M_E_Metric_Data__c mData = new M_E_Metric_Data__c();
         mData.Subcounty__c = subcountyId;

         mData.Numerator__c = 0.0;
         mData.Denumerator__c = 0.0;
         mData.Manual_Value__c = 0.0;
         mData.Is_Cumulative__c = false;
         mData.Date__c = startDate;
         mData.M_E_Metric__c = metric.Id;
         mData.Projected_Value__c = metric.Projected_Value__c;
         return mData;
     }
    
     static testMethod void testProcessNaadsBaselineSurvey() {

        Account testAccount = new Account();
        testAccount.BillingState = 'CA';
        testAccount.Name = 'TestOrg'; 
        database.SaveResult accountSaveResult = database.insert(testAccount);

        M_E_Metric__c metric1 = new M_E_Metric__c();
        metric1.Name = 'Percentage_of_beneficiaries_satisfied_with_advisory_services';
        metric1.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric2= new M_E_Metric__c();
        metric2.Name = 'Percentage_of_farmers_noticing_improvement_in_NAADS_extension_services';
        metric2.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric3= new M_E_Metric__c();
        metric3.Name = 'Percentage_of_farmers_reporting_a_feedback_channel_for_NAADS';
        metric3.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric4= new M_E_Metric__c();
        metric4.Name = 'Percentage_of_farmers_satisfied_with_feedback_channel_for_NAADS';
        metric4.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric5= new M_E_Metric__c();
        metric5.Name = 'Percentage_of_beneficiaries_perceiving_involvement_in_group_decision_making';
        metric5.Organisation__c = accountSaveResult.getId();
        
        database.insert(new M_E_Metric__c[] { metric1,  metric2, metric3, metric4, metric5});

        ProcessSurveySubmission.SurveySubmission submission = new ProcessSurveySubmission.SurveySubmission();
        submission.handsetSubmitTime = Datetime.now().getTime().format().replace(',', '');
        submission.submissionStartTime = Datetime.now().addMinutes(30).getTime().format().replace(',', '');
        submission.imei = '32432443253';
        submission.resultHash = '1';
            
        Map<String, Submission_Answer__c> answers = new Map<String, Submission_Answer__c>();
        answers.put('q6_0', Utils.createTestSubmissionAnswer(null, 'q6', 'Suker', null, null, null));
        answers.put('q5_0', Utils.createTestSubmissionAnswer(null, 'q5', 'Parish', null, null, null));
        answers.put('q4_0', Utils.createTestSubmissionAnswer(null, 'q4', 'Village', null, null, null));
        answers.put('q3_0', Utils.createTestSubmissionAnswer(null, 'q3', '2', null, null, null));
        answers.put('q32_0', Utils.createTestSubmissionAnswer(null, 'q32', '1', null, null, null));
        answers.put('q41_0', Utils.createTestSubmissionAnswer(null, 'q41', '1', null, null, null));
        answers.put('q60_0', Utils.createTestSubmissionAnswer(null, 'q60', '1', null, null, null));
        answers.put('q37_0', Utils.createTestSubmissionAnswer(null, 'q37', '1', null, null, null));
        answers.put('q71_0', Utils.createTestSubmissionAnswer(null, 'q71', '3', null, null, null));
        answers.put('q60_0', Utils.createTestSubmissionAnswer(null, 'q67', '2', null, null, null));
        answers.put('q50_0', Utils.createTestSubmissionAnswer(null, 'q50', '5', null, null, null));

        Person__c person = Utils.createTestPerson(null, 'TestingNAADS', true, null, 'Female');
        District__c district = new District__c();
        district.Name = 'Serere';
        database.SaveResult saveResult = database.insert(district);
        
        // Create subcounty
        Subcounty__c kyere = new Subcounty__c();
        kyere.District__c = saveResult.getId();
        kyere.Display_Name__c = 'Kyere';
        database.insert(kyere);
        List<String> returnValues = new List<String>();
        returnValues = processNaadsBaselineSurvey(submission, answers, person);
        System.assert(returnValues.get(0).equals('1'));
     }
     
     static testMethod void testProcessAdvisoryServiceSurvey() {
     
        // Create a NAADS ASP
        Person__c person = Utils.createTestPerson(null, 'NAADS', true, null, 'Female');
        person.Type__c = 'ASP';
        database.insert(person);
        District__c district = new District__c();
        district.Name = 'Serere';
        database.SaveResult saveResult = database.insert(district);
        
        // Create subcounty
        Subcounty__c kateta = new Subcounty__c();
        kateta.District__c = saveResult.getId();
        kateta.Display_Name__c = 'Kateta';
        database.insert(kateta);
        Account testAccount = new Account();
        testAccount.BillingState = 'CA';
        testAccount.Name = 'TestOrg'; 
        database.SaveResult accountSaveResult = database.insert(testAccount);

        M_E_Metric__c metric1 = new M_E_Metric__c();
        metric1.Name = 'Farmer_group_trainings_meetings_or_attended';
        metric1.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric2= new M_E_Metric__c();
        metric2.Name = 'Number_of_farmer_supervisory_visits_conducted';
        metric2.Organisation__c = accountSaveResult.getId();
        M_E_Metric__c metric3= new M_E_Metric__c();
        metric3.Name = 'Number_of_farmers_attending_group_trainings_meetings';
        metric3.Organisation__c = accountSaveResult.getId();
        database.insert(new M_E_Metric__c[] { metric1,  metric2, metric3});
        
        ProcessSurveySubmission.SurveySubmission submission = new ProcessSurveySubmission.SurveySubmission();
        submission.handsetSubmitTime = Datetime.now().getTime().format().replace(',', '');
        submission.submissionStartTime = Datetime.now().addMinutes(30).getTime().format().replace(',', '');
        submission.imei = '32432443253';
        submission.resultHash = '1';
        
        // Test Farmer group training
        Map<String, Submission_Answer__c> answers = new Map<String, Submission_Answer__c>();
        answers.put('q1_0', Utils.createTestSubmissionAnswer(null, 'q1', '2', null, null, null));
        answers.put('q19_0', Utils.createTestSubmissionAnswer(null, 'q19', '9', null, null, null));
        answers.put('q3_0', Utils.createTestSubmissionAnswer(null, 'q3', '6', null, null, null));
        List<String> returnValues = new List<String>();
        returnValues = processAdvisoryServiceSurvey(submission, answers, person);         
        System.assert(returnValues.get(0).equals('1'));
         
        // Test Supervisory visiting report
        Map<String, Submission_Answer__c> supervisoryAnswers = new Map<String, Submission_Answer__c>();
        supervisoryAnswers .put('q1_0', Utils.createTestSubmissionAnswer(null, 'q1', '3', null, null, null));
        supervisoryAnswers .put('q3_0', Utils.createTestSubmissionAnswer(null, 'q3', '6', null, null, null));
        returnValues = processAdvisoryServiceSurvey(submission, supervisoryAnswers, person);         
        System.assert(returnValues.get(0).equals('1'));
     }
}