src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <fields>
        <fullName>Latitude__c</fullName>
        <description>The central latitude of the district. This is where maps will center if this district is the focus of the map.</description>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <description>The central longitude of the district</description>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EADD_Farmer_extra_info__c.object
<CustomObject>
    <description>Extra information from an EADD Farmer</description>
    <fields>
        <fullName>Access_AH__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has access to Animal Health services</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Access_farmer_trainings__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has access to farmer trainings</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Access_financial_services__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Does farmer have access to financial services/SACCO</description>
        <label>Do you Has access to financial services</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Access_transport_services__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has access to transport services</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Accesses_AI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has access to artificial insemination</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Accesses_checkoff_services__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has access to check-off services</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Accesses_farm_inputs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has access to farm inputs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Accesses_feeds__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has access to feeds supplies</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>District of the dairy farmer</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>EADD Farmer extra info</relationshipLabel>
        <relationshipName>EADD_Farmer_extra_info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Farmer object of the farmer giving these details</description>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>EADD Farmer extra info</relationshipLabel>
        <relationshipName>EADD_Farmer_extra_info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>The name of the farmer</description>
        <label>Name</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty of the dairy farmer</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>EADD Farmer extra info</relationshipLabel>
        <relationshipName>EADD_Farmer_extra_info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Uses_AI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uses artificial insemination</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Uses_dryseason_feeding__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uses dry season feeding</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Uses_highquality_feeds__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uses high quality feeds</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Uses_supplementary_feeding__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uses supplementary feeding</label>
        <type>Checkbox</type>
    </fields>
    <label>EADD Farmer extra info</label>
    <nameField>
        <label>EADD Farmer extra info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EADD Farmer extra info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EADD_Hub__c.object
<CustomObject>
    <description>An EADD Hub or Milk collection center</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date for collection of this data</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>District In which the Hub is located</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>EADD Hubs</relationshipLabel>
        <relationshipName>EADD_Hubs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Farmers_served_by_hub__c</fullName>
        <description>Number of farmers that bring milk to the hub</description>
        <inlineHelpText>Number of farmers that bring milk to the hub</inlineHelpText>
        <label>Farmers served by hub</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hub_capacity_utilization__c</fullName>
        <label>Hub capacity utilization</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milk_sale_profits__c</fullName>
        <label>Milk sale profits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milk_sale_revenue__c</fullName>
        <label>Milk sale revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milk_volumes_bulked__c</fullName>
        <label>Milk volumes bulked</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Radius_Covered__c</fullName>
        <description>Radius of hub in terms of diary farmer coverage (km)</description>
        <label>Radius Covered</label>
        <precision>11</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>EADD Hubs</relationshipLabel>
        <relationshipName>EADD_Hubs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EADD Hub</label>
    <nameField>
        <label>EADD Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EADD Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>The age of a person</description>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subcounty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Subcounty</description>
        <label>Subcounty</label>
        <referenceTo>Subcounty__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subcounty__c.object
<CustomObject>
    <description>Subcounty</description>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>The name of the subcounty</description>
        <label>Display Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>Subcountry District</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>Subcounties</relationshipLabel>
        <relationshipName>Subcounties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <description>Latitude</description>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <description>Longitude</description>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <label>Subcounty</label>
    <nameField>
        <displayFormat>SUB-C-{00000000}</displayFormat>
        <label>Subcounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subcounties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submission_Answer__c.object
<CustomObject>
    <description>Object to hold one answer to a survey</description>
    <label>Submission Answer</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Submission Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProcessEADDSurveys.cls
/**
 *
 * Copyright (c) 2013 AppLab, Grameen Foundation
 *
 *  This class carries out the EADD Surveys post-processing
 *  Its test methods are in the EADDDashboardTests class
 **/
public with sharing class ProcessEADDSurveys {

    /**
    *  Fill in the objects for this Hub Registration
    *  We expect one metric data for a hub in a month thus
    *  a need to check existance before creating a new metric
    *
    *  @param submission - The submission object being processed
    *  @param answers    - A map containing the values for the registration
    *                       The keys are <binding>_<instance> for compatibility
    *  @param person     - The Person__c object of the CKW who submitted the form
    *
    *  @return - A three element list of Strings with the following format
    *              element 1 - Binary indicator of success (0 = fail, 1 = success)
    *              element 2 - Error message if required for the logs and tech team
    *              element 3 - Message body to the CKW if required.
    */	
	public static List<String> processEADDHubRegistration(ProcessSurveySubmission.SurveySubmission submission, Map<String, Submission_Answer__c> answers, Person__c interviewer) {
		
		String hubName = ProcessSubmissionHelpers.getAnswerString(answers.get('q1_0')).trim();
		System.debug('Registering Hub ' + hubName);
		String districtSelected = ProcessSubmissionHelpers.getAnswerString(answers.get('q2_0'));
		String subcountyGiven = ProcessSubmissionHelpers.getAnswerString(answers.get('q3_0'));
		Date dateOfCollection = Date.valueOf(ProcessSubmissionHelpers.getAnswerString(answers.get('q6_0')));
		decimal radiusCovered = decimal.valueOf(ProcessSubmissionHelpers.getAnswerString(answers.get('q8_0')));		
		decimal suplliers = decimal.valueOf(ProcessSubmissionHelpers.getAnswerString(answers.get('q9_0')));
		decimal volumes = decimal.valueOf(ProcessSubmissionHelpers.getAnswerString(answers.get('q11_0')));
		decimal revenues = decimal.valueOf(ProcessSubmissionHelpers.getAnswerString(answers.get('q16_0')));
		decimal profits = decimal.valueOf(ProcessSubmissionHelpers.getAnswerString(answers.get('q18_0')));
		String hubUtilization = ProcessSubmissionHelpers.getAnswerString(answers.get('q19_0'));
		String location = ProcessSubmissionHelpers.getAnswerString(answers.get('q20_0'));
		
		District__c[] district = database.query('SELECT Id, Name FROM District__c WHERE Name = :districtSelected');
		if(district.isEmpty()){
			return new String[]{ '0', 'The district provided is not in salesforce', 'SUPRESSMSG' };
		}
		Id districtId = district[0].Id;
		Subcounty__c[] subcounty = database.query(
									'SELECT '								+
										'Id, '								+
										'Display_Name__c '					+
									'FROM '									+
										'Subcounty__c '						+
									'WHERE '								+
										'Display_Name__c = :subcountyGiven '+	
										'AND District__c = :districtId'
									);
									
		if(subcounty.isEmpty()){
			return new String[]{ '0', 'The subcounty provided is not in salesforce or the district specified', 'SUPRESSMSG' };
		}
		Id subcountyId = subcounty[0].Id;
		
		//we need one record per month
		dateOfCollection = dateOfCollection.toStartOfMonth();
		EADD_Hub__c[] hubs = database.query(
								'SELECT '							+
									'Id, '							+
									'Name__c '						+
								'FROM '								+
									'EADD_Hub__c '					+
								'WHERE '							+
									'Date__c = :dateOfCollection '	+
									'AND Name__c = :hubName '		+
									'AND District__c = :districtId '+
									'AND Subcounty__c = :subcountyId'
								);
		
		EADD_Hub__c hub = hubs.isEmpty()? new EADD_Hub__c(): hubs[0];
		hub.Date__c = dateOfCollection;
		hub.District__c = districtId;
		hub.Farmers_served_by_hub__c = suplliers;
		hub.Hub_capacity_utilization__c = hubUtilization;
		hub.Milk_sale_profits__c = profits;
		hub.Milk_sale_revenue__c = revenues;
		hub.Milk_volumes_bulked__c =  volumes;
		hub.Name__c = hubName;
		hub.Subcounty__c = subcountyId;
		//we extract latitude and longitude from the GPS location
		hub.Longitude__c = location.split(' ')[1];
		hub.Latitude__c = location.split(' ')[0];
		hub.Radius_Covered__c = radiusCovered;
		if(hub.Id == null){
			insert hub;	
		} else {
			update hub;
		}
		return new String[]{ '1', 'EADD Hub Registration successful for IMEI: ' + submission.imei, 'SUPRESSMSG' };
	}

    /**
    *  Fill in the objects for this Farmer Registration
    *  This farmer registration does not have Poverty Index data
    *  What is most important is verifying the District, Subcounty and then
    *  creating/updating metric datas to store info from the farmer
    *  Metric data is stored in the EADD_Farmer_extra_info__c object
    *
    *  @param submission - The submission object being processed
    *  @param answers    - A map containing the values for the registration
    *                       The keys are <binding>_<instance> for compatibility
    *  @param person     - The Person__c object of the CKW who submitted the form
    *
    *  @return - A three element list of Strings with the following format
    *              element 1 - Binary indicator of success (0 = fail, 1 = success)
    *              element 2 - Error message if required for the logs and tech team
    *              element 3 - Message body to the CKW if required.
    */
	public static List<String> processEADDFarmerRegistration(ProcessSurveySubmission.SurveySubmission submission, Map<String, Submission_Answer__c> answers, Person__c interviewer) {
		
		String farmerName = ProcessSubmissionHelpers.getAnswerString(answers.get('q1_0')).trim();
		System.debug('Registering Hub ' + farmerName);
		integer age = integer.valueOf(ProcessSubmissionHelpers.getAnswerString(answers.get('q3_0')));
		String districtSelected = ProcessSubmissionHelpers.getAnswerString(answers.get('q4_0'));
		String subcountyGiven = ProcessSubmissionHelpers.getAnswerString(answers.get('q5_0'));
		boolean accessesFinancialsServices = ProcessSubmissionHelpers.getAnswerString(answers.get('q14_0')) == 'Yes';
		boolean accessesAnimalHealth = ProcessSubmissionHelpers.getAnswerString(answers.get('q11_0')) == 'Yes';
		boolean accessesAI = ProcessSubmissionHelpers.getAnswerString(answers.get('q10_0')) == 'Yes';
		boolean accessesCheckoffServices = ProcessSubmissionHelpers.getAnswerString(answers.get('q16_0')) == 'Yes';
		boolean accessesTrainings = ProcessSubmissionHelpers.getAnswerString(answers.get('q12_0')) == 'Yes';
		boolean accessesFarmInputs = ProcessSubmissionHelpers.getAnswerString(answers.get('q8_0')) == 'Yes';
		boolean accessesFeeds = ProcessSubmissionHelpers.getAnswerString(answers.get('q13_0')) == 'Yes';
		boolean accessesTransportServices = ProcessSubmissionHelpers.getAnswerString(answers.get('q15_0')) == 'Yes';
		boolean usesAI = ProcessSubmissionHelpers.getAnswerString(answers.get('q17_0')) == 'Yes';
		boolean usesDrySeasonFeed = ProcessSubmissionHelpers.getAnswerString(answers.get('q18_0')) == 'Yes';	
		boolean usesHQFeed = ProcessSubmissionHelpers.getAnswerString(answers.get('q20_0')) == 'Yes';	
		boolean usesSupplementaries = ProcessSubmissionHelpers.getAnswerString(answers.get('q19_0')) == 'Yes';	
		String gender = ProcessSubmissionHelpers.getAnswerString(answers.get('q2_0'));
		
		DateTime submissionTime = ProcessSurveySubmission.getTimestamp(submission.submissionStartTime);
		Date submissionDate = submissionTime.date();
		//lets ensure one record per month
		submissionDate = submissionDate.toStartOfMonth();
		
		District__c[] district = database.query('SELECT Id, Name FROM District__c WHERE Name = :districtSelected');
		if(district.isEmpty()){
			return new String[]{ '0', 'The district provided is not in salesforce', 'SUPRESSMSG' };
		}
		Id districtId = district[0].Id;
		Subcounty__c[] subcounty = database.query(
									'SELECT '								+
										'Id, '								+
										'Display_Name__c '					+
									'FROM '									+
										'Subcounty__c '						+
									'WHERE '								+
										'Display_Name__c = :subcountyGiven '+
										'AND District__c = :districtId'
									);
		if(subcounty.isEmpty()){
			return new String[]{ '0', 'The subcounty provided is not in salesforce or the district specified', 'SUPRESSMSG' };
		}
		Id subcountyId = subcounty[0].Id;
		
		Farmer__c[] farmers = Utils.loadFarmerFromId(submission.farmerId);
		Farmer__c farmer = farmers[0];
		Id farmerId = farmer.Id;
		
		EADD_Farmer_extra_info__c[] infos = database.query(
											'SELECT '							+
												'Id, '							+
												'Farmer__c '					+
											'FROM '								+
												'EADD_Farmer_extra_info__c '	+
											'WHERE '							+
												'Date__c = :submissionDate '	+
												'AND Farmer__c = :farmerId'
											);
		
		EADD_Farmer_extra_info__c metricData = infos.isEmpty()? new EADD_Farmer_extra_info__c(): infos[0];
		metricData.Age__c = age;
		metricData.Date__c = submissionDate;
		metricData.District__c = districtId;
		metricData.Access_financial_services__c = accessesFinancialsServices;
		metricData.Gender__c =  gender;
		metricData.Access_AH__c =  accessesAnimalHealth;
		metricData.Accesses_AI__c =  accessesAI;
		metricData.Accesses_checkoff_services__c =  accessesCheckoffServices;
		metricData.Access_farmer_trainings__c =  accessesTrainings;
		metricData.Accesses_farm_inputs__c =  accessesFarmInputs;
		metricData.Accesses_feeds__c =  accessesFeeds;
		metricData.Access_transport_services__c = accessesTransportServices; 
		metricData.Name__c = farmerName;
		metricData.Subcounty__c = subcountyId;
		metricData.Uses_AI__c =  usesAI;
		metricData.Uses_dryseason_feeding__c = usesDrySeasonFeed; 
		metricData.Uses_highquality_feeds__c =  usesHQFeed;
		metricData.Uses_supplementary_feeding__c =  usesSupplementaries;
		metricData.Farmer__c = farmer.Id;
		if(metricData.Id == null){
			insert metricData;
		} else {
			update metricData;
		}
		
		return new String[]{ '1', 'EADD Farmer extra info Registration successful for IMEI: ' + submission.imei, 'SUPRESSMSG' };
	}
}