src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Registered_By__c</fullName>
        <label>Registered By</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers Registered</relationshipLabel>
        <relationshipName>Farmers_Registered</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Age__c</fullName>
        <description>The age of a person</description>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fathers_Name__c</fullName>
        <description>Name of person&apos;s father&apos;s name, used for identification purposes</description>
        <label>Father&apos;s Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physical handset assigned to this Person (in the case of GF-managed assets)</description>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Assignee</relationshipLabel>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>(optional) middle name for the person</description>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FarmerCache.cls
global class FarmerCache {

    /**
    * This returns a string of the farmer cache
    */    
    webservice static String getFarmerCache(String imei, String lastUpdateDate) {        
        // Get Farmers registered by CKW with specified IMEI
        List<FarmerCacheObject> farmers = getFarmersByCkwImei(imei, lastUpdateDate);
        
        if (farmers == null) {
            farmers = new List<FarmerCacheObject>();
        }
        //Json serialize and return records
        return JSON.serialize(farmers);
    }
    
    private static List<FarmerCacheObject> getFarmersByCkwImei(String imei, String lastUpdateDate) {
        
        List<FarmerCacheObject> farmerCacheObjects = new List<FarmerCacheObject>();
        
        List<Person__c> persons = [
            SELECT
                p.Id,
                p.District__r.Name
            FROM
                Person__c p
            WHERE
                p.Handset__r.IMEI__c = :imei];
        
        if (persons == null || persons.size() == 0) {
            return farmerCacheObjects;
        }
        
        //Do not return anything if this person has no district set
        //Otherwise all the USSD farmers will be returned
        if (null == persons.get(0).District__r.Name) {
            return farmerCacheObjects;
        }
        
        for (Farmer__c farmer : [
            SELECT
                Id,
                Name,
                Person__r.First_Name__c,
                Person__r.Last_Name__c,
                Person__r.Middle_Name__c,
                Person__r.Fathers_Name__c,
                Person__r.Age__c
            FROM 
                Farmer__c
            WHERE
                LastModifiedDate > :datetime.valueOf(lastUpdateDate)
            AND
            	Person__r.First_Name__c != 'Not Registered'
            AND
            //old code that was for other sections
               Registered_By__c = :persons.get(0).Id ]) {  
               // Person__r.District__r.Name = :persons.get(0).District__r.Name ]) {       
                
            farmerCacheObjects.add(new FarmerCacheObject(farmer.Id, farmer.Name, farmer.Person__r.First_Name__c,
                                                       farmer.Person__r.Middle_Name__c, farmer.Person__r.Last_Name__c,
                                                       farmer.Person__r.Fathers_Name__c, farmer.Person__r.Age__c));       
            
        }
        return farmerCacheObjects;
    }

    global class FarmerCacheObject {
        String sfId;
        String fId;
        String fName;
        String mName;
        String lName;
        String pName;
        Decimal age;
        
        FarmerCacheObject(String sfId, String fId, String fName, 
            String mName, String lName, String pName, Decimal age) {
            
            this.sfId = sfId;
            this.fId = fId;
            this.fName = fName;
            this.mName = mName;
            this.lName = lName;
            this.pName = pName;
            this.age = age;
        }
    }
    
    static testMethod void canGetFarmerCache() {
        
        District__c district = Utils.createTestDistrict('Kakamega');
        database.insert(district);
        
        Phone__c phone = Utils.createTestHandset('21342342345345434');      
        database.insert(phone);
        
        Person__c person = Utils.createTestPerson(phone.Id, 'Oloo', false, district.Id, 'Male');
        database.insert(person);
        
        Person__c farmerPerson = Utils.createTestPerson(phone.Id, 'James', true, district.Id, 'Male');
        database.insert(farmerPerson);
        
        Farmer__c farmer = Utils.createTestFarmer('DE423423', farmerPerson.Id, 'Dummy farmer', false, district.Id, 'Male');     
        farmer.Registered_By__c = person.Id;
        database.insert(farmer);
        
        String cache = FarmerCache.getFarmerCache('21342342345345434', '2011-04-03 00:00:00');
        System.assertNotEquals(cache, '');
    } 
}