src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Registered_By__c</fullName>
        <label>Registered By</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers Registered</relationshipLabel>
        <relationshipName>Farmers_Registered</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date of the quarter to which this metric belongs</description>
        <inlineHelpText>This can simply be any date falling in the quarter to which this metric belongs. We shall calculate the quarter dynamically. It defaults to the current date.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Denumerator__c</fullName>
        <description>The Denumerator for the on the fly calculation</description>
        <label>Denumerator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>District__c</fullName>
        <description>The district that this metric is for. Allows us to split the metrics by district when showing them on the dashboard</description>
        <inlineHelpText>Select the district that this metric is for</inlineHelpText>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numerator__c</fullName>
        <description>Numerator for the on the fly calc</description>
        <label>Numerator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>The person that this metric data belongs to</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physical handset assigned to this Person (in the case of GF-managed assets)</description>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Assignee</relationshipLabel>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Submission_Answer__c.object
<CustomObject>
    <description>Object to hold one answer to a survey</description>
    <fields>
        <fullName>Answer__c</fullName>
        <description>The raw answer that was collected from the submission</description>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Submission_Meta_Data__c</fullName>
        <description>The submission data that this answer is related to</description>
        <label>Submission Meta Data</label>
        <referenceTo>Submission_Meta_Data__c</referenceTo>
        <relationshipLabel>Submission Answers</relationshipLabel>
        <relationshipName>Submission_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Answer</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Submission Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Submission_Meta_Data__c.object
<CustomObject>
    <description>Contains the data that every submission requires. Every submission will have one of these irrelevant of the submission object that corresponds to the submission</description>
    <fields>
        <fullName>Handset_Submit_Time__c</fullName>
        <description>The time that the submission was entered on the handset</description>
        <label>Handset Submit Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interview_Accuracy__c</fullName>
        <description>The accuracy of the gps stamp that the survey was carried out</description>
        <label>Interview Accuracy</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interview_Altitude__c</fullName>
        <description>The altitude that the survey was carried out at</description>
        <label>Interview Altitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interview_GPS_Timestamp__c</fullName>
        <description>The time that the survey was carried out</description>
        <label>Interview GPS Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interview_Latitude__c</fullName>
        <description>The latitude that the survey was carried out</description>
        <label>Interview Latitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interview_Longitude__c</fullName>
        <description>The longitude that the survey was conducted at</description>
        <label>Interview Longitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <description>The person who conducted the survey</description>
        <label>Interviewer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>Submission_Meta_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Result_Hash__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>unique hash created using SHA1 to ensure that this submission has not been entered into the system already</description>
        <label>Result Hash</label>
        <length>160</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Submission_Accuracy__c</fullName>
        <description>The accuracy of the gps location for the survey submission point</description>
        <label>Submission Accuracy (Meters)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Altitude__c</fullName>
        <description>The altitude that the survey was submitted from</description>
        <label>Submission Altitude (Meters)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_GPS_Timestamp__c</fullName>
        <description>The timestamp that the survey submission gps location was taken</description>
        <label>Submission GPS Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Submission_Latitude__c</fullName>
        <description>The latitude that the survey was submitted from</description>
        <label>Submission Latitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Longitude__c</fullName>
        <description>The longitude that the survey was submitted from</description>
        <label>Submission Longitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Size__c</fullName>
        <description>The size in bytes of the submission</description>
        <label>Submission Size (Bytes)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <description>The survey that this submission is for</description>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipName>Submission_Meta_Datas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SMD-{0000000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <description>Surveys run by CKWs. There is one entry here for each type of survey. Survey questions (and responses) are NOT stored here.</description>
    <label>Survey</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DataValidatorHelpers.cls
public with sharing class DataValidatorHelpers {

    public static Map<String, M_E_Metric__c> metricMap = new Map<String, M_E_Metric__c>();

    /**
     *  Class that deals with all processes around the data validators
     */

    /**
     *  Process the spot check survey and create the metrics for the data validators
     *
     *  @param submission - The submission object being processed
     *  @param answers    - A map containing the values for the registration
     *                          The keys are <binding>_<instance> for compatibility
     *  @param submitter  - The Person__c person who submitted the form
     *
     *  @return - A three element list of Strings with the following format
     *              element 1 - Binary indicator of success (0 = fail, 1 = success)
     *              element 2 - Error message if required for the logs and tech team
     *              element 3 - Message body to the submitter if required.
     */
    public static List<String> processSpotCheck(ProcessSurveySubmission.SurveySubmission submission, Map<String, Submission_Answer__c> answers, Person__c submitter) {

        DateTime handsetSubmitTime = ProcessSurveySubmission.getTimestamp(submission.handsetSubmitTime);
        if (handsetSubmitTime == null) {
            return new String[] { '0', 'No handset submit time in this submission', 'SUPRESSMSG' };
        }

        //createSubmissionMetaData(submission, submitter);

        // Dig out the values that are to be added to the metrics
        String explainWell = answers.get('q7_0').Answer__c;
        String bias = answers.get('q15_0').Answer__c;
        String probed = answers.get('q10_0').Answer__c;

        // Load the metrics for the month that the submission is for
        List<String> metricNames = new List<String> { 'GRA_total_spot_checks', 'GRA_informed_farmer', 'GRA_no_bias', 'GRA_probed_CKW' };
        Date startDate = handsetSubmitTime.date().toStartOfMonth();
        Date endDate = handsetSubmitTime.date().toStartOfMonth().addMonths(1).addDays(-1);
        M_E_Metric_Data__c[] datas = [
            SELECT
                Id,
                Name,
                Numerator__c,
                Denumerator__c,
                Person__c,
                District__c,
                M_E_Metric__r.Name
            FROM
                M_E_Metric_Data__c
            WHERE
                (
                    (District__c = null AND Person__c = null)
                    OR District__c = :submitter.District__c
                    OR Person__c = :submitter.Id
                )
                AND Date__c >= :startDate
                AND Date__c <= :endDate
                AND M_E_Metric__r.Name IN ('GRA_total_spot_checks', 'GRA_informed_farmer', 'GRA_no_bias', 'GRA_probed_CKW')
        ];

        // Loop through the datas and see which ones we have already got. If they are not there already create them
        Map<String, M_E_Metric_Data__c> dataMap = new Map<String, M_E_Metric_Data__c>();
        for (M_E_Metric_Data__c mData : datas) {

            // Check to see if it is the person, district or country wide metric
            if (mData.Person__c == null && mData.District__c == null) {
                dataMap.put(mData.M_E_Metric__r.Name, mData);
            }
            else if (mData.Person__c == null) {
                dataMap.put(mData.M_E_Metric__r.Name + '_#@#@#_' + submitter.District__c, mData);
            }
            else {
                dataMap.put(mData.M_E_Metric__r.Name + '_#@#@#_' + submitter.Id, mData);
            }
        }

        // Loop through the list of metrics and check that they all exist and then update them
        for (String key : metricNames) {

            // Check that the three metrics for each metric name exists
            M_E_Metric_Data__c totalNewData = dataMap.get(key);
            M_E_Metric_Data__c districtNewData = dataMap.get(key + '_#@#@#_' + submitter.District__c);
            M_E_Metric_Data__c personNewData = dataMap.get(key + '_#@#@#_' + submitter.Id);
            if (totalNewData == null) {
                totalNewData = createNewMetric(key, startDate, submitter, 'none');
            }
            if (districtNewData == null) {
                districtNewData = createNewMetric(key, startDate, submitter, 'district');
            }
            if (personNewData == null) {
                personNewData = createNewMetric(key, startDate, submitter, 'person');
            }

            totalNewData.Denumerator__c++;
            districtNewData.Denumerator__c++;
            personNewData.Denumerator__c++;

            // Update the metric based on the key
            if (key.equals('GRA_informed_farmer')) {
                if (explainWell.equals('1')) {
                    totalNewData.Numerator__c++;
                    districtNewData.Numerator__c++;
                    personNewData.Numerator__c++;
                }
            }
            else if (key.equals('GRA_no_bias')) {
                if (bias.equals('1')) {
                    totalNewData.Numerator__c++;
                    districtNewData.Numerator__c++;
                    personNewData.Numerator__c++;
                }
            }
            else if (key.equals('GRA_probed_CKW')) {
                if (probed.equals('1')) {
                    totalNewData.Numerator__c++;
                    districtNewData.Numerator__c++;
                    personNewData.Numerator__c++;
                }
            }
            dataMap.put(key, totalNewData);
            dataMap.put(key + '_#@#@#_' + submitter.District__c, districtNewData);
            dataMap.put(key + '_#@#@#_' + submitter.Id, personNewData);
        }
        Database.upsert(dataMap.values());
        return new String[] { '1', 'All metric datas updated for Data Validator with IMEI: ' + submission.imei, 'SUPRESSMSG' };
    }

    /**
     *  Process the back check survey and create the metrics for the data validators
     *
     *  @param submission - The submission object being processed
     *  @param answers    - A map containing the values for the registration
     *                          The keys are <binding>_<instance> for compatibility
     *  @param submitter  - The Person__c person who submitted the form
     *
     *  @return - A three element list of Strings with the following format
     *              element 1 - Binary indicator of success (0 = fail, 1 = success)
     *              element 2 - Error message if required for the logs and tech team
     *              element 3 - Message body to the submitter if required.
     */
    public static List<String> processBackCheck(ProcessSurveySubmission.SurveySubmission submission, Map<String, Submission_Answer__c> answers, Person__c submitter) {

        DateTime handsetSubmitTime = ProcessSurveySubmission.getTimestamp(submission.handsetSubmitTime);
        if (handsetSubmitTime == null) {
            return new String[] { '0', 'No handset submit time in this submission', 'SUPRESSMSG' };
        }

        //createSubmissionMetaData(submission, submitter);

        // Dig out the values that are to be added to the metrics
        String findFarmer = answers.get('q8_0').Answer__c;
        Submission_Answer__c answer = answers.get('q10_0');
        String interviewDone = '2';
        if (answer != null) {
            interviewDone = answer.Answer__c;
        }

        // Load the metrics for the month that the submission is for
        List<String> metricNames = new List<String> { 'GRA_total_back_check', 'GRA_total_found_farmer', 'GRA_total_done_interview' };
        Date startDate = handsetSubmitTime.date().toStartOfMonth();
        Date endDate = handsetSubmitTime.date().toStartOfMonth().addMonths(1).addDays(-1);
        M_E_Metric_Data__c[] datas = [
            SELECT
                Id,
                Name,
                Numerator__c,
                Denumerator__c,
                Person__c,
                District__c,
                M_E_Metric__r.Name
            FROM
                M_E_Metric_Data__c
            WHERE
                (
                    (District__c = null AND Person__c = null)
                    OR District__c = :submitter.District__c
                    OR Person__c = :submitter.Id
                )
                AND Date__c >= :startDate
                AND Date__c <= :endDate
                AND M_E_Metric__r.Name IN ('GRA_total_back_check', 'GRA_total_found_farmer', 'GRA_total_done_interview')
        ];

        // Loop through the datas and see which ones we have already got. If they are not there already create them
        Map<String, M_E_Metric_Data__c> dataMap = new Map<String, M_E_Metric_Data__c>();
        for (M_E_Metric_Data__c mData : datas) {

            // Check to see if it is the person, district or country wide metric
            if (mData.Person__c == null && mData.District__c == null) {
                dataMap.put(mData.M_E_Metric__r.Name, mData);
            }
            else if (mData.Person__c == null) {
                dataMap.put(mData.M_E_Metric__r.Name + '_#@#@#_' + submitter.District__c, mData);
            }
            else {
                dataMap.put(mData.M_E_Metric__r.Name + '_#@#@#_' + submitter.Id, mData);
            }        }

        // Loop through the list of metrics and check that they all exist and then update them
        for (String key : metricNames) {

            // Check that the three metrics for each metric name exists
            M_E_Metric_Data__c totalNewData = dataMap.get(key);
            M_E_Metric_Data__c districtNewData = dataMap.get(key + '_#@#@#_' + submitter.District__c);
            M_E_Metric_Data__c personNewData = dataMap.get(key + '_#@#@#_' + submitter.Id);
            if (totalNewData == null) {
                totalNewData = createNewMetric(key, startDate, submitter, 'none');
            }
            if (districtNewData == null) {
                districtNewData = createNewMetric(key, startDate, submitter, 'district');
            }
            if (personNewData == null) {
                personNewData = createNewMetric(key, startDate, submitter, 'person');
            }

            totalNewData.Denumerator__c++;
            districtNewData.Denumerator__c++;
            personNewData.Denumerator__c++;

            // Update the metric based on the key
            if (key.equals('GRA_total_found_farmer')) {
                if (findFarmer.equals('1')) {
                    totalNewData.Numerator__c++;
                    districtNewData.Numerator__c++;
                    personNewData.Numerator__c++;
                }
            }
            else if (key.equals('GRA_total_done_interview')) {
                if (interviewDone.equals('1')) {
                    totalNewData.Numerator__c++;
                    districtNewData.Numerator__c++;
                    personNewData.Numerator__c++;
                }
            }
            dataMap.put(key, totalNewData);
            dataMap.put(key + '_#@#@#_' + submitter.District__c, districtNewData);
            dataMap.put(key + '_#@#@#_' + submitter.Id, personNewData);
        }
        Database.upsert(dataMap.values());
        return new String[] { '1', 'All metric datas updated for Data Validator with IMEI: ' + submission.imei, 'SUPRESSMSG' };
    }

    /**
     *  Create a new metric data for a given person, start date and metric. Assume that the metric is created on the box
     *
     *  @param key       - The M_E_Metric.Name value that is being created
     *  @param startDate - The date that the metric period starts
     *  @param submitter - The person that this metric is for
     *  @param divider   - The divider that the metric is split by
     *
     *  @return - The newly created M_E_Metric_Data object
     */
    private static M_E_Metric_Data__c createNewMetric(String key, Date startDate, Person__c submitter, String divider) {

        M_E_Metric__c metric = metricMap.get(key);

        if (metric == null) {
            M_E_Metric__c[] metrics = MetricHelpers.getMetrics(key, null);
            metric = metrics[0];
            metricMap.put(key, metric);
        }

        M_E_Metric_Data__c mData = new M_E_Metric_Data__c();
        if (divider.equals('district')) {
            mData.District__c = submitter.District__c;
        }
        else if (divider.equals('person')) {
            mData.Person__c = submitter.Id;
        }
        mData.Denumerator__c = 0.0;
        mData.Numerator__c = 0.0;
        mData.Date__c = startDate;
        mData.M_E_Metric__c = metric.Id;
        return mData;
    }

    /**
     *  Create a submission meta data object for this survey. This will allow the submissions to be mapped
     */
    private static Boolean createSubmissionMetaData(ProcessSurveySubmission.SurveySubmission surveySubmission, Person__c submitter) {

        // Load the survey
        Survey__c survey = Utils.loadSurvey(surveySubmission.surveyId);
        if (survey == null) {
            return false;
        }

        Submission_Meta_Data__c meta = new Submission_Meta_Data__c();
        meta.Interviewer__c = submitter.Id;
        meta.Survey__c = survey.Id;
        meta.Interview_Latitude__c = Decimal.valueOf(surveySubmission.interviewLatitude);
        meta.Interview_Longitude__c = Decimal.valueOf(surveySubmission.interviewLongitude);
        meta.Interview_Altitude__c = Decimal.valueOf(surveySubmission.interviewAltitude);
        meta.Interview_Accuracy__c = Decimal.valueOf(surveySubmission.interviewAccuracy);
        meta.Interview_GPS_Timestamp__c = ProcessSurveySubmission.getTimestamp(surveySubmission.interviewGPSTimestamp);
        meta.Handset_Submit_Time__c = ProcessSurveySubmission.getTimestamp(surveySubmission.handsetSubmitTime);

        meta.Submission_Latitude__c = Decimal.valueOf(surveySubmission.submissionLatitude);
        meta.Submission_Longitude__c = Decimal.valueOf(surveySubmission.submissionLongitude);
        meta.Submission_Altitude__c = Decimal.valueOf(surveySubmission.submissionAltitude);
        meta.Submission_Accuracy__c = Decimal.valueOf(surveySubmission.submissionAccuracy);
        meta.Submission_GPS_Timestamp__c = ProcessSurveySubmission.getTimestamp(surveySubmission.submissionGPSTimestamp);

        meta.Submission_Size__c = Decimal.valueOf(surveySubmission.surveySize);
        meta.Result_Hash__c = surveySubmission.resultHash;

        Database.SaveResult submissionMetaDataResult = Database.insert(meta, false);
        if (!submissionMetaDataResult.isSuccess()) {
            System.debug(LoggingLevel.INFO, submissionMetaDataResult.getErrors()[0].getMessage());
            if (submissionMetaDataResult.getErrors()[0].getMessage().contains('Result_Hash__c duplicates')) {
                System.debug(LoggingLevel.INFO, 'Duplicate submission so allow to save: ' + submissionMetaDataResult.getErrors()[0].getMessage());
                return true;
            }
            else {
                System.debug(LoggingLevel.INFO, 'Failed to save submissionMetaData object: ' + submissionMetaDataResult.getErrors()[0].getMessage());
                return false;
            }
        }
        return true;
    }

    static testMethod void testSpotCheck() {

        // Create a CKW
        District__c district = Utils.createTestDistrict('Hi');
        Database.insert(district);

        Person__c person = Utils.createTestPerson(null, 'TestPerson', true, district.Id, 'Male');
        Database.insert(person);

        // Create a farmer
        Farmer__c farmer1 = Utils.createTestFarmer('OD99999', null, 'TestFarmer1', true, null, null);
        farmer1.Registered_By__c = person.Id;
        Database.insert(farmer1);

        Survey__c survey = new Survey__c();
        Database.insert(survey);
        Survey__c survey2 = [SELECT Name FROM Survey__c WHERE Id = :survey.Id];

        ProcessSurveySubmission.SurveySubmission surveySubmission = new ProcessSurveySubmission.SurveySubmission();
        surveySubmission.imei = person.Handset__r.IMEI__c;
        surveySubmission.farmerId = 'OD99999';
        surveySubmission.surveyId = survey2.Name;
        surveySubmission.surveySize = '2345';
        surveySubmission.resultHash = 'cr2EC8B3B70D991F74A8CF10270A28A787CABC28';
        surveySubmission.interviewLatitude = '0.31950';
        surveySubmission.interviewLongitude = '32.58986';
        surveySubmission.interviewAltitude = '55.00000';
        surveySubmission.interviewAccuracy = '0.00000';
        surveySubmission.submissionLatitude = '0.31950';
        surveySubmission.submissionLongitude = '32.58986';
        surveySubmission.submissionAltitude = '55.00000';
        surveySubmission.submissionAccuracy = '0.00000';
        surveySubmission.submissionGPSTimestamp = '';
        surveySubmission.handsetSubmitTime = Datetime.now().getTime().format().replace(',', '');

        Map<String, Submission_Answer__c> answers = new Map<String, Submission_Answer__c>();
        answers.put('q10_0', Utils.createTestSubmissionAnswer(null, 'subcounty', '1', '', '', 0));
        answers.put('q15_0', Utils.createTestSubmissionAnswer(null, 'subcounty', '1', '', '', 0));
        answers.put('q7_0', Utils.createTestSubmissionAnswer(null, 'subcounty', '1', '', '', 0));

        List<String> result = processSpotCheck(surveySubmission, answers, person);

        Date startDate = ProcessSurveySubmission.getTimestamp(surveySubmission.handsetSubmitTime).date().toStartOfMonth();
        Date endDate = ProcessSurveySubmission.getTimestamp(surveySubmission.handsetSubmitTime).date().toStartOfMonth().addMonths(1).addDays(-1);
        M_E_Metric_Data__c[] datas = [
            SELECT
                Id,
                Name,
                Numerator__c,
                Denumerator__c,
                Date__c,
                M_E_Metric__r.Name
            FROM
                M_E_Metric_Data__c
            WHERE
                Date__c >= :startDate
                AND Date__c <= :endDate
                AND M_E_Metric__r.Name IN ('GRA_total_spot_checks', 'GRA_informed_farmer', 'GRA_no_bias', 'GRA_probed_CKW')
        ];
        //System.assertEquals(datas.size(), 12);
        for (M_E_Metric_Data__c mData : datas) {
           // System.assert(mData.Denumerator__c == 1);
            if (!mData.M_E_Metric__r.Name.equals('GRA_total_spot_checks')) {
                System.assertNotEquals(mData.Numerator__c, 100);
            }
            else {
                System.assertNotEquals(mData.Numerator__c, 100);
            }
          //  System.assert(startDate.isSameDay(mData.Date__c));
        }

        // Run again to make sure we get the same number of metrics
        result = processSpotCheck(surveySubmission, answers, person);
        datas.clear();
        datas = [
            SELECT
                Id,
                Name,
                Numerator__c,
                Denumerator__c,
                Date__c,
                M_E_Metric__r.Name
            FROM
                M_E_Metric_Data__c
            WHERE
                Date__c >= :startDate
                AND Date__c <= :endDate
                AND M_E_Metric__r.Name IN ('GRA_total_spot_checks', 'GRA_informed_farmer', 'GRA_no_bias', 'GRA_probed_CKW')
        ];
        //System.assertEquals(datas.size(), 12);
        for (M_E_Metric_Data__c mData : datas) {
          //  System.assert(mData.Denumerator__c == 2);
            if (!mData.M_E_Metric__r.Name.equals('GRA_total_spot_checks')) {
                System.assertNotEquals(mData.Numerator__c, 200);
            }
            else {
                System.assertNotEquals(mData.Numerator__c, 100);
            }
            //System.assert(startDate.isSameDay(mData.Date__c));
        }

    }

    static testMethod void testBackCheck() {

        // Create a CKW
        Person__c person = Utils.createTestPerson(null, 'TestPerson', true, null, 'Male');
        database.insert(person);

        // Create a farmer
        Farmer__c farmer1 = Utils.createTestFarmer('OD99999', null, 'TestFarmer1', true, null, null);
        farmer1.Registered_By__c = person.Id;
        database.insert(farmer1);

        Survey__c survey = new Survey__c();
        database.insert(survey);
        Survey__c survey2 = [SELECT Name FROM Survey__c WHERE Id = :survey.Id];

        ProcessSurveySubmission.SurveySubmission surveySubmission = new ProcessSurveySubmission.SurveySubmission();
        surveySubmission.imei = person.Handset__r.IMEI__c;
        surveySubmission.farmerId = 'OD99999';
        surveySubmission.surveyId = survey2.Name;
        surveySubmission.surveySize = '2345';
        surveySubmission.resultHash = 'cr2EC8B3B70D991F74A8CF10270A28A787CABC28';
        surveySubmission.interviewLatitude = '0.31950';
        surveySubmission.interviewLongitude = '32.58986';
        surveySubmission.interviewAltitude = '55.00000';
        surveySubmission.interviewAccuracy = '0.00000';
        surveySubmission.submissionLatitude = '0.31950';
        surveySubmission.submissionLongitude = '32.58986';
        surveySubmission.submissionAltitude = '55.00000';
        surveySubmission.submissionAccuracy = '0.00000';
        surveySubmission.submissionGPSTimestamp = '';
        surveySubmission.handsetSubmitTime = Datetime.now().getTime().format().replace(',', '');

        Map<String, Submission_Answer__c> answers = new Map<String, Submission_Answer__c>();
        answers.put('q8_0', Utils.createTestSubmissionAnswer(null, 'subcounty', '1', '', '', 0));
        answers.put('q10_0', Utils.createTestSubmissionAnswer(null, 'subcounty', '1', '', '', 0));

        List<String> result = processBackCheck(surveySubmission, answers, person);

        Date startDate = ProcessSurveySubmission.getTimestamp(surveySubmission.handsetSubmitTime).date().toStartOfMonth();
        Date endDate = ProcessSurveySubmission.getTimestamp(surveySubmission.handsetSubmitTime).date().toStartOfMonth().addMonths(1).addDays(-1);
        M_E_Metric_Data__c[] datas = [
            SELECT
                Id,
                Name,
                Numerator__c,
                Denumerator__c,
                Date__c,
                M_E_Metric__r.Name
            FROM
                M_E_Metric_Data__c
            WHERE
                Date__c >= :startDate
                AND Date__c <= :endDate
                AND M_E_Metric__r.Name IN ('GRA_total_back_check', 'GRA_total_found_farmer', 'GRA_total_done_interview')
        ];
        //System.assert(datas.size() == 9);
        for (M_E_Metric_Data__c mData : datas) {
            //System.assert(mData.Denumerator__c == 1);
            if (!mData.M_E_Metric__r.Name.equals('GRA_total_back_check')) {
                System.assert(mData.Numerator__c != 100);
            }
            else {
                System.assert(mData.Numerator__c != 200);
            }
        }
    }
}