src/objects/District__c.object
<CustomObject>
    <description>Shows the locations for a district. Used to get GPS values</description>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Districts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Harvest__c.object
<CustomObject>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <picklist>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pigeon peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black beans(Dolichos)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cow peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green grams</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_Harvested__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date Harvested</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Harvests</relationshipLabel>
        <relationshipName>Harvests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Accepted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Accepted</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Harvested__c</fullName>
        <label>Quantity Harvested</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Rejected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Rejected</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Harvest</label>
    <nameField>
        <displayFormat>H{000000}</displayFormat>
        <label>Harvest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>District__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The district for the person</description>
        <label>District</label>
        <referenceTo>District__c</referenceTo>
        <relationshipLabel>People</relationshipLabel>
        <relationshipName>People</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sale__c.object
<CustomObject>
    <description>Represents a sale transaction from the warehouse</description>
    <fields>
        <fullName>Beans_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Beans Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beans_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Beans Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cow Peas Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cow Peas Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dolichos_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Dolichos Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dolichos_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Dolichos Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Green_Grams_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Green Grams Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Green_Grams_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Green Grams Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maize_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maize Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maize_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maize Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Pigeon Peas Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Pigeon Peas Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>The date the transaction was made</description>
        <label>Sale Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Sale</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Sale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sale_Farmer_Association__c.object
<CustomObject>
    <fields>
        <fullName>Beans_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Beans Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cow Peas Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dolichos_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Dolichos Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Sale Farmer Associations</relationshipLabel>
        <relationshipName>Sale_Farmer_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Green_Grams_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Green Grams Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maize_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maize Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Pigeon Peas Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale__c</fullName>
        <label>Sale</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipLabel>Sale Farmer Associations</relationshipLabel>
        <relationshipName>Sale_Farmer_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sale Farmer Association</label>
    <nameField>
        <displayFormat>SFN-{000000}</displayFormat>
        <label>Sale Farmer Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sale Farmer Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Scheduled_Message_Queue__c.object
<CustomObject>
    <description>object to hold messages that are meant to be sent at a time in the future</description>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person to whom the message is directed</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Scheduled Message Queues</relationshipLabel>
        <relationshipName>Scheduled_Message_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scheduled Message Queue</label>
    <nameField>
        <label>Scheduled Message Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Message Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EwarehouseTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class EwarehouseTriggerHandlerTest {

    static testMethod void testonAfterHarvestInsert() {


        //Setup data for the test
        District__c testDistrict = Utils.createTestDistrict('Ewarehouse');
        insert testDistrict;

        Person__c testPerson = Utils.createTestPerson(null, 'E-FARMER', true, null, 'Female');
        insert testPerson;

        Farmer__c testFarmer = Utils.createTestFarmer('ABC123', testPerson.Id, '', false, testDistrict.Id, 'Male');
        insert testFarmer;

        Integer beforeMessageCount = [SELECT COUNT() FROM Scheduled_Message_Queue__c WHERE Person__c =:testPerson.id];
        Harvest__c testHarvest = new Harvest__c();
        testHarvest.Crop__c = 'Maize';
        testHarvest.Farmer__c = testFarmer.Id;
        testHarvest.Date_Harvested__c = date.today();
        testHarvest.Quantity_Harvested__c = 100;
        testHarvest.Quantity_Accepted__c = 10;
        testHarvest.Quantity_Rejected__c = 90;
        insert testHarvest;

        Integer afterMessageCount  = [SELECT COUNT() FROM Scheduled_Message_Queue__c WHERE Person__c =:testPerson.id];
        //System.assert(afterMessageCount - beforeMessageCount == 1);
    }

    static testMethod void testonAfterSaleRegistrationInsert() {


        //Setup data for the test
        District__c testDistrict = Utils.createTestDistrict('Ewarehouse');
        insert testDistrict;

        Person__c testPerson = Utils.createTestPerson(null, 'E-FARMER2', true, null, 'Female');
        insert testPerson;

        Farmer__c testFarmer = Utils.createTestFarmer('ABC1234', testPerson.Id, '', false, testDistrict.Id, 'Male');
        insert testFarmer;

        Integer beforeMessageCount = [SELECT COUNT() FROM Scheduled_Message_Queue__c WHERE Person__c =:testPerson.id];

        Sale__c saleObject = new Sale__c();
        saleObject.Dolichos_Number_of_90kg_Bags_Sold__c = 5;
        saleObject.Dolichos_Price_Per_90kg_Bag__c = 140;
        saleObject.Beans_Number_of_90kg_Bags_Sold__c = 9;
        saleObject.Beans_Price_Per_90kg_Bag__c = 55;
        saleObject.Cow_Peas_Number_of_90kg_Bags_Sold__c = 4;
        saleObject.Cow_Peas_Price_Per_90kg_Bag__c = 60;
        saleObject.Green_Grams_Number_of_90kg_Bags_Sold__c = 0;
        saleObject.Green_Grams_Price_Per_90kg_Bag__c = 0;
        saleObject.Maize_Number_of_90kg_Bags_Sold__c = 20;
        saleObject.Maize_Price_Per_90kg_Bag__c = 45;
        saleObject.Pigeon_Peas_Number_of_90kg_Bags_Sold__c = 15;
        saleObject.Pigeon_Peas_Price_Per_90kg_Bag__c = 50;
        saleObject.Sale_Date__c = date.today();
        insert saleObject;

        Sale_Farmer_Association__c saleFarmer = new Sale_Farmer_Association__c();
        saleFarmer.Farmer__c = testFarmer.Id;
        saleFarmer.Sale__c = saleObject.Id;
        saleFarmer.Dolichos_Number_of_90kg_Bags_Sold__c = 3;
        saleFarmer.Pigeon_Peas_Number_of_90kg_Bags_Sold__c = 4;
        saleFarmer.Cow_Peas_Number_of_90kg_Bags_Sold__c = 30;
        saleFarmer.Beans_Number_of_90kg_Bags_Sold__c = 7;
        salefarmer.Maize_Number_of_90kg_Bags_Sold__c = 20;
        saleFarmer.Green_Grams_Number_of_90kg_Bags_Sold__c = 14;
        insert saleFarmer;      

        Integer afterMessageCount  = [SELECT COUNT() FROM Scheduled_Message_Queue__c WHERE Person__c =:testPerson.id];
        System.assert(afterMessageCount - beforeMessageCount == 1);
    }
}