src/objects/EADD_Hub__c.object
<CustomObject>
    <description>An EADD Hub or Milk collection center</description>
    <fields>
        <fullName>Hub_capacity_utilization__c</fullName>
        <label>Hub capacity utilization</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Radius_Covered__c</fullName>
        <description>Radius of hub in terms of diary farmer coverage (km)</description>
        <label>Radius Covered</label>
        <precision>11</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>EADD Hub</label>
    <nameField>
        <label>EADD Hub Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EADD Hubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EADDMapMarkers.cls
/**
 *
 * Copyright (c) 2013 AppLab, Grameen Foundation
 *
 *  Holds map markers for the EADD dashboard map parameters
 *
 **/
public with sharing class EADDMapMarkers extends MapMarkers {

	private EADD_Hub__c hub;
	
    public EADDMapMarkers(EADD_Hub__c hub) {
        this.hub = hub;
        this.setLatitude(hub.Latitude__c);
        this.setLongitude(hub.Longitude__c);
        this.setMarkerTitle(hub.Name__c);
        setDefaultColour('Green');
    }
    
    // Generate the content string for a Hub
    public override String getMarkerInfoContentString() {

        String content = 	'<table border="0">'										+
							'	<tr>'													+
							'		<td>Hub Details</td>'								+
							'		<td></td>'											+
							'	</tr>'													+
							'	<tr>'													+
							'		<td>Name:</td>'										+
							'		<td>' + hub.Name__c + '</td>'						+
							'	</tr>'													+
							'	<tr>'													+
							'		<td>Utilization level: </td>'						+
							'		<td>' + hub.Hub_capacity_utilization__c + '</td>'	+
							'	</tr>'													+
							'	<tr>'													+
							'		<td>Coverage(km)</td>'								+
							'		<td>' + hub.Radius_Covered__c + '</td>'				+
							'	</tr>'													+
							'</table>';          
        return content;
    }
}