src/objects/EMP_Consultant__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Consultant_contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EMP Consultants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Consultant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Consultant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Consultants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LacFarmerProfilePageControllerTest.cls
/**
	Test class for LacFarmerProfilePageController 
*/
@isTest
private class LacFarmerProfilePageControllerTest {

	private LAC_Farmer_Details__c farmerDetails = createLacFarmer();
	private ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
	private LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc);

	public static testMethod void testGetCoffeeVarieties() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc); 
		
		system.assertEquals(ctrl.getCoffeeVarieties(), ''); 
	}
	
	public static testMethod void testGetProductivity() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc); 
		
		system.assertEquals(ctrl.getProductivity(), 'N/A');	
	}

	public static testMethod void testGetProduction() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc); 
		
		system.assertEquals(ctrl.getProduction(), 0); 
	}
	public static testMethod void testGetCoffeePlantedArea() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc); 
		
		system.assertEquals(ctrl.getCoffeePlantedArea(), 0); 	
	}
	public static testMethod void testGetCertifications() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc); 
		
		system.assertEquals(ctrl.getCertifications(), ''); 
	}
	public static testMethod void testGetFMPCategoryResultsGroup() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc); 
		
		system.assertEquals(ctrl.getFMPCategoryResultsGroup().size(), 0);		
	}
	
	public static testMethod void testGetFamManagementPlansResults() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc); 
		
		system.assertEquals(ctrl.getFamManagementPlansResults().size(), 0);
	}
	
	public static testMethod void testGetFMPFarmScores() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc); 
		
		system.assertEquals(ctrl.getFMPFarmScores().size(), 0);
	}
	
	public static testMethod void testGetFoodSecs() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc); 
		
		system.assertEquals(ctrl.getFoodSecs().size(), 0);
	}
	
	public static testMethod void testGetCblLots() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc); 
		
		system.assertEquals(ctrl.getCblLots().size(), 0);
	}
	
	public static testMethod void testGetSignatureFarm() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc);
		system.assertEquals(ctrl.getSignatureFarm(), null);
	}	
	
	public static testMethod void testGetCblFarms() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc);
		system.assertEquals(ctrl.getCblFarms().size(), 0);
	}	

	public static testMethod void testGetCblCommercialization() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc);
		system.assertEquals(ctrl.getCblCommercialization(), null);
	}	
	
	public static testMethod void testGetSocioEconomic() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc);
		system.assertEquals(ctrl.getSocioEconomic(), null);
	}	
	
	public static testMethod void testGetCoffeeBaselines() {
		LAC_Farmer_Details__c farmerDetails = createLacFarmer();
		
		ApexPages.StandardController sc = new ApexPages.StandardController(farmerDetails);
		LacFarmerProfilePageController ctrl = new LacFarmerProfilePageController(sc);
		system.assertEquals(ctrl.getCoffeeBaselines().size(), 0);
	}
		
	private static LAC_Farmer_Details__c createLacFarmer() {
		//Person__c person = new Person__c();
		Contact contact = new Contact();
		User user = new User();
		
		LAC_Farmer_Details__c farmerDetails = new LAC_Farmer_Details__c();
		//farmerDetails.Person__c = person.Id;
		farmerDetails.Contact__c = contact.Id;
		farmerDetails.Contact__r = contact;
				
		return farmerDetails;
	}

}