src/objects/EMP_Organization_Member_Beneficiary__c.object
<CustomObject>
    <label>EMP Organization Member Beneficiary</label>
    <nameField>
        <displayFormat>EMPOMB-{000000}</displayFormat>
        <label>EMP Organization Member Beneficiary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Organization Member Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Training_Assistant__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Training_Assistant_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EMP Training Assistant Member</label>
        <referenceTo>EMP_Organization_Member__c</referenceTo>
        <relationshipLabel>EMP Training Assistants</relationshipLabel>
        <relationshipName>EMP_Training_Assistants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EMP_Training_Assistant__c</fullName>
        <label>EMP Training Assistant</label>
        <referenceTo>EMP_Training__c</referenceTo>
        <relationshipLabel>EMP Training Assistants</relationshipLabel>
        <relationshipName>EMP_Training_Assistants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Identification_Number__c</fullName>
        <label>Identification Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>EMP Training Assistant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Training Assistant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Training Assistants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EMPTrainingAsistantBatchJob.cls
global class EMPTrainingAsistantBatchJob implements Database.Batchable<sObject> {
	
	 global Database.QueryLocator start(Database.BatchableContext bc) {
      // 
      String query = 'Select Id, EMP_Training_Assistant_Member__c, EMP_Organization_Member_Beneficiary__c, Identification_Number__c from EMP_Training_Assistant__c where EMP_Organization_Member_Beneficiary__c = null' ;
      return Database.getQueryLocator(query);
  }
  
  global void execute(Database.BatchableContext bc, List<EMP_Training_Assistant__c> empTAs) {
    for (EMP_Training_Assistant__c empTA : empTAs) {
        EMPTrainingasistantHandler handler = new EMPTrainingasistantHandler(empTA); 
        handler.handle();
    }
    update empTAs;
  }
  
  global void finish(Database.BatchableContext bc) {
    // Do nothing
  }
	
}