src/objects/EMP_Consultant__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Consultant_contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EMP Consultants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Consultant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Consultant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Consultants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ewarehouse_Farmer__c.object
<CustomObject>
    <description>This is the farmer that is registered by the VKW at the field.</description>
    <fields>
        <fullName>Auto_Generated_Farmer_ID__c</fullName>
        <label>Farmer FCI Id</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ewarehouse Farmers</relationshipLabel>
        <relationshipName>Ewarehouse_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Ewarehouse Farmers</relationshipLabel>
        <relationshipName>Ewarehouse_Farmers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ewarehouse Farmer</label>
    <nameField>
        <label>Ewarehouse Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ewarehouse_Harvest__c.object
<CustomObject>
    <fields>
        <fullName>Beans_Harvested__c</fullName>
        <label>Beans Harvested</label>
        <summarizedField>Ewarehouse_Harvest_Crop__c.Beans_Harvested__c</summarizedField>
        <summaryForeignKey>Ewarehouse_Harvest_Crop__c.Ewarehouse_Harvest__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Black_Beans_Harvested__c</fullName>
        <label>Black Beans Harvested</label>
        <summarizedField>Ewarehouse_Harvest_Crop__c.Black_Beans_Harvested__c</summarizedField>
        <summaryForeignKey>Ewarehouse_Harvest_Crop__c.Ewarehouse_Harvest__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Harvested__c</fullName>
        <label>Cow Peas Harvested</label>
        <summarizedField>Ewarehouse_Harvest_Crop__c.Cow_Peas_Harvested__c</summarizedField>
        <summaryForeignKey>Ewarehouse_Harvest_Crop__c.Ewarehouse_Harvest__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Farmer__c</fullName>
        <label>Ewarehouse Farmer</label>
        <referenceTo>Ewarehouse_Farmer__c</referenceTo>
        <relationshipLabel>Ewarehouse Harvests</relationshipLabel>
        <relationshipName>Ewarehouse_Harvests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Green_Grams_Harvested__c</fullName>
        <label>Green Grams Harvested</label>
        <summarizedField>Ewarehouse_Harvest_Crop__c.Green_Grams_Harvested__c</summarizedField>
        <summaryForeignKey>Ewarehouse_Harvest_Crop__c.Ewarehouse_Harvest__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Harvest_Date__c</fullName>
        <label>Harvest Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maize_Harvested__c</fullName>
        <label>Maize Harvested</label>
        <summarizedField>Ewarehouse_Harvest_Crop__c.Maize_Harvested__c</summarizedField>
        <summaryForeignKey>Ewarehouse_Harvest_Crop__c.Ewarehouse_Harvest__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Notification_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Harvested__c</fullName>
        <label>Pigeon Peas Harvested</label>
        <summarizedField>Ewarehouse_Harvest_Crop__c.Pigeon_Peas_Harvested__c</summarizedField>
        <summaryForeignKey>Ewarehouse_Harvest_Crop__c.Ewarehouse_Harvest__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Ewarehouse Harvest</label>
    <nameField>
        <label>Ewarehouse Harvest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Harvests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduledHarvestMessageSender.cls
global class ScheduledHarvestMessageSender implements Schedulable {
    
    // Cron Expression to schedule the job to run at 15 minutes to the top of the hour
    public static String cronExpression = '0 45 1-23 * * ?';
    
    global void execute(SchedulableContext sc) {
        String queryString = 'SELECT ' +
            'Id,' +
            'Ewarehouse_Farmer__r.Id,' +
            'Ewarehouse_Farmer__r.Auto_Generated_Farmer_ID__c,' +
            'Ewarehouse_Farmer__r.Contact__r.FirstName,' +
            'Ewarehouse_Farmer__r.Contact__r.LastName,' +
            'Ewarehouse_Farmer__r.Contact__r.MobilePhone,' +
            'Ewarehouse_Farmer__r.Ewarehouse_Person__r.Id, ' +
            'Harvest_Date__c, ' +
            'Beans_Harvested__c,' +
            'Maize_Harvested__c,' +
            'Cow_Peas_Harvested__c,' +
            'Black_Beans_Harvested__c, ' +
            'Green_Grams_Harvested__c, ' +
            'Pigeon_Peas_Harvested__c ' +
        'FROM ' +
            ' Ewarehouse_Harvest__c ' +
        ' WHERE ' +
            'Notification_Sent__c = false'; 
        ID batchProcessId = Database.executeBatch(new HarvestMessageSender(queryString), 50);
    }
}