src/objects/EMP_Consultant__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Name__c</fullName>
        <label>Consultant Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMP_Consultant_contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>EMP Consultants</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Consultant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Consultant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Consultants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Farm__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Farm_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EMP Farm Leader</label>
        <referenceTo>EMP_Leader__c</referenceTo>
        <relationshipLabel>EMP Farms</relationshipLabel>
        <relationshipName>EMP_Farms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EMP_Farm__c</fullName>
        <label>EMP Farm</label>
        <referenceTo>EMP_Organization_Member__c</referenceTo>
        <relationshipLabel>EMP Farms</relationshipLabel>
        <relationshipName>EMP_Farms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Farm_Name__c</fullName>
        <label>Farm Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>EMP Farm</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Farm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Farms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Farm_Baseline__c.object
<CustomObject>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <label>Organization Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>EMP Farm Baseline</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Farm Baseline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Farm Baselines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Farm_BPA_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Corrective_Actions__c</fullName>
        <label>Batch Corrective Actions</label>
        <picklist>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Batch_Inspection__c</fullName>
        <label>Batch Inspection</label>
        <picklist>
            <picklistValues>
                <fullName>SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EMP_Farm_BPA_Checklist__c</fullName>
        <label>EMP Farm BPA Checklist</label>
        <referenceTo>EMP_Farm__c</referenceTo>
        <relationshipLabel>EMP Farm BPA Checklists</relationshipLabel>
        <relationshipName>EMP_Farm_BPA_Checklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Farm_Name__c</fullName>
        <label>Farm Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_Number__c</fullName>
        <label>Id Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <label>Organization Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>EMP Farm BPA Checklist</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Farm BPA Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Farm BPA Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Farm_Diagnostic_and_Targets__c.object
<CustomObject>
    <fields>
        <fullName>Farm__c</fullName>
        <label>Farm</label>
        <referenceTo>EMP_Farm__c</referenceTo>
        <relationshipLabel>EMP Farm diagnosis and targets</relationshipLabel>
        <relationshipName>EMP_Farm_Diagnosis_and_Targets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Farm Diagnosis and Targets</label>
    <nameField>
        <label>EMP Farm Diagnostic and Targets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EMP Farm Diagnosis and Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Leader__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Leader_Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EMP Leader Consultant</label>
        <referenceTo>EMP_Consultant__c</referenceTo>
        <relationshipLabel>EMP Leaders</relationshipLabel>
        <relationshipName>EMP_Leaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EMP_Leader__c</fullName>
        <label>EMP Leader</label>
        <referenceTo>EMP_Organization__c</referenceTo>
        <relationshipLabel>EMP Leaders</relationshipLabel>
        <relationshipName>EMP_Leaders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Leader</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Leader Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Leaders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Organization__c.object
<CustomObject>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <label>Organization Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>EMP Organization</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Organization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EMP_organization_consultant__c.object
<CustomObject>
    <fields>
        <fullName>Consultant_Name__c</fullName>
        <formula>EMP_Consultant__r.Consultant_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Consultant Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMP_Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EMP Consultant</label>
        <referenceTo>EMP_Consultant__c</referenceTo>
        <relationshipLabel>EMP Consultant</relationshipLabel>
        <relationshipName>EMP_organization_consultants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EMP_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EMP Organization</label>
        <referenceTo>EMP_Organization__c</referenceTo>
        <relationshipLabel>EMP Organization</relationshipLabel>
        <relationshipName>EMP_organization_consultants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <formula>EMP_Organization__r.Organization_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization Name</label>
        <type>Text</type>
    </fields>
    <label>EMP organization consultant</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>EMP organization consultant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP organization consultants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EMP_Organization_Member__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Organization_Member_Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EMP Organization Member Consultant</label>
        <referenceTo>EMP_Consultant__c</referenceTo>
        <relationshipLabel>EMP Organization Members</relationshipLabel>
        <relationshipName>EMP_Organization_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EMP_Organization__c</fullName>
        <label>EMP Organization</label>
        <referenceTo>EMP_Organization__c</referenceTo>
        <relationshipLabel>EMP Organization Members</relationshipLabel>
        <relationshipName>EMP_Organization_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Organization Member</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Organization Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Organization Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Organization_Member_Beneficiary__c.object
<CustomObject>
    <fields>
        <fullName>ID_Number__c</fullName>
        <label>ID Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Member__c</fullName>
        <label>Organization_Member</label>
        <referenceTo>EMP_Organization_Member__c</referenceTo>
        <relationshipLabel>EMP_OMBeneficiary_Organization_Member</relationshipLabel>
        <relationshipName>EMP_OMBeneficiary_Organization_Member</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Organization Member Beneficiary</label>
    <nameField>
        <displayFormat>EMPOMB-{000000}</displayFormat>
        <label>EMP Organization Member Beneficiary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Organization Member Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Technical_Assistance__c.object
<CustomObject>
    <fields>
        <fullName>Identification_Number__c</fullName>
        <label>Identification Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <label>Organization Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>EMP Technical Assistance</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Technical Assistance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Technical Assistances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Training__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Training__c</fullName>
        <label>EMP Training</label>
        <referenceTo>EMP_Consultant__c</referenceTo>
        <relationshipLabel>EMP Trainings</relationshipLabel>
        <relationshipName>EMP_Trainings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Training_Name__c</fullName>
        <label>Training Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>EMP Training</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Training_Assistant__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Training_Assistant_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EMP Training Assistant Member</label>
        <referenceTo>EMP_Organization_Member__c</referenceTo>
        <relationshipLabel>EMP Training Assistants</relationshipLabel>
        <relationshipName>EMP_Training_Assistants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EMP_Training_Assistant__c</fullName>
        <label>EMP Training Assistant</label>
        <referenceTo>EMP_Training__c</referenceTo>
        <relationshipLabel>EMP Training Assistants</relationshipLabel>
        <relationshipName>EMP_Training_Assistants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Identification_Number__c</fullName>
        <label>Identification Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <label>Organization Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>EMP Training Assistant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Training Assistant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Training Assistants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EMPOrganizationProfileTest.cls
@isTest
private class EMPOrganizationProfileTest {
    
    @isTest static void test_method_one() {
        //create contact
        Contact contact = new Contact(LastName = 'Perez');
        insert contact;

        //create consultant
        EMP_Consultant__c consultor = new EMP_Consultant__c();
        consultor.EMP_Consultant_contact__c = contact.Id;
        consultor.Consultant_Name__c = 'Pepito Perez';
        insert consultor;

        EMP_Organization__c organizacion = new EMP_Organization__c();
        organizacion.Organization_Name__c = 'La organziación';
        insert organizacion;

        EMP_organization_consultant__c consultororg = new EMP_organization_consultant__c();
        consultororg.EMP_Consultant__c = consultor.Id;
        consultororg.EMP_Organization__c = organizacion.Id;
        insert consultororg;

        EMP_Organization_Member__c miembro = new EMP_Organization_Member__c();
        miembro.EMP_Organization__c = organizacion.Id;
        miembro.EMP_Organization_Member_Consultant__c = consultor.Id;
        insert miembro;

        EMP_Organization_Member_Beneficiary__c beneficiario = new EMP_Organization_Member_Beneficiary__c();
        beneficiario.Organization_Member__c = miembro.Id;
        beneficiario.ID_Number__c = '123';
        insert beneficiario;

        EMP_Organization_Member_Beneficiary__c beneficiario2 = new EMP_Organization_Member_Beneficiary__c();
        beneficiario2.Organization_Member__c = miembro.Id;
        beneficiario2.ID_Number__c = '12345';
        insert beneficiario2;

        EMP_Training__c training = new EMP_Training__c();
        training.EMP_Training__c = consultor.Id;
        training.Training_Name__c = 'Plantulación';
        insert training;

        EMP_Training_Assistant__c asistencia1 = new EMP_Training_Assistant__c();
        asistencia1.EMP_Training_Assistant__c = training.Id;
        asistencia1.Identification_Number__c = '123';
        asistencia1.Organization_Name__c = 'el plan';
        insert asistencia1;

        EMP_Training_Assistant__c asistencia2 = new EMP_Training_Assistant__c();
        asistencia2.EMP_Training_Assistant__c = training.Id;
        asistencia2.Identification_Number__c = '123';
        asistencia2.EMP_Organization_Member_Beneficiary__c = beneficiario.Id;
        asistencia2.EMP_Training_Assistant_Member__c = miembro.Id;
        asistencia2.Organization_Name__c = 'el plan';
        insert asistencia2;

        EMP_Training_Assistant__c asistencia3 = new EMP_Training_Assistant__c();
        asistencia3.EMP_Training_Assistant__c = training.Id;
        asistencia3.Identification_Number__c = '12345';
        asistencia3.Organization_Name__c = 'el plan';
        insert asistencia3;

        EMP_Leader__c lider = new EMP_Leader__c();
        lider.EMP_Leader__c = organizacion.Id;
        lider.EMP_Leader_Consultant__c = consultor.Id;
        insert lider;

        EMP_Farm__c finca = new EMP_Farm__c();
        finca.EMP_Farm__c = miembro.Id;
        finca.EMP_Farm_Leader__c = lider.Id;
        finca.Farm_Name__c = 'La Finquita';
        insert finca;

        EMP_Farm_BPA_Checklist__c bpa = new EMP_Farm_BPA_Checklist__c();
        bpa.EMP_Farm_BPA_Checklist__c = finca.Id;
        bpa.Batch_Inspection__c = 'SI';
        bpa.Batch_Corrective_Actions__c = 'SI';
        bpa.Quality_Seed_Area__c = 'SI';
        insert bpa;

        EMP_Farm_Baseline__c baseline = new EMP_Farm_Baseline__c();
        baseline.EMP_Farm_Baseline__c = finca.Id;
        insert baseline;

        EMP_Farm_Diagnostic_and_Targets__c diagnostic = new EMP_Farm_Diagnostic_and_Targets__c();
        diagnostic.Farm__c = finca.Id;
        insert diagnostic;

        EMP_Farm_Follow_Up__c followup = new EMP_Farm_Follow_Up__c();
        followup.Farm_diagnosis_and_targets__c = diagnostic.Id;
        insert followup;

        EMP_Technical_Assistance__c techAsistance = new EMP_Technical_Assistance__c();
        techAsistance.EMP_Technical_Assistance__c = finca.Id;
        techAsistance.EMP_Technical_Assistance_Consultant__c = consultor.Id;
        insert techAsistance;

        EMPOrganizationProfile op = new EMPOrganizationProfile(new ApexPages.StandardController(organizacion));

        op.getOrganizationId();
        System.assert(op.organizationId != null);

        op.getBpaCheckList();
        System.assert(op.bpaCheckList == null);

        op.getSocios();
        System.assert(op.socios == null);

        op.getSociosQuantity();
        System.assert(op.sociosQuantity == null);

        op.getBaseline();
        System.assert(op.farmBaseline != null);

        op.getReplicaActiva();
        System.assert(op.replicaActiva == null);

        op.getReplicaInactiva();
        System.assert(op.replicaInactiva == null);

        op.getInscripcionTraining();
        System.assert(op.inscripcionTraining == null);

        op.getOrgConsultant();
        System.assert(op.orgConsultants.size() > 0);

        //op.getTraining();
        //System.assert(op.trainings != null);

        op.getTrainingAsistance();
        System.assert(op.trainingAssitance == null);

        op.getTrainingAssitanceSocio();
        System.assert(op.trainingAssitanceSocio == null);

        String testName = 'test';
        Integer testSize = 1000;
        Integer testSize2 = 1000;

        EMPOrganizationProfile.Data innerClass = new EMPOrganizationProfile.Data(testName, testSize, testSize2);
        List<EMPOrganizationProfile.Data> testList = op.getParcelaData();
        System.assert(testList != null);

        //EMPOrganizationProfile.PieWedgeData innerClass2 = new EMPOrganizationProfile.PieWedgeData(testName, testSize);
        //List<EMPOrganizationProfile.PieWedgeData> testList2 = op.getPieWedgeData();
        //System.assert(testList2 != null);

        EMPOrganizationProfile.SociosQuantityData innerClass3 = new EMPOrganizationProfile.SociosQuantityData(testName, testSize);
        List<EMPOrganizationProfile.SociosQuantityData> testList3 = op.getSociosQuantityData();
        System.assert(testList3 != null);

        EMPOrganizationProfile.ReplicaData innerClass4 = new EMPOrganizationProfile.ReplicaData(testName, testSize);
        List<EMPOrganizationProfile.ReplicaData> testList4 = op.getReplicaData();
        System.assert(testList4 != null);

        EMPOrganizationProfile.InscripcionTrainingData innerClass5 = new EMPOrganizationProfile.InscripcionTrainingData(testName, testSize);
        List<EMPOrganizationProfile.InscripcionTrainingData> testList5 = op.getInscripcionTrainingData();
        System.assert(testList5 != null);

        EMPOrganizationProfile.TrainingAsistanceData innerClass6 = new EMPOrganizationProfile.TrainingAsistanceData(testName, testSize, testSize);
        List<EMPOrganizationProfile.TrainingAsistanceData> testList6 = op.getTrainingAsistanceData();
        System.assert(testList6 != null);

    }
    
}