src/objects/EMP_Organization_Member__c.object
<CustomObject>
    <label>EMP Organization Member</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Organization Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Organization Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Organization_Member_Beneficiary__c.object
<CustomObject>
    <fields>
        <fullName>ID_Number__c</fullName>
        <label>ID Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Member__c</fullName>
        <label>Organization_Member</label>
        <referenceTo>EMP_Organization_Member__c</referenceTo>
        <relationshipLabel>EMP_OMBeneficiary_Organization_Member</relationshipLabel>
        <relationshipName>EMP_OMBeneficiary_Organization_Member</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EMP Organization Member Beneficiary</label>
    <nameField>
        <displayFormat>EMPOMB-{000000}</displayFormat>
        <label>EMP Organization Member Beneficiary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Organization Member Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EMP_Training_Assistant__c.object
<CustomObject>
    <fields>
        <fullName>EMP_Training_Assistant_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EMP Training Assistant Member</label>
        <referenceTo>EMP_Organization_Member__c</referenceTo>
        <relationshipLabel>EMP Training Assistants</relationshipLabel>
        <relationshipName>EMP_Training_Assistants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EMP_Training_Assistant__c</fullName>
        <label>EMP Training Assistant</label>
        <referenceTo>EMP_Training__c</referenceTo>
        <relationshipLabel>EMP Training Assistants</relationshipLabel>
        <relationshipName>EMP_Training_Assistants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Identification_Number__c</fullName>
        <label>Identification Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>EMP Training Assistant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EMP Training Assistant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMP Training Assistants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EMPTrainingasistantHandler.cls
public with sharing class EMPTrainingasistantHandler {

	public EMP_Training_Assistant__c empTA;

	public EMPTrainingasistantHandler(EMP_Training_Assistant__c et) {
		empTA = et;

	}

	public void Handle(){
		for(List<EMP_Organization_Member_Beneficiary__c> beneficiaries : [SELECT Id, Organization_Member__c, Organization_Member__r.Id, ID_Number__c FROM EMP_Organization_Member_Beneficiary__c WHERE ID_Number__c like :empTA.Identification_Number__c]){
			for(EMP_Organization_Member_Beneficiary__c beneficiary : beneficiaries){
				empTA.EMP_Organization_Member_Beneficiary__c = beneficiary.Id;
				empTA.EMP_Training_Assistant_Member__c = beneficiary.Organization_Member__c;
				update empTA;
			}
		}
	}
}