src/objects/Ewarehouse_Farmer__c.object
<CustomObject>
    <description>This is the farmer that is registered by the VKW at the field.</description>
    <fields>
        <fullName>Auto_Generated_Farmer_ID__c</fullName>
        <label>Farmer FCI Id</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ewarehouse Farmer</label>
    <nameField>
        <label>Ewarehouse Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ewarehouse_Sale_Beans_Association__c.object
<CustomObject>
    <fields>
        <fullName>Ewarehouse_Sale__c</fullName>
        <label>Ewarehouse Sale</label>
        <referenceTo>Sale_Record__c</referenceTo>
        <relationshipLabel>Ewarehouse Sale Beans Associations</relationshipLabel>
        <relationshipName>Ewarehouse_Sale_Beans_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Farmer_FCI_ID__c</fullName>
        <label>Farmer FCI ID</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Moisture_Content__c</fullName>
        <label>Moisture Content</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Bags_Sold__c</fullName>
        <label>Total Bags Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ewarehouse Sale Beans Association</label>
    <nameField>
        <label>Ewarehouse Sale Beans Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Sale Beans Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sale_Farmer_Associations__c.object
<CustomObject>
    <fields>
        <fullName>Beans_Moisture_Content__c</fullName>
        <label>Beans Moisture Content</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Beans_Number_of_90kg_Bags__c</fullName>
        <label>Beans Number of 90kg Bags</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Farmer__c</fullName>
        <label>Ewarehouse Farmer</label>
        <referenceTo>Ewarehouse_Farmer__c</referenceTo>
        <relationshipLabel>Ewarehouse Sale Farmer Associations</relationshipLabel>
        <relationshipName>Ewarehouse_Sale_Farmer_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Sale_Beans_Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ewarehouse Sale Beans Association</label>
        <referenceTo>Ewarehouse_Sale_Beans_Association__c</referenceTo>
        <relationshipLabel>Ewarehouse Sale Farmer Associations</relationshipLabel>
        <relationshipName>Ewarehouse_Sale_Farmer_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ewarehouse_Sale__c</fullName>
        <label>Ewarehouse Sale</label>
        <referenceTo>Sale_Record__c</referenceTo>
        <relationshipLabel>Ewarehouse Sale Farmer Associations</relationshipLabel>
        <relationshipName>Ewarehouse_Sale_Farmer_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sale_Farmer_Unique_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Sale Farmer Unique ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Ewarehouse Sale Farmer Association</label>
    <nameField>
        <label>Ewarehouse Sale Farmer Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ewarehouse Sale Farmer Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BeansSaleFarmerAssociationCreator.cls
public class BeansSaleFarmerAssociationCreator{
     //Method to fetch the Bean Association details of the bean sale association that was created
     public static void getSaleFarmerDetails(Ewarehouse_Sale_Beans_Association__c[] bean_association) {
         //Variable to hold the FCI ID's from the Bean association record
         List<String> ewarehouse_id= new List<String>();
         for(Ewarehouse_Sale_Beans_Association__c bean_associations : bean_association){
             if(bean_associations.Farmer_FCI_ID__c != null){
                 ewarehouse_id.add(bean_associations.Farmer_FCI_ID__c);
             }
         }  
         //The Variable object to fetch the Ewarehouse Farmer ID to be used to create a new Ewarehouse Sale Farmer Association Record
         Ewarehouse_Farmer__c[] existing_farmer = [SELECT Ewarehouse_Farmer__c.Id, Ewarehouse_Farmer__c.Auto_Generated_Farmer_ID__c, Ewarehouse_Farmer__c.Status__c FROM Ewarehouse_Farmer__c WHERE Ewarehouse_Farmer__c.Auto_Generated_Farmer_ID__c IN : ewarehouse_id];   
         for(Ewarehouse_Farmer__c farmer_details : existing_farmer){
             if(farmer_details.Status__c == 'New Farmer'){
                 farmer_details.Status__c = 'New';
             }             
         }
         update existing_farmer;
         
         //Create a variable to hold the new Sale Farmer Association records
         Sale_Farmer_Associations__c[] newFarmerAssociations = new List<Sale_Farmer_Associations__c>();
         for(Ewarehouse_Sale_Beans_Association__c bean_associations : bean_association){
             for(Ewarehouse_Farmer__c existing_farmers : existing_farmer ){
                 if(bean_associations.Farmer_FCI_ID__c == existing_farmers.Auto_Generated_Farmer_ID__c){
                     newFarmerAssociations.add(new Sale_Farmer_Associations__c (Ewarehouse_Sale__c = bean_associations.Ewarehouse_Sale__c,Ewarehouse_Sale_Beans_Association__c = bean_associations.Id,Beans_Moisture_Content__c=bean_associations.Moisture_Content__c,Beans_Number_of_90kg_Bags__c=bean_associations.Total_Bags_Sold__c,Ewarehouse_Farmer__c = existing_farmers.Id,Sale_Farmer_Unique_ID__c = ''+bean_associations.Ewarehouse_Sale__c+''+existing_farmers.Id ));
                     break;
                 }else{
                     
                 }
             }
         }
         //Check that the array object variable for insertion is not empty
         if(newFarmerAssociations.size() > 0) {
             upsert newFarmerAssociations Sale_Farmer_Unique_ID__c;
         } 
     } 
}