src/objects/Farmer__c.object
<CustomObject>
    <description>A farmer who has registered in our system, associated with a Person object.</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>Parent object with core person details</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Farmers</relationshipLabel>
        <relationshipName>Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Farmer</label>
    <nameField>
        <label>Farmer ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Harvest__c.object
<CustomObject>
    <fields>
        <fullName>Crop__c</fullName>
        <label>Crop</label>
        <picklist>
            <picklistValues>
                <fullName>Maize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pigeon peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black beans(Dolichos)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cow peas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green grams</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Harvests</relationshipLabel>
        <relationshipName>Harvests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Accepted__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity Accepted</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Harvest</label>
    <nameField>
        <displayFormat>H{000000}</displayFormat>
        <label>Harvest Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Harvests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <description>A message sent to a user in our system</description>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of the message</description>
        <label>Subject</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>MSG-{00000000}</displayFormat>
        <label>Message ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sale__c.object
<CustomObject>
    <description>Represents a sale transaction from the warehouse</description>
    <fields>
        <fullName>Beans_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Beans Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beans_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Beans Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cow Peas Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cow Peas Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dolichos_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Dolichos Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dolichos_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Dolichos Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Green_Grams_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Green Grams Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Green_Grams_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Green Grams Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maize_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maize Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maize_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maize Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Pigeon Peas Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Price_Per_90kg_Bag__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Pigeon Peas Price Per 90kg Bag</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Sale</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Sale Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sale_Farmer_Association__c.object
<CustomObject>
    <fields>
        <fullName>Beans_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Beans Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cow_Peas_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Cow Peas Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dolichos_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Dolichos Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Farmer__c</fullName>
        <label>Farmer</label>
        <referenceTo>Farmer__c</referenceTo>
        <relationshipLabel>Sale Farmer Associations</relationshipLabel>
        <relationshipName>Sale_Farmer_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Green_Grams_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Green Grams Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maize_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maize Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pigeon_Peas_Number_of_90kg_Bags_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Pigeon Peas Number of 90kg Bags Sold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sale__c</fullName>
        <label>Sale</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipLabel>Sale Farmer Associations</relationshipLabel>
        <relationshipName>Sale_Farmer_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sale Farmer Association</label>
    <nameField>
        <displayFormat>SFN-{000000}</displayFormat>
        <label>Sale Farmer Association Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sale Farmer Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Scheduled_Message_Queue__c.object
<CustomObject>
    <description>object to hold messages that are meant to be sent at a time in the future</description>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <defaultValue>NOW() + 30</defaultValue>
        <label>Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>The message to be sent</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person to whom the message is directed</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Scheduled Message Queues</relationshipLabel>
        <relationshipName>Scheduled_Message_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Date_Time__c</fullName>
        <description>The date and time at which the message should be sent.</description>
        <label>Send Date Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Send_Via_Pulse__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Send message via pulse</description>
        <label>Send_Via_Pulse</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Send_Via_Sms__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Send message via SMS</description>
        <label>Send_Via_Sms</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sender__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person sending the message</description>
        <label>Sender</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scheduled_Message_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <defaultValue>&quot;No Subject&quot;</defaultValue>
        <description>The subject or theme of the message</description>
        <label>Subject</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scheduled Message Queue</label>
    <nameField>
        <label>Scheduled Message Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Message Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EwarehouseTriggerHandler.cls
public with sharing class EwarehouseTriggerHandler {

    public void onAfterHarvestInsert(List<Harvest__c> objects) {
        User sender = [
                    SELECT
                        Id,
                        Name
                    FROM
                        User
                    WHERE
                        Name = 'ckw admin'
                ];
        String messageSubject = 'Harvest Received';
        //Schedule the message for sending
        Savepoint sp = Database.setSavepoint();
        List<Scheduled_Message_Queue__c> messageQueue = new List<Scheduled_Message_Queue__c>();
        for (Harvest__c harvest: objects) {
            Farmer__c recipient = getFarmerPerson(harvest);
            String messageBody = getHarvestValue(harvest);
            Scheduled_Message_Queue__c message = new Scheduled_Message_Queue__c(
                Subject__c = messageSubject,
                Message__c = messageBody,
                Sender__c = sender.Id,
                Expiration_Date__c = datetime.now().addDays(1),
                Send_Via_Pulse__c = false,
                Send_Via_SMS__c = true,
                Send_Date_Time__c = datetime.now(),
                Person__c = recipient.Person__r.Id
            );
            System.debug(message);
            messageQueue.add(message);
        }
     
        // Save the scheduled messsages. Parse the SaveResults and roll back all the new messages if there is a failure.
        Database.SaveResult[] saveMessageResults = Database.insert(messageQueue, false);
        for (Database.SaveResult result : saveMessageResults) {
            if (!result.isSuccess()) {
                for (Database.Error error : result.getErrors()) {
                    System.debug(LoggingLevel.INFO, error.getMessage());
                }
                //TODO: Notify tech team of this failure
                
                Database.rollBack(sp);
            }
        }
    }
    
    
    private Farmer__c getFarmerPerson(Harvest__c harvest) {
        return [SELECT Person__r.Id FROM Farmer__c WHERE Id =: harvest.Farmer__c];
    }
    
    private String getHarvestValue(Harvest__c harvest) {
        Harvest__c harvestDetails = [SELECT 
                                         Farmer__r.Name, 
                                         Crop__c, 
                                         Quantity_Accepted__c, 
                                         Farmer__r.Person__r.First_Name__c, 
                                         Farmer__r.Person__r.Last_Name__c
                                      FROM 
                                         Harvest__c 
                                      WHERE 
                                         Id =: harvest.Id];
        String message = harvestDetails.Farmer__r.Person__r.First_Name__c + ' ' + 
                         harvestDetails.Farmer__r.Person__r.Last_Name__c + ' ' +
                         harvestDetails.Farmer__r.Name + ': ' +
                         harvestDetails.Quantity_Accepted__c + 'bags ' +
                         harvestDetails.Crop__c + '= ' +
                         '2000';
        return message;
    }
    
    public void onAfterSaleRegistrationInsert(List<Sale_Farmer_Association__c> objects) {
        User sender = [
                    SELECT
                        Id,
                        Name
                    FROM
                        User
                    WHERE
                        Name = 'ckw admin'
                ];
        String messageSubject = 'Sale Registration Received';
        //Schedule the message for sending
        Savepoint sp = Database.setSavepoint();
        List<Scheduled_Message_Queue__c> messageQueue = new List<Scheduled_Message_Queue__c>();
        for (Sale_Farmer_Association__c saleFarmer: objects) {
            Farmer__c recipient = getFarmerSalePerson(saleFarmer);
            String messageBody = getSaleValue(saleFarmer);
            Scheduled_Message_Queue__c message = new Scheduled_Message_Queue__c(
                Subject__c = messageSubject,
                Message__c = messageBody,
                Sender__c = sender.Id,
                Expiration_Date__c = datetime.now().addDays(1),
                Send_Via_Pulse__c = false,
                Send_Via_SMS__c = true,
                Send_Date_Time__c = datetime.now(),
                Person__c = recipient.Person__r.Id
            );
            System.debug(message);
            messageQueue.add(message);
        }
     
        // Save the scheduled messsages. Parse the SaveResults and roll back all the new messages if there is a failure.
        Database.SaveResult[] saveMessageResults = Database.insert(messageQueue, false);
        for (Database.SaveResult result : saveMessageResults) {
            if (!result.isSuccess()) {
                for (Database.Error error : result.getErrors()) {
                    System.debug(LoggingLevel.INFO, error.getMessage());
                }
                //TODO: Notify tech team of this failure
                
                Database.rollBack(sp);
            }
        }   	
    }
    
    private Farmer__c getFarmerSalePerson(Sale_Farmer_Association__c saleFarmer) {
        return [SELECT Person__r.Id FROM Farmer__c WHERE Id =: saleFarmer.Farmer__c];
    }
    
    private String getSaleValue(Sale_Farmer_Association__c saleFarmer) {
        Sale_Farmer_Association__c saleDetails = [SELECT 
                                         Farmer__r.Name, 
                                         Beans_Number_of_90kg_Bags_Sold__c, 
                                         Cow_Peas_Number_of_90kg_Bags_Sold__c,
                                         Dolichos_Number_of_90kg_Bags_Sold__c,
                                         Green_Grams_Number_of_90kg_Bags_Sold__c,
                                         Maize_Number_of_90kg_Bags_Sold__c,
                                         Pigeon_Peas_Number_of_90kg_Bags_Sold__c,
                                         Sale__c,
                                         Sale__r.Beans_Price_Per_90kg_Bag__c,
                                         Sale__r.Cow_Peas_Price_Per_90kg_Bag__c,
                                         Sale__r.Dolichos_Price_Per_90kg_Bag__c,
                                         Sale__r.Green_Grams_Price_Per_90kg_Bag__c,
                                         Sale__r.Maize_Price_Per_90kg_Bag__c,
                                         Sale__r.Pigeon_Peas_Price_Per_90kg_Bag__c,
                                         Farmer__r.Person__r.First_Name__c, 
                                         Farmer__r.Person__r.Last_Name__c
                                      FROM 
                                         Sale_Farmer_Association__c 
                                      WHERE 
                                         Id =: saleFarmer.Id];
                                         
        Decimal totalSale = saleDetails.Beans_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Beans_Price_Per_90kg_Bag__c +
        					saleDetails.Cow_Peas_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Cow_Peas_Price_Per_90kg_Bag__c +
        					saleDetails.Dolichos_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Dolichos_Price_Per_90kg_Bag__c + 
        					saleDetails.Green_Grams_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Green_Grams_Price_Per_90kg_Bag__c +
        					saleDetails.Maize_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Maize_Price_Per_90kg_Bag__c +
        					saleDetails.Pigeon_Peas_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Pigeon_Peas_Price_Per_90kg_Bag__c;
       
	    String beanString = (saleDetails.Beans_Number_of_90kg_Bags_Sold__c > 0) ? saleDetails.Beans_Number_of_90kg_Bags_Sold__c + ' bags Beans =  Ksh ' + (saleDetails.Beans_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Beans_Price_Per_90kg_Bag__c)  : '';
	    String cowPeasString = (saleDetails.Cow_Peas_Number_of_90kg_Bags_Sold__c > 0) ? saleDetails.Cow_Peas_Number_of_90kg_Bags_Sold__c + ' bags Cow Peas =  Ksh ' + (saleDetails.Cow_Peas_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Cow_Peas_Price_Per_90kg_Bag__c)  : '';
	    String dolichosString = (saleDetails.Dolichos_Number_of_90kg_Bags_Sold__c > 0) ? saleDetails.Dolichos_Number_of_90kg_Bags_Sold__c + ' bags Dolichos =  Ksh ' + (saleDetails.Dolichos_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Dolichos_Price_Per_90kg_Bag__c)  : '';
	    String greenGramsString = (saleDetails.Green_Grams_Number_of_90kg_Bags_Sold__c > 0) ? saleDetails.Green_Grams_Number_of_90kg_Bags_Sold__c + ' bags Green grams =  Ksh ' + (saleDetails.Green_Grams_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Green_Grams_Price_Per_90kg_Bag__c)  : '';                   
	    String maizeString = (saleDetails.Maize_Number_of_90kg_Bags_Sold__c > 0) ? saleDetails.Maize_Number_of_90kg_Bags_Sold__c + ' bags Maize =  Ksh ' + (saleDetails.Maize_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Maize_Price_Per_90kg_Bag__c)  : '' ;
	    String pigeonPeasString = (saleDetails.Pigeon_Peas_Number_of_90kg_Bags_Sold__c > 0) ? saleDetails.Pigeon_Peas_Number_of_90kg_Bags_Sold__c + ' bags Pigeon Peas =  Ksh ' + (saleDetails.Pigeon_Peas_Number_of_90kg_Bags_Sold__c * saleDetails.Sale__r.Pigeon_Peas_Price_Per_90kg_Bag__c)  : '';                   
                         
                         
                         
                         				
        String message = saleDetails.Farmer__r.Person__r.First_Name__c + ' ' + 
                         saleDetails.Farmer__r.Person__r.Last_Name__c + ' ' +
                         saleDetails.Farmer__r.Name + ': ' +
                         beanString +
						 cowPeasString  +
						 dolichosString +
                         greenGramsString +
                         maizeString +
                         pigeonPeasString;
        
        message.trim();              
        return message + ' Total sale = Ksh ' + totalSale;
    }
}