src/objects/Focus_Farmer__c.object
<CustomObject>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Focus Farmers</relationshipLabel>
        <relationshipName>Focus_Farmers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Focus Farmer</label>
    <nameField>
        <displayFormat>FFN{YYYY}{MM}{DD}{0}</displayFormat>
        <label>Focus Farmer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Focus Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>Construct that represents a group of People. Used by features including Agriculture Information channel, survey assignment, bulk SMS.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Handset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Physical handset assigned to this Person (in the case of GF-managed assets)</description>
        <label>Handset</label>
        <referenceTo>Phone__c</referenceTo>
        <relationshipLabel>Assignee</relationshipLabel>
        <relationshipName>Assignee</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person_Group_Association__c.object
<CustomObject>
    <description>Junction object used for many-to-many relationship between Person and Group objects. The existence of a Person-Group Association is what defines a single &quot;membership&quot;.</description>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group associated with this junction object</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person-Group Association</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Person Group Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person-Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Search_Log__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Accuracy__c</fullName>
        <label>Accuracy</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Altitude__c</fullName>
        <label>Altitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Search__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CKW 3.O tracks group searches with this flag</description>
        <label>Group Search</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The group to which the interviewer/CKW is associated</description>
        <inlineHelpText>The group to which the interviewer/CKW is associated</inlineHelpText>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Search Logs</relationshipLabel>
        <relationshipName>Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Handset_Submit_Time__c</fullName>
        <description>Time the phone sent the request</description>
        <label>Handset Submit Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person who requests information</description>
        <label>Interviewee</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Administered)</relationshipLabel>
        <relationshipName>Interviewee_Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interviewer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Search Logs</relationshipLabel>
        <relationshipName>Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CKW/Interviewer as obtained from Salesforce using handset id</description>
        <label>Interviewer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Done)</relationshipLabel>
        <relationshipName>Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Server_Entry_Time__c</fullName>
        <description>Time the server received the request</description>
        <label>Server Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Submission_Accuracy__c</fullName>
        <description>The accuracy of the GPS reading when the log was sent from the phone</description>
        <label>Submission Accuracy</label>
        <precision>18</precision>
        <scale>13</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Altitude__c</fullName>
        <description>The altitude that the log was submitted from</description>
        <label>Submission Altitude</label>
        <precision>18</precision>
        <scale>13</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_GPS_Timestamp__c</fullName>
        <description>The timestamp that the log was submitted from the phone</description>
        <label>Submission GPS Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Submission_Latitude__c</fullName>
        <description>The latitude that the log was submitted from</description>
        <label>Submission Latitude</label>
        <precision>18</precision>
        <scale>13</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Longitude__c</fullName>
        <description>The longitude that the log was submitted from</description>
        <label>Submission Longitude</label>
        <precision>18</precision>
        <scale>13</scale>
        <type>Number</type>
    </fields>
    <label>Search Log</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SearchCreateLogs.cls
/**
 *
 * Copyright (c) 2014 AppLab, Grameen Foundation
 *
 *  This class is a part of the CKW Search 3.0 Bundle
 *  Tests are in SearchServerTests class
 **/
global class SearchCreateLogs {

    public static String createSearchLogs(String jsonRequestString) {
        
        //Create the response wrapper for this request
        ResponseWrapper responseWrapper = new ResponseWrapper();
        
        //Build the request object
        SearchLogRequest request = null;
        try {
            System.debug(jsonRequestString);
            request = (SearchLogRequest) JSON.deserialize(jsonRequestString, SearchLogRequest.class);
        }
        catch(Exception e) {
            responseWrapper.resultCode = '10';
            responseWrapper.resultMessage = 'Request could not be decoded';
            return JSON.serializePretty(responseWrapper);
        }
        Person__c[] people = [
            SELECT
                Name,
                Id,
                Contact__c
            FROM
                Person__c
            WHERE
                Handset__r.IMEI__c = :request.imei
            LIMIT 1];
        Person__c interviewer = people.isEmpty() ? null : people[0];
        if(interviewer == null){
            responseWrapper.resultCode = '10';
            responseWrapper.resultMessage = 'Search logs from unknown user';
            return JSON.serializePretty(responseWrapper);
        }
         
		Person_Group_Association__c[] applabStaffs = [      
	        SELECT 
	            Person__c
	        FROM
	            Person_Group_Association__c
	        WHERE
	            Group__r.Name = 'Applab Staff' AND
	            Person__c = :interviewer.Id
        ];
		if(!applabStaffs.isEmpty()) {
            responseWrapper.resultCode = '0';
            responseWrapper.resultMessage = 'Search logs from staff user ignored. Request Successful';
            return JSON.serializePretty(responseWrapper);			
		}
                
        for(SearchLog searchLog : request.searchLogs){
            String[] location = searchLog.gpsLocation.split(' ');
            String[] submissionLocation = searchLog.submissionLocation.split(' ');
            Integer len = location.size();
            Integer len2 = submissionLocation.size();
            Search_Log__c log = new Search_Log__c();
            log.Accuracy__c = len > 3 ? Double.valueOf(location[3]) : null;
            log.Altitude__c = len > 2 ? Double.valueOf(location[2]) : null;
            log.Handset_Submit_Time__c = Datetime.now();
            log.Interviewee__c = searchLog.clientId.equals(SearchGetFarmersHelper.GROUP_SEARCH_FARMER_TEMPLATE_ID) ? null :
            	[SELECT Person__r.Id FROM Focus_Farmer__c WHERE Id = :searchLog.clientId].get(0).Person__r.Id;
        	log.Group_Search__c = searchLog.clientId.equals(SearchGetFarmersHelper.GROUP_SEARCH_FARMER_TEMPLATE_ID) ? true : false;
            log.Interviewer__c = interviewer.Id;
            log.Interviewer_Contact__c = interviewer.Contact__c;
            log.Query__c = searchLog.content;
            log.Category__c = searchLog.category;
            log.Latitude__c = len > 1 ? Double.valueOf(location[0]) : null;
            log.Longitude__c = len > 1 ? Double.valueOf(location[1]) : null;
            log.Server_Entry_Time__c = Datetime.now();
            log.Submission_Accuracy__c = len2 > 3 ? Double.valueOf(submissionLocation[3]) : null;
            log.Submission_Altitude__c = len2 > 2 ? Double.valueOf(submissionLocation[2]) : null;
            log.Submission_Latitude__c = len2 > 1 ? Double.valueOf(submissionLocation[0]) : null;
            log.Submission_Longitude__c = len2 > 1 ? Double.valueOf(submissionLocation[1]) : null;
            log.Submission_GPS_Timestamp__c = DateTime.valueOfGmt((searchLog.dateCreated).replaceAll('T',' '));
            
            insert log;
        }
        
        responseWrapper.resultCode = '0';
        responseWrapper.resultMessage = 'Request Successful';
        return JSON.serializePretty(responseWrapper);
    }
    
    public class SearchLog {
        //public Integer id{get; set;}
        //public String menuItemId{get; set;}
        public String content{get; set;}
        public String category{get; set;}
        public String dateCreated{get; set;}
        public String clientId{get; set;}
        public String gpsLocation{get; set;}
        public String submissionLocation{get; set;}
        //public boolean testLog{get; set;}
    }
    
    public class SearchLogRequest {
        //String request {get;set;}
        String imei {get;set;}
        List<SearchLog> searchLogs {get;set;}        
    }
    
    class ResponseWrapper {
        String resultCode {get;set;}
        String resultMessage {get;set;}
    }
}