src/objects/Group__c.object
<CustomObject>
    <description>Construct that represents a group of People. Used by features including Agriculture Information channel, survey assignment, bulk SMS.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this group active?</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Menu__c.object
<CustomObject>
    <description>Used to develop ckw search menus</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>The Name/Label for this menu</description>
        <inlineHelpText>The Name/Label for this menu</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Menu</label>
    <nameField>
        <displayFormat>M-{0000000000}</displayFormat>
        <label>Menu Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Menu_Group_Association__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>Article_Menu_Group_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Menu__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Menu</label>
        <referenceTo>Menu__c</referenceTo>
        <relationshipLabel>Menu Group Associations</relationshipLabel>
        <relationshipName>Menu_Group_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Menu Group Association</label>
    <nameField>
        <displayFormat>MGA-{0000000000}</displayFormat>
        <label>Menu Group Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Menu Group Associations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person_Group_Association__c.object
<CustomObject>
    <description>Junction object used for many-to-many relationship between Person and Group objects. The existence of a Person-Group Association is what defines a single &quot;membership&quot;.</description>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group associated with this junction object</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person-Group Association</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Person Group Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person-Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateKeywordsFromCache.cls
global class UpdateKeywordsFromCache {    
    /**
    * Get keywords as document cache
    */
    webservice static String getCachedKeywords(String imei) {
        
        String menuName = getAllowedMenuByImei(imei);
        
        if (null == menuName) {
        	return '';
        }
        menuName = menuName.trim().remove(' ');
        
        Document doc = 
            [
             SELECT 
                 Id,
                 Body
             FROM 
                 Document
             WHERE
                 Name = :menuName
             LIMIT 1
             ];
         return doc.Body.toString();
    }
    
    // For now this takes the top most menu
    private static String getAllowedMenuByImei(String imei) {
    	
    	Person__c person = Utils.loadPersonImei(imei);
    	List<Id> groupIds = new List<Id>(); 
    	
    	// select groups in which person belongs
    	for (Person_Group_Association__c association : [
    		SELECT
    		  	Group__c 
    		FROM
    		  	Person_Group_Association__c
    		WHERE
    		  	Person__c = :person.Id
    	]) {
    		groupIds.add(association.Group__c);
    	}
    	
    	// Select one menu group association and get relevant Menu label
    	List<Menu__c> menus = [
    		SELECT
    			Id,
    			Label__c
    		FROM
    			Menu__c
    		WHERE
    			Id
    		  IN (
    		  		SELECT
    		  			Menu__c
    		  		FROM
    		  			Menu_Group_Association__c
    		  		WHERE
    		  			Group__c
    		  		  IN :(groupIds) 
    		  	)
    		];
    	
		if (null == menus || menus.size() == 0) {
			return null;
		}
    	return menus[0].Label__c;
    }
    
    static testmethod void testAll() {    	
    	// create test people
    	Person__c testPerson = Utils.createTestPerson(null, '234342', true, null, null);
    	database.insert(testPerson);
    	
    	Person__c testPerson2 = Utils.createTestPerson(null, '22222', true, null, null);
    	database.insert(testPerson2);
    	
    	// create Menu
    	Menu__c testMenu = new Menu__c();
    	testMenu.Label__c = 'Test Menu';
    	database.insert(testMenu);
    	
    	// create test group
    	Group__c testGroup = new Group__c();
    	testGroup.Name = 'test Group';
    	testGroup.Active__c = true;
    	database.insert(testGroup);
    	
    	// create menu group association
    	Menu_Group_Association__c mgAssoc = new Menu_Group_Association__c();
    	mgAssoc.Group__c = testGroup.Id;
    	mgAssoc.Menu__c = testMenu.Id;
    	database.insert(mgAssoc);
    	
    	// create person group association
    	Person_Group_Association__c pgAssoc = new Person_Group_Association__c();
    	pgAssoc.Person__c = testPerson.Id;
    	pgAssoc.Group__c = testGroup.Id;
    	database.insert(pgAssoc);
    	
    	// create document and save
    	Document doc = new Document();
        doc.Name = testMenu.Label__c.remove(' ');
        doc.Body = Blob.valueOf('representative data for search, this would be Json');
        doc.ContentType = 'text/plain';
        Folder f = [Select Id from Folder where Name = 'Search' LIMIT 1];
        doc.FolderId= f.Id;
        doc.Type = 'txt';
        insert doc;
    	
    	// test cases when there is a related menu and where there isnt 
    	system.assert(getCachedKeywords('234342') != '');
    	system.assert(getCachedkeywords('22222') ==  '');   	
    }
}