src/objects/Group__c.object
<CustomObject>
    <description>Construct that represents a group of People. Used by features including Agriculture Information channel, survey assignment, bulk SMS.</description>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_E__c</fullName>
        <description>GPS Location E. Must be in Decimal format</description>
        <label>GPS Location E</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPS_Location_N__c</fullName>
        <description>GPS Location N. Must be in Decimal forma</description>
        <label>GPS Location N</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person_Group_Association__c.object
<CustomObject>
    <description>Junction object used for many-to-many relationship between Person and Group objects. The existence of a Person-Group Association is what defines a single &quot;membership&quot;.</description>
    <fields>
        <fullName>Group__c</fullName>
        <description>The Group associated with this junction object</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>PersonGroupAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Person-Group Association</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Person Group Association ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person-Group Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AgrowaysVacsMapController.cls
public class AgrowaysVacsMapController {

	private List<Person__c> agrowaysPersons = new List<Person__c>();

	public AgrowaysVacsMapController() {
		agrowaysPersons = [SELECT Id,
									GPS_Location_E__c,
									GPS_Location_N__c,
									First_Name__c,
									Last_Name__c
								FROM Person__c
								WHERE Id 
								IN (Select Person__c 
									FROM Person_Group_Association__c
									WHERE 
									Group__r.Name ='Agroways VACs')];

	}

	public List<List<String>> getGpsLocations() {
		List<List<String>> gpsLocations = new List<List<String>>();
		for (Person__c person : agrowaysPersons) {
			String[] addressList = new String[] {String.valueOf(person.GPS_Location_E__c), 
												String.valueOf(person.GPS_Location_N__c)};
			gpsLocations.add(addressList);
		}
		return gpsLocations;
	}
}