src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <formula>Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>We have a gender field here because the options in LAC surveys are in Spanish and IBT doesn&apos;t yet (v 2.22 and earlier) support different labels and values for options</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <formula>Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>The label for this metric. Will be displayed on the dashboard.</description>
        <inlineHelpText>The label for this metric. Will be displayed on the dashboard.</inlineHelpText>
        <label>Label</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Actual_Value__c</fullName>
        <description>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</description>
        <inlineHelpText>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</inlineHelpText>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manual_Value__c</fullName>
        <description>Manually set value for a metric. Will override the actual value in display</description>
        <label>Manual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numerator__c</fullName>
        <description>Numerator for the on the fly calc</description>
        <label>Numerator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>The person that this metric data belongs to</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually.</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the person</description>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the person</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AsocatiDashDAL.cls
/**
	Data Access Layer class for AsocatiDashboard.page
*/

public with sharing class AsocatiDashDAL {

	public static List<M_E_Metric_Data__c> getProductionMetrics(){
	
		    M_E_Metric_Data__c[] productionMetrics = [
            SELECT
            	M_E_Metric__r.Label__c,
            	Projected_Value__c,
                Actual_Value__c,
                Manual_Value__c,
                Numerator__c                       
            FROM
                M_E_Metric_Data__c               
             WHERE
                M_E_Metric__r.Name IN ('total_Prod_Hectare','prod_Plants_Hectare','total_Month_Prod')
            
           
        ];
    
        return productionMetrics;
		
	}
	
	public static List<M_E_Metric_Data__c> getQualityMetrics(){
	
		    M_E_Metric_Data__c[] qualityMetrics = [
            SELECT
            	M_E_Metric__r.Label__c,
            	Projected_Value__c,
                Actual_Value__c,
                Manual_Value__c,
                Numerator__c                       
            FROM
                M_E_Metric_Data__c               
             WHERE
                M_E_Metric__r.Name IN ('average_Premium_Grain_Produced')
            
           
        ];
    
        return qualityMetrics;
		
	}
	
	public static List<M_E_Metric_Data__c> getCommercializationMetrics(){
	
		    M_E_Metric_Data__c[] commercializationMetrics = [
            SELECT
            	M_E_Metric__r.Label__c,
            	Projected_Value__c,
                Actual_Value__c,
                Manual_Value__c,
                Numerator__c                       
            FROM
                M_E_Metric_Data__c               
             WHERE
                M_E_Metric__r.Name IN ('prod_Sold_Asocati','certified_Kilos_Sold_By_Asocati','exported_Vs_National')
            
           
        ];
    
        return commercializationMetrics;
		
	}
	
	public static List<M_E_Metric_Data__c> getCertificationMetrics(){
	
		    M_E_Metric_Data__c[] certificationMetrics = [
            SELECT
            	M_E_Metric__r.Label__c,
            	Projected_Value__c,
                Actual_Value__c,
                Manual_Value__c,
                Numerator__c
            FROM
                M_E_Metric_Data__c               
             WHERE
                M_E_Metric__r.Name IN ('cocoa_Practices','certified_Producers','producers_Being_Certified','price_Differences')
            
           
        ];
    
        return certificationMetrics;
		
	}
	
	public static List<M_E_Metric_Data__c> getSocialMetrics(){
	
		    M_E_Metric_Data__c[] socialMetrics = [
            SELECT
            	M_E_Metric__r.Label__c,
            	Projected_Value__c,
                Actual_Value__c,
                Manual_Value__c,
                Numerator__c                       
            FROM
                M_E_Metric_Data__c               
             WHERE
                M_E_Metric__r.Name IN ('number_Beneficiaries','number_Associates','number_Mobile_Sys_Users',
                						'number_Users_Registered','percentage_Active_Users','insertTotalReached','VulnerableFarmersReached',
                						'FemaleFarmersReached','EthnicMinorityReached','insertDisplacedReached','CKW_PerformanceData'
                						)
            
           
        ];
    
        return socialMetrics;
		
	}
	
	
	public static List<M_E_Metric_Data__c> getFinancialMetrics(){
	
		    M_E_Metric_Data__c[] financialMetrics = [
            SELECT
            	M_E_Metric__r.Label__c,
            	Projected_Value__c,
                Actual_Value__c,
                Manual_Value__c,
                Numerator__c    
                       
            FROM
                M_E_Metric_Data__c               
             WHERE
                M_E_Metric__r.Name IN ('financial_Access','mobile_Money')            
           
        ];
    
        return financialMetrics;
		
	}
	
	
		LAC_Farmer_Details__c getLacFarmer(Person__c interviewee){
		
		LAC_Farmer_Details__c[] farmer =  [
            SELECT
            	Person__c                       
            FROM
                LAC_Farmer_Details__c               
       //     WHERE
         //       LAC_Farmer_Details__c.Person__r.Id = farmer
             LIMIT 1
                
        ];
        
        if(farmer.size()>0)
        	return farmer[0];
        else
        	return null;
		
	}
	
	LAC_Farmer_Details__c getLacFarmer(String id){
		
		LAC_Farmer_Details__c[] farmer =  [
            SELECT
            	Person__c                       
            FROM
                LAC_Farmer_Details__c               
       //     WHERE
         //       LAC_Farmer_Details__c.Person__r.Id = id
             LIMIT 1
                
        ];
        
        if(farmer.size()>0)
        	return farmer[0];
        else
        	return null;
	
	}
	
	public static void insertMetric(M_E_Metric__c metric){
		//TODO:Improve this by checking exceptions thrown (if any)
		Database.insert(metric);
	}
	
	public static void insertMetric(M_E_Metric_Data__c metric){
		//TODO:Improve this by checking exceptions thrown (if any)
		Database.insert(metric);
	}
	
	/**
	TEST METHODS
	*/
	
	public static void testDeleteMetrics()
	{
		M_E_Metric_Data__c[] productionMetrics = [
            SELECT
            	M_E_Metric__r.Label__c,
            	Projected_Value__c,
                Actual_Value__c
                       
            FROM
                M_E_Metric_Data__c               
             WHERE
                M_E_Metric__r.Name IN ('total_Prod_Hectare','prod_Plants_Hectare','total_Month_Prod',
                						'average_Premium_Grain_Produced',
                						'prod_Sold_Asocati','certified_Kilos_Sold_By_Asocati','exported_Vs_National',
                						'cocoa_Practices','certified_Producers','producers_Being_Certified','price_Differences',
                						'number_Beneficiaries','number_Associates','number_Mobile_Sys_Users',
                						'number_Users_Registered','percentage_Active_Users','CKW_PerformanceData',
                						'insertTotalReached','VulnerableFarmersReached',
                						'FemaleFarmersReached','EthnicMinorityReached','insertDisplacedReached',
                						'financial_Access','mobile_Money')
        ];
		
		Database.delete(productionMetrics,false);
		
	}
	
	
	public static LAC_Farmer_Details__c[] getTestLacFarmer()
	{
		LAC_Farmer_Details__c[] farmer =  [
            SELECT
            	Person__c                       
            FROM
                LAC_Farmer_Details__c               
             WHERE
                LAC_Farmer_Details__c.Person__r.First_Name__c  = 'Pepito' AND
                LAC_Farmer_Details__c.Person__r.Last_Name__c = 'Perez'
        ];
        
        return farmer;
		
	}
	
	public static LAC_Farmer_Details__c testCreateLacFarmer(){
	
		//TODO: Check why this is not working anymore...
		Person__c testPerson = new Person__c();
        testPerson.First_Name__c = 'Pepito';
        testPerson.Last_Name__c = 'Perez';
        testPerson.Gender__c = 'Male';
        Database.insert(testPerson);

        LAC_Farmer_Details__c testFarmer = new LAC_Farmer_Details__c();
        testFarmer.Person__c = testPerson.Id;
        Database.insert(testFarmer);
			
		return testFarmer;
	}
	
	public static void testDeleteFarmer(){
		
		
		LAC_Farmer_Details__c[] farmer = getTestLacFarmer();
				
		Database.delete(farmer,false);
	}
	


}