src/objects/LAC_Farm__c.object
<CustomObject>
    <fields>
        <fullName>LAC_Farmer_Id_Temp__c</fullName>
        <description>Deprecated: July 2013 - This field isn&apos;t needed since TaroWorks now supports related object mapping.</description>
        <label>LAC Farmer Id Temp</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAC_Household__c</fullName>
        <label>LAC Household</label>
        <referenceTo>LAC_Household__c</referenceTo>
        <relationshipLabel>LAC Farms</relationshipLabel>
        <relationshipName>LAC_Farms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LAC Farm</label>
    <nameField>
        <label>LAC Farm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LAC_Farmer_Details__c.object
<CustomObject>
    <description>Custom fields for LAC farmers</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Image_Document_Id__c</fullName>
        <description>Store the Identifier of the document that represents an image for the Lac Farmer Detail</description>
        <label>Image Document Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LAC_Farmer_Id_Temp__c</fullName>
        <description>Deprecated: July 2013 - This field isn&apos;t needed since TaroWorks now supports related object mapping.</description>
        <label>LAC Farmer Id Temp</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LAC_Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LAC Household</label>
        <referenceTo>LAC_Household__c</referenceTo>
        <relationshipLabel>LAC Farmer Details</relationshipLabel>
        <relationshipName>LAC_Farmer_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LAC Farmer Details</label>
    <nameField>
        <label>LAC Farmer Details Record Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LAC Farmer Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAC_Household__c.object
<CustomObject>
    <description>Object that contains details about the household that people can belong to</description>
    <fields>
        <fullName>LAC_Farmer_Id_Temp__c</fullName>
        <description>Deprecated: July 2013 - This field isn&apos;t needed since TaroWorks now supports related object mapping.</description>
        <label>LAC Farmer Id Temp (Deprecated)</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>LAC Household</label>
    <nameField>
        <displayFormat>HH-{0000000}</displayFormat>
        <label>LAC Household Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LAC Households</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Message__c.object
<CustomObject>
    <description>A message sent to a user in our system</description>
    <fields>
        <fullName>Recipient__c</fullName>
        <description>The recipient of the message</description>
        <label>Recipient</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>MSG-{00000000}</displayFormat>
        <label>Message ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>LAC_Farmer_Id_Temp__c</fullName>
        <label>LAC Farmer Id Temp</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Search_Log__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Interviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person who requests information</description>
        <label>Interviewee</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Administered)</relationshipLabel>
        <relationshipName>Interviewee_Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search Log</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Submission_Meta_Data__c.object
<CustomObject>
    <description>Contains the data that every submission requires. Every submission will have one of these irrelevant of the submission object that corresponds to the submission</description>
    <fields>
        <fullName>Interviewee__c</fullName>
        <description>The person answering the survey</description>
        <label>Interviewee</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipName>Submission_Meta_Datas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SMD-{0000000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LacFarmerDetailsController.cls
public with sharing class LacFarmerDetailsController {
	private LAC_Farmer_Details__c obj;
	private Document profilePicture;
	private ApexPages.StandardController stdController; 

	public LacFarmerDetailsController(ApexPages.StandardController controller) {
		this.stdController = controller;
		this.obj = (LAC_Farmer_Details__c)controller.getRecord();
		
		if (this.obj.Id == null) {
			this.obj.OwnerId = UserInfo.getUserId();
		}
		
		profilePicture = new Document();
	}

	public Decimal getSearchesNum() {
		return [SELECT COUNT() FROM Search_Log__c WHERE Interviewee__c = :this.obj.Person__c LIMIT 50000];
	}

	public Decimal getSubmissionsNum() {
		return [SELECT COUNT() FROM Submission_Meta_Data__c WHERE Interviewee__c = :this.obj.Person__c LIMIT 50000];
	}
	
	public LAC_Farmer_Details__c getFarmer(){ 
		return this.obj;
	}
	
	public Document getProfilePicture() {
		if (this.obj.Image_Document_Id__c != null) {
			List<Document> docs = [SELECT Id, Name, Body, FolderId FROM Document WHERE Id = :this.obj.Image_Document_Id__c ];
			if (!docs.isEmpty()) {
				this.profilePicture = docs.get(0);
			}
		}		
		return this.profilePicture;
	}

	public Decimal getMessagesNum() {
		return [SELECT COUNT() FROM Message__c WHERE Recipient__c = :this.obj.Person__c LIMIT 50000];
	}
	
	public PageReference save() {
		this.profilePicture.folderid = UserInfo.getUserId(); //this puts it in My Personal Documents
		upsert this.profilePicture;
		
		this.obj.Image_Document_Id__c = this.profilePicture.Id;
		upsert this.obj;
		
		changeOwner();
		
		PageReference pageReference = new PageReference('/apex/LacFarmerDetails?id='+obj.id);
        pageReference.setRedirect(true);
        
        return pageReference;
	}
	
	private void changeOwner(){
		List<Contact> contacts = [SELECT Id, OwnerId FROM Contact WHERE Id = :obj.Contact__c];
		if (!contacts.isEmpty()) {
			contacts.get(0).OwnerId = obj.OwnerId;
			update contacts;
		}
		
		List<Person__c> persons = [SELECT Id, OwnerId FROM Person__c WHERE Id = :obj.Person__c];
		if (!persons.isEmpty()) {
			persons.get(0).OwnerId = obj.OwnerId;
			update persons;
		}
		
		List<LAC_Household__c> households = [SELECT Id, OwnerId FROM LAC_Household__c WHERE Id = :obj.LAC_Household__c];
		if (!households.isEmpty()) {
			households.get(0).OwnerId = obj.OwnerId;
			update households;
		}
		
		List<LAC_Farm__c> farms = 
			[SELECT 
				Id, 
				OwnerId, 
				LAC_Household__c 
			FROM 
				LAC_Farm__c 
			WHERE 
				LAC_Household__c IN (SELECT Id FROM LAC_Household__c WHERE LAC_Farmer_Id_Temp__c = :obj.Name)];
		
		if (!farms.isEmpty()) {
			for (LAC_Farm__c farm : farms) {
				farm.OwnerId = obj.OwnerId;
			}
			
			update farms;
		}
	}
}