src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Actual_Value__c</fullName>
        <description>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</description>
        <inlineHelpText>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</inlineHelpText>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date of the quarter to which this metric belongs</description>
        <inlineHelpText>This can simply be any date falling in the quarter to which this metric belongs. We shall calculate the quarter dynamically. It defaults to the current date.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Denumerator__c</fullName>
        <description>The Denumerator for the on the fly calculation</description>
        <label>Denumerator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Numerator__c</fullName>
        <description>Numerator for the on the fly calc</description>
        <label>Numerator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestAgrowaysHouseholdsReachedCalculator.cls
@isTest
public class TestAgrowaysHouseholdsReachedCalculator {

    static TestMethod void testCalculateHouseholdsReached() {
        M_E_Metric__c metric = new M_E_Metric__c(Name='Agroways Total Households Reached');
        insert metric;
        Date startDate = date.today().toStartOfMonth();
        Test.startTest();
        AgrowaysHouseholdsReachedCalculator.calculateHouseholdsReached();
        Test.stopTest();
        M_E_Metric_Data__c[] metricDatas = [Select Numerator__c,
                                                    Denumerator__c,
                                                    Actual_Value__c
                                            from 
                                                M_E_Metric_Data__c 
                                            where 
                                                Date__c =:startDate
                                            AND 
                                                M_E_Metric__r.Name ='Agroways Total Households Reached' 
                                            order by date__c desc];
        System.assertEquals(metricDatas.size(), 1);
    }
}