src/objects/M_E_Metric__c.object
<CustomObject>
    <description>M &amp; E Metrics</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>The label for this metric. Will be displayed on the dashboard.</description>
        <inlineHelpText>The label for this metric. Will be displayed on the dashboard.</inlineHelpText>
        <label>Label</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>M_E_Area__c</fullName>
        <description>Under what M&amp;E area does this metric fall? This helps with organisation on the dashboard.</description>
        <inlineHelpText>Under what M&amp;E area does this metric fall? This helps with organisation on the dashboard.</inlineHelpText>
        <label>M&amp;E Area</label>
        <picklist>
            <picklistValues>
                <fullName>Impact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustainability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Ordering in list</description>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update_Period__c</fullName>
        <description>How often is this metric updated</description>
        <label>Update Period</label>
        <picklist>
            <picklistValues>
                <fullName>TBC</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Ticker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biannually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>M&amp;E Metric</label>
    <nameField>
        <label>M&amp;E Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metrics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/M_E_Metric_Data__c.object
<CustomObject>
    <description>Quarterly Data for M&amp;E Metrics</description>
    <fields>
        <fullName>Actual_Value__c</fullName>
        <description>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</description>
        <inlineHelpText>The actual value for this metric. This will usually be calculated, but may be entered manually for some metrics</inlineHelpText>
        <label>Actual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>M_E_Metric__c</fullName>
        <description>The Metric to which this data belongs</description>
        <inlineHelpText>The Metric to which this data belongs</inlineHelpText>
        <label>M&amp;E Metric</label>
        <referenceTo>M_E_Metric__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manual_Value__c</fullName>
        <description>Manually set value for a metric. Will override the actual value in display</description>
        <label>Manual Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Numerator__c</fullName>
        <description>Numerator for the on the fly calc</description>
        <label>Numerator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>The person that this metric data belongs to</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>M&amp;E Metric Data</relationshipLabel>
        <relationshipName>M_E_Metric_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projected_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The projected value for this metric for the given quarter. Should be entered manually.</description>
        <inlineHelpText>The projected value for this metric for the given quarter. Should be entered manually.</inlineHelpText>
        <label>Projected Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>M&amp;E Metric Data</label>
    <nameField>
        <label>Metric Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>M&amp;E Metric Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Submission_Answer__c.object
<CustomObject>
    <description>Object to hold one answer to a survey</description>
    <label>Submission Answer</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Submission Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AsocatiDashCocoaPractHelper.cls
//This is the class for the post-processing of the survey "CACAO PRACTICES"

public with sharing class AsocatiDashCocoaPractHelper {

	public static List<String> processBaseline(ProcessSurveySubmission.SurveySubmission submission, Map<String, Submission_Answer__c> answers, Person__c submitter, Person__c interviewee) {

	DateTime handsetSubmitTime = ProcessSurveySubmission.getTimestamp(submission.handsetSubmitTime);
    
    if (handsetSubmitTime == null) {
            return new String[] { '0', 'No handset submit time in this submission', 'SUPRESSMSG' };
    }
    
    //TODO: Get the metrics and do the post-processing!
            
	return new String[] { '1', 'All metric datas updated for farmer with id: ' + interviewee.id, 'SUPRESSMSG' };

	}
	
	
	public static void insertCocoaPractices(Integer answer, Integer projectedValue){
		
		M_E_Metric__c cocoaPractices = new M_E_Metric__c();
        cocoaPractices.Name = 'cocoa_Practices';
        cocoaPractices.Label__c = '% promedio en el cumplimiento de las prácticas de cacao';
        cocoaPractices.M_E_Area__c = 'Certification';
        //What does this mean?
        cocoaPractices.Order__c = 4;
        //Trimestral value should be added to this picklist
        cocoaPractices.Update_Period__c = 'Quarterly';
        
        Database.insert(cocoaPractices);
        
         //Create a M_E_Metric_Data__c object
        M_E_Metric_Data__c cocoaPracticesData = new M_E_Metric_Data__c();
        
        cocoaPracticesData.M_E_Metric__c = cocoaPractices.Id;
        cocoaPracticesData.Actual_Value__c = answer;
        //This will be defined manually
        cocoaPracticesData.Projected_Value__c = projectedValue;
        
           //This is only for Mastercard demo. Need to be calculated and stored in the proper object/fields
        //Used for anterior column
        cocoaPracticesData.Manual_Value__c = 80;
        //Used for variacion column
        cocoaPracticesData.Numerator__c = 45;
        
        Database.insert(cocoaPracticesData);	
		
	}
}