src/objects/Mana_Food__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Cereals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dairy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fruits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legumes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meat And Eggs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vegetables</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Mana Food</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mana Foods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mana_Food_Consumption_Record__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <formula>TEXT(Food__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Food__c</fullName>
        <label>Food</label>
        <referenceTo>Mana_Food__c</referenceTo>
        <relationshipLabel>Food Consumption Records</relationshipLabel>
        <relationshipName>Food_Consumption_Records</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Mana_Household__c</referenceTo>
        <relationshipLabel>Food Consumption Records</relationshipLabel>
        <relationshipName>Food_Consumption_Records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Mana Food Consumption Record</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mana Food Consumption Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mana_Household__c.object
<CustomObject>
    <label>Mana Household</label>
    <nameField>
        <label>Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mana Households</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ManaConsumptionChart.cls
public class ManaConsumptionChart {

    private ApexPages.StandardController stdController;
	private Mana_Household__c houseHold;
    private List<AggregateResult> foodConsumption;

    public ManaConsumptionChart(ApexPages.StandardController controller) {
        this.stdController = controller;
        this.houseHold = (Mana_Household__c)controller.getRecord();                                                
    }

    public List<AggregateResult> getFoodConsumption() {
        List<AggregateResult> foodConsumption = [Select Count (Id) i, 
                                                                    Food__r.Category__c nm
                                                                    From Mana_Food_Consumption_Record__c
                                                                    where Household__c =:houseHold.Id 
                                                                    group by  Food__r.Category__c];
                                                                    
        return foodConsumption;
    }

    public List<PieWedgeData> getPieData(){

    List<PieWedgeData> data = new List<PieWedgeData>();
    for (AggregateResult ar : getFoodConsumption()) {
        data.add(new PieWedgeData(
                (String) ar.get('nm'),
                (Integer) ar.get('i')
                ));
    }
    return data;
}

public class PieWedgeData {

        public String name { get; set; }
        public Integer data { get; set; }

        public PieWedgeData(String name, Integer data) {
            this.name = name;
            this.data = data;
        }
    }
}