src/objects/Mana_Food_Consumption_Submission__c.object
<CustomObject>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Mana_Household__c</referenceTo>
        <relationshipLabel>Food Consumption Submissions</relationshipLabel>
        <relationshipName>Mana_Food_Consumption_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission</label>
        <referenceTo>gfsurveys__Submission__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>temp_processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>temp processed</label>
        <type>Checkbox</type>
    </fields>
    <label>Mana Food Consumption Submission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mana Food Consumption Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mana_Household__c.object
<CustomObject>
    <label>Mana Household</label>
    <nameField>
        <label>Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mana Households</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ManaFoodConsRecCreateBatchJobTest.cls
@isTest
private class ManaFoodConsRecCreateBatchJobTest {
    
     @isTest static void testBatchJob() {

        Mana_Household__c mhh = new Mana_Household__c();
        mhh.Name = '123';
        insert mhh;

        gfsurveys__Survey__c survey =new gfsurveys__Survey__c();
        survey.Name = 'prueba';
        insert survey;

        gfsurveys__Submission__c submission = new gfsurveys__Submission__c();
        submission.gfsurveys__Survey__c = survey.Id;
        insert submission;
        
        Mana_Food_Consumption_Submission__c mfcs = new Mana_Food_Consumption_Submission__c();
        mfcs.Household__c = mhh.Id;
        mfcs.Submission__c = submission.Id;
        mfcs.temp_processed__c = False;
        insert  mfcs;

        ManaFoodConsumptionRecordsCreateBatchJob  manaCreateRecords = new ManaFoodConsumptionRecordsCreateBatchJob();

        Test.startTest();
        Database.executeBatch(manaCreateRecords,1);
        Test.stopTest();
    }
    
}