src/objects/Menu__c.object
<CustomObject>
    <description>Used to develop ckw search menus</description>
    <fields>
        <fullName>Label__c</fullName>
        <description>The Name/Label for this menu</description>
        <inlineHelpText>The Name/Label for this menu</inlineHelpText>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Menu</label>
    <nameField>
        <displayFormat>M-{0000000000}</displayFormat>
        <label>Menu Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Menu_Item__c.object
<CustomObject>
    <fields>
        <fullName>Article_Id__c</fullName>
        <description>The Article to which this item points, if it is the last item in its hierarchy</description>
        <label>Article Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Menu__c</fullName>
        <label>Menu</label>
        <referenceTo>Menu__c</referenceTo>
        <relationshipLabel>Menu Items</relationshipLabel>
        <relationshipName>Menu_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Item__c</fullName>
        <label>Parent Item</label>
        <referenceTo>Menu_Item__c</referenceTo>
        <relationshipName>Sub_Article_Menu_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Menu Item</label>
    <nameField>
        <displayFormat>MI-{0000000000}</displayFormat>
        <label>Menu Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Menu Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MenuManagement.cls
public with sharing class MenuManagement { 
    public Menu__c currentMenu {get; set;}
    
    public MenuManagement(ApexPages.StandardController controller) {
        this.currentMenu = this.loadCurrentMenu();
    }
    
    public MenuManagement() {
        this.currentMenu = this.loadCurrentMenu();
    }
    
    public Menu_Item__c[] getTopLevelMenuItems() {
        return [Select Id, Name, Article_Id__c, Content__c, Position__c, Label__c, Attribution__c from Menu_Item__c where Menu__c = :System.currentPageReference().getParameters().get('id') and (Parent_Item__c = NULL or Parent_Item__c = '') order by Position__c ASC, Label__c ASC];
    }
    
    private Menu__c loadCurrentMenu() {
        return [Select Id, Name from Menu__c where Id = :System.currentPageReference().getParameters().get('id') limit 1];
    }
    
    static testMethod void testMenuManagement() {
        Menu__c testMenu = new Menu__c();
        testMenu.Label__c = 'test';
        database.insert(testMenu);
        
        Menu_Item__c testItem = new Menu_Item__c();
        testItem.Label__c = 'test';
        testItem.Menu__c = testMenu.Id;
        database.insert(testItem);
        
        System.currentPageReference().getParameters().put('id', testMenu.Id);
        MenuManagement mm = new MenuManagement();
        mm.loadCurrentMenu();
        mm.getTopLevelMenuItems();
    }
}