src/objects/Message__c.object
<CustomObject>
    <description>A message sent to a user in our system</description>
    <fields>
        <fullName>Body__c</fullName>
        <description>The body of the message</description>
        <label>Body</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Expiration_Time__c</fullName>
        <defaultValue>NOW() + 30</defaultValue>
        <description>The date/time that this message expires and will no longer be displayed. We will also periodically purge expired messages from the system.</description>
        <label>Expiration Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <description>The Salesforce user who sent the message</description>
        <label>From</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <description>The recipient of the message</description>
        <label>Recipient</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Messages</relationshipLabel>
        <relationshipName>Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sent_Time__c</fullName>
        <defaultValue>Now()</defaultValue>
        <description>The time that the message was sent</description>
        <label>Sent Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of the message</description>
        <label>Subject</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Message</label>
    <nameField>
        <displayFormat>MSG-{00000000}</displayFormat>
        <label>Message ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SendMessageViaPulse.cls
public class SendMessageViaPulse implements SendViaSMSGateway {

    /**
     * Send a message via pulse.
     */

    public String execute(List<Message> inputMessages) {

        String output = '';
        List<Message__c> messages = new List<Message__c>();
        for (Message inputMessage : inputMessages) {
            for (SendSMSHelpers.Recipient recipient : inputMessage.recipients.values()) {
                messages.add(new Message__c(
                    Body__c = inputMessage.body,
                    Recipient__c = recipient.personId,
                    Subject__c = inputMessage.subject,
                    From__c = inputMessage.senderId,
                    Expiration_Time__c = inputMessage.expirationTime,
                    Sent_Time__c = inputMessage.sentTime,
                    Category__c = inputMessage.catgory
                ));
                output += recipient.personId + '_splitter_' + inputMessage.getMessageHash() + ',';
            }
        }

        // May have to move this inside the outer for loop if groups get very very large
        try {
            insert messages;
        }
        catch (Exception e) {
            System.debug(LoggingLevel.INFO, e.getMessage());
            return 'FAIL,' + output;
        }
        return 'SUCCESS,' + output;
    }

    // Not needed as no callout is made to save pulse messages
    public String createBody(List<Message> inputMessages, Boolean single) {
        return '';
    }
    public HttpRequest buildRequest(String body, Boolean single) {
        return null;
    }
    public HttpResponse sendRequest(HttpRequest request) {
        return null;
    }

    // Callback implementation
    public Map<String, Boolean> callback(String results, Map<String, Boolean> resultMap) {

        if (resultMap == null) {
            resultMap = new Map<String, Boolean>();
        }
        List<String> idList = results.split(',');
        Boolean success = true;
        if (idList.size() == 1 || idList[0].equals('FAIL')) {
            success = false;
        }

        idList.remove(0);
        for (String key : idList) {
            resultMap.put(key, success);
        }
        return resultMap;
    }
}