src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Search_Log__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Interviewee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person who requests information</description>
        <label>Interviewee</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Administered)</relationshipLabel>
        <relationshipName>Interviewee_Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The CKW/Interviewer as obtained from Salesforce using handset id</description>
        <label>Interviewer</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Search Logs (Searches Done)</relationshipLabel>
        <relationshipName>Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Server_Entry_Time__c</fullName>
        <description>Time the server received the request</description>
        <label>Server Entry Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Submission_GPS_Timestamp__c</fullName>
        <description>The timestamp that the log was submitted from the phone</description>
        <label>Submission GPS Timestamp</label>
        <type>DateTime</type>
    </fields>
    <label>Search Log</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduledSearchLogsGAPSKnowledgeMining.cls
/**
 *
 * Copyright (c) 2015 Grameen Foundation
 *
 *  Scheduling class for processing previous day's Search Logs by
 *	discovering the GAPs knowledge a farmer acquired
 *
 *  Tests are in SearchServerTests
 **/
global class ScheduledSearchLogsGAPSKnowledgeMining implements Schedulable {
    
    global void execute(SchedulableContext context){
        
        System.debug(Logginglevel.INFO, 'Data mining for GAPs Knowledge in Search Logs started ...');
        
        String query = 
		'SELECT '								+
			'Id, '								+
			'Interviewer__c, '					+
			'Interviewee__c, '					+
			'Submission_GPS_Timestamp__c, '		+
			'Interviewee__r.Name, '				+
			'Query__c '							+
		'FROM '									+
			'Search_Log__c '					+
		'WHERE '								+
			'Server_Entry_Time__c = YESTERDAY';
		
		ID batchprocessid = Database.executeBatch(new SearchLogsGAPSKnowledgeMining(query), 40);
    }
}