src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TDR__c.object
<CustomObject>
    <description>A Trade Visit Representative for MTN. These objects should only be viewable by Sys Admin and MTN profiles. Only updatable by Sys Admin and MTN Management Profile</description>
    <fields>
        <fullName>Person__c</fullName>
        <description>The person object for this TDR. Will contain the bio details for the TDR</description>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>TDRs</relationshipLabel>
        <relationshipName>TDRs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TDR</label>
    <nameField>
        <displayFormat>TDR-{YY}-{00000000}</displayFormat>
        <label>TDR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TDRs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScheduledTdrWeeklyEmail.cls
global class ScheduledTdrWeeklyEmail implements Schedulable {

    global void execute(SchedulableContext sc) {

        Map<String, List<String>> addresses = new Map<String, List<String>>();


        // Add the dates for yesterday
        Date startDate = Date.today().addDays(-8);

        // Send the emails to the national level
        List<String> emailAddresses = new List<String>();
        emailAddresses.add('opetoo@mtn.co.ug');
        emailAddresses.add('harunas@mtn.co.ug');
        emailAddresses.add('kobaa@mtn.co.ug');
        emailAddresses.add('asiimwi@mtn.co.ug');
        emailAddresses.add('nimusid@mtn.co.ug');

        addresses.put('all', emailAddresses);
        // Send to Central region
        List<String> centralEmails= new List<String>();
        centralEmails.add('kiwagin@mtn.co.ug');
        addresses.put('Central', centralEmails);

        // Send to East region
        List<String> eastEmails= new List<String>();
        eastEmails.add('gyagene@mtn.co.ug');
        addresses.put('Eastern', eastEmails);

        // Send to West region
        List<String> westEmails = new List<String>();
        westEmails.add('ndobolj@mtn.co.ug');
        addresses.put('Western', westEmails);

        // Send to South West region
        List<String> southWestEmails= new List<String>();
        southWestEmails.add('mutakar@mtn.co.ug');
        addresses.put('South Western', southWestEmails);

        // Send to North region
        List<String> northEmails = new List<String>();
        northEmails.add('ogwangp@mtn.co.ug');
        addresses.put('Northern', northEmails);

        // Send email to West Nile region
        List<String> westNileEmails = new List<String>();
        westNileEmails.add('kibirae@mtn.co.ug');
        addresses.put('West Nile', westNileEmails);

		List<String> personIds = new List<String>();
		Person__c[] people = 
		    [SELECT 
		        Id 
		    FROM 
		        Person__c 
		    WHERE 
		        Type__c = 'TDR' 
		      AND 
		        ID IN 
		        (SELECT 
		             Person__c 
		         FROM 
		             TDR__c )];
                       
        for (Person__c person : people) {
            personIds.add(person.Id);
        }
        TdrHelpers.sendWeeklyEmails(addresses, personIds, startDate);
    }
}