src/objects/Person__c.object
<CustomObject>
    <description>Represents a person that uses the CKW system. This includes farmers, CKWs, staff, field officers, etc.</description>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Is the person male or female</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>What type of person this is</description>
        <inlineHelpText>Use person if none of the other option match your requirements</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CKW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coffee A Cup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Validator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asocati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MTN Channels Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Based Trainer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IITA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRAC PA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Village__c</fullName>
        <description>Village that the person lives in</description>
        <label>Village</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Person</label>
    <nameField>
        <displayFormat>Person-{000000}</displayFormat>
        <label>Person ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>People</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduledC3P0FarmerInteractionCalculator.cls
global class ScheduledC3P0FarmerInteractionCalculator implements Schedulable {

    public static String cronExpression = '0 0 5 * * ?'; // run every day at 5am
    
    global void execute(SchedulableContext sc) {
        String farmerQuery =
            'SELECT '                   +
                'Name, '                +
                'Id, '                  +
                'Gender__c, ' +
                'Village__c ' +
            'FROM '                     +
                'Person__c '            +
            'WHERE '                    +
                'Type__c = \'Focus Farmer\' ';
        ID batchprocessid = Database.executeBatch(new CalculateFarmerInteractions(farmerQuery), 10);
    }
}