src/objects/Survey__c.object
<CustomObject>
    <description>Surveys run by CKWs. There is one entry here for each type of survey. Survey questions (and responses) are NOT stored here.</description>
    <fields>
        <fullName>Export_URL__c</fullName>
        <defaultValue>&quot;NONE&quot;</defaultValue>
        <description>The URL to export a survey to</description>
        <label>Export URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date of Survey</description>
        <inlineHelpText>Start Date of Survey</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <description>A unique name for the survey</description>
        <inlineHelpText>Please select a friendly name for the survey</inlineHelpText>
        <label>Survey Name</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Survey_Status__c</fullName>
        <description>Current status of survey</description>
        <inlineHelpText>Select Active to create a form and questions for the survey. Select Published to make it available to the phones. Select completed to hide it from the phones.</inlineHelpText>
        <label>Survey Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{0000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LacDashboardController.cls
public with sharing class LacDashboardController {

        
        
        
        private final List<Survey__c> survey;

        public LacDashboardController() {
                survey = [select Survey_Name__c, Export_URL__c, Start_Date__c, Survey_Status__c from Survey__c];
                                
        }
        
        public List<Survey__c> getSurvey(){
                return survey; 
                
        }
}